Repository giantswarm/happa, pull requests merged in 2020-10, with the labels that each got.

#1878 add cert-manager to pre-installed apps list
  src/components/Cluster/ClusterDetail/ClusterApps.js
  src/images/app_icons/cert_manager@2x.png
Labels: kind/ux-enhancement

#1879 Allow having apps defined without labels
  src/@types/appcatalogs.d.ts
  src/@types/v4clusters.d.ts
  src/components/Cluster/ClusterDetail/ClusterApps.js
Labels: kind/bug

#1877 Move all loading/error state management to their own domains
  src/components/AppCatalog/AppDetail/AppDetail.js
  src/components/AppCatalog/AppList/AppList.js
  src/components/Cluster/ClusterDetail/AppDetailsModal/AppDetailsModal.js
  src/components/Cluster/ClusterDetail/ClusterApps.js
  src/components/Cluster/ClusterDetail/ClusterDetailView.js
  src/components/Cluster/ClusterDetail/Ingress/InstallIngressButton.tsx
  src/components/Cluster/ClusterDetail/KeyPairs.js
  src/components/Cluster/ClusterDetail/V5ClusterDetailTable.js
  src/components/Footer/Footer.tsx
  src/components/Home/ClusterDashboardItem.js
  src/components/Home/ClusterDashboardResourcesV4.js
  src/components/Home/ClusterDashboardResourcesV5.js
  src/components/Organizations/Organizations.js
  src/reducers/entityErrorReducer.js
  src/reducers/entityLoadingReducer.js
  src/reducers/index.js
  src/reducers/loadingReducer.js
  src/reducers/types.ts
  src/stores/cluster/selectors.ts
  src/stores/entityerror/constants.ts
  src/stores/entityerror/reducer.ts
  src/stores/entityerror/selectors.ts
  src/stores/entityerror/types.ts
  src/stores/entityloading/reducer.ts
  src/stores/entityloading/selectors.ts
  src/stores/entityloading/types.ts
  src/stores/loading/reducer.ts
  src/stores/loading/selectors.ts
  src/stores/loading/types.ts
Labels: kind/refactor

#1876 Move all main actions to the main state management domain
  src/@types/info.d.ts
  src/actions/batchedActions.js
  src/components/AccountSettings/AccountSettings.js
  src/components/AppCatalog/AppCatalog.js
  src/components/Auth/AdminLogin.tsx
  src/components/Auth/Login.tsx
  src/components/Auth/Logout.js
  src/components/Auth/OAuthCallback.js
  src/components/Cluster/ClusterDetail/AddNodePool.js
  src/components/Cluster/ClusterDetail/ClusterApps.js
  src/components/Cluster/ClusterDetail/ClusterDetailView.js
  src/components/Cluster/NewCluster/CreateRegularCluster.js
  src/components/Cluster/NewCluster/NewClusterWrapper.tsx
  src/components/Cluster/NewCluster/ReleaseSelector/ReleaseSelector.tsx
  src/components/Cluster/NewCluster/ReleaseSelector/__tests__/ReleaseSelector.ts
  src/components/ForgotPassword/ForgotPassword.js
  src/components/ForgotPassword/SetPassword.js
  src/components/SignUp/SignUp.js
  src/lib/giantswarmClientPatcher.ts
  src/lib/hooks/useInstanceTypeSelectionConfiguration.ts
  src/model/services/giantSwarm/info.ts
  src/model/services/giantSwarm/types.ts
  src/reducers/index.js
  src/reducers/mainReducer.js
  src/reducers/types.ts
  src/selectors/featureSelectors.ts
  src/selectors/mainInfoSelectors.ts
  src/selectors/releaseSelectors.ts
  src/stores/cluster/__tests__/selectors.ts
  src/stores/cluster/selectors.ts
  src/stores/cluster/utils.ts
  src/stores/global/actions.ts
  src/stores/global/constants.ts
  src/stores/global/types.ts
  src/stores/main/__tests__/selectors.ts
  src/stores/main/actions.ts
  src/stores/main/constants.ts
  src/stores/main/reducer.ts
  src/stores/main/selectors.ts
  src/stores/main/types.ts
  src/stores/organization/actions.ts
  src/stores/releases/actions.ts
  src/stores/user/actions.ts
  src/stores/user/constants.ts
  src/stores/user/selectors.ts
  src/stores/user/types.ts
  testUtils/modelMocks.js
  testUtils/preloginState.js
Labels: kind/refactor

#1881 Display node pools loading errors on a new line
  src/components/Home/ClusterDashboardItem.js
  src/shared/constants/index.ts
Labels: kind/ux-enhancement

#1892 Do not check non-related to cloud capabilities
  helm/happa/templates/configmap.yaml
  helm/happa/templates/deployment.yaml
Labels: kind/bug

#1893 Do not check for non-related capabilities in start script
  scripts/start.sh
Labels: kind/bug

#1896 Don't let user execute requests if they are not logged in
  src/stores/main/__tests__/selectors.ts
  src/stores/main/selectors.ts
Labels: kind/bug

#1894 Extract k8s version into component, remove patch level
  src/components/Cluster/ClusterDetail/RegionAndVersions.tsx
  src/components/Home/ClusterDashboardItem.js
  src/components/UI/KubernetesVersionLabel.tsx
Labels: kind/change

#1898 Display full cluster update error details
  src/components/Cluster/ClusterDetail/__tests__/ScaleClusterModal.js
  src/stores/cluster/actions.ts
  src/utils/__tests__/errorUtils.ts
  src/utils/errorUtils.ts
Labels: kind/ux-enhancement

#1900 Update various dependencies at once.
  package.json
  yarn.lock
Labels: dependencies

#1911 Update various dependencies all at once
  package.json
  yarn.lock
Labels: dependencies

#1923 Automatically enable the latest active version, even for admins
  src/components/Cluster/NewCluster/ReleaseSelector/ReleaseSelector.tsx
  src/components/Cluster/NewCluster/ReleaseSelector/__tests__/ReleaseSelector.ts
Labels: kind/dev-change

#1899 Add information about Kubernetes versions' EOL status
  src/@types/info.d.ts
  src/@types/releases.d.ts
  src/components/Cluster/ClusterDetail/ClusterApps.js
  src/components/Cluster/ClusterDetail/RegionAndVersions.tsx
  src/components/Cluster/NewCluster/ReleaseSelector/ReleaseRow.tsx
  src/components/Cluster/NewCluster/ReleaseSelector/ReleaseSelector.tsx
  src/components/Cluster/NewCluster/ReleaseSelector/__tests__/ReleaseSelector.ts
  src/components/Home/ClusterDashboardItem.js
  src/components/Modals/ReleaseDetailsModal.js
  src/components/UI/KubernetesVersionLabel.tsx
  src/components/UI/__tests__/KubernetesVersionLabel.tsx
  src/lib/__tests__/helpers.ts
  src/lib/helpers.tsx
  src/shared/constants/index.ts
  src/stores/main/__tests__/selectors.ts
  src/stores/main/selectors.ts
  src/stores/releases/__tests__/utils.ts
  src/stores/releases/actions.ts
  src/stores/releases/utils.ts
Labels: kind/feature

#1925 Add basic dependabot configuration
  .github/dependabot.yml
Labels: kind/dev-change

#1871 Add data-dd-action-name attribute to clickable items for better event names
  src/components/Cluster/ClusterDetail/AddNodePool.js
  src/components/Cluster/ClusterDetail/AvailabilityZonesParser.js
  src/components/Cluster/ClusterDetail/InstanceTypeSelector/InstanceTypeRow.tsx
  src/components/Cluster/ClusterDetail/InstanceTypeSelector/InstanceTypeSelector.tsx
  src/components/Cluster/ClusterDetail/V5ClusterDetailTable.js
  src/components/Cluster/NewCluster/CreateNodePoolsCluster.js
  src/components/Cluster/NewCluster/CreateRegularCluster.js
  src/components/Cluster/NewCluster/KVMWorkerConfiguration.tsx
  src/components/Cluster/NewCluster/ReleaseSelector/ReleaseRow.tsx
  src/components/Cluster/NewCluster/ReleaseSelector/ReleaseSelector.tsx
  src/components/Cluster/NewCluster/V4AvailabilityZonesSelector.js
  src/components/UI/AvailabilityZonesLabel.js
  src/components/UI/Navigation/Navigation.js
  src/components/UI/NumberPicker.js
  src/components/shared/NodeCountSelector.js
Labels: kind/dev-change

#1924 Record user action for viewport size
  src/components/index.tsx
Labels: kind/dev-change

#1927 Record window and screen size on page load
  src/components/index.tsx
Labels: kind/dev-change

#1929 Worker node counter is broken when there are no node pools
  src/components/Cluster/ClusterDetail/NodesRunning.tsx
Labels: kind/bug

#1932 Discourage the usage of pre-release versions
  src/components/Cluster/NewCluster/ReleaseSelector/ReleaseSelector.tsx
  src/components/Cluster/NewCluster/ReleaseSelector/__tests__/ReleaseSelector.ts
  src/stores/cluster/__tests__/selectors.ts
  src/stores/cluster/__tests__/utils.ts
  src/stores/cluster/selectors.ts
  src/stores/cluster/utils.ts
  src/stores/releases/__tests__/utils.ts
  src/stores/releases/utils.ts
Labels: kind/ux-enhancement

#1935 Improve RUM event binding
  src/@types/realUserMonitoring.d.ts
  src/components/Cluster/ClusterDetail/AddNodePool.js
  src/components/Cluster/ClusterDetail/InstanceTypeSelector/InstanceTypeRow.tsx
  src/components/Cluster/ClusterDetail/InstanceTypeSelector/InstanceTypeSelector.tsx
  src/components/Cluster/ClusterDetail/V5ClusterDetailTable.js
  src/components/Cluster/NewCluster/CreateNodePoolsCluster.js
  src/components/Cluster/NewCluster/CreateRegularCluster.js
  src/components/Cluster/NewCluster/ReleaseSelector/ReleaseRow.tsx
  src/components/Cluster/NewCluster/ReleaseSelector/ReleaseSelector.tsx
  src/components/RUM/RUMActionTarget.tsx
  src/components/RUM/__tests__/RUMActionTarget.tsx
  src/components/UI/AvailabilityZonesLabel.js
  src/components/UI/Navigation/Navigation.js
  src/components/UI/NumberPicker.js
  src/components/index.tsx
  src/shared/constants/realUserMonitoring.ts
  src/utils/__tests__/realUserMonitoringUtils.ts
  src/utils/realUserMonitoringUtils.ts
Labels: kind/dev-change

#1937 Set background color early
  src/index.html
Labels: kind/ux-enhancement

#1940 Show upgrade in progress immediately after upgrade has been started
  src/@types/v4clusters.d.ts
  src/@types/v5clusters.d.ts
  src/components/AppCatalog/AppDetail/AppDetail.js
  src/components/AppCatalog/AppDetail/InstallAppModal.js
  src/components/Cluster/ClusterDetail/ClusterApps.js
  src/components/Cluster/ClusterDetail/ClusterDetailView.js
  src/components/Cluster/ClusterDetail/Ingress/InstallIngressButton.tsx
  src/components/Cluster/ClusterDetail/V5ClusterDetailTable.js
  src/components/Home/ClusterStatus.tsx
  src/components/Home/__tests__/ClusterStatus.tsx
  src/lib/__tests__/helpers.ts
  src/stores/cluster/__tests__/selectors.ts
  src/stores/cluster/__tests__/utils.ts
  src/stores/cluster/reducer.ts
  src/stores/cluster/selectors.ts
  src/stores/cluster/types.ts
  src/stores/cluster/utils.ts
  testUtils/mockHttpCalls/clusters.js
  testUtils/preloginState.js
Labels: kind/ux-enhancement

#1941 azure v5: change 'None' node pool AZ selection to 'Not specified'
  src/components/Cluster/ClusterDetail/AddNodePool/AddNodePool.js
  src/components/Cluster/ClusterDetail/AddNodePool/AddNodePoolAZSelection.tsx
  src/components/Cluster/ClusterDetail/AddNodePool/AddNodePoolAZSelectionCheckbox.tsx
  src/components/Cluster/ClusterDetail/AddNodePool/AddNodePoolMachineType.tsx
  src/components/Cluster/ClusterDetail/AddNodePool/AddNodePoolUtils.ts
  src/components/Cluster/ClusterDetail/V5ClusterDetailTable.js
  src/components/Cluster/NewCluster/CreateNodePoolsCluster.js
  src/shared/constants/realUserMonitoring.ts
Labels: kind/ux-enhancement

#1942 Show full error from API when NP creation fails
  src/stores/nodepool/actions.ts
Labels: kind/ux-enhancement

#1943 Select the organization ID from storage before comparing it to the cluster owner reference
  src/components/AppCatalog/AppDetail/InstallAppModal.js
  src/components/Home/ClusterDashboardItem.js
  src/components/Organizations/Detail/Detail.js
  src/components/UI/OrganizationList/OrganizationList.js
  src/lib/__tests__/helpers.ts
  src/lib/helpers.tsx
  src/stores/cluster/actions.ts
  src/stores/cluster/selectors.ts
  src/stores/nodepool/actions.ts
  src/stores/organization/__tests__/utils.ts
  src/stores/organization/selectors.ts
  src/stores/organization/utils.ts
Labels: kind/dev-change

#1945 Record core web vitals
  package.json
  src/@types/realUserMonitoring.d.ts
  src/@types/web-vitals.d.ts
  src/components/index.tsx
  src/shared/constants/realUserMonitoring.ts
  yarn.lock
Labels: kind/dev-change

#1944 Fix relative URLs in READMEs
  src/components/AppCatalog/AppDetail/AppDetail.js
  src/components/UI/AppDetails/AppDetails.js
  src/shared/constants/index.ts
  src/stores/appcatalog/actions.ts
  src/stores/appcatalog/selectors.ts
Labels: kind/bug

#1948 Update lodash to fix a vulnerability
  package.json
  yarn.lock
Labels: dependencies

#1946 Clarify invites and expiry dates on users page
  __tests__/Users.js
  src/components/Users/InvitesTable.js
  src/components/Users/Users.js
  src/components/Users/UsersTable.js
  src/components/Users/UsersUtils.js
  testUtils/mockHttpCalls/invites.js
  testUtils/mockHttpCalls/user.js
Labels: kind/change

#1952 Don't reload the page when pressing enter in the app search form.
  src/components/AppCatalog/AppList/AppListSearch.js
Labels: kind/bug

#1954 Hack the catalog urls for helm stable special case.
  src/stores/appcatalog/actions.ts
Labels: kind/change
