Repository giantswarm/happa, pull requests merged in 2020-06, with the labels that each got.

#1517 Implement catalog visibility
  __tests__/AppCatalog.js
  src/components/AppCatalog/AppList/AppListInner.js
  src/components/AppCatalog/CatalogList/CatalogList.js
  src/components/AppCatalog/CatalogList/CatalogRepo.js
  src/components/UI/CatalogTypeLabel.js
  testUtils/mockHttpCalls/appCatalogs.js
Labels: kind/change

#1532 Add a page that lets us generate uncaught exceptions.
  src/components/ExceptionNotificationTest/ExceptionNotificationTest.tsx
  src/components/Layout.js
  src/shared/constants/routes.js
Labels: kind/feature

#1531 Input field refactoring
  src/components/AppCatalog/AppDetail/ClusterPicker.js
  src/components/AppCatalog/AppDetail/InstallAppForm.js
  src/components/Cluster/ClusterDetail/AddNodePool.js
  src/components/Cluster/ClusterDetail/ClusterDetailView.js
  src/components/Cluster/ClusterDetail/ClusterLabels/EditLabelTooltip.tsx
  src/components/Cluster/ClusterDetail/NodePool.tsx
  src/components/Cluster/NewCluster/CreateNodePoolsCluster.js
  src/components/UI/Inputs/FileInput.tsx
  src/components/UI/Inputs/Input.tsx
  src/components/UI/Inputs/ValidityStyledInputElement.tsx
  src/components/UI/ViewEditName.tsx
  src/components/UI/__tests__/ViewEditName.js
  src/shared/constants/index.js
Labels: kind/refactor

#1544 Cluster creation refactor
  .eslintrc.js
  src/@types/releases.d.ts
  src/@types/validation.d.ts
  src/components/Cluster/Cluster.js
  src/components/Cluster/ClusterDetail/AddNodePool.js
  src/components/Cluster/ClusterDetail/V5ClusterDetailTable.js
  src/components/Cluster/NewCluster/AWSInstanceTypeSelector.js
  src/components/Cluster/NewCluster/ClusterCreationDuration.js
  src/components/Cluster/NewCluster/CreateNodePoolsCluster.js
  src/components/Cluster/NewCluster/CreateRegularCluster.js
  src/components/Cluster/NewCluster/NewCluster.js
  src/components/Cluster/NewCluster/NewClusterWrapper.tsx
  src/components/Cluster/NewCluster/ReleaseSelector.js
  src/components/Cluster/NewCluster/V4AvailabilityZonesSelector.js
  src/components/UI/Checkbox.js
  src/components/UI/ClusterCreation/ClusterCreationLabelSpan.tsx
  src/components/UI/ClusterCreation/Headline.tsx
  src/components/UI/ClusterCreation/HorizontalLine.tsx
  src/components/UI/ClusterCreation/InstanceTypeSelection.tsx
  src/components/UI/ClusterCreation/NameInput.tsx
  src/components/UI/ClusterCreation/Section.tsx
  src/components/UI/ClusterCreation/StyledInput.tsx
  src/components/UI/FlexDivs.tsx
  src/components/UI/Inputs/Input.tsx
  src/components/UI/NumberPicker.js
  src/hooks/useValidatingInternalValue.ts
  src/selectors/mainInfoSelectors.ts
  src/styles/cluster-creation.ts
  src/styles/index.ts
  src/styles/theme.ts
  src/utils/labelUtils.ts
Labels: kind/refactor

#1545 Move add labels button out of the info text
  __tests__/V5ClusterManagement.js
  src/components/Cluster/ClusterDetail/ClusterLabels/ClusterLabels.tsx
  src/components/Cluster/ClusterDetail/ClusterLabels/EditLabelTooltip.tsx
Labels: kind/ux-enhancement

#1546 Fix feature flag loading from environment
  webpack.common.js
Labels: kind/bug

#1548 Fix feature flags, part 2
  webpack.common.js
Labels: kind/dev-change

#1549 Make upgrades to inactive releases possible for admins
  src/selectors/clusterSelectors.js
Labels: kind/dev-change

#1562 Set gs client back to master.
  package.json
  yarn.lock
Labels: kind/dev-change

#1564 Make add labels button label all caps
  src/components/Cluster/ClusterDetail/ClusterLabels/EditLabelTooltip.tsx
Labels: kind/ux-enhancement

#1569 Remove escaped html character from reset password error
  src/components/ForgotPassword/ForgotPassword.js
Labels: kind/ux-enhancement

#1570 Center node pools availability zones
  src/components/Cluster/ClusterDetail/AvailabilityZonesWrapper.js
  src/components/Cluster/ClusterDetail/NodePool.tsx
  src/components/Cluster/ClusterDetail/V5ClusterDetailTable.js
  src/selectors/clusterSelectors.js
Labels: kind/ux-enhancement

#1571 Remove all console.error calls
  __tests__/AdminLogin.js
  __tests__/Login.js
  src/actions/appActions.js
  src/actions/batchedActions.js
  src/actions/catalogActions.js
  src/actions/clusterActions.js
  src/actions/invitationActions.js
  src/actions/nodePoolActions.js
  src/actions/organizationActions.js
  src/actions/userActions.js
  src/components/Cluster/ClusterDetail/__tests__/ScaleClusterModal.js
  src/components/GettingStarted/Steps/ConfigureKubectlAlternative.js
  src/lib/pageVisibilityTracker.js
Labels: kind/dev-change

#1572 Display Get Started button label on cluster list page in all caps
  src/components/Home/ClusterDashboardItem.js
Labels: kind/ux-enhancement

#1550 Inline release selection
  __tests__/ClusterManagement.js
  src/@types/releases.d.ts
  src/components/Cluster/NewCluster/NewClusterWrapper.tsx
  src/components/Cluster/NewCluster/ReleaseSelector.js
  src/components/Cluster/NewCluster/ReleaseSelector/ReleaseRow.tsx
  src/components/Cluster/NewCluster/ReleaseSelector/ReleaseSelector.tsx
  src/components/Cluster/NewCluster/ReleaseSelector/__tests__/ReleaseSelector.ts
  src/hooks/useReleaseNotesURL.ts
Labels: kind/refactor, kind/ux-enhancement

#1563 Adapt upgrade information to mention multiple master nodes
  src/components/Cluster/ClusterDetail/UpgradeClusterModal.js
Labels: kind/dev-change

#1574 Account for having no conditions when cluster is creating
  src/utils/clusterUtils.js
Labels: kind/dev-change

#1573 Use errors from the server, if they are available
  src/actions/clusterActions.js
  src/actions/nodePoolActions.js
Labels: kind/ux-enhancement

#1575 Use response from API for release notes url
  src/components/Cluster/NewCluster/ReleaseSelector/ReleaseRow.tsx
  src/hooks/useReleaseNotesURL.ts
Labels: kind/bug

#1565 remove FEATURE_CLUSTER_LABELS_V0 feature flag
  jest.config.js
  src/@types/global.d.ts
  src/components/Cluster/ClusterDetail/V5ClusterDetailTable.js
  src/shared/FeatureFlags.ts
  webpack.common.js
Labels: kind/dev-change

#1567 Add cors proxy plugin 🏄
  .circleci/config.yml
  README.md
  helm/happa/templates/configmap.yaml
  helm/happa/templates/deployment.yaml
  jest.config.js
  package.json
  scripts/start.sh
  scripts/webpack/getServiceURL.js
  scripts/webpack/proxyPlugin.js
  src/components/index.tsx
  src/index.html
  src/lib/auth0.js
  webpack.common.js
  webpack.dev.js
  yarn.lock
Labels: kind/dev-change

#1576 Faster rebuilds by changing the dev sourcemap generator
  webpack.dev.js
Labels: kind/dev-change

#1577 Always display the cluster creation date
  src/actions/clusterActions.js
Labels: kind/bug

#1579 Make precommit hook quicker
  .eslintrc.js
Labels: kind/dev-change

#1580 Fixing errors in tests
  src/components/Auth/AdminLogin.tsx
  src/components/Cluster/ClusterDetail/ClusterDetail.js
  src/components/Cluster/ClusterDetail/ClusterDetailView.js
Labels: kind/dev-change

#1578 Prevent trying to fetch node pools for deleted clusters
  src/actions/nodePoolActions.js
Labels: kind/bug

#1582 Prevent duplicate FlashMessages by default
  src/lib/Queue.ts
  src/lib/__tests__/Queue.ts
  src/lib/__tests__/flashMessage.ts
  src/lib/flashMessage.js
Labels: kind/ux-enhancement

#1585 Redirect user to homepage after they deleted a cluster
  __tests__/V4AWSClusterManagement.js
  __tests__/V5ClusterManagement.js
  src/actions/batchedActions.js
Labels: kind/ux-enhancement

#1581 Inline instance selection
  src/components/Cluster/ClusterDetail/AddNodePool.js
  src/components/Cluster/ClusterDetail/InstanceTypeSelector/InstanceTypeRow.tsx
  src/components/Cluster/ClusterDetail/InstanceTypeSelector/InstanceTypeSelector.tsx
  src/components/Cluster/ClusterDetail/WorkerNodesAWS.js
  src/components/Cluster/ClusterDetail/WorkerNodesAzure.js
  src/components/Cluster/NewCluster/AWSInstanceTypeSelector.js
  src/components/Cluster/NewCluster/AzureVMSizeSelector.js
  src/components/Cluster/NewCluster/CreateRegularCluster.js
  src/components/Cluster/NewCluster/KVMWorkerConfiguration.tsx
  src/components/Cluster/NewCluster/ReleaseSelector/ReleaseRow.tsx
  src/components/Cluster/NewCluster/ReleaseSelector/ReleaseSelector.tsx
  src/components/UI/ClusterCreation/InstanceTypeSelection.tsx
  src/components/UI/ExpandableSelector/Items.tsx
  src/components/UI/ExpandableSelector/Selector.tsx
  src/components/UI/InstanceType.tsx
  src/hooks/useInstanceTypeSelectionConfiguration.ts
  src/selectors/mainInfoSelectors.ts
Labels: kind/refactor, kind/ux-enhancement

#1586 Let user install IC from the Cluster Detail Ingress tab
  src/components/Cluster/ClusterDetail/ClusterDetailView.js
  src/components/Cluster/ClusterDetail/Ingress/Ingress.tsx
  src/components/Cluster/ClusterDetail/Ingress/InstallIngressButton.tsx
  src/components/Cluster/ClusterDetail/Ingress/Instructions.tsx
  src/components/Cluster/ClusterDetail/Ingress/__tests__/Ingress.ts
  src/components/Cluster/ClusterDetail/Ingress/__tests__/InstallIngressButton.ts
  src/components/Cluster/ClusterDetail/Ingress/util.ts
  src/components/GettingStarted/Steps/InstallIngress.js
  src/components/UI/Button.js
  src/components/UI/LoadingIndicator.js
  testUtils/renderUtils.js
Labels: kind/ux-enhancement

#1587 Refactor releases state to use store & let ReleaseSelector directly access the state
  __tests__/ClusterManagement.js
  src/@types/releases.d.ts
  src/actions/actionTypes.js
  src/actions/batchedActions.js
  src/actions/releaseActions.js
  src/components/Cluster/Cluster.js
  src/components/Cluster/ClusterDetail/ClusterDetailView.js
  src/components/Cluster/NewCluster/NewCluster.js
  src/components/Cluster/NewCluster/NewClusterWrapper.tsx
  src/components/Cluster/NewCluster/ReleaseSelector/ReleaseRow.tsx
  src/components/Cluster/NewCluster/ReleaseSelector/ReleaseSelector.tsx
  src/components/Cluster/NewCluster/ReleaseSelector/__tests__/ReleaseSelector.ts
  src/components/Home/UpgradeNotice.tsx
  src/reducers/index.js
  src/reducers/releaseReducer.js
  src/selectors/releaseSelectors.ts
  src/stores/releases/actions.ts
  src/stores/releases/reducer.ts
  src/stores/releases/types.ts
  yarn.lock
Labels: kind/dev-change

#1598 Make non-active releases better discoverable for Giant Swarm staff
  src/components/Cluster/NewCluster/ReleaseSelector/ReleaseRow.tsx
  src/components/Cluster/NewCluster/ReleaseSelector/ReleaseSelector.tsx
  src/components/Cluster/NewCluster/ReleaseSelector/__tests__/ReleaseSelector.ts
  src/components/UI/ExpandableSelector/Items.tsx
  src/selectors/authSelectors.js
  src/styles/index.ts
  src/styles/theme.ts
Labels: kind/feature

#1600 Dont fetch all catalog indexes from the catalog listing page
  __tests__/AppCatalog.js
  src/components/AppCatalog/AppCatalog.js
  src/components/AppCatalog/CatalogList/CatalogList.js
  src/components/AppCatalog/CatalogList/CatalogRepo.js
Labels: kind/change

#1605 Update opsctl command
  scripts/webpack/getServiceURL.js
Labels: kind/change

#1599 Set catalog placeholder image background based on color hash
  src/components/AppCatalog/CatalogList/CatalogRepo.js
  src/components/Cluster/ClusterDetail/CertificateOrgsLabel.js
  src/components/UI/ClusterIDLabel.js
  src/components/shared/ImgWithFallback.tsx
  src/utils/cachingColorHash.ts
Labels: kind/ux-enhancement
