Repository giantswarm/happa, pull requests merged in 2020-12, with the labels that each got.

#1994 Fix organization credential form not appearing
  src/components/Organizations/Detail/Detail.js
  src/components/Organizations/Detail/View.js
  src/components/Organizations/Detail/__tests__/View.tsx
Labels: kind/bug

#1990 Adjust headline case to 'Delete this organization'
  src/components/Organizations/Detail/View.js
Labels: kind/change

#1996 Unify AZ selection styling
  .eslintrc.js
  src/components/Cluster/AZSelection/AZSelection.tsx
  src/components/Cluster/AZSelection/AZSelectionAutomatic.tsx
  src/components/Cluster/AZSelection/AZSelectionCheckbox.tsx
  src/components/Cluster/AZSelection/AZSelectionManual.tsx
  src/components/Cluster/AZSelection/AZSelectionNotSpecified.tsx
  src/components/Cluster/AZSelection/AZSelectionUtils.tsx
  src/components/Cluster/ClusterDetail/AddNodePool/AddNodePool.js
  src/components/Cluster/ClusterDetail/AddNodePool/AddNodePoolAZSelection.tsx
  src/components/Cluster/ClusterDetail/AddNodePool/AddNodePoolUtils.ts
  src/components/Cluster/NewCluster/CreateNodePoolsCluster.js
  src/shared/constants/realUserMonitoring.ts
Labels: kind/ux-enhancement

#2000 Rewrite user dropdown using our custom dropdown component
  src/components/UI/Navigation/Navigation.js
  src/components/UI/Navigation/UserDropdown.js
  src/components/UI/Navigation/UserDropdown.tsx
  src/styles/index.ts
  src/styles/theme.ts
Labels: kind/bug

#2003 Fix cluster stuck on 'Awaiting upgrade' after the upgrade request failed
  src/stores/cluster/reducer.ts
Labels: kind/bug

#1999 Remove the usage of 'react-addons-update'
  package.json
  src/components/AccountSettings/ChangeEmailForm.js
  yarn.lock
Labels: kind/security

#2002 Fix V5 cluster creation loading flag being stuck after completing the request
  src/components/Cluster/NewCluster/CreateNodePoolsCluster.js
  src/components/Cluster/NewCluster/CreateRegularCluster.js
  src/stores/batchActions.ts
  src/stores/cluster/actions.ts
  src/stores/cluster/constants.ts
  src/stores/cluster/types.ts
Labels: kind/bug
