Repository giantswarm/happa, pull requests merged in 2020-11, with the labels that each got.

#1953 Fix app names that disappear on hover
  src/components/UI/AppContainer.js
Labels: kind/bug

#1957 In app details, don't show PROVIDES label if appVersion is not given
  src/components/UI/AppDetails/AppDetails.js
Labels: kind/bug

#1958 Display unknown if appVersion not given
  src/components/UI/AppDetails/ChartVersionsTable.js
Labels: kind/change

#1947 Write RUM data to custom analytics endpoint
  jest.config.js
  package.json
  scripts/start.sh
  src/components/index.tsx
  src/index.html
  yarn.lock
Labels: kind/dev-change

#1960 Relax a test by using a regex instead of a single string match
  src/stores/releases/__tests__/utils.ts
Labels: kind/dev-change

#1972 Display that NP creation failed when trying to create a cluster and NPs at the same time
  src/stores/batchActions.ts
Labels: kind/bug

#1974 Let users retry creating a cluster, if there was an error on the server side the first time around
  src/components/Cluster/NewCluster/CreateNodePoolsCluster.js
  src/components/Cluster/NewCluster/CreateRegularCluster.js
  src/stores/cluster/actions.ts
Labels: kind/ux-enhancement

#1975 Remove minimum width from the release selector component
  src/components/Cluster/NewCluster/ReleaseSelector/ReleaseRow.tsx
Labels: kind/dev-change

#1966 UX enhancements in the "About upgrading" dialog
  src/components/Cluster/ClusterDetail/UpgradeClusterModal.js
  src/components/Cluster/ClusterDetail/__tests__/UpgradeClusterModal.tsx
  src/styles/_base.sass
Labels: kind/ux-enhancement

#1976 Create utility class for parsing semver-formatted versions
  src/lib/Version.ts
  src/lib/__tests__/Version.ts
Labels: kind/dev-change

#1977 Improve upgrade UI interaction during Azure v4 to v5 cluster upgrade
  src/@types/clusters.d.ts
  src/components/Cluster/ClusterDetail/ClusterDetailView.js
  src/stores/batchActions.ts
  src/stores/cluster/actions.ts
  src/stores/cluster/reducer.ts
  src/stores/cluster/types.ts
  src/stores/cluster/utils.ts
Labels: kind/ux-enhancement

#1978 Only display that a new happa version is available if a user is logged in
  src/components/Footer/Footer.tsx
  src/components/Footer/FooterUtils.ts
Labels: kind/ux-enhancement

#1979 Clean up version picker component and truncate values
  src/components/UI/VersionPicker/VersionPicker.tsx
  src/components/UI/VersionPicker/VersionPickerUtils.ts
  src/components/UI/VersionPicker/__tests__/VersionPicker.js
Labels: kind/bug

#1981 Let the 'Release notes' link in the footer point to the docs.giantswarm.io release page
  src/components/Footer/FooterUtils.ts
Labels: kind/ux-enhancement

#1980 Fix 'SNYK-JS-TRIM-1017038' and 'SNYK-JS-AXIOS-1038255' vulnerabilities
  package.json
  yarn.lock
Labels: kind/security

#1971 Allow for node pools with zero nodes
  src/components/shared/NodeCountSelector.js
  src/components/shared/__tests__/NodeCountSelector.js
Labels: kind/change

#1985 Add support for testing beta versions
  src/components/Cluster/ClusterDetail/ClusterDetailView.js
  src/components/Cluster/ClusterDetail/RegionAndVersions.tsx
  src/components/Cluster/ClusterDetail/V4ClusterDetailTable.js
  src/components/Cluster/ClusterDetail/V5ClusterDetailTable.js
  src/components/Modals/ReleaseDetailsModal.js
  src/components/Modals/ReleaseDetailsModal/ReleaseDetailsModal.js
  src/components/Modals/ReleaseDetailsModal/ReleaseDetailsModalSection.tsx
  src/components/Modals/ReleaseDetailsModal/ReleaseDetailsModalUpgradeOptions.tsx
  src/components/Modals/ReleaseDetailsModal/ReleaseDetailsModalUpgradeOptionsBetaDisclaimer.tsx
  src/components/Modals/ReleaseDetailsModal/ReleaseDetailsModalUpgradeOptionsBetaLabel.tsx
  src/components/Modals/ReleaseDetailsModal/ReleaseDetailsModalUpgradeOptionsVersion.tsx
  src/components/Modals/ReleaseDetailsModal/__tests__/ReleaseDetailsModalUpgradeOptions.tsx
  src/components/UI/ComponentChangelog.js
  src/lib/ReleaseHelper.ts
  src/lib/__tests__/ReleaseHelper.ts
  src/styles/components/_release_selector.sass
Labels: kind/feature

#1983 Move organization delete button into org details
  __tests__/Organization.js
  src/components/Modals/Modals.js
  src/components/Organizations/Detail/Credentials.js
  src/components/Organizations/Detail/CredentialsDisplay.js
  src/components/Organizations/Detail/Detail.js
  src/components/Organizations/Detail/View.js
  src/components/Organizations/Detail/__tests__/View.tsx
  src/components/Organizations/List/List.js
  src/components/UI/OrganizationList/OrganizationList.js
  src/components/UI/OrganizationList/OrganizationListRow.js
  src/components/UI/Section.js
  src/stores/batchActions.ts
  src/stores/organization/actions.ts
  src/stores/organization/utils.ts
Labels: kind/ux-enhancement

#1987 Fix cluster not being selected for app installation
  src/components/AppCatalog/AppDetail/AppDetail.js
  src/components/AppCatalog/AppDetail/ClusterPicker.tsx
  src/stores/main/reducer.ts
  src/stores/main/types.ts
  testUtils/preloginState.js
Labels: kind/bug

#1970 Refactor clusterId to id in some actions so that they show up in the 'loading flags by entity' state
  src/components/Layout.js
  src/components/Organizations/Detail/Detail.js
  src/stores/batchActions.ts
  src/stores/cluster/actions.ts
  src/stores/cluster/reducer.ts
  src/stores/cluster/types.ts
Labels: kind/refactor

#1988 Align release skipping logic with docs
  src/components/Cluster/ClusterDetail/ClusterDetailView.js
  src/components/Cluster/ClusterDetail/UpgradeClusterModal.js
  src/components/Cluster/ClusterDetail/UpgradeClusterModalVersionChanger.tsx
  src/components/Cluster/ClusterDetail/__tests__/UpgradeClusterModal.tsx
  src/components/Modals/ReleaseDetailsModal/__tests__/ReleaseDetailsModalUpgradeOptions.tsx
  src/lib/ReleaseHelper.ts
  src/lib/__tests__/ReleaseHelper.ts
Labels: kind/bug

#1984 Remove nginx namespace limitation
  __tests__/AppCatalog.js
  src/components/AppCatalog/AppDetail/InstallAppForm.js
  src/components/AppCatalog/AppDetail/InstallAppModal.js
  src/components/AppCatalog/AppDetail/__tests__/InstallAppForm.js
  src/components/UI/VersionPicker/__tests__/VersionPicker.js
Labels: kind/change

#1991 Hide availability zone options when location does not support AZs
  src/components/Cluster/ClusterDetail/AddNodePool/AddNodePool.js
  src/components/Cluster/ClusterDetail/AddNodePool/AddNodePoolAZSelection.tsx
Labels: kind/change, kind/ux-enhancement
