Repository giantswarm/happa, pull requests merged in 2020-09, with the labels that each got.

#1778 Rewrite error reporting logic in TypeScript
  src/@types/stacktrace-gps.d.ts
  src/actions/batchedActions.js
  src/components/Cluster/ClusterDetail/ClusterDetailView.js
  src/components/Cluster/ClusterDetail/NodePool.tsx
  src/components/ExceptionNotificationTest/ExceptionNotificationTest.tsx
  src/components/index.tsx
  src/components/shared/ErrorBoundary.tsx
  src/lib/errors/CustomError.ts
  src/lib/errors/ErrorReporter.js
  src/lib/errors/ErrorReporter.ts
  src/lib/errors/__tests__/CustomError.ts
  src/lib/errors/__tests__/ErrorReporter.ts
  src/lib/errors/__tests__/util.ts
  src/lib/errors/index.js
  src/lib/errors/util.js
  src/lib/errors/util.ts
  src/stores/appcatalog/actions.ts
Labels: kind/refactor

#1776 Rewrite React Hooks in TypeScript
  package.json
  src/components/AppCatalog/AppList/AppList.js
  src/components/Cluster/ClusterDetail/AddNodePoolMachineType.tsx
  src/components/Cluster/ClusterDetail/AppDetailsModal/AppDetailsModal.js
  src/components/Cluster/ClusterDetail/AppDetailsModal/EditChartVersionPane.js
  src/components/Cluster/ClusterDetail/ClusterLabels/EditLabelTooltip.tsx
  src/components/Cluster/ClusterDetail/InstanceTypeSelector/InstanceTypeRow.tsx
  src/components/Cluster/ClusterDetail/InstanceTypeSelector/InstanceTypeSelector.tsx
  src/components/Cluster/ClusterDetail/KeypairCreateModal/AddKeyPairSuccessTemplate.tsx
  src/components/Cluster/ClusterDetail/KeypairCreateModal/KeyPairCreateModal.tsx
  src/components/Cluster/ClusterDetail/KeypairCreateModal/__tests__/KeyPairCreateModal.tsx
  src/components/Cluster/ClusterDetail/URIBlock.js
  src/components/Cluster/ClusterDetail/__tests__/URIBlock.js
  src/components/Cluster/NewCluster/NewClusterWrapper.tsx
  src/components/GettingStarted/CodeBlock.js
  src/components/GettingStarted/FileBlock.js
  src/components/GettingStarted/__tests__/CodeBlock.js
  src/components/GettingStarted/__tests__/FileBlock.js
  src/components/UI/ClusterIDLabel.js
  src/components/UI/RefreshableLabel.js
  src/components/Users/InviteUserModal/index.js
  src/components/shared/Copyable.js
  src/components/shared/DocumentTitle.js
  src/components/shared/__tests__/Copyable.js
  src/lib/effects/useCopyToClipboard.js
  src/lib/effects/useDebounce.js
  src/lib/effects/usePrevious.js
  src/lib/hooks/__tests__/useCopyToClipboard.ts
  src/lib/hooks/__tests__/useDocumentTitle.ts
  src/lib/hooks/useCopyToClipboard.ts
  src/lib/hooks/useDebounce.ts
  src/lib/hooks/useDelayedChange.ts
  src/lib/hooks/useDocumentTitle.ts
  src/lib/hooks/useError.ts
  src/lib/hooks/useInstanceTypeSelectionConfiguration.ts
  src/lib/hooks/usePrevious.ts
  src/lib/hooks/useValidatingInternalValue.ts
  src/styles/transitions/BaseTransition.js
  yarn.lock
Labels: kind/refactor

#1779 Convert constants to TypeScript
  __tests__/AdminLogin.js
  __tests__/Logout.js
  __tests__/SignUp.js
  __tests__/Users.js
  src/components/Cluster/ClusterDetail/Ingress/InstallIngressButton.tsx
  src/components/Cluster/ClusterDetail/Ingress/__tests__/Ingress.ts
  src/components/Cluster/ClusterDetail/Ingress/__tests__/InstallIngressButton.ts
  src/components/Cluster/ClusterDetail/KeypairCreateModal/AddKeyPairTemplate.tsx
  src/components/Cluster/ClusterDetail/KeypairCreateModal/KeyPairCreateModal.tsx
  src/components/Cluster/ClusterDetail/KeypairCreateModal/__tests__/KeyPairCreateModal.tsx
  src/components/Cluster/ClusterDetail/NodePool.tsx
  src/components/Cluster/ClusterDetail/V5ClusterDetailTableNodePoolScaling.tsx
  src/components/Cluster/ClusterDetail/__tests__/ScaleClusterModal.js
  src/components/SignUp/SignUp.js
  src/components/UI/Navigation/UserDropdown.js
  src/selectors/authSelectors.js
  src/selectors/clusterSelectors.js
  src/selectors/ingressTabSelectors.ts
  src/shared/constants/authorizationTypes.ts
  src/shared/constants/fallbackMessages.ts
  src/shared/constants/index.ts
  src/shared/constants/providers.ts
  src/shared/constants/routes.ts
  src/shared/constants/statusCodes.ts
  src/shared/index.js
  src/stores/appcatalog/actions.ts
  src/utils/labelUtils.ts
  src/utils/localStorageUtils.js
  testUtils/ingressCatalogStateMocks.ts
  testUtils/modelMocks.js
Labels: kind/refactor

#1780 Rewrite all src/lib helpers in TypeScript
  __tests__/ForgotPassword.js
  __tests__/SignUp.js
  __tests__/Users.js
  package.json
  src/components/AccountSettings/ChangePasswordForm.js
  src/components/Auth/AdminLogin.tsx
  src/components/SignUp/StatusMessage.js
  src/lib/__tests__/passwordValidation.ts
  src/lib/__tests__/routePath.ts
  src/lib/auth0.ts
  src/lib/flashMessage.ts
  src/lib/giantswarmClientPatcher.js
  src/lib/giantswarmClientPatcher.ts
  src/lib/helpers.tsx
  src/lib/pageVisibilityTracker.js
  src/lib/pageVisibilityTracker.ts
  src/lib/passageClient.js
  src/lib/passageClient.ts
  src/lib/passwordValidation.js
  src/lib/passwordValidation.ts
  src/lib/patchedAirbrakeRequester.js
  src/lib/patchedAirbrakeRequester.ts
  src/lib/platform.js
  src/lib/platform.ts
  src/lib/routePath.ts
  src/model/clients/GenericResponse.ts
  src/model/clients/HttpClient.ts
  yarn.lock
Labels: kind/refactor

#1794 Supply ClusterDetailView with all releases
  src/components/Cluster/ClusterDetail/ClusterDetailView.js
Labels: kind/bug

#1795 Rewrite utils in TypeScript
  src/@types/clusterLabels.d.ts
  src/@types/clusters.d.ts
  src/@types/users.d.ts
  src/@types/v4clusters.d.ts
  src/@types/v5clusters.d.ts
  src/components/Cluster/ClusterDetail/Ingress/Ingress.tsx
  src/components/Cluster/ClusterDetail/Ingress/InstallIngressButton.tsx
  src/components/Cluster/ClusterDetail/KeypairCreateModal/KeyPairCreateModal.tsx
  src/components/Cluster/ClusterDetail/NodePool.tsx
  src/components/Home/ClusterDashboardResourcesV4.js
  src/components/Home/ClusterStatus.tsx
  src/components/Home/__tests__/ClusterStatus.tsx
  src/lib/helpers.tsx
  src/lib/hooks/useInstanceTypeSelectionConfiguration.ts
  src/stores/clusterapps/actions.ts
  src/utils/__tests__/canClusterUpgrade.ts
  src/utils/__tests__/clusterUtils.ts
  src/utils/__tests__/computeCapabilities.ts
  src/utils/clusterUtils.js
  src/utils/clusterUtils.ts
  src/utils/localStorageUtils.js
  src/utils/localStorageUtils.ts
  src/utils/v4orV5.js
  testUtils/preloginState.js
Labels: kind/refactor

#1796 Write tests for 'src/utils' and fix the issues that the tests found
  src/@types/v4clusters.d.ts
  src/utils/__tests__/cachingColorHash.ts
  src/utils/__tests__/canClusterUpgrade.ts
  src/utils/__tests__/clusterUtils.ts
  src/utils/__tests__/computeCapabilities.ts
  src/utils/__tests__/labelUtils.ts
  src/utils/__tests__/localStorageUtils.ts
  src/utils/clusterUtils.ts
  src/utils/localStorageUtils.ts
Labels: kind/dev-change

#1808 Force http-proxy to version >=1.18.1
  package.json
Labels: kind/security

#1809 Fix updateApp action request payload
  src/stores/clusterapps/__tests__/actions.ts
  src/stores/clusterapps/actions.ts
Labels: kind/bug

#1797 Write unit tests for 'lib/*' helpers
  src/lib/__tests__/auth0.ts
  src/lib/__tests__/flashMessage.ts
  src/lib/__tests__/giantswarmClientPatcher.ts
  src/lib/__tests__/helpers.ts
  src/lib/__tests__/pageVisibilityTracker.ts
  src/lib/__tests__/patchedAirbrakeRequester.ts
  src/lib/__tests__/platform.ts
  src/lib/auth0.ts
  src/lib/flashMessage.ts
  src/lib/giantswarmClientPatcher.ts
  src/lib/helpers.tsx
Labels: kind/dev-change

#1820 Add real user monitoring for test installations
  .circleci/config.yml
  .dockerignore
  Dockerfile
  helm/happa/ci/default-values.yaml
  helm/happa/templates/configmap.yaml
  helm/happa/templates/deployment.yaml
  scripts/rum.inc.html
  scripts/start.sh
  src/index.html
Labels: kind/change

#1822 Fix V4 cluster creation by actually filling the array of workers with workers
  src/components/Cluster/NewCluster/CreateRegularCluster.js
Labels: kind/bug

#1824 Use EnableUserMonitoring setting to enable user monitoring
  helm/happa/ci/default-values.yaml
  helm/happa/templates/configmap.yaml
Labels: kind/change

#1826 Improve wording regarding installing apps
  src/components/Cluster/ClusterDetail/UserInstalledApps/UserInstalledApps.js
Labels: kind/ux-enhancement

#1825 azure v5: Enable node pool autoscaling
  src/actions/nodePoolActions.js
  src/components/Cluster/ClusterDetail/AddNodePool.js
  src/components/Cluster/ClusterDetail/NodePool.tsx
  src/components/Cluster/ClusterDetail/NodePoolScaling.tsx
  src/components/Cluster/ClusterDetail/ScaleNodePoolModal.js
  src/components/Cluster/ClusterDetail/V5ClusterDetailTable.js
  src/components/Cluster/ClusterDetail/V5ClusterDetailTableNodePoolScaling.tsx
  src/shared/constants/index.ts
Labels: kind/dev-change

#1823 Allow having no worker nodes in V4 clusters
  src/components/Cluster/ClusterDetail/V4ClusterDetailTable.js
  src/selectors/clusterSelectors.js
  src/utils/__tests__/clusterUtils.ts
  src/utils/clusterUtils.ts
Labels: kind/bug

#1827 Fix breaking app catalog layout after clearing the search bar
  src/components/AppCatalog/AppList/AppListInner.js
  src/components/AppCatalog/AppList/AppListItems.js
Labels: kind/bug

#1829 Force 'ua-parser-js' version v0.7.22 to fix vulnerability
  package.json
  yarn.lock
Labels: kind/security

#1828 Force 'node-fetch' version v2.6.1 to fix vulnerability
  package.json
  yarn.lock
Labels: kind/security

#1830 Refactor metadata state interaction to a domain-oriented approach
  __tests__/AdminLogin.js
  src/actions/actionTypes.js
  src/actions/metadataActions.ts
  src/components/Footer/Footer.tsx
  src/components/Home/__tests__/ClusterStatus.tsx
  src/model/services/metadata/configuration.ts
  src/reducers/index.js
  src/reducers/mainReducer.js
  src/reducers/types.ts
  src/selectors/metadataSelectors.ts
  src/stores/asynchronousAction.ts
  src/stores/metadata/actions.ts
  src/stores/metadata/constants.ts
  src/stores/metadata/reducer.ts
  src/stores/metadata/selectors.ts
  src/stores/metadata/types.ts
  testUtils/preloginState.js
Labels: kind/refactor

#1841 Change icon for cluster creation in progress
  src/components/Home/ClusterStatus.tsx
Labels: kind/ux-enhancement

#1842 De-duplicate release information
  docs/Release.md
Labels: kind/dev-change

#1843 Refactor error state management to a domain-specific way
  src/actions/actionTypes.js
  src/actions/errorActions.js
  src/components/AppCatalog/AppDetail/AppDetail.js
  src/components/Cluster/NewCluster/CreateNodePoolsCluster.js
  src/components/Cluster/NewCluster/CreateRegularCluster.js
  src/components/Home/Home.js
  src/lib/hooks/useError.ts
  src/reducers/errorReducer.js
  src/reducers/index.js
  src/reducers/types.ts
  src/selectors/clusterSelectors.js
  src/stores/error/actions.ts
  src/stores/error/constants.ts
  src/stores/error/reducer.ts
  src/stores/error/selectors.ts
  src/stores/error/types.ts
  testUtils/preloginState.js
Labels: kind/refactor

#1847 Refactor node pools state management to a domain-specific way
  src/@types/v5clusters.d.ts
  src/actions/actionTypes.js
  src/actions/batchedActions.js
  src/actions/nodePoolActions.js
  src/components/Cluster/ClusterDetail/ClusterDetailView.js
  src/components/Cluster/ClusterDetail/NodePool.tsx
  src/components/Cluster/ClusterDetail/NodePoolScaling.tsx
  src/components/Cluster/ClusterDetail/ScaleNodePoolModal.js
  src/components/Cluster/ClusterDetail/V5ClusterDetailTable.js
  src/components/Home/ClusterDashboardItem.js
  src/components/Home/ClusterDashboardResourcesV5.js
  src/components/Modals/Modals.js
  src/reducers/index.js
  src/reducers/loadingReducer.js
  src/reducers/modalReducer.js
  src/reducers/nodePoolReducer.js
  src/reducers/types.ts
  src/selectors/clusterSelectors.js
  src/shared/types.ts
  src/stores/cluster/reducer.ts
  src/stores/nodepool/actions.ts
  src/stores/nodepool/constants.ts
  src/stores/nodepool/reducer.ts
  src/stores/nodepool/selectors.ts
  src/stores/nodepool/types.ts
  src/utils/clusterUtils.ts
  testUtils/preloginState.js
Labels: kind/dev-change

#1845 Refactor and clean up FlashMessage component
  src/components/AccountSettings/ChangeEmailForm.js
  src/components/AccountSettings/ChangePasswordForm.js
  src/components/Cluster/ClusterDetail/AppDetailsModal/EditChartVersionPane.js
  src/components/Cluster/ClusterDetail/ClusterApps.js
  src/components/Cluster/ClusterDetail/ExpiryHoursPicker.js
  src/components/Cluster/ClusterDetail/KeyPairs.js
  src/components/Cluster/ClusterDetail/KeypairCreateModal/AddKeyPairErrorTemplate.tsx
  src/components/Cluster/ClusterDetail/ScaleClusterModal.js
  src/components/Cluster/ClusterDetail/ScaleNodePoolModal.js
  src/components/Cluster/ClusterDetail/UpgradeClusterModal.js
  src/components/Cluster/NewCluster/CreateNodePoolsCluster.js
  src/components/Cluster/NewCluster/CreateRegularCluster.js
  src/components/FlashMessages/FlashMessage.js
  src/components/FlashMessages/FlashMessages.js
  src/components/GettingStarted/Steps/ConfigureKubectlAlternative.js
  src/components/UI/FlashMessage.tsx
  src/components/Users/InviteUserModal/InviteUserForm.js
  src/styles/components/_create_key_pair.sass
  src/styles/components/_flash_messages.sass
  src/styles/index.ts
  src/styles/theme.ts
Labels: kind/refactor

#1846 Re-enable Install Ingress button for non-ready clusters
  src/components/Cluster/ClusterDetail/Ingress/InstallIngressButton.tsx
Labels: kind/change

#1844 Refactor organizations state management to a domain-specific way
  src/@types/organizations.d.ts
  src/actions/actionTypes.js
  src/actions/batchedActions.js
  src/actions/organizationActions.js
  src/components/Cluster/NewCluster/ProviderCredentials.js
  src/components/Modals/Modals.js
  src/components/Organizations/Detail/Credentials.js
  src/components/Organizations/Detail/View.js
  src/components/Organizations/List/List.js
  src/components/shared/EmailField.js
  src/reducers/credentialReducer.js
  src/reducers/index.js
  src/reducers/mainReducer.js
  src/reducers/modalReducer.js
  src/reducers/organizationReducer.js
  src/reducers/types.ts
  src/stores/error/reducer.ts
  src/stores/organization/actions.ts
  src/stores/organization/constants.ts
  src/stores/organization/reducer.ts
  src/stores/organization/types.ts
  src/utils/__tests__/organizationUtils.ts
  src/utils/localStorageUtils.ts
  src/utils/organizationUtils.ts
  testUtils/preloginState.js
Labels: kind/refactor

#1848 Refactor users state management to a domain-specific way
  __tests__/ClusterManagement.js
  src/@types/users.d.ts
  src/actions/actionTypes.js
  src/actions/batchedActions.js
  src/actions/userActions.js
  src/components/AccountSettings/AccountSettings.js
  src/components/Auth/AdminLogin.tsx
  src/components/Auth/Login.tsx
  src/components/Auth/Logout.js
  src/components/Auth/OAuthCallback.js
  src/components/Cluster/ClusterDetail/ClusterDetailView.js
  src/components/Cluster/ClusterDetail/__tests__/UpgradeClusterModal.tsx
  src/components/Cluster/NewCluster/ReleaseSelector/ReleaseSelector.tsx
  src/components/Cluster/NewCluster/ReleaseSelector/__tests__/ReleaseSelector.ts
  src/components/ForgotPassword/SetPassword.js
  src/components/Home/__tests__/ClusterStatus.tsx
  src/components/Layout.js
  src/components/Organizations/Detail/Detail.js
  src/components/Organizations/Organizations.js
  src/components/SignUp/SignUp.js
  src/components/Users/Users.js
  src/lib/giantswarmClientPatcher.ts
  src/model/services/giantSwarm/info.ts
  src/model/services/giantSwarm/types.ts
  src/reducers/index.js
  src/reducers/loadingReducer.js
  src/reducers/mainReducer.js
  src/reducers/types.ts
  src/reducers/userReducer.js
  src/selectors/__tests__/clusterSelectors.ts
  src/selectors/authSelectors.js
  src/selectors/clusterSelectors.js
  src/selectors/mainInfoSelectors.ts
  src/selectors/releaseSelectors.ts
  src/stores/global/actions.ts
  src/stores/global/constants.ts
  src/stores/global/types.ts
  src/stores/user/__tests__/selectors.ts
  src/stores/user/actions.ts
  src/stores/user/constants.ts
  src/stores/user/reducer.ts
  src/stores/user/selectors.ts
  src/stores/user/types.ts
  src/utils/__tests__/clusterUtils.ts
  src/utils/__tests__/localStorageUtils.ts
  src/utils/localStorageUtils.ts
  testUtils/modelMocks.js
Labels: kind/refactor

#1849 Move all password reset actions into the user state management domain
  src/actions/actionTypes.js
  src/actions/forgotPasswordActions.js
  src/components/ForgotPassword/ForgotPassword.js
  src/components/ForgotPassword/SetPassword.js
  src/stores/user/actions.ts
  src/stores/user/constants.ts
  src/stores/user/types.ts
Labels: kind/refactor

#1850 Refactor modal state management to a domain-specific way
  src/actions/actionTypes.js
  src/actions/batchedActions.js
  src/actions/modalActions.js
  src/components/Modals/Modals.js
  src/reducers/index.js
  src/reducers/modalReducer.js
  src/reducers/types.ts
  src/stores/modal/actions.ts
  src/stores/modal/constants.ts
  src/stores/modal/reducer.ts
  src/stores/modal/types.ts
  src/stores/nodepool/actions.ts
  src/stores/organization/actions.ts
  testUtils/preloginState.js
Labels: kind/refactor

#1852 Remove Google Analytics tracking code used in test installations
  scripts/rum.inc.html
Labels: kind/removal

#1851 Move all invitation state management into the user state management domain
  src/@types/users.d.ts
  src/actions/actionTypes.js
  src/actions/invitationActions.js
  src/components/Users/Users.js
  src/reducers/index.js
  src/reducers/invitationReducer.js
  src/reducers/types.ts
  src/stores/user/actions.ts
  src/stores/user/constants.ts
  src/stores/user/reducer.ts
  src/stores/user/types.ts
  testUtils/preloginState.js
Labels: kind/refactor

#1864 Move all credential-specific state management logic into the organization domain
  src/components/Cluster/ClusterDetail/ClusterDetailView.js
  src/components/Cluster/NewCluster/ProviderCredentials.js
  src/components/Organizations/Detail/Credentials.js
  src/reducers/credentialReducer.js
  src/reducers/index.js
  src/stores/organization/reducer.ts
  src/stores/organization/types.ts
  testUtils/preloginState.js
Labels: kind/refactor

#1866 Use the correct release format in the 'release-drafter' latest version
  .github/workflows/release-notes.yml
Labels: kind/dev-change

#1867 Show kubernetes version in cluster overview
  src/components/Home/ClusterDashboardItem.js
Labels: kind/feature

#1868 move RegionAndVersions to Typescript
  src/components/Cluster/ClusterDetail/RegionAndVersions.js
  src/components/Cluster/ClusterDetail/RegionAndVersions.tsx
  src/components/Cluster/ClusterDetail/V4ClusterDetailTable.js
  src/components/Cluster/ClusterDetail/V5ClusterDetailTable.js
Labels: kind/refactor

#1870 Move all the app related state interaction into the app catalog state domain
  package.json
  src/@types/appcatalogs.d.ts
  src/@types/clusters.d.ts
  src/actions/__tests__/appActions.js
  src/actions/actionTypes.js
  src/actions/appActions.js
  src/actions/appConfigActions.js
  src/actions/appSecretActions.js
  src/actions/batchedActions.js
  src/components/AppCatalog/AppDetail/AppDetail.js
  src/components/AppCatalog/AppDetail/InstallAppModal.js
  src/components/Cluster/ClusterDetail/AppDetailsModal/AppDetailsModal.js
  src/components/Cluster/ClusterDetail/AppDetailsModal/EditChartVersionPane.js
  src/components/Cluster/ClusterDetail/ClusterApps.js
  src/components/Cluster/ClusterDetail/Ingress/Ingress.tsx
  src/components/Cluster/ClusterDetail/Ingress/InstallIngressButton.tsx
  src/reducers/mainReducer.js
  src/selectors/clusterSelectors.js
  src/stores/appcatalog/__tests__/actions.ts
  src/stores/appcatalog/actions.ts
  src/stores/appcatalog/constants.ts
  src/stores/appcatalog/reducer.ts
  src/stores/appcatalog/selectors.ts
  src/stores/appcatalog/types.ts
  src/stores/cluster/reducer.ts
  src/stores/clusterapps/__tests__/actions.ts
  src/stores/clusterapps/actions.ts
  src/stores/global/actions.ts
  src/stores/global/constants.ts
  src/stores/global/types.ts
  yarn.lock
Labels: kind/refactor

#1872 refactor ClusterDetail/NodesRunning into typescript
  src/components/Cluster/ClusterDetail/NodesRunning.tsx
  src/components/Cluster/ClusterDetail/V5ClusterDetailTable.js
Labels: kind/refactor

#1873 change dropdown trigger & menu width
  src/components/UI/DropdownMenu.js
  src/components/UI/Navigation/OrganizationDropdown.js
  src/components/UI/Truncated.tsx
Labels: kind/change

#1875 Create new semver compare utility, which can compare pre-release versions
  package.json
  src/components/Cluster/ClusterDetail/AddNodePool.js
  src/components/Cluster/ClusterDetail/ClusterApps.js
  src/components/Cluster/ClusterDetail/ScaleClusterModal.js
  src/components/Cluster/ClusterDetail/UpgradeClusterModalVersionChanger.tsx
  src/components/Cluster/NewCluster/NewClusterWrapper.tsx
  src/components/Cluster/NewCluster/V4AvailabilityZonesSelector.js
  src/components/Organizations/Detail/View.js
  src/lib/__tests__/semver.ts
  src/lib/semver.ts
  src/selectors/clusterSelectors.js
  src/selectors/releaseSelectors.ts
  src/shared/constants/index.ts
  src/utils/clusterUtils.ts
  yarn.lock
Labels: kind/bug
