Repository giantswarm/happa, pull requests merged in 2020-03, with the labels that each got.

#1194 Remove an exclamation mark.
  src/components/Cluster/ClusterDetail/ClusterApps.js
Labels: kind/change

#1193 Don't show cert-exporter and net-exporter twice.
  __tests__/AppCatalog.js
  src/components/Cluster/ClusterDetail/ClusterApps.js
  testUtils/mockHttpCalls/releases.js
Labels: kind/dev-change

#1195 Add support for 'giantswarm' authorization schemes
  src/actions/userActions.js
  src/components/SignUp/SignUp.js
  src/components/UI/Navigation/UserDropdown.js
  src/model/clients/GiantSwarmClient.js
  src/model/clients/HttpClient.js
  src/selectors/authSelectors.js
  src/shared/constants/authorizationTypes.js
  src/utils/localStorageUtils.js
  testUtils/modelMocks.js
Labels: kind/bug

#1197 Add kiam and external-dns to essentials in preinstalled apps.
  src/components/Cluster/ClusterDetail/ClusterApps.js
  src/images/app_icons/external_dns@2x.png
  src/images/app_icons/icons.sketch
  src/images/app_icons/kiam@2x.png
Labels: kind/change

#1198 Cleanup in redux nodepools
  src/actions/actionTypes.js
  src/actions/nodePoolActions.js
  src/reducers/nodePoolsReducer.js
Labels: kind/dev-change

#1200 Chart version table
  src/components/AppCatalog/AppDetail/AppDetail.js
  src/components/UI/AppDetails/AppDetails.js
  src/components/UI/AppDetails/ChartVersionsTable.js
  src/components/shared/Copyable.js
Labels: kind/feature

#1201 Remove 'NODE_VERSION' variable declaration from ci configuration
  .circleci/config.yml
Labels: kind/dev-change

#1202 Version picker during app installation
  src/components/AppCatalog/AppDetail/AppDetail.js
  src/components/AppCatalog/AppDetail/Input.js
  src/components/AppCatalog/AppDetail/InstallAppForm.js
  src/components/AppCatalog/AppDetail/InstallAppModal.js
  src/components/UI/VersionPicker/VersionPicker.js
Labels: kind/feature

#1204 Upgrade notice in clusters list
  src/actions/batchedActions.js
  src/components/Cluster/ClusterDetail/ClusterDetail.js
  src/components/Cluster/ClusterDetail/RegionAndVersions.js
  src/components/Cluster/ClusterDetail/V4ClusterDetailTable.js
  src/components/Cluster/ClusterDetail/V5ClusterDetailTable.js
  src/components/Home/ClusterDashboardItem.js
  src/components/Home/UpgradeNotice.js
  src/selectors/clusterSelectors.js
Labels: kind/feature

#1206 Fix triggering of update cluster modal
  src/components/Cluster/ClusterDetail/ClusterDetailView.js
Labels: kind/bug

#1207 Clusters are created in the currently selected organization, instead of a picked organization
  src/components/Cluster/NewCluster/CreateNodePoolsCluster.js
  src/components/Cluster/NewCluster/CreateRegularCluster.js
  src/components/Cluster/NewCluster/NewCluster.js
Labels: kind/bug

#1203 Write tests and comments for the new model layer
  src/model/clients/GiantSwarmClient.js
  src/model/clients/HttpClient.js
  src/model/clients/__tests__/GiantSwarmClient.js
  src/model/clients/__tests__/HttpClient.js
  src/model/services/giantSwarm/__tests__/info.js
  src/model/services/giantSwarm/constants.js
  src/model/services/giantSwarm/info.js
  src/model/storage/LocalStorage.js
  src/model/storage/__tests__/LocalStorage.js
  src/selectors/__tests__/authSelectors.js
  src/selectors/authSelectors.js
  testUtils/modelMocks.js
Labels: kind/change

#1209 Reset organization provider credentials form on page leave
  src/actions/actionTypes.js
  src/actions/organizationActions.js
  src/components/Organizations/Detail/Credentials.js
  src/reducers/organizationReducer.js
Labels: kind/bug

#1210 Refactor InstallAppForm to remove memory leak
  src/components/AppCatalog/AppDetail/InstallAppForm.js
Labels: kind/refactor

#1211 Close modal on route change
  src/actions/actionTypes.js
  src/reducers/modalReducer.js
Labels: kind/ux-enhancement

#1212 Refactor the app detail modal in preparation of editing app version.
  src/components/Cluster/ClusterDetail/AppDetailsModal.js
  src/components/Cluster/ClusterDetail/AppDetailsModal/AppDetailsModal.js
  src/components/Cluster/ClusterDetail/AppDetailsModal/DeleteConfirmFooter.js
  src/components/Cluster/ClusterDetail/AppDetailsModal/EditChartVersionPane.js
  src/components/Cluster/ClusterDetail/AppDetailsModal/InitialPane.js
  src/components/Cluster/ClusterDetail/AppDetailsModal/YamlFileUpload.js
  src/components/Cluster/ClusterDetail/ClusterApps.js
Labels: kind/refactor

#1223 Refactor keypair test and fix overloaded action type.
  __tests__/KeyPairs.js
  src/actions/actionTypes.js
  src/actions/clusterActions.js
  src/reducers/clusterReducer.js
Labels: kind/bug, kind/refactor

#1224 Add action for automatic-assigning of authors
  .github/workflows/main.yml
Labels: kind/dev-change

#1208 Upgrade available icon in org details
  src/components/Home/UpgradeNotice.js
  src/components/Organizations/Detail/Detail.js
  src/components/Organizations/Detail/View.js
Labels: kind/ux-enhancement

#1226 Create custom response object
  __tests__/V4AzureClusterManagement.js
  src/actions/userActions.js
  src/components/Cluster/ClusterDetail/__tests__/ScaleClusterModal.js
  src/model/clients/GenericResponse.js
  src/model/clients/HttpClient.js
  src/model/clients/__tests__/GenericResponse.js
  src/model/clients/__tests__/HttpClient.js
  testUtils/mockHttpCalls/constantsAndHelpers.js
  testUtils/mockHttpCalls/info.js
Labels: kind/refactor

#1227 Add a way to change the app version of an installed app.
  __tests__/AppCatalog.js
  src/actions/actionTypes.js
  src/actions/appActions.js
  src/components/Cluster/ClusterDetail/AppDetailsModal/AppDetailsModal.js
  src/components/Cluster/ClusterDetail/AppDetailsModal/EditChartVersionPane.js
  src/components/Cluster/ClusterDetail/AppDetailsModal/InitialPane.js
  src/components/Cluster/ClusterDetail/ClusterApps.js
  src/components/UI/VersionPicker/VersionPicker.js
  src/styles/components/_cluster_apps.sass
  testUtils/mockHttpCalls/appCatalogs.js
  testUtils/mockHttpCalls/apps.js
Labels: kind/feature

#1228 Change appReducer to mainReducer
  __tests__/AdminLogin.js
  src/actions/actionTypes.js
  src/actions/clusterActions.js
  src/actions/invitationActions.js
  src/actions/nodePoolActions.js
  src/actions/organizationActions.js
  src/actions/userActions.js
  src/components/AccountSettings/AccountSettings.js
  src/components/AppCatalog/AppDetail/AppDetail.js
  src/components/Auth/AdminLogin.js
  src/components/Auth/Login.js
  src/components/Auth/Logout.js
  src/components/Auth/OAuthCallback.js
  src/components/Auth/OAuthCallbackDebug.js
  src/components/Cluster/ClusterDetail/AddNodePool.js
  src/components/Cluster/ClusterDetail/ClusterDetail.js
  src/components/Cluster/ClusterDetail/KeyPairs.js
  src/components/Cluster/ClusterDetail/ScaleClusterModal.js
  src/components/Cluster/ClusterDetail/__tests__/ScaleClusterModal.js
  src/components/Cluster/NewCluster/CreateNodePoolsCluster.js
  src/components/Cluster/NewCluster/CreateRegularCluster.js
  src/components/Cluster/NewCluster/NewCluster.js
  src/components/Cluster/NewCluster/ProviderCredentials.js
  src/components/GettingStarted/Steps/ConfigureKubectl.js
  src/components/Home/Home.js
  src/components/Layout.js
  src/components/Modals/Modals.js
  src/components/Organizations/Detail/Credentials.js
  src/components/Organizations/Detail/Detail.js
  src/components/Organizations/List/List.js
  src/components/Users/Users.js
  src/lib/patchedAirbrakeRequester.js
  src/reducers/catalogReducer.js
  src/reducers/index.js
  src/reducers/mainReducer.js
  src/reducers/nodePoolReducer.js
  src/selectors/__tests__/authSelectors.js
  src/selectors/authSelectors.js
  src/selectors/clusterSelectors.js
  testUtils/modelMocks.js
  testUtils/preloginState.js
Labels: kind/refactor

#1230 Check cluster existence in dashboard resouces component
  src/components/Home/ClusterDashboardResources.js
Labels: kind/bug

#1231 Return empty array if no cluster in selectClusterNodePools
  src/selectors/clusterSelectors.js
Labels: kind/bug

#1233 Upgrade cluster modal: avoid rerendering after dispatching the action
  src/components/Cluster/ClusterDetail/UpgradeClusterModal.js
Labels: kind/bug

#1232 Add support for chaining HttpClient methods
  src/model/clients/HttpClient.js
  src/model/clients/__tests__/HttpClient.js
Labels: kind/dev-change

#1235 Fix an error when deleting an app.
  __tests__/AppCatalog.js
  src/components/Cluster/ClusterDetail/AppDetailsModal/AppDetailsModal.js
Labels: kind/bug

#1234 Make user-installed app list auto refresh
  src/components/Cluster/ClusterDetail/ClusterApps.js
  src/components/Cluster/ClusterDetail/ClusterDetailView.js
  src/components/Cluster/ClusterDetail/UserInstalledApps/InstalledApp.js
  src/components/Cluster/ClusterDetail/UserInstalledApps/UserInstalledApps.js
  src/styles/app.sass
  src/styles/components/_cluster_apps.sass
Labels: kind/ux-enhancement

#1236 More keypair tests.
  __tests__/KeyPairs.js
  src/components/Cluster/ClusterDetail/KeyPairCreateModal.js
  testUtils/mockHttpCalls/index.js
  testUtils/mockHttpCalls/keypairs.js
Labels: kind/dev-change

#1237 Split cluster resources component
  src/components/Home/ClusterDashboardItem.js
  src/components/Home/ClusterDashboardNodes.js
  src/components/Home/ClusterDashboardResources.js
  src/components/Home/ClusterDashboardResourcesV4.js
  src/components/Home/ClusterDashboardResourcesV5.js
Labels: kind/dev-change

#1245 Redirect to organizations home if the organization is not found
  src/components/Organizations/Detail/Detail.js
Labels: kind/bug

#1247 Fix for undefined API endpoint in cluster details view
  src/components/Cluster/ClusterDetail/ClusterDetailView.js
Labels: kind/bug

#1246 Fix admin login if switching endpoints
  __tests__/AdminLogin.js
  __tests__/AppCatalog.js
  __tests__/SignUp.js
  src/actions/userActions.js
  src/reducers/mainReducer.js
Labels: kind/bug

#1248 Optimistic update on cluster name change
  __tests__/V4AWSClusterManagement.js
  __tests__/V5ClusterManagement.js
  src/components/Cluster/ClusterDetail/AppDetailsModal/AppDetailsModal.js
  src/components/Cluster/ClusterDetail/ClusterDetailView.js
  src/components/Cluster/ClusterDetail/NodePool.js
  src/components/UI/ViewEditName.js
  src/components/UI/__tests__/ViewEditName.js
  src/components/index.js
  src/lib/ErrorReporter.js
  testUtils/setupTests.js
Labels: kind/ux-enhancement

#1251 Refactor app catalog tests
  __tests__/AppCatalog.js
  __tests__/AppDetailPane.js
Labels: kind/refactor

#1252 Fixes a bug when showing the app detail pane for apps on internal or otherwise hidden catalogs
  __tests__/AppDetailPane.js
  src/components/Cluster/ClusterDetail/AppDetailsModal/AppDetailsModal.js
  src/components/Cluster/ClusterDetail/AppDetailsModal/InitialPane.js
  testUtils/mockHttpCalls/apps.js
Labels: kind/bug

#1249 Using error.response instead superagent custom message
  src/actions/batchedActions.js
  src/actions/clusterActions.js
  src/actions/nodePoolActions.js
  src/components/Cluster/ClusterDetail/ClusterDetailView.js
  src/reducers/clusterReducer.js
Labels: kind/bug

#1253 Address objects inside of the error fallback helper
  src/actions/clusterActions.js
  src/actions/nodePoolActions.js
  src/components/Home/Home.js
  src/components/UI/ErrorFallback.js
Labels: kind/bug

#1254 Responsive clusters list
  src/components/Home/ClusterDashboardItem.js
  src/shared/constants/cssBreakpoints.js
  src/shared/constants/index.js
  src/styles/index.js
  src/styles/theme.js
Labels: kind/ux-enhancement

#1267 Remove AWS condition from the whitelisting Ingress annotation
  helm/happa-chart/templates/ingress.yaml
Labels: kind/change

#1269 Fix test router redirecting
  __tests__/AdminLogin.js
  __tests__/ForgotPassword.js
  __tests__/SignUp.js
  testUtils/renderUtils.js
  testUtils/setupTests.js
Labels: kind/dev-change

#1266 Version picker error handling
  __tests__/AppDetailPane.js
  src/actions/actionTypes.js
  src/actions/appActions.js
  src/components/Cluster/ClusterDetail/AppDetailsModal/AppDetailsModal.js
  src/components/Cluster/ClusterDetail/AppDetailsModal/EditChartVersionPane.js
  src/components/Cluster/ClusterDetail/AppDetailsModal/InitialPane.js
  src/hooks/errors.js
  src/reducers/entityLoadingReducer.js
  src/reducers/errorReducer.js
  testUtils/mockHttpCalls/catalogIndex.js
  testUtils/setupTests.js
Labels: kind/ux-enhancement

#1250 Create custom error object with detailed stack traces
  package.json
  src/components/Cluster/ClusterDetail/ClusterDetailView.js
  src/components/Cluster/ClusterDetail/NodePool.js
  src/components/index.js
  src/lib/ErrorReporter.js
  src/lib/errors/CustomError.js
  src/lib/errors/ErrorReporter.js
  src/lib/errors/__tests__/CustomError.js
  src/lib/errors/__tests__/ErrorReporter.js
  src/lib/errors/__tests__/util.js
  src/lib/errors/index.js
  src/lib/errors/util.js
  src/selectors/clusterSelectors.js
  testUtils/setupTests.js
  yarn.lock
Labels: kind/feature

#1283 (version picker) Show the button loading when the request is in flight.
  src/components/Cluster/ClusterDetail/AppDetailsModal/AppDetailsModal.js
Labels: kind/change

#1284 Fix kubernetes release label
  src/components/Cluster/NewCluster/ReleaseSelector.js
  src/components/UI/ReleaseComponentLabel.js
Labels: kind/bug, kind/refactor

#1286 Remove noty top right overlapping user & org components
  src/styles/components/_flash_messages.sass
Labels: kind/ux-enhancement

#1268 Hackathon Q1: Introducing TypeScript
  .babelrc
  .eslintignore
  .eslintrc
  .eslintrc.js
  Dockerfile.dev
  Makefile
  docker-compose.yml
  package.json
  src/@types/emotion.d.ts
  src/components/App.tsx
  src/components/Auth/Login.tsx
  src/components/Cluster/ClusterDetail/KeyPairDetailsModal.js
  src/components/Cluster/ClusterDetail/KeyPairs.js
  src/components/Cluster/ClusterDetail/NodePool.tsx
  src/components/Cluster/ClusterDetail/RegionAndVersions.js
  src/components/Cluster/NewCluster/AWSInstanceTypeSelector.js
  src/components/Cluster/NewCluster/AzureVMSizeSelector.js
  src/components/Cluster/NewCluster/CreateNodePoolsCluster.js
  src/components/Cluster/NewCluster/CreateRegularCluster.js
  src/components/Home/ClusterDashboardItem.js
  src/components/Home/ClusterDashboardNodes.tsx
  src/components/Home/UpgradeNotice.tsx
  src/components/Modals/ReleaseDetailsModal.js
  src/components/Organizations/Detail/View.js
  src/components/UI/ErrorFallback.tsx
  src/components/UI/VersionPicker/VersionPicker.tsx
  src/components/Users/UsersTable.js
  src/components/index.tsx
  src/images/index.js
  src/lib/helpers.js
  src/lib/passageClient.js
  src/lib/platform.js
  src/model/clients/HttpClient.js
  src/react-app-env.d.ts
  src/selectors/authSelectors.js
  src/shared/constants/cssBreakpoints.js
  src/shared/constants/cssBreakpoints.ts
  src/shared/constants/index.js
  src/shared/types.ts
  src/stores/configureStore.ts
  src/styles/index.ts
  src/styles/theme.ts
  tsconfig.json
  webpack.common.js
  yarn.lock
Labels: kind/dev-change

#1229 Error message above button in cluster creation when no releases
  __tests__/ClusterManagement.js
  __tests__/V4AzureClusterManagement.js
  src/actions/releaseActions.js
  src/components/Cluster/NewCluster/CreateRegularCluster.js
  src/components/UI/ErrorFallback.tsx
Labels: kind/ux-enhancement
