Repository giantswarm/happa, pull requests merged in 2020-04, with the labels that each got.

#1288 Fix CVE 2019 20149
  package.json
  yarn.lock
Labels: kind/security

#1289 Fix instance type position inside the create node pool form
  src/components/Cluster/ClusterDetail/ClusterApps.js
  src/components/Cluster/ClusterDetail/ClusterDetailView.js
  src/components/Cluster/ClusterDetail/KeyPairs.js
  yarn.lock
Labels: kind/bug

#1290 Run typechecking before committing and as a CI step
  .circleci/config.yml
  Makefile
  package.json
  src/components/App.tsx
Labels: kind/dev-change

#1287 Responsive nav with hamburger
  src/components/Cluster/ClusterDetail/NodePoolDropdownMenu.js
  src/components/UI/DropdownMenu.js
  src/components/UI/Navigation/Hamburger.js
  src/components/UI/Navigation/MainMenu.js
  src/components/UI/Navigation/Navigation.js
  src/components/UI/VersionPicker/VersionPicker.tsx
  src/styles/index.ts
  src/styles/theme.ts
Labels: kind/ux-enhancement

#1291 Happa home mobile changes
  src/components/Home/ClusterDashboardItem.js
  src/styles/_base.sass
Labels: kind/ux-enhancement

#1294 Avoid polyfilling fs
  webpack.common.js
Labels: kind/dev-change

#1292 Add tooltips to explain DESIRED node count
  src/components/Cluster/ClusterDetail/V5ClusterDetailTable.js
  src/components/Cluster/ClusterDetail/WorkerNodesAWS.js
  src/shared/constants/index.js
Labels: kind/ux-enhancement

#1296 Add explicit app deletion message
  __tests__/AppDetailPane.js
  src/actions/appActions.js
Labels: kind/ux-enhancement

#1297 Improve wording/grammar
  src/shared/constants/index.js
Labels: kind/ux-enhancement

#1295 Update GS API client to expose TypeScript types
  yarn.lock
Labels: kind/dev-change

#1298 Implement smart truncation for strings
  Makefile
  src/components/Cluster/ClusterDetail/AppDetailsModal/InitialPane.js
  src/components/UI/AppContainer.js
  src/components/UI/AppDetails/AppDetails.js
  src/components/UI/AppDetails/ChartVersionsTable.js
  src/components/UI/Truncated.tsx
  src/components/UI/__tests__/Truncated.ts
  src/lib/__tests__/helpers.js
  src/lib/helpers.js
  testUtils/renderUtils.js
  tsconfig.json
Labels: kind/ux-enhancement

#1309 Update giantswarm-js-client
  yarn.lock
Labels: dependencies

#1311 Add a guard in dashboard item
  src/components/Home/ClusterDashboardItem.js
Labels: kind/bug

#1314 Node pools messages in delete modal
  __tests__/V5ClusterManagement.js
  src/components/Modals/Modals.js
Labels: kind/ux-enhancement

#1315 Check if error.response object exist in catch blocks
  src/actions/clusterActions.js
  src/actions/nodePoolActions.js
Labels: kind/bug

#1312 Add more tooltips to node pools list
  src/components/Cluster/ClusterDetail/V5ClusterDetailTable.js
  src/shared/constants/index.js
Labels: kind/ux-enhancement

#1310 Clusters list performance improvements
  src/actions/clusterActions.js
  src/components/Cluster/ClusterDetail/V4ClusterDetailTable.js
  src/components/Home/ClusterDashboardItem.js
  src/components/Home/ClusterDashboardResourcesV4.js
  src/components/Home/Home.js
  src/reducers/clusterReducer.js
  src/selectors/clusterSelectors.js
Labels: kind/refactor

#1332 Fix cluster list selector
  src/components/Home/Home.js
  src/selectors/clusterSelectors.js
Labels: kind/bug

#1316 Add new action for refreshing clusters list
  src/actions/actionTypes.js
  src/actions/batchedActions.js
  src/actions/clusterActions.js
  src/reducers/clusterReducer.js
Labels: kind/feature

#1318 Restructure CI to run checks in parallel
  .circleci/config.yml
  package.json
Labels: kind/dev-change

#1333 Redirect from details after deletion
  src/actions/clusterActions.js
  src/components/Cluster/ClusterDetail/ClusterDetailView.js
Labels: kind/bug

#1317 App readme "backend" changes.
  package.json
  src/actions/__tests__/appActions.js
  src/actions/actionTypes.js
  src/actions/appActions.js
  src/components/AppCatalog/AppDetail/AppDetail.js
  src/components/UI/AppContainer.js
  src/reducers/catalogReducer.js
  src/shared/constants/routes.js
  yarn.lock
Labels: kind/feature

#1320 Add ingress instructions tab to cluster detail view
  src/components/Cluster/ClusterDetail/ClusterDetailView.js
  src/components/Cluster/ClusterDetail/Ingress/Components.tsx
  src/components/Cluster/ClusterDetail/Ingress/Ingress.tsx
  src/components/Cluster/ClusterDetail/Ingress/Option.tsx
  src/components/Cluster/ClusterDetail/Ingress/Ports.tsx
  src/components/Cluster/ClusterDetail/URIBlock.js
  src/components/Cluster/ClusterDetail/__tests__/Ingress.ts
  src/components/Cluster/ClusterDetail/__tests__/URIBlock.js
  src/shared/constants/index.js
  src/shared/types.ts
  testUtils/renderUtils.js
Labels: kind/feature

#1334 Add warning if there is a newer version of the app available
  __tests__/AccountSettings.js
  __tests__/AdminLogin.js
  __tests__/AppCatalog.js
  __tests__/AppDetailPane.js
  __tests__/ClusterManagement.js
  __tests__/ForgotPassword.js
  __tests__/GettingStarted.js
  __tests__/KeyPairs.js
  __tests__/Login.js
  __tests__/Logout.js
  __tests__/Organization.js
  __tests__/SignUp.js
  __tests__/Users.js
  __tests__/V4AWSClusterManagement.js
  __tests__/V4AzureClusterManagement.js
  __tests__/V4KVMClusterManagement.js
  __tests__/V5ClusterManagement.js
  scripts/start.sh
  src/actions/actionTypes.js
  src/actions/metadataActions.ts
  src/components/App.tsx
  src/components/Footer/Footer.tsx
  src/components/Footer/FooterUpdateButton.tsx
  src/components/Footer/FooterUtils.ts
  src/components/Footer/FooterVersion.tsx
  src/components/Footer/__tests__/Footer.ts
  src/components/UI/LoadingIndicator.js
  src/index.html
  src/lib/flashMessage.js
  src/metadata.json
  src/model/clients/SelfClient.ts
  src/model/clients/__tests__/SelfClient.ts
  src/model/services/metadata/__tests__/configuration.ts
  src/model/services/metadata/configuration.ts
  src/model/services/metadata/index.ts
  src/model/services/metadata/types.ts
  src/reducers/mainReducer.js
  src/reducers/types.ts
  src/selectors/metadataSelectors.ts
  src/shared/constants/index.js
  src/stores/configureStore.ts
  src/styles/_base.sass
  testUtils/mockHttpCalls/index.js
  testUtils/mockHttpCalls/metadata.ts
  testUtils/modelMocks.js
  testUtils/preloginState.js
  testUtils/renderUtils.js
  testUtils/setupTests.js
  webpack.prod.js
Labels: kind/feature

#1336 Fix app creation
  __tests__/AppCatalog.js
  src/components/AppCatalog/AppDetail/AppDetail.js
  src/components/AppCatalog/AppList/AppList.js
  src/components/AppCatalog/CatalogList/CatalogRepo.js
  src/components/UI/AppContainer.js
  src/components/UI/AppDetails/AppDetails.js
  src/shared/constants/routes.js
Labels: kind/bug

#1342 run all ci jobs for vX.X.X tags & all branches
  .circleci/config.yml
Labels: kind/bug, kind/dev-change

#1343 Display warning if keypair TTL > 30 days
  __tests__/KeyPairs.js
  src/components/Cluster/ClusterDetail/ExpiryHoursPicker.js
  src/components/Cluster/ClusterDetail/KeyPairCreateModal.js
  src/shared/constants/index.js
  src/styles/components/_expiry_hours_picker.sass
Labels: kind/ux-enhancement

#1349 Fix get started button positioning on small screens for v4 clusters
  src/components/Cluster/ClusterDetail/URIBlock.js
  src/components/Cluster/ClusterDetail/V4ClusterDetailTable.js
  src/components/Cluster/ClusterDetail/V5ClusterDetailTable.js
Labels: kind/bug

#1350 Use templated endpoints in index.html
  src/index.html
  webpack.common.js
Labels: kind/dev-change

#1360 Show app release status in the app detail modal.
  src/components/Cluster/ClusterDetail/AppDetailsModal/InitialPane.js
Labels: kind/change

#1366 Use tabs in the app detail view.
  src/components/Cluster/ClusterDetail/ClusterDetailView.js
  src/components/UI/AppDetails/AppDetails.js
  src/components/UI/AppDetails/ChartVersionsTable.js
  src/components/UI/AppDetails/VersionsRow.js
  src/components/shared/Tabs.js
  src/components/shared/__tests__/Tabs.js
Labels: kind/change

#1367 Improve Error Handling when fetching Readmes
  src/actions/__tests__/appActions.js
  src/actions/appActions.js
  src/actions/errorActions.js
  src/components/AppCatalog/AppDetail/AppDetail.js
  src/components/UI/AppDetails/AppDetails.js
Labels: kind/bug

#1368 Add the possibility to provide environmental variables with a configuration file
  .gitignore
  package.json
  webpack.common.js
  yarn.lock
Labels: kind/dev-change

#1270 add spot instance ui stuff
  __tests__/AccountSettings.js
  __tests__/AppCatalog.js
  __tests__/AppDetailPane.js
  __tests__/ClusterManagement.js
  __tests__/ForgotPassword.js
  __tests__/GettingStarted.js
  __tests__/Login.js
  __tests__/Logout.js
  __tests__/Organization.js
  __tests__/SignUp.js
  __tests__/Users.js
  __tests__/V4AWSClusterManagement.js
  __tests__/V4AzureClusterManagement.js
  __tests__/V4KVMClusterManagement.js
  __tests__/V5ClusterManagement.js
  src/components/Cluster/ClusterDetail/AddNodePool.js
  src/components/Cluster/ClusterDetail/NodePool.tsx
  src/components/Cluster/ClusterDetail/V5ClusterDetailTable.js
  src/components/Cluster/NewCluster/CreateNodePoolsCluster.js
  src/components/UI/Checkbox.js
  src/components/UI/NumberPicker.js
  src/shared/constants/index.js
  src/shared/types.ts
Labels: kind/feature

#1379 Fix clusters not being updated after created with external tools
  src/actions/clusterActions.js
Labels: kind/bug

#1387 Adjust the guide to support optional ingress controller clusters.
  src/actions/appActions.js
  src/components/GettingStarted/GettingStarted.js
  src/components/GettingStarted/Steps/ConfigureKubectl.js
  src/components/GettingStarted/Steps/InstallIngress.js
  src/components/GettingStarted/Steps/Overview.js
  src/components/GettingStarted/Steps/SimpleExample.js
  src/components/UI/ClusterIDLabel.js
  src/selectors/clusterSelectors.js
  src/shared/constants/routes.js
  src/styles/components/_step_selector.sass
Labels: kind/change

#1393 Update prompt output for the simple example.
  src/components/GettingStarted/Steps/SimpleExample.js
Labels: kind/bug

#1399 Open changelog links in new tab
  src/components/UI/ComponentChangelog.js
Labels: kind/change

#1401 Show a more appropriate error for certain cases of app creation failure.
  src/actions/appActions.js
  src/components/AppCatalog/AppDetail/InstallAppModal.js
Labels: kind/change

#1402 Catch only errors from renewing the token.
  src/lib/giantswarmClientPatcher.js
Labels: kind/bug

#1400 Stay on app page after installing app
  __tests__/AppCatalog.js
  __tests__/AppDetailPane.js
  __tests__/ClusterManagement.js
  __tests__/KeyPairs.js
  __tests__/V4AWSClusterManagement.js
  __tests__/V4AzureClusterManagement.js
  __tests__/V4KVMClusterManagement.js
  __tests__/V5ClusterManagement.js
  src/actions/batchedActions.js
  src/components/AppCatalog/AppDetail/InstallAppModal.js
  src/components/Cluster/Cluster.js
  src/components/Cluster/ClusterDetail/ClusterDetail.js
  src/components/Cluster/ClusterDetail/ClusterDetailView.js
  src/components/Home/ClusterDashboardItem.js
  src/components/Organizations/Detail/View.js
  src/components/UI/AppDetails/AppDetails.js
  src/components/shared/Tabs.js
  src/components/shared/Tabs.tsx
  src/components/shared/__tests__/Tabs.js
  src/components/shared/__tests__/Tabs.tsx
  src/shared/constants/routes.js
  testUtils/renderUtils.js
Labels: kind/ux-enhancement

#1413 introduce & use foreground color to theme
  .circleci/config.yml
  src/components/Cluster/ClusterDetail/Ingress/Components.tsx
  src/components/Cluster/ClusterDetail/UserInstalledApps/InstalledApp.js
  src/components/Cluster/ClusterDetail/V5ClusterDetailTable.js
  src/components/Home/ClusterDashboardItem.js
  src/components/UI/ReleaseComponentLabel.js
  src/components/UI/ValueLabel.tsx
  src/styles/index.ts
  src/styles/theme.ts
Labels: kind/dev-change, kind/refactor

#1414 Wire up a default request timeout configuration property.
  .circleci/config.yml
  helm/happa-chart/templates/configmap.yaml
  helm/happa-chart/templates/deployment.yaml
  jest.config.js
  scripts/start.sh
  src/components/Layout.js
  src/components/index.tsx
  src/index.html
Labels: kind/ux-enhancement
