Repository giantswarm/happa, pull requests merged in 2020-02, with the labels that each got.

#1080 [CHANGE] Update circle CI node.js version to 12.15.0
  .circleci/config.yml
Labels: kind/chore

#1082 [BUGFIX] Add apps and keypair calls to cluster detail batched function
  src/actions/actionTypes.js
  src/actions/batchedActions.js
  src/actions/clusterActions.js
  src/components/Cluster/ClusterDetail/KeyPairs.js
  src/reducers/clusterReducer.js
Labels: kind/bug

#1085 Remove PR title prefix validation
  .github/pull_request_template.md
  .github/release-template.yml
  .github/workflows/main.yml
Labels: kind/dev-change

#1083 Prevent v4 to v5 upgrade.
  src/components/Cluster/ClusterDetail/ClusterDetail.js
  src/components/Cluster/ClusterDetail/ClusterDetailView.js
  src/selectors/clusterSelectors.js
  src/shared/constants/index.js
  src/utils/__tests__/canClusterUpgrade.js
  src/utils/clusterUtils.js
Labels: kind/ux-enhancement

#1086 Delete cluster on 404
  src/actions/clusterActions.js
  src/reducers/clusterReducer.js
Labels: kind/bug

#1087 Reset create organization modal before closing
  src/components/Modals/Modals.js
Labels: kind/bug

#1088 Fix tag filter now that we prepend with v.
  .circleci/config.yml
Labels: kind/dev-change

#1089 Fix JWT token not being used after being refreshed
  src/actions/userActions.js
  src/components/Auth/AdminLogin.js
  src/lib/giantswarmClientPatcher.js
  src/reducers/appReducer.js
Labels: kind/bug

#1099 Wait for delete before redirecting.
  src/actions/batchedActions.js
Labels: kind/change

#1100 Add error reducer
  src/reducers/errorReducer.js
  src/reducers/index.js
Labels: kind/change

#1102 Write integration test for the Sign Up user flow
  __tests__/SignUp.js
  src/components/SignUp/SignUp.js
Labels: kind/change

#1101 Add entity error reducer and ErrorFallback component
  src/components/Home/ClusterDashboardItem.js
  src/components/UI/ErrorFallback.js
  src/reducers/entityErrorReducer.js
  src/reducers/errorReducer.js
  src/reducers/index.js
  src/selectors/clusterSelectors.js
Labels: kind/ux-enhancement

#1104 Change ErrorFallback so that it accepts an array
  src/components/Home/ClusterDashboardItem.js
  src/components/UI/ErrorFallback.js
Labels: kind/change

#1107 Update circle CI node.js version to 12.16.0
  .circleci/config.yml
Labels: kind/dev-change

#1106 Write integration test for the OAuth admin login user flow
  __tests__/AdminLogin.js
  src/components/Auth/OAuthCallback.js
  testUtils/renderUtils.js
Labels: kind/change

#1103 Fallback message when nodes are not ready yet
  __tests__/V5ClusterManagement.js
  src/components/Cluster/ClusterDetail/NodesRunning.js
  src/components/Home/ClusterDashboardResources.js
  src/shared/constants/fallbackMessages.js
  src/shared/constants/index.js
Labels: kind/ux-enhancement

#1105 Cleanup in cluster actions
  src/actions/clusterActions.js
Labels: kind/dev-change

#1108 Change nodes not ready condition
  src/components/Cluster/ClusterDetail/NodesRunning.js
  src/components/Cluster/ClusterDetail/V4ClusterDetailTable.js
  src/components/Cluster/ClusterDetail/V5ClusterDetailTable.js
  src/components/Home/ClusterDashboardResources.js
  src/utils/clusterUtils.js
Labels: kind/change

#1115 Universal loading selector for loadingFlags and errors objects
  src/components/AppCatalog/AppDetail/AppDetail.js
  src/components/Cluster/ClusterDetail/ClusterDetailView.js
  src/components/Cluster/ClusterDetail/KeyPairs.js
  src/components/Cluster/ClusterDetail/V5ClusterDetailTable.js
  src/components/Home/ClusterDashboardResources.js
  src/components/Layout.js
  src/components/Organizations/Organizations.js
  src/selectors/clusterSelectors.js
Labels: kind/dev-change

#1116 Temporary fix for last updated label
  src/components/Cluster/ClusterDetail/V4ClusterDetailTable.js
  src/components/Cluster/ClusterDetail/V5ClusterDetailTable.js
  src/components/Home/Home.js
Labels: kind/change

#1109 Adapt Happa to use new error/loading reducers in clusterReducer and cluster views
  __tests__/V5ClusterManagement.js
  src/actions/actionTypes.js
  src/actions/appActions.js
  src/components/Cluster/ClusterDetail/ClusterApps.js
  src/components/Cluster/ClusterDetail/ClusterDetailView.js
  src/components/Cluster/ClusterDetail/__tests__/ClusterApps.js
  src/components/Home/ClusterDashboardItem.js
  src/components/Home/Home.js
  src/reducers/clusterReducer.js
  src/selectors/clusterSelectors.js
Labels: kind/refactor

#1122 Handle releases fetch failure in releasesAction
  src/actions/releaseActions.js
Labels: kind/change

#1123 selectErrorByIdAndAction to use helper
  src/selectors/clusterSelectors.js
Labels: kind/dev-change

#1125 Entity loading reducer
  src/actions/clusterActions.js
  src/actions/nodePoolActions.js
  src/components/Cluster/ClusterDetail/ClusterDetailView.js
  src/components/Cluster/ClusterDetail/V5ClusterDetailTable.js
  src/components/Organizations/Detail/Detail.js
  src/reducers/clusterReducer.js
  src/reducers/entityErrorReducer.js
  src/reducers/entityLoadingReducer.js
  src/reducers/index.js
  src/selectors/clusterSelectors.js
Labels: kind/bug

#1126 Sort store objects
  src/reducers/index.js
Labels: kind/dev-change

#1127 Change error messages when releases fetching or data processing fails
  src/actions/releaseActions.js
Labels: kind/ux-enhancement

#1128 Revert "Change nodes not ready condition"
  src/components/Cluster/ClusterDetail/NodesRunning.js
  src/components/Cluster/ClusterDetail/V4ClusterDetailTable.js
  src/components/Cluster/ClusterDetail/V5ClusterDetailTable.js
  src/components/Home/ClusterDashboardResources.js
  src/utils/clusterUtils.js
Labels: kind/removal

#1129 Revert "Fallback message when nodes are not ready yet"
  src/components/Cluster/ClusterDetail/NodesRunning.js
  src/components/Home/ClusterDashboardResources.js
  src/shared/constants/fallbackMessages.js
  src/shared/constants/index.js
Labels: kind/removal

#1121 Override crypto-js with updated version
  package.json
  yarn.lock
Labels: dependencies

#1137 Fallback message when nodes are not ready yet with UTC
  src/components/Cluster/ClusterDetail/NodesRunning.js
  src/components/Cluster/ClusterDetail/V4ClusterDetailTable.js
  src/components/Cluster/ClusterDetail/V5ClusterDetailTable.js
  src/components/Home/ClusterDashboardResources.js
  src/shared/constants/fallbackMessages.js
  src/shared/constants/index.js
  src/utils/clusterUtils.js
Labels: kind/ux-enhancement

#1130 Update production build
  .circleci/config.yml
  Dockerfile
  helm/happa-chart/templates/deployment.yaml
  helm/happa-chart/templates/ingress.yaml
  helm/happa-chart/values.yaml
  nginx.conf
  scripts/start.sh
  webpack.common.js
  webpack.prod.js
Labels: kind/refactor

#1140 Remove local certs
  test/certs/README
  test/certs/crt
  test/certs/key
Labels: kind/dev-change, kind/refactor

#1142 shrink images
  src/images/app_icon.png
  src/images/app_icon_128.png
  src/images/app_icon_192.png
  src/images/app_icons/calico@2x.png
  src/images/app_icons/cert_exporter@2x.png
  src/images/app_icons/chart_operator@2x.png
  src/images/app_icons/cluster_autoscaler@2x.png
  src/images/app_icons/container_linux@2x.png
  src/images/app_icons/coredns@2x.png
  src/images/app_icons/docker@2x.png
  src/images/app_icons/etcd@2x.png
  src/images/app_icons/kube_state_metrics@2x.png
  src/images/app_icons/kubernetes@2x.png
  src/images/app_icons/kubernetes_components@2x.png
  src/images/app_icons/kubernetes_manifest@2x.png
  src/images/app_icons/metrics_server@2x.png
  src/images/app_icons/net_exporter@2x.png
  src/images/app_icons/nginx_ingress_controller@2x.png
  src/images/app_icons/node_exporter@2x.png
  src/images/app_icons/rbac_and_psp_defaults@2x.png
  src/images/app_icons/tiller@2x.png
  src/images/repo_icons/community.png
  src/images/repo_icons/incubator.png
  src/images/repo_icons/managed.png
Labels: kind/dev-change, kind/refactor

#1141 Not ready in cluster details instad n/a or 0 nodes
  src/components/Cluster/ClusterDetail/NodesRunning.js
  src/components/Cluster/ClusterDetail/V4ClusterDetailTable.js
  src/components/Cluster/ClusterDetail/WorkerNodesAWS.js
  src/components/Cluster/ClusterDetail/WorkerNodesAzure.js
  src/components/Cluster/ClusterDetail/WorkerNodesKVM.js
  src/components/Home/ClusterDashboardResources.js
  src/styles/index.js
Labels: kind/ux-enhancement

#1144 Use [hash] for js asset in dev
  webpack.dev.js
Labels: kind/dev-change

#1143 Fix flash in v4 cluster details views
  src/components/Cluster/ClusterDetail/V4ClusterDetailTable.js
Labels: kind/ux-enhancement

#1138 Remove deleted cluster from calls in batchedRefreshClusters
  src/actions/clusterActions.js
  src/actions/nodePoolActions.js
Labels: kind/bug

#899 Add Multi-AZ support for Azure clusters
  __tests__/V4AzureClusterManagement.js
  __tests__/V4KVMClusterManagement.js
  src/components/Cluster/ClusterDetail/V4ClusterDetailTable.js
  src/components/Cluster/ClusterDetail/WorkerNodesAzure.js
  src/components/Cluster/NewCluster/CreateRegularCluster.js
  src/components/Cluster/NewCluster/V4AvailabilityZonesSelector.js
  src/components/UI/AvailabilityZonesLabel.js
  src/components/UI/AvailabilityZonesLabels.js
  src/index.html
  src/shared/constants/index.js
  testUtils/mockHttpCalls/clusters.js
  testUtils/mockHttpCalls/info.js
  testUtils/mockHttpCalls/releases.js
Labels: kind/feature

#1148 Fix capabilities not being injected during the deployment process
  .circleci/config.yml
  src/index.html
Labels: kind/bug

#1120 Add tests for app installation and editing
  __tests__/AppCatalog.js
  src/components/Cluster/ClusterDetail/AppDetailsModal.js
  src/components/Cluster/ClusterDetail/ClusterApps.js
  src/components/Cluster/ClusterDetail/YamlFileUpload.js
  src/lib/flashMessage.js
  testUtils/mockHttpCalls/apps.js
Labels: kind/change

#1146 Change organization tests to not use persisted nock mocks.
  __tests__/Organization.js
  __tests__/V4AWSClusterManagement.js
  __tests__/V5ClusterManagement.js
Labels: kind/refactor

#1149 Add _REQUEST suffix to actions
  src/actions/actionTypes.js
  src/actions/appActions.js
  src/actions/appConfigActions.js
  src/actions/appSecretActions.js
  src/actions/catalogActions.js
  src/actions/clusterActions.js
  src/actions/forgotPasswordActions.js
  src/actions/invitationActions.js
  src/actions/nodePoolActions.js
  src/actions/organizationActions.js
  src/actions/userActions.js
  src/reducers/catalogsReducer.js
  src/reducers/clusterReducer.js
  src/reducers/credentialReducer.js
  src/reducers/entityErrorReducer.js
  src/reducers/entityLoadingReducer.js
  src/reducers/invitationReducer.js
  src/reducers/modalReducer.js
  src/reducers/nodePoolsReducer.js
  src/reducers/organizationReducer.js
  src/reducers/releaseReducer.js
  src/reducers/userReducer.js
  src/selectors/clusterSelectors.js
  src/selectors/selectorUtils.js
Labels: kind/change

#1150 Fix app details infinite spinner
  src/components/AppCatalog/AppDetail/AppDetail.js
Labels: kind/bug

#1151 toggleChecked only returns function if it exists
  src/components/UI/AvailabilityZonesLabel.js
Labels: kind/bug

#1153 Update resources.
  helm/happa-chart/templates/deployment.yaml
  helm/happa-chart/templates/psp.yaml
Labels: kind/dev-change

#1152 Fix 'cannot read property 'displayname' of null' error in dev.
  .babelrc
  package.json
  src/components/app.js
  webpack.common.js
  yarn.lock
Labels: kind/dev-change

#1154 Add reset password tests
  __tests__/ForgotPassword.js
  __tests__/Logout.js
  __tests__/PasswordForgot.js
  __tests__/SignUp.js
  src/components/AccountSettings/__tests__/ChangePasswordForm.js
  src/components/ForgotPassword/SetPassword.js
  src/components/SignUp/PasswordField.js
  testUtils/renderUtils.js
Labels: kind/change

#1166 Clean up V4AzureClusterManagement tests
  __tests__/V4AzureClusterManagement.js
Labels: kind/dev-change

#1165 Redirect when cluster id doesn't exist
  src/components/Cluster/ClusterDetail/ClusterDetail.js
  src/selectors/clusterSelectors.js
Labels: kind/feature

#1167 Added a missing word
  src/components/Organizations/Detail/CredentialsForm.js
Labels: kind/ux-enhancement

#1169 Error handling in cluster creation views
  src/actions/clusterActions.js
  src/components/Cluster/NewCluster/CreateNodePoolsCluster.js
  src/components/Cluster/NewCluster/CreateRegularCluster.js
  src/reducers/errorReducer.js
Labels: kind/bug

#1168 Add integration tests for the Users page and modals
  __tests__/Users.js
  src/components/Users/InviteUserModal/InviteUserForm.js
  testUtils/mockHttpCalls/index.js
  testUtils/mockHttpCalls/invites.js
  testUtils/mockHttpCalls/organizations.js
  testUtils/mockHttpCalls/user.js
Labels: kind/change

#1170 Ellipsis in members list and as a composable
  src/components/Cluster/ClusterDetail/NodePool.js
  src/components/Organizations/Detail/View.js
  src/styles/index.js
Labels: kind/ux-enhancement

#1171 Show app name instead of object Object in flash and error to reducer
  src/actions/appActions.js
Labels: kind/bug

#1164 Add a version picker component.
  src/components/UI/DropdownMenu.js
  src/components/UI/StyleGuide.js
  src/components/UI/VersionPicker/VersionPicker.js
  src/components/UI/VersionPicker/__tests__/VersionPicker.js
Labels: kind/feature

#1172 Cluster name input autofocus and autoselect
  src/components/Cluster/NewCluster/CreateNodePoolsCluster.js
Labels: kind/ux-enhancement

#1173 Try to catch the api endpoint that is triggering the error
  src/components/Cluster/ClusterDetail/KeyPairs.js
Labels: kind/dev-change

#1175 moved Root app Component to own file
  src/components/App.js
  src/components/index.js
  webpack.common.js
Labels: kind/dev-change

#1176 Clusters list tests
  __tests__/ClusterManagement.js
  src/components/Home/ClusterDashboardResources.js
  src/components/Home/Home.js
  src/index.html
  testUtils/mockHttpCalls/clusters.js
Labels: kind/change

#1178 revert to correct development index.html
  src/index.html
Labels: kind/dev-change

#1181 Get started button tests
  __tests__/GettingStarted.js
Labels: kind/dev-change

#1177 Make the whole catalog repo clickable
  src/components/AppCatalog/CatalogList/CatalogExternalLink.js
  src/components/AppCatalog/CatalogList/CatalogList.js
  src/components/AppCatalog/CatalogList/CatalogRepo.js
  src/components/UI/AppContainer.js
  src/styles/components/_app_catalog.sass
Labels: kind/ux-enhancement

#1180 Clean up automated tests
  __tests__/AccountSettings.js
  __tests__/AdminLogin.js
  __tests__/AppCatalog.js
  __tests__/ClusterManagement.js
  __tests__/ForgotPassword.js
  __tests__/GettingStarted.js
  __tests__/Login.js
  __tests__/Logout.js
  __tests__/Organization.js
  __tests__/SignUp.js
  __tests__/Users.js
  __tests__/V4AWSClusterManagement.js
  __tests__/V4AzureClusterManagement.js
  __tests__/V4KVMClusterManagement.js
  __tests__/V5ClusterManagement.js
  jest.config.js
  src/components/AccountSettings/__tests__/ChangeEmailForm.js
  src/components/AccountSettings/__tests__/ChangePasswordForm.js
  src/components/Cluster/ClusterDetail/ClusterApps.js
  src/components/Cluster/ClusterDetail/__tests__/ScaleClusterModal.js
  src/components/SignUp/SignUp.js
  testUtils/setupTests.js
Labels: kind/dev-change

#1145 Create model layer for the control plane API
  __tests__/AccountSettings.js
  __tests__/AdminLogin.js
  __tests__/AppCatalog.js
  __tests__/ClusterManagement.js
  __tests__/ForgotPassword.js
  __tests__/GettingStarted.js
  __tests__/KeyPairs.js
  __tests__/Login.js
  __tests__/Logout.js
  __tests__/Organization.js
  __tests__/SignUp.js
  __tests__/Users.js
  __tests__/V4AWSClusterManagement.js
  __tests__/V4AzureClusterManagement.js
  __tests__/V4KVMClusterManagement.js
  __tests__/V5ClusterManagement.js
  jest.config.js
  package.json
  src/actions/userActions.js
  src/components/Auth/AdminLogin.js
  src/components/Auth/OAuthCallback.js
  src/lib/auth0.js
  src/lib/giantswarmClientPatcher.js
  src/model/clients/GiantSwarmClient.js
  src/model/clients/HttpClient.js
  src/model/clients/index.js
  src/model/services/giantSwarm/constants.js
  src/model/services/giantSwarm/index.js
  src/model/services/giantSwarm/info.js
  src/model/storage/LocalStorage.js
  src/reducers/appReducer.js
  src/selectors/authSelectors.js
  testUtils/modelMocks.js
  yarn.lock
Labels: kind/feature

#1182 Only accept json as response in GS client
  src/model/clients/GiantSwarmClient.js
Labels: kind/dev-change
