Repository giantswarm/happa, pull requests merged in 2020-08, with the labels that each got.

#1708 Fix empty release rows in cluster creation for non-admins
  __tests__/ClusterManagement.js
  src/selectors/releaseSelectors.ts
  src/stores/releases/actions.ts
  src/stores/releases/reducer.ts
  src/stores/releases/types.ts
Labels: kind/bug

#1709 bump some dependencies
  package.json
  yarn.lock
Labels: dependencies

#1712 Refactor cluster details sass
  src/components/Cluster/ClusterDetail/AppDetailsModal/AppDetailsModal.js
  src/components/Cluster/ClusterDetail/AppDetailsModal/InitialPane.js
  src/components/Cluster/ClusterDetail/CertificateOrgsLabel.js
  src/components/Cluster/ClusterDetail/ClusterDetailView.js
  src/components/Cluster/ClusterDetail/KeyPairDetailsModal.js
  src/components/Cluster/ClusterDetail/KeyPairs.js
  src/components/UI/DetailList.js
  src/styles/app.sass
  src/styles/components/_cluster_details.sass
  src/styles/components/_create_key_pair.sass
Labels: kind/refactor

#1711 azure v5: enable scaling on NP creation
  src/components/Cluster/ClusterDetail/AddNodePool.js
  src/shared/constants/index.js
Labels: kind/dev-change

#1714 Make upgrade version configurable for admins
  src/components/Cluster/ClusterDetail/ClusterDetail.js
  src/components/Cluster/ClusterDetail/ClusterDetailView.js
  src/components/Cluster/ClusterDetail/InstanceTypeSelector/InstanceTypeSelector.tsx
  src/components/Cluster/ClusterDetail/UpgradeClusterModal.js
  src/components/Cluster/ClusterDetail/UpgradeClusterModalVersionChanger.tsx
  src/components/Cluster/ClusterDetail/__tests__/UpgradeClusterModal.tsx
  src/components/Cluster/NewCluster/ReleaseSelector/ReleaseRow.tsx
  src/components/Cluster/NewCluster/ReleaseSelector/ReleaseSelector.tsx
  src/components/Cluster/NewCluster/ReleaseSelector/__tests__/ReleaseSelector.ts
  src/components/Home/UpgradeNotice.tsx
  src/components/UI/ExpandableSelector/Items.tsx
  src/components/UI/ExpandableSelector/Selector.tsx
  src/selectors/__tests__/clusterSelectors.ts
  src/selectors/clusterSelectors.js
Labels: kind/ux-enhancement

#1727 Redirect user to the login page if initial data fetch fails
  src/actions/batchedActions.js
Labels: kind/bug

#1725 Use alternative unused expressions typescript-eslint rule
  .eslintrc.js
  src/actions/metadataActions.ts
  src/components/AppCatalog/CatalogList/CatalogExternalLink.js
  src/components/Cluster/ClusterDetail/MasterNodes/MasterNodesConverter.tsx
  src/components/Cluster/ClusterDetail/MasterNodes/MasterNodesInfo.tsx
  src/components/Cluster/ClusterDetail/NodePool.tsx
  src/components/Cluster/NewCluster/MasterNodes.tsx
  src/components/Home/UpgradeNotice.tsx
  src/components/UI/Inputs/FileInput.tsx
  src/components/UI/Inputs/Input.tsx
  src/components/UI/ViewEditName.tsx
  src/lib/errors/ErrorReporter.js
  src/lib/flashMessage.js
Labels: kind/dev-change

#1729 remove 'next' button from install app modal
  src/components/AppCatalog/AppDetail/ClusterPicker.js
  src/components/AppCatalog/AppDetail/InstallAppModal.js
Labels: kind/bug

#1730 Sass refactoring
  src/components/GettingStarted/Steps/ConfigureKubectl.js
  src/components/GettingStarted/Steps/ConfigureKubectlAlternative.js
  src/components/GettingStarted/Steps/SimpleExample.js
  src/components/UI/Aside.js
  src/components/Users/UsersTable.js
  src/styles/app.sass
  src/styles/components/_text.sass
  src/styles/components/_toggle_alternative.sass
  src/styles/components/_users_table.sass
Labels: kind/refactor

#1732 force serialize-javascript to 4.0.0
  package.json
  yarn.lock
Labels: kind/security

#1733 Fix error on app values/secrets upload cancellation
  src/components/AppCatalog/AppDetail/InstallAppModal.js
Labels: kind/bug

#1734 add ErrorBoundary around Clusterlist to catch Errors there
  src/components/Home/ClusterDashboardItem.js
  src/components/UI/ErrorFallback.tsx
  src/components/UI/ErrorText.tsx
  src/components/shared/ErrorBoundary.tsx
Labels: kind/change

#1747 Fix cannot set state of unmounted component warning in test.
  src/components/Users/Users.js
Labels: kind/bug

#1713 create install ingress actions & reenable tests
  src/components/Cluster/ClusterDetail/Ingress/InstallIngressButton.tsx
  src/components/Cluster/ClusterDetail/Ingress/__tests__/Ingress.ts
  src/components/Cluster/ClusterDetail/Ingress/__tests__/InstallIngressButton.ts
  src/selectors/clusterSelectors.js
  src/selectors/ingressTabSelectors.ts
  src/stores/appcatalog/__tests__/actions.ts
  src/stores/appcatalog/actions.ts
  src/stores/appcatalog/types.ts
  src/stores/asynchronousAction.ts
  testUtils/ingressCatalogStateMocks.ts
Labels: kind/refactor

#1749 customer bug: nginx IC is not visible under installed apps, if ICs are optional
  src/components/Cluster/ClusterDetail/ClusterApps.js
Labels: kind/bug

#1752 [CP Auth 2/5]: Add OIDC login helpers
  package.json
  src/lib/OAuth2/OAuth2.ts
  src/lib/OAuth2/OAuth2CustomMetadata.ts
  src/lib/OAuth2/OAuth2User.ts
  yarn.lock
Labels: kind/dev-change

#1751 [CP Auth 1/5]: Add environment configuration
  .circleci/config.yml
  README.md
  helm/happa/ci/default-values.yaml
  helm/happa/templates/configmap.yaml
  helm/happa/templates/deployment.yaml
  jest.config.js
  scripts/start.sh
  scripts/webpack/proxyPlugin.js
  src/@types/global.d.ts
  src/index.html
  src/shared/FeatureFlags.ts
  webpack.common.js
  webpack.dev.js
Labels: kind/dev-change

#1768 Fix app name validation in the app installation modal
  src/components/AppCatalog/AppDetail/InstallAppModal.js
  src/components/AppCatalog/AppDetail/InstallAppModalUtils.ts
  src/components/AppCatalog/AppDetail/__tests__/InstallAppModalUtils.ts
Labels: kind/bug

#1769 Update Getting Started code example to mention kubectl label selector
  src/components/GettingStarted/Steps/SimpleExample.js
Labels: kind/ux-enhancement

#1753 [CP Auth 3/5]: add CP client and catalog service
  package.json
  src/components/Auth/AdminLogin.tsx
  src/components/Cluster/ClusterDetail/__tests__/UpgradeClusterModal.tsx
  src/components/index.tsx
  src/model/clients/CPClient.ts
  src/model/clients/FetchAdapter.ts
  src/model/clients/GenericResponse.js
  src/model/services/controlplane/appcatalogs/appcatalogs.ts
  src/model/services/controlplane/appcatalogs/types.ts
  src/model/services/controlplane/base.ts
  src/reducers/types.ts
  src/selectors/ingressTabSelectors.ts
  src/stores/appcatalog/__tests__/actions.ts
  src/stores/appcatalog/actions.ts
  src/stores/appcatalog/reducer.ts
  src/stores/appcatalog/types.ts
  src/stores/configureStore.ts
  webpack.common.js
  yarn.lock
Labels: kind/dev-change

#1772 Add creation in progress label
  src/components/Cluster/ClusterDetail/RegionAndVersions.js
  src/components/Home/ClusterDashboardItem.js
  src/components/Home/ClusterStatus.tsx
  src/components/Home/UpgradeNotice.tsx
  src/components/Home/__tests__/ClusterStatus.tsx
  src/components/Organizations/Detail/View.js
Labels: kind/ux-enhancement

#1770 proxy external app catalog through happa nginx
  Dockerfile
  nginx.conf
  scripts/start.sh
  src/actions/catalogActions.js
  webpack.dev.js
Labels: kind/refactor

#1767 [CP Auth 4/5]: add the CP Auth object and redux logic
  src/actions/batchedActions.js
  src/components/index.tsx
  src/lib/CPAuth/CPAuth.ts
  src/lib/CPAuth/config.ts
  src/reducers/index.js
  src/shared/constants/routes.js
  src/stores/configureStore.ts
  src/stores/cpauth/actions.ts
  src/stores/cpauth/constants.ts
  src/stores/cpauth/middleware.ts
  src/stores/cpauth/reducer.ts
  src/stores/cpauth/selectors.ts
  src/stores/cpauth/types.ts
  testUtils/renderUtils.js
Labels: kind/dev-change

#1773 Fix or remove already fixed TODOs in code
  __tests__/V5ClusterManagement.js
  src/actions/clusterActions.js
  src/actions/userActions.js
  src/components/Auth/Login.tsx
  src/components/Cluster/ClusterDetail/NodesRunning.js
  src/components/Cluster/NewCluster/CreateNodePoolsCluster.js
  src/components/Cluster/NewCluster/CreateRegularCluster.js
  src/utils/clusterUtils.js
Labels: kind/refactor

#1547 [CP Auth 5/5]: Add React components and link everything together
  src/components/App.tsx
  src/components/Auth/CP/CPAuthProvider.tsx
  src/components/Auth/CP/CPLoginButton.tsx
  src/components/Auth/CP/CPLoginPage.tsx
  src/components/Auth/CP/CPLoginStatusText.tsx
  src/components/Auth/Logout.js
  src/components/Layout.js
  src/components/UI/Navigation/UserDropdown.js
  src/reducers/index.js
  src/reducers/types.ts
  src/stores/appcatalog/actions.ts
Labels: kind/feature

#1775 split container build & update nginx image version
  Dockerfile
  scripts/start.sh
Labels: kind/change

#1774 Rewrite HTTP clients in TypeScript
  __tests__/AccountSettings.js
  __tests__/AdminLogin.js
  __tests__/AppCatalog.js
  __tests__/AppDetailPane.js
  __tests__/ClusterManagement.js
  __tests__/ForgotPassword.js
  __tests__/GettingStarted.js
  __tests__/KeyPairs.js
  __tests__/Login.js
  __tests__/Logout.js
  __tests__/Organization.js
  __tests__/SignUp.js
  __tests__/Users.js
  __tests__/V4AWSClusterManagement.js
  __tests__/V4AzureClusterManagement.js
  __tests__/V4KVMClusterManagement.js
  __tests__/V5ClusterManagement.js
  src/actions/metadataActions.ts
  src/actions/userActions.js
  src/components/Footer/__tests__/Footer.ts
  src/model/clients/CPClient.ts
  src/model/clients/FetchAdapter.ts
  src/model/clients/GenericResponse.ts
  src/model/clients/GiantSwarmClient.js
  src/model/clients/GiantSwarmClient.ts
  src/model/clients/HttpClient.js
  src/model/clients/HttpClient.ts
  src/model/clients/SelfClient.ts
  src/model/clients/__tests__/GenericResponse.ts
  src/model/clients/__tests__/GiantSwarmClient.ts
  src/model/clients/__tests__/HttpClient.ts
  src/model/clients/__tests__/SelfClient.ts
  src/model/clients/index.js
  src/model/services/controlplane/appcatalogs/appcatalogs.ts
  src/model/services/controlplane/base.ts
  src/model/services/giantSwarm/__tests__/info.ts
  src/model/services/giantSwarm/constants.js
  src/model/services/giantSwarm/index.js
  src/model/services/giantSwarm/info.js
  src/model/services/giantSwarm/info.ts
  src/model/services/giantSwarm/types.ts
  src/model/services/metadata/__tests__/configuration.ts
  src/model/services/metadata/configuration.ts
  src/model/services/metadata/index.ts
  src/model/storage/LocalStorage.js
  src/model/storage/__tests__/LocalStorage.js
  testUtils/mockHttpCalls/metadata.ts
  testUtils/modelMocks.js
Labels: kind/refactor

#1777 Rewrite various helpers in TypeScript
  src/components/Cluster/ClusterDetail/AddNodePool.js
  src/components/Cluster/NewCluster/NewClusterWrapper.tsx
  src/components/UI/ViewEditName.tsx
  src/lib/__tests__/helpers.ts
  src/lib/helpers.js
  src/lib/helpers.tsx
  src/shared/types.ts
Labels: kind/refactor
