Repository giantswarm/happa, pull requests merged in 2020-05, with the labels that each got.

#1422 Revert moment dependency upgrade.
  package.json
  yarn.lock
Labels: kind/bug

#1428 Handle error if Key Pair creation fails due to PKI backend not being ready
  __tests__/KeyPairs.js
  src/components/Cluster/ClusterDetail/KeyPairCreateModal.js
  src/components/Cluster/ClusterDetail/KeyPairs.js
  src/components/Cluster/ClusterDetail/KeypairCreateModal/AddKeyPairErrorTemplate.tsx
  src/components/Cluster/ClusterDetail/KeypairCreateModal/AddKeyPairGenericError.tsx
  src/components/Cluster/ClusterDetail/KeypairCreateModal/AddKeyPairServiceUnavailableError.tsx
  src/components/Cluster/ClusterDetail/KeypairCreateModal/AddKeyPairSuccessTemplate.tsx
  src/components/Cluster/ClusterDetail/KeypairCreateModal/AddKeyPairTemplate.tsx
  src/components/Cluster/ClusterDetail/KeypairCreateModal/DownloadKubeconfigButton.tsx
  src/components/Cluster/ClusterDetail/KeypairCreateModal/KeyPairCreateModal.tsx
  src/components/Cluster/ClusterDetail/KeypairCreateModal/Utils.ts
  src/components/Cluster/ClusterDetail/KeypairCreateModal/__tests__/KeyPairCreateModal.tsx
  src/components/FlashMessages/FlashMessage.js
  src/components/UI/Button.js
  src/components/UI/LoadingIndicator.js
  src/shared/types.ts
  src/styles/components/_create_key_pair.sass
Labels: kind/ux-enhancement

#1442 Add a logo for aws-cni component
  src/components/Cluster/ClusterDetail/ClusterApps.js
  src/images/app_icons/awscni@2x.png
Labels: kind/change

#1448 show flatcar app for containerlinux components above 2345.3.1
  src/components/Cluster/ClusterDetail/ClusterApps.js
  src/images/app_icons/flatcar_linux@2x.png
  src/shared/constants/index.js
Labels: kind/change

#1452 Fix copy button display on the invite user modal on installations with longer base URLs
  src/components/Cluster/ClusterDetail/URIBlock.js
  src/components/Users/InviteUserModal/InviteUserSuccess.js
Labels: kind/bug

#1453 Refactor the 'AdminLogin' component
  src/components/Auth/AdminLogin.js
  src/components/Auth/AdminLogin.tsx
  src/lib/auth0.js
Labels: kind/refactor

#1455 Add forgotten InviteUser modal style changes
  src/components/Users/InviteUserModal/InviteUserSuccess.js
Labels: kind/dev-change

#1454 Add feature flags
  README.md
  src/shared/FeatureFlags.ts
  webpack.common.js
Labels: kind/dev-change

#1460 Show flatcar in release selection modal
  __tests__/ClusterManagement.js
  __tests__/V4AzureClusterManagement.js
  src/components/Modals/ReleaseDetailsModal.js
  testUtils/mockHttpCalls/releases.js
Labels: kind/feature

#1461 update giantswarm-js-client for cluster labeling & other recent changes
  yarn.lock
Labels: kind/dev-change

#1471 Create an general Input component from one in AppCatalog
  src/components/AppCatalog/AppDetail/ClusterPicker.js
  src/components/AppCatalog/AppDetail/FileInput.js
  src/components/AppCatalog/AppDetail/InstallAppForm.js
  src/components/UI/Input.tsx
Labels: kind/refactor

#1472 filter labels from api responses, add input validation for cluster la…
  src/actions/clusterActions.js
  src/shared/constants/index.js
  src/utils/clusterUtils.js
  src/utils/labelUtils.ts
Labels: kind/change, kind/feature

#1473 don't show the string 'flatcar' for containerlinux >= 2345.3.1
  __tests__/ClusterManagement.js
  src/components/Cluster/ClusterDetail/ClusterApps.js
  src/components/Modals/ReleaseDetailsModal.js
Labels: kind/refactor

#1474 Cluster label editing UI (without adding)
  jest.config.js
  src/components/Cluster/ClusterDetail/ClusterLabels/ClusterLabels.tsx
  src/components/Cluster/ClusterDetail/V5ClusterDetailTable.js
  src/components/UI/EditableValueLabel.tsx
  src/hooks/useValidatingInternalValue.ts
  testUtils/mockHttpCalls/clusters.js
Labels: kind/feature

#1482 Add HA Masters feature flag
  .eslintrc.js
  jest.config.js
  src/@types/global.d.ts
  src/components/Cluster/NewCluster/CreateNodePoolsCluster.js
  src/components/shared/Tabs.tsx
  src/shared/FeatureFlags.ts
  webpack.common.js
Labels: kind/dev-change

#1484 Add link to security policy
  SECURITY.md
Labels: kind/dev-change

#1499 Cluster labelling UI for adding
  src/components/Cluster/ClusterDetail/ClusterLabels/ClusterLabels.tsx
  src/components/Cluster/ClusterDetail/ClusterLabels/DeleteLabelButton.tsx
  src/components/Cluster/ClusterDetail/ClusterLabels/EditLabelTooltip.tsx
  src/components/UI/ClusterLabels/DeleteLabelButton.tsx
  src/components/UI/ClusterLabels/EditValueTooltip.tsx
  src/components/UI/ClusterLabels/LabelWrapper.tsx
  src/components/UI/ClusterLabels/ValidationError.tsx
  src/components/UI/ClusterLabels/ValidityStyledInputElement.tsx
  src/components/UI/ClusterLabels/ValueLabel.tsx
  src/components/UI/EditableValueLabel.tsx
  src/components/UI/ValueLabel.tsx
  src/utils/labelUtils.ts
Labels: kind/feature

#1500 copy chart to prepare for app migration
  helm/happa/Chart.yaml
  helm/happa/templates/_helpers.tpl
  helm/happa/templates/certs-secret.yaml
  helm/happa/templates/configmap.yaml
  helm/happa/templates/deployment.yaml
  helm/happa/templates/ingress.yaml
  helm/happa/templates/network-policy.yaml
  helm/happa/templates/psp.yaml
  helm/happa/templates/pull-secret.yml
  helm/happa/templates/rbac.yaml
  helm/happa/templates/service-account.yaml
  helm/happa/templates/service.yaml
  helm/happa/values.yaml
Labels: kind/dev-change

#1487 Move Happa to app collection deployment method
  .circleci/config.yml
  helm/happa/Chart.yaml
  helm/happa/ci/default-values.yaml
  helm/happa/templates/deployment.yaml
  helm/happa/values.yaml
Labels: kind/dev-change

#1502 remove old chart
  helm/happa-chart/Chart.yaml
  helm/happa-chart/templates/_helpers.tpl
  helm/happa-chart/templates/certs-secret.yaml
  helm/happa-chart/templates/configmap.yaml
  helm/happa-chart/templates/deployment.yaml
  helm/happa-chart/templates/ingress.yaml
  helm/happa-chart/templates/network-policy.yaml
  helm/happa-chart/templates/psp.yaml
  helm/happa-chart/templates/pull-secret.yml
  helm/happa-chart/templates/rbac.yaml
  helm/happa-chart/templates/service-account.yaml
  helm/happa-chart/templates/service.yaml
  helm/happa-chart/values.yaml
Labels: kind/dev-change

#1503 Underscore cleanup
  src/actions/invitationActions.js
  src/actions/userActions.js
  src/components/Cluster/ClusterDetail/UpgradeClusterModal.js
  src/components/Home/Home.js
  src/components/Modals/ReleaseDetailsModal.js
  src/components/UI/Navigation/OrganizationDropdown.js
  src/lib/helpers.js
Labels: kind/refactor

#1501 Cluster labelling wiring
  __tests__/V5ClusterManagement.js
  src/@types/clusterLabels.d.ts
  src/components/Cluster/ClusterDetail/ClusterLabels/ClusterLabels.tsx
  src/components/Cluster/ClusterDetail/ClusterLabels/DeleteLabelButton.tsx
  src/components/Cluster/ClusterDetail/ClusterLabels/EditLabelTooltip.tsx
  src/components/UI/ClusterLabels/DeleteLabelButton.tsx
  src/reducers/clusterReducer.js
  src/reducers/index.js
  src/selectors/clusterLabelSelectors.ts
  src/stores/clusterlabels/actions.ts
  src/stores/clusterlabels/reducer.ts
  testUtils/mockHttpCalls/clusters.js
  testUtils/mockHttpCalls/constantsAndHelpers.js
Labels: kind/feature

#1506 Make inactive releases visible to developers
  __tests__/ClusterManagement.js
  src/actions/releaseActions.js
Labels: kind/dev-change

#1505 Enable cluster labelling through feature flag
  src/components/Cluster/ClusterDetail/ClusterLabels/EditLabelTooltip.tsx
  src/shared/FeatureFlags.ts
  webpack.common.js
Labels: kind/feature

#1507 Make the success button the same size as the regular button
  src/styles/components/_button.sass
Labels: kind/ux-enhancement

#1509 Add support for reloading the cluster details after modifying them
  src/actions/clusterActions.js
Labels: kind/dev-change

#1508 Add boilerplate for the HA masters feature
  jest.config.js
  src/shared/constants/index.js
  src/utils/__tests__/computeCapabilities.js
  src/utils/clusterUtils.js
  testUtils/mockHttpCalls/clusters.js
Labels: kind/dev-change

#1510 Render internal catalogs for admins.
  __tests__/AppCatalog.js
  src/components/AppCatalog/AppCatalog.js
  src/components/AppCatalog/AppList/AppListInner.js
  src/components/AppCatalog/CatalogList/CatalogList.js
  src/components/UI/CatalogTypeLabel.js
  src/stores/appcatalog/actions.ts
Labels: kind/feature

#1511 Add HA Masters cluster creation components
  src/components/Cluster/NewCluster/CreateNodePoolsCluster.js
  src/components/Cluster/NewCluster/CreateRegularCluster.js
  src/components/Cluster/NewCluster/MasterNodes.tsx
  src/components/Cluster/NewCluster/NewCluster.js
  src/components/Cluster/NewCluster/__tests__/MasterNodes.ts
Labels: kind/dev-change

#1512 Add components for displaying master nodes in the cluster detail page
  src/components/Cluster/ClusterDetail/MasterNodes/MasterNodes.tsx
  src/components/Cluster/ClusterDetail/MasterNodes/MasterNodesConverter.tsx
  src/components/Cluster/ClusterDetail/MasterNodes/MasterNodesInfo.tsx
  src/components/Cluster/ClusterDetail/MasterNodes/MasterNodesUtils.ts
  src/components/Cluster/ClusterDetail/MasterNodes/__tests__/MasterNodes.ts
  src/components/Cluster/ClusterDetail/MasterNodes/__tests__/MasterNodesUtils.ts
  tsconfig.json
Labels: kind/dev-change

#1513 Show '1 node pool' instead of '1 node pools' in cluster overview
  src/components/Home/ClusterDashboardResourcesV5.js
Labels: kind/bug

#1515 Delete old label on label key change
  src/@types/clusterLabels.d.ts
  src/components/Cluster/ClusterDetail/ClusterLabels/EditLabelTooltip.tsx
  src/stores/clusterlabels/actions.ts
Labels: kind/change

#1516 add 'Cancel' button to v4 cluster creation & wire it up
  src/components/Cluster/NewCluster/ClusterCreationDuration.js
  src/components/Cluster/NewCluster/CreateNodePoolsCluster.js
  src/components/Cluster/NewCluster/CreateRegularCluster.js
  src/components/Cluster/NewCluster/NewCluster.js
Labels: kind/change
