Repository giantswarm/happa, pull requests merged in 2020-07, with the labels that each got.

#1616 Catalog Icon fixes
  src/components/AppCatalog/CatalogList/CatalogRepo.js
  src/components/shared/ImgWithFallback.tsx
Labels: kind/dev-change

#1618 Listen for connections on local interface only.
  scripts/webpack/proxyPlugin.js
Labels: kind/security

#1617 Don't rely on bootstrap's col-x classes for layout.
  src/components/AccountSettings/AccountSettings.js
  src/components/AccountSettings/ChangePasswordForm.js
  src/components/Auth/AdminLogin.tsx
  src/components/Auth/Login.tsx
  src/components/Auth/Logout.js
  src/components/Auth/OAuthCallback.js
  src/components/Auth/OAuthCallbackDebug.js
  src/components/Cluster/ClusterDetail/AddNodePool.js
  src/components/Cluster/ClusterDetail/ClusterApps.js
  src/components/Cluster/ClusterDetail/ClusterDetailView.js
  src/components/Cluster/ClusterDetail/Ingress/Ingress.tsx
  src/components/Cluster/ClusterDetail/Ingress/Instructions.tsx
  src/components/Cluster/ClusterDetail/KeyPairDetailsModal.js
  src/components/Cluster/ClusterDetail/KeyPairs.js
  src/components/Cluster/ClusterDetail/KeypairCreateModal/AddKeyPairTemplate.tsx
  src/components/Cluster/ClusterDetail/UserInstalledApps/UserInstalledApps.js
  src/components/Cluster/ClusterDetail/V5ClusterDetailTable.js
  src/components/Cluster/NewCluster/ProviderCredentials.js
  src/components/Cluster/NewCluster/V4AvailabilityZonesSelector.js
  src/components/Footer/Footer.tsx
  src/components/ForgotPassword/ForgotPassword.js
  src/components/ForgotPassword/SetPassword.js
  src/components/GettingStarted/GettingStarted.js
  src/components/GettingStarted/Steps/ConfigureKubectl.js
  src/components/GettingStarted/Steps/ConfigureKubectlAlternative.js
  src/components/GettingStarted/Steps/InstallIngress.js
  src/components/GettingStarted/Steps/NextSteps.js
  src/components/GettingStarted/Steps/Overview.js
  src/components/GettingStarted/Steps/SimpleExample.js
  src/components/Home/ClusterDashboardItem.js
  src/components/Layout.js
  src/components/NotFound/NotFound.js
  src/components/Organizations/Detail/View.js
  src/components/Organizations/List/List.js
  src/components/SignUp/SignUp.js
  src/components/UI/AppDetails/AppDetails.js
  src/components/UI/CatalogTypeLabel.js
  src/components/UI/Navigation/Hamburger.js
  src/components/UI/Navigation/MainMenu.js
  src/components/UI/Navigation/Navigation.js
  src/components/UI/Section.js
  src/components/UI/StyleGuide.js
  src/components/UI/TwoInputArea.js
  src/components/Users/Users.js
  src/components/Users/UsersPlaceholder.js
  src/components/Users/UsersTable.js
  src/components/shared/NodeCountSelector.js
  src/styles/_base.sass
  src/styles/app.sass
  src/styles/components/_app_catalog.sass
  src/styles/components/_breadcrumbs.sass
  src/styles/components/_cluster_details.sass
  src/styles/components/_create_cluster.sass
  src/styles/components/_login_form.sass
  src/styles/components/_node_table.sass
  src/styles/components/_signup.sass
  src/styles/theme.ts
Labels: kind/refactor

#1621 Fix flickery ingress button states
  src/components/Cluster/ClusterDetail/Ingress/InstallIngressButton.tsx
  src/components/Cluster/ClusterDetail/Ingress/__tests__/Ingress.ts
  src/components/Cluster/ClusterDetail/Ingress/__tests__/InstallIngressButton.ts
  src/lib/effects/useDelayedChange.js
Labels: kind/bug

#1622 Update architect
  .circleci/config.yml
Labels: kind/dev-change

#1635 Set extractComments to 'some' in Terser config
  package.json
  webpack.prod.js
  yarn.lock
Labels: kind/dev-change

#1646 Move delete app action to stores folder.
  src/actions/actionTypes.js
  src/actions/appActions.js
  src/components/Cluster/ClusterDetail/AppDetailsModal/AppDetailsModal.js
  src/stores/clusterapps/actions.ts
  src/utils/v4orV5.js
Labels: kind/refactor

#1475 Make ingress controller optional in azure release >=12.0.0
  src/utils/__tests__/computeCapabilities.js
  src/utils/clusterUtils.js
Labels: kind/feature

#1648 Move update app action to stores folder
  src/actions/actionTypes.js
  src/actions/appActions.js
  src/components/Cluster/ClusterDetail/AppDetailsModal/AppDetailsModal.js
  src/components/Cluster/ClusterDetail/AppDetailsModal/EditChartVersionPane.js
  src/components/Cluster/ClusterDetail/ClusterDetailView.js
  src/components/Cluster/ClusterDetail/Ingress/Instructions.tsx
  src/stores/callAPIMiddleware.js
  src/stores/clusterapps/actions.ts
Labels: kind/refactor

#1649 Remove HA Masters feature flag and use server-side feature flag
  jest.config.js
  src/@types/global.d.ts
  src/actions/clusterActions.js
  src/components/Cluster/ClusterDetail/V5ClusterDetailTable.js
  src/components/Cluster/NewCluster/NewClusterWrapper.tsx
  src/selectors/featureSelectors.ts
  src/selectors/mainInfoSelectors.ts
  src/shared/FeatureFlags.ts
  src/utils/__tests__/computeCapabilities.js
  src/utils/clusterUtils.js
  webpack.common.js
Labels: kind/dev-change

#1650 Remove jq from dockerfile.
  Dockerfile
Labels: kind/security

#1651 Don't push container image twice
  .circleci/config.yml
Labels: kind/dev-change

#1652 Force a updated lodash
  package.json
  yarn.lock
Labels: kind/security

#1653 remove bootstrap from existing dropdowns
  src/components/Cluster/ClusterDetail/NodePoolDropdownMenu.js
  src/components/UI/DropdownMenu.js
  src/components/UI/Navigation/Hamburger.js
  src/components/UI/Navigation/MainMenu.js
  src/components/UI/VersionPicker/VersionPicker.tsx
  src/styles/index.ts
  src/styles/theme.ts
Labels: kind/dev-change

#1655 Set lodash to 4.17.19
  package.json
Labels: kind/security

#1654 Refactor Organization Dropdown & make it scrollable
  src/components/UI/DropdownMenu.js
  src/components/UI/Navigation/OrganizationDropdown.js
Labels: kind/change, kind/refactor

#1666 Fix borked organization dropdown
  src/components/UI/Navigation/OrganizationDropdown.js
Labels: kind/bug

#1667 make dev cors headers more production alike
  scripts/webpack/proxyPlugin.js
Labels: kind/dev-change

#1647 Add compatibility changes for Azure V5
  src/components/Cluster/ClusterDetail/NodePool.tsx
  src/components/Cluster/ClusterDetail/NodePoolDropdownMenu.js
  src/components/Cluster/ClusterDetail/NodePoolScaling.tsx
  src/components/Cluster/ClusterDetail/V5ClusterDetailTable.js
  src/components/Cluster/ClusterDetail/V5ClusterDetailTableNodePoolScaling.tsx
  src/components/Cluster/ClusterDetail/WorkerNodesAzure.js
  src/components/Cluster/NewCluster/NewClusterWrapper.tsx
  src/components/UI/AvailabilityZonesLabels.js
  src/selectors/mainInfoSelectors.ts
  src/shared/constants/index.js
  src/shared/types.ts
  src/utils/__tests__/clusterUtils.ts
  src/utils/clusterUtils.js
  yarn.lock
Labels: kind/dev-change

#1668 Clean up some unused props in cluster overview (Home)
  src/components/Home/ClusterDashboardItem.js
  src/components/Home/Home.js
  src/components/UI/ClusterEmptyState.js
Labels: kind/refactor

#1669 No unused proptypes
  .eslintrc.js
  src/components/AppCatalog/AppList/AppListInner.js
  src/components/AppCatalog/CatalogList/CatalogList.js
  src/components/Auth/AdminLogin.tsx
  src/components/Auth/Login.tsx
  src/components/Auth/OAuthCallbackDebug.js
  src/components/Cluster/ClusterDetail/AddNodePool.js
  src/components/Cluster/ClusterDetail/AvailabilityZonesParser.js
  src/components/Cluster/ClusterDetail/ClusterApps.js
  src/components/Cluster/ClusterDetail/ClusterDetailView.js
  src/components/Cluster/ClusterDetail/KeyPairs.js
  src/components/Cluster/ClusterDetail/V4ClusterDetailTable.js
  src/components/Cluster/ClusterDetail/V5ClusterDetailTable.js
  src/components/Cluster/NewCluster/NewClusterWrapper.tsx
  src/components/Cluster/NewCluster/ProviderCredentials.js
  src/components/Cluster/NewCluster/ReleaseSelector/ReleaseRow.tsx
  src/components/ForgotPassword/ForgotPassword.js
  src/components/GettingStarted/Steps/ConfigureKubectl.js
  src/components/GettingStarted/Steps/ConfigureKubectlAlternative.js
  src/components/GettingStarted/Steps/InstallIngress.js
  src/components/GettingStarted/Steps/NextSteps.js
  src/components/GettingStarted/Steps/Overview.js
  src/components/GettingStarted/Steps/SimpleExample.js
  src/components/Home/ClusterDashboardResourcesV4.js
  src/components/Home/ClusterDashboardResourcesV5.js
  src/components/Home/UpgradeNotice.tsx
  src/components/Layout.js
  src/components/Organizations/Detail/Credentials.js
  src/components/Organizations/Detail/CredentialsDisplay.js
  src/components/Organizations/Detail/CredentialsForm.js
  src/components/Organizations/Detail/View.js
  src/components/Organizations/Organizations.js
  src/components/UI/NumberPicker.js
  src/components/UI/OrganizationList/OrganizationListRow.js
  src/components/UI/RefreshableLabel.js
  src/components/shared/VirtualizedScrollableGrid.js
Labels: kind/refactor

#1671 fix non-admins couldn't see release changes
  src/components/Cluster/ClusterDetail/ClusterDetail.js
  src/selectors/releaseSelectors.ts
  src/stores/releases/actions.ts
Labels: kind/bug

#1673 Clean up various old things
  .babelrc
  .circleci/config.yml
  .eslintignore
  Dockerfile.dev
  Makefile
  README.md
  docker-compose.yml
  package.json
  scripts/dev.sh
Labels: kind/dev-change

#1672 Fix typo in invalid credentials error
  src/components/Auth/parseErrorMessages.js
Labels: kind/bug

#1676 Fix trying to use apps before loading them in an app catalog
  __tests__/AppCatalog.js
  src/actions/catalogActions.js
  src/components/AppCatalog/AppList/AppList.js
  src/components/AppCatalog/AppList/AppListInner.js
Labels: kind/bug

#1677 Fix trying to use an 'undefined' response in HttpClient
  src/model/clients/HttpClient.js
  src/model/clients/__tests__/HttpClient.js
Labels: kind/bug

#1675 Load app catalog for latest ingress app version
  src/components/Cluster/ClusterDetail/Ingress/InstallIngressButton.tsx
  src/components/Cluster/ClusterDetail/Ingress/__tests__/Ingress.ts
  src/components/Cluster/ClusterDetail/Ingress/__tests__/InstallIngressButton.ts
  src/shared/constants/index.js
Labels: kind/change

#1670 azure v5: nodepool creation
  src/components/Cluster/ClusterDetail/AddNodePool.js
  src/components/Cluster/ClusterDetail/AddNodePoolMachineType.tsx
  src/shared/constants/index.js
  yarn.lock
Labels: kind/dev-change

#1681 Improve error message when the apps in a catalog failed loading
  __tests__/AppCatalog.js
  src/components/AppCatalog/AppList/AppListItems.js
  src/components/AppCatalog/AppList/AppListPlaceholder.tsx
Labels: kind/ux-enhancement

#1680 Cluster dashboard sass cleanup, fix animations
  src/components/Home/Home.js
  src/styles/app.sass
  src/styles/components/_cluster_dashboard.sass
Labels: kind/refactor

#1693 Remove some superfluous tooltips.
  src/components/Cluster/ClusterDetail/AppDetailsModal/InitialPane.js
  src/components/UI/Truncated.tsx
  src/components/UI/__tests__/Truncated.ts
Labels: kind/ux-enhancement

#1679 Extract TOS sass, clean up some unused sass I found along the way.
  src/components/SignUp/TermsOfService.js
  src/components/UI/Navigation/UserDropdown.js
  src/styles/app.sass
  src/styles/components/_copy_link.sass
  src/styles/components/_domain_list.sass
  src/styles/components/_email.sass
  src/styles/components/_signup.sass
  src/styles/components/_terms_of_service.sass
Labels: kind/refactor

#1674 Remove app_catalog.sass
  src/components/AppCatalog/AppCatalog.js
  src/components/AppCatalog/AppList/AppList.js
  src/components/AppCatalog/AppList/AppListInner.js
  src/components/AppCatalog/AppList/AppListSearch.js
  src/components/AppCatalog/CatalogList/CatalogList.js
  src/components/Cluster/ClusterDetail/AppDetailsModal/InitialPane.js
  src/components/UI/Well.js
  src/styles/app.sass
  src/styles/components/_app_catalog.sass
  src/styles/components/_cluster_details.sass
  src/styles/components/_form.sass
Labels: kind/refactor

#1678 Remove _breadcrumbs.sass and _gadget.sass
  src/components/UI/Navigation/Navigation.js
  src/styles/_base.sass
  src/styles/app.sass
  src/styles/components/_breadcrumbs.sass
  src/styles/components/_gadget.sass
Labels: kind/refactor

#1696 azure v5: hide CAPI cluster name label
  __tests__/V5ClusterManagement.js
  src/components/Cluster/ClusterDetail/ClusterLabels/ClusterLabels.tsx
  src/utils/clusterUtils.js
  src/utils/labelUtils.ts
Labels: kind/dev-change
