Repository giantswarm/happa, pull requests merged in 2021-02, with the labels that each got.

#2099 Create basic grommet theme
  .storybook/preview.js
  src/@types/styled-components.d.ts
  src/components/App.tsx
  src/components/Cluster/ClusterDetail/__tests__/NodePoolDropdownMenu.js
  src/components/Cluster/ClusterDetail/__tests__/PortMappingsRow.js
  src/styles/ThemeProvider.tsx
  src/styles/index.ts
  src/styles/theme.ts
  testUtils/renderUtils.js
Labels: kind/dev-change

#2079 Implement support for Spot instances on Azure
  src/components/Cluster/ClusterDetail/AddNodePool/AddNodePool.js
  src/components/Cluster/ClusterDetail/AddNodePool/AddNodePoolSpotInstances.tsx
  src/components/Cluster/ClusterDetail/AddNodePool/AddNodePoolSpotInstancesAzure.tsx
  src/components/Cluster/ClusterDetail/AddNodePool/__tests__/AddNodePool.tsx
  src/components/Cluster/ClusterDetail/NodePool.tsx
  src/components/Cluster/ClusterDetail/NodePoolScaling.tsx
  src/components/Cluster/ClusterDetail/NodePoolScalingSpotInstancesDetails.tsx
  src/components/Cluster/ClusterDetail/V5ClusterDetailTable.js
  src/components/Cluster/ClusterDetail/V5ClusterDetailTableNodePoolScaling.tsx
  src/components/Cluster/ClusterDetail/V5ClusterDetailTableSpotInstancesTab.tsx
  src/components/Cluster/ClusterDetail/__tests__/NodePoolScaling.tsx
  src/components/Cluster/ClusterDetail/__tests__/V5ClusterDetailTableNodePoolScaling.tsx
  src/components/UI/Inputs/CurrencyInput/__tests__/CurrencyInput.tsx
  src/components/UI/Inputs/CurrencyInput/index.tsx
  src/components/UI/Inputs/CurrencyInput/stories/CurrencyInput.stories.tsx
  src/components/UI/Inputs/CurrencyInput/stories/ValidationError.tsx
  src/components/UI/Inputs/Input.tsx
  src/shared/constants/index.ts
  src/shared/constants/realUserMonitoring.ts
  src/shared/types.ts
  src/stores/nodepool/utils.ts
  storybook-static/favicon.ico
  storybook-static/iframe.html
  storybook-static/index.html
  storybook-static/main.710e7868125fa06ec5e8.bundle.js
  storybook-static/main.7dc4a49775ec4f182f2c.bundle.js
  storybook-static/main.7dc4a49775ec4f182f2c.bundle.js.map
  storybook-static/runtime~main.6a9b04192e3176eff72a.bundle.js
  storybook-static/runtime~main.7dc4a49775ec4f182f2c.bundle.js
  storybook-static/runtime~main.7dc4a49775ec4f182f2c.bundle.js.map
  storybook-static/static/media/code-brackets.2e1112d7.svg
  storybook-static/static/media/colors.a4bd0486.svg
  storybook-static/static/media/comments.a3859089.svg
  storybook-static/static/media/direction.b770f9af.svg
  storybook-static/static/media/flow.edad2ac1.svg
  storybook-static/static/media/glyphicons-halflings-regular.060b2710.svg
  storybook-static/static/media/glyphicons-halflings-regular.4692b9ec.ttf
  storybook-static/static/media/glyphicons-halflings-regular.5be1347c.eot
  storybook-static/static/media/glyphicons-halflings-regular.82b1212e.woff
  storybook-static/static/media/glyphicons-halflings-regular.be810be3.woff2
  storybook-static/static/media/plugin.d494b228.svg
  storybook-static/static/media/repo.6d496322.svg
  storybook-static/static/media/stackalt.dba9fbb3.svg
  storybook-static/vendors~main.5bac919f011b504f9311.bundle.js
  storybook-static/vendors~main.5bac919f011b504f9311.bundle.js.LICENSE.txt
  storybook-static/vendors~main.7dc4a49775ec4f182f2c.bundle.js
  storybook-static/vendors~main.7dc4a49775ec4f182f2c.bundle.js.LICENSE.txt
  storybook-static/vendors~main.7dc4a49775ec4f182f2c.bundle.js.map
  yarn.lock
Labels: kind/feature

#2117 Automatically create storybook docs
  .storybook/main.js
  package.json
  src/components/UI/Inputs/CurrencyInput/index.tsx
  storybook-static/favicon.ico
  storybook-static/iframe.html
  storybook-static/index.html
  storybook-static/main.710e7868125fa06ec5e8.bundle.js
  storybook-static/main.7dc4a49775ec4f182f2c.bundle.js
  storybook-static/main.7dc4a49775ec4f182f2c.bundle.js.map
  storybook-static/runtime~main.6a9b04192e3176eff72a.bundle.js
  storybook-static/runtime~main.7dc4a49775ec4f182f2c.bundle.js
  storybook-static/runtime~main.7dc4a49775ec4f182f2c.bundle.js.map
  storybook-static/static/media/code-brackets.2e1112d7.svg
  storybook-static/static/media/colors.a4bd0486.svg
  storybook-static/static/media/comments.a3859089.svg
  storybook-static/static/media/direction.b770f9af.svg
  storybook-static/static/media/flow.edad2ac1.svg
  storybook-static/static/media/glyphicons-halflings-regular.060b2710.svg
  storybook-static/static/media/glyphicons-halflings-regular.4692b9ec.ttf
  storybook-static/static/media/glyphicons-halflings-regular.5be1347c.eot
  storybook-static/static/media/glyphicons-halflings-regular.82b1212e.woff
  storybook-static/static/media/glyphicons-halflings-regular.be810be3.woff2
  storybook-static/static/media/plugin.d494b228.svg
  storybook-static/static/media/repo.6d496322.svg
  storybook-static/static/media/stackalt.dba9fbb3.svg
  storybook-static/vendors~main.5bac919f011b504f9311.bundle.js
  storybook-static/vendors~main.5bac919f011b504f9311.bundle.js.LICENSE.txt
  storybook-static/vendors~main.7dc4a49775ec4f182f2c.bundle.js
  storybook-static/vendors~main.7dc4a49775ec4f182f2c.bundle.js.LICENSE.txt
  storybook-static/vendors~main.7dc4a49775ec4f182f2c.bundle.js.map
  yarn.lock
Labels: kind/dev-change

#2121 Make currency input have consistent layout on all major browsers
  src/components/UI/Inputs/CurrencyInput/index.tsx
Labels: kind/bug

#2131 Rely on API to set the default max price for spot instances on Azure
  src/components/Cluster/ClusterDetail/AddNodePool/AddNodePool.js
  src/components/Cluster/ClusterDetail/AddNodePool/__tests__/AddNodePool.tsx
Labels: kind/dev-change

#2132 Remove the warning regarding runnin minimum 3 nodes in a pool
  src/components/Cluster/ClusterDetail/ScaleNodePoolModal.js
Labels: kind/change

#2124 Create new text input component and replace all existing ones with it
  __tests__/AppCatalog.js
  __tests__/KeyPairs.js
  __tests__/Organization.js
  __tests__/Users.js
  __tests__/V5ClusterManagement.js
  package.json
  src/components/AccountSettings/ChangeEmailForm.js
  src/components/AccountSettings/ChangePasswordForm.js
  src/components/AccountSettings/__tests__/ChangeEmailForm.js
  src/components/AccountSettings/__tests__/ChangePasswordForm.js
  src/components/AppCatalog/AppDetail/ClusterPicker.tsx
  src/components/AppCatalog/AppDetail/InstallAppForm.js
  src/components/AppCatalog/AppDetail/__tests__/InstallAppForm.js
  src/components/AppCatalog/AppList/AppListSearch.js
  src/components/Auth/Login.tsx
  src/components/Cluster/ClusterDetail/AddNodePool/AddNodePool.js
  src/components/Cluster/ClusterDetail/ClusterLabels/EditLabelTooltip.tsx
  src/components/Cluster/ClusterDetail/ExpiryHoursPicker.js
  src/components/Cluster/ClusterDetail/KeypairCreateModal/AddKeyPairTemplate.tsx
  src/components/Cluster/ClusterDetail/NodePool.tsx
  src/components/Cluster/NewCluster/NewClusterWrapper.tsx
  src/components/ForgotPassword/ForgotPassword.js
  src/components/ForgotPassword/SetPassword.js
  src/components/Modals/Modals.js
  src/components/Organizations/Detail/CredentialsForm.js
  src/components/SignUp/SignUp.js
  src/components/UI/Display/Cluster/ClusterCreation/NameInput.tsx
  src/components/UI/Inputs/TextInput/__tests__/__snapshots__/index.tsx.snap
  src/components/UI/Inputs/TextInput/__tests__/index.tsx
  src/components/UI/Inputs/TextInput/index.tsx
  src/components/UI/Inputs/TextInput/stories/Disabled.tsx
  src/components/UI/Inputs/TextInput/stories/Error.tsx
  src/components/UI/Inputs/TextInput/stories/Help.tsx
  src/components/UI/Inputs/TextInput/stories/Info.tsx
  src/components/UI/Inputs/TextInput/stories/Label.tsx
  src/components/UI/Inputs/TextInput/stories/Simple.tsx
  src/components/UI/Inputs/TextInput/stories/TextInput.stories.tsx
  src/components/UI/Inputs/ViewEditName.tsx
  src/components/Users/InviteUserModal/InviteUserForm.js
  src/stores/modal/reducer.ts
  src/stores/organization/actions.ts
  src/stores/organization/constants.ts
  src/stores/organization/types.ts
  src/styles/components/_create_cluster.sass
  src/styles/components/_expiry_hours_picker.sass
  src/styles/components/_form.sass
  src/styles/components/_signup.sass
  src/styles/components/_textfield.sass
  src/styles/theme.ts
Labels: kind/refactor

#2142 Create new checkbox input and replace all the existing ones with it
  src/components/Cluster/ClusterDetail/AddNodePool/AddNodePool.js
  src/components/Cluster/ClusterDetail/AddNodePool/AddNodePoolSpotInstancesAzure.tsx
  src/components/Cluster/ClusterDetail/KeypairCreateModal/AddKeyPairTemplate.tsx
  src/components/Cluster/ClusterDetail/KeypairCreateModal/KeyPairCreateModal.tsx
  src/components/Cluster/ClusterDetail/KeypairCreateModal/__tests__/KeyPairCreateModal.tsx
  src/components/SignUp/SignUp.js
  src/components/UI/Controls/VersionPicker/VersionPicker.tsx
  src/components/UI/Inputs/CheckBoxInput/__tests__/__snapshots__/index.tsx.snap
  src/components/UI/Inputs/CheckBoxInput/__tests__/index.tsx
  src/components/UI/Inputs/CheckBoxInput/index.tsx
  src/components/UI/Inputs/CheckBoxInput/stories/CheckBoxInput.stories.tsx
  src/components/UI/Inputs/CheckBoxInput/stories/Disabled.tsx
  src/components/UI/Inputs/CheckBoxInput/stories/Error.tsx
  src/components/UI/Inputs/CheckBoxInput/stories/FieldLabel.tsx
  src/components/UI/Inputs/CheckBoxInput/stories/Help.tsx
  src/components/UI/Inputs/CheckBoxInput/stories/Info.tsx
  src/components/UI/Inputs/CheckBoxInput/stories/Simple.tsx
  src/components/UI/Inputs/CheckBoxInput/stories/Toggle.tsx
  src/components/UI/Inputs/Checkbox.js
  src/components/Users/InviteUserModal/InviteUserForm.js
  src/styles/theme.ts
Labels: kind/dev-change

#2162 Create new radio input and replace all the existing ones with it
  src/components/Cluster/AZSelection/AZSelectionCheckbox.tsx
  src/components/Cluster/ClusterDetail/ExpiryHoursPicker.js
  src/components/Cluster/ClusterDetail/InstanceTypeSelector/InstanceTypeRow.tsx
  src/components/Cluster/NewCluster/ReleaseSelector/ReleaseRow.tsx
  src/components/UI/Controls/ExpandableSelector/Items.tsx
  src/components/UI/Inputs/RadioInput.tsx
  src/components/UI/Inputs/RadioInput/__tests__/__snapshots__/index.tsx.snap
  src/components/UI/Inputs/RadioInput/__tests__/index.tsx
  src/components/UI/Inputs/RadioInput/index.tsx
  src/components/UI/Inputs/RadioInput/stories/Disabled.tsx
  src/components/UI/Inputs/RadioInput/stories/Error.tsx
  src/components/UI/Inputs/RadioInput/stories/FieldLabel.tsx
  src/components/UI/Inputs/RadioInput/stories/Help.tsx
  src/components/UI/Inputs/RadioInput/stories/Info.tsx
  src/components/UI/Inputs/RadioInput/stories/Multiple.tsx
  src/components/UI/Inputs/RadioInput/stories/RadioInput.stories.tsx
  src/components/UI/Inputs/RadioInput/stories/Simple.tsx
  src/components/UI/StyleGuide.js
  src/styles/theme.ts
Labels: kind/dev-change

#2167 Make sure toggling helm catalog the first time works.
  src/components/Apps/AppsList/AppsList.tsx
  src/stores/appcatalog/selectors.ts
Labels: kind/bug

#2172 Remove glyphicons-halflings fonts
  src/styles/fonts/glyphicons-halflings-regular.eot
  src/styles/fonts/glyphicons-halflings-regular.svg
  src/styles/fonts/glyphicons-halflings-regular.ttf
  src/styles/fonts/glyphicons-halflings-regular.woff
  src/styles/fonts/glyphicons-halflings-regular.woff2
Labels: kind/dev-change

#2173 Boyscouting: remove duplicate color declaration
  src/components/UI/Controls/Navigation/UserDropdown.tsx
Labels: kind/dev-change

#2180 Update some minor deps all at once
  package.json
  yarn.lock
Labels: kind/dev-change

#2175 Migrate styleguide to storybook
  src/components/Routes.js
  src/components/UI/Controls/VersionPicker/stories/IncludingTestVersions.tsx
  src/components/UI/Controls/VersionPicker/stories/Simple.tsx
  src/components/UI/Controls/VersionPicker/stories/VersionPicker.stories.tsx
  src/components/UI/Display/Cluster/ClusterEmptyState/index.js
  src/components/UI/Display/Cluster/ClusterEmptyState/stories/ClusterEmptyState.stories.tsx
  src/components/UI/Display/Cluster/ComponentChangelog/index.js
  src/components/UI/Display/Cluster/ComponentChangelog/stories/ComponentChangelog.stories.tsx
  src/components/UI/Display/Cluster/ReleaseComponentLabel/index.js
  src/components/UI/Display/Cluster/ReleaseComponentLabel/stories/ReleaseComponentLabel.stories.tsx
  src/components/UI/StyleGuide.js
Labels: kind/dev-change

#2181 Move docs URLs into library
  src/components/Cluster/ClusterDetail/ClusterApps.js
  src/components/Cluster/ClusterDetail/UpgradeClusterModal.js
  src/components/Cluster/ClusterDetail/V5ClusterDetailTable.js
  src/components/GettingStarted/Steps/ConfigureKubectlAlternative.js
  src/components/GettingStarted/Steps/NextSteps.js
  src/components/Organizations/Detail/CredentialsForm.js
  src/components/UI/Controls/Navigation/MainMenu.js
  src/components/UI/Display/Apps/AppList/AppsListPage.tsx
  src/lib/docs.ts
  testUtils/mockHttpCalls/releases.js
Labels: kind/dev-change

#2182 Add FlashMessage to storybook
  src/components/UI/Display/FlashMessage/index.tsx
  src/components/UI/Display/FlashMessage/stories/FlashMessage.stories.tsx
Labels: kind/dev-change

#2187 Create textarea input
  src/components/Cluster/ClusterDetail/KeypairCreateModal/AddKeyPairSuccessTemplate.tsx
  src/components/Cluster/ClusterDetail/KeypairCreateModal/KeyPairCreateModal.tsx
  src/components/Cluster/ClusterDetail/KeypairCreateModal/__tests__/KeyPairCreateModal.tsx
  src/components/UI/Inputs/TextArea/__tests__/__snapshots__/index.tsx.snap
  src/components/UI/Inputs/TextArea/__tests__/index.tsx
  src/components/UI/Inputs/TextArea/index.tsx
  src/components/UI/Inputs/TextArea/stories/Disabled.tsx
  src/components/UI/Inputs/TextArea/stories/Error.tsx
  src/components/UI/Inputs/TextArea/stories/Help.tsx
  src/components/UI/Inputs/TextArea/stories/Info.tsx
  src/components/UI/Inputs/TextArea/stories/Label.tsx
  src/components/UI/Inputs/TextArea/stories/Simple.tsx
  src/components/UI/Inputs/TextArea/stories/TextArea.stories.tsx
  src/styles/theme.ts
Labels: kind/dev-change

#2183 Create new date input and replace all the existing ones with it
  .storybook/preview.js
  package.json
  src/components/Cluster/ClusterDetail/ExpiryHoursPicker.js
  src/components/UI/Inputs/DateInput/__tests__/__snapshots__/index.tsx.snap
  src/components/UI/Inputs/DateInput/__tests__/index.tsx
  src/components/UI/Inputs/DateInput/index.tsx
  src/components/UI/Inputs/DateInput/stories/Button.tsx
  src/components/UI/Inputs/DateInput/stories/DateInput.stories.tsx
  src/components/UI/Inputs/DateInput/stories/Disabled.tsx
  src/components/UI/Inputs/DateInput/stories/Error.tsx
  src/components/UI/Inputs/DateInput/stories/Help.tsx
  src/components/UI/Inputs/DateInput/stories/Info.tsx
  src/components/UI/Inputs/DateInput/stories/Label.tsx
  src/components/UI/Inputs/DateInput/stories/Simple.tsx
  src/components/index.tsx
  src/styles/components/_create_key_pair.sass
  src/styles/theme.ts
  yarn.lock
Labels: kind/dev-change

#2188 Refactor NumberPicker to use the new input and structure
  src/components/Cluster/ClusterDetail/AddNodePool/AddNodePool.js
  src/components/Cluster/ClusterDetail/AddNodePool/AddNodePoolSpotInstances.tsx
  src/components/Cluster/ClusterDetail/AddNodePool/__tests__/AddNodePool.tsx
  src/components/Cluster/ClusterDetail/AvailabilityZonesParser.js
  src/components/Cluster/NewCluster/KVMWorkerConfiguration.tsx
  src/components/Cluster/NewCluster/V4AvailabilityZonesSelector.js
  src/components/UI/Inputs/NumberPicker.js
  src/components/UI/Inputs/NumberPicker/__tests__/__snapshots__/index.tsx.snap
  src/components/UI/Inputs/NumberPicker/__tests__/index.tsx
  src/components/UI/Inputs/NumberPicker/index.tsx
  src/components/UI/Inputs/NumberPicker/stories/NumberPicker.stories.tsx
  src/components/UI/Inputs/NumberPicker/stories/Simple.tsx
  src/components/UI/Inputs/TextInput/index.tsx
  src/components/shared/NodeCountSelector.js
  src/components/shared/__tests__/NodeCountSelector.js
Labels: kind/refactor

#2193 Update lodash to v4.17.21
  package.json
  yarn.lock
Labels: dependencies, kind/security

#2201 Refactor CurrencyInput to use the new input and structure
  src/components/Cluster/ClusterDetail/AddNodePool/AddNodePoolSpotInstancesAzure.tsx
  src/components/UI/Inputs/CurrencyInput/__tests__/CurrencyInput.tsx
  src/components/UI/Inputs/CurrencyInput/__tests__/__snapshots__/CurrencyInput.tsx.snap
  src/components/UI/Inputs/CurrencyInput/index.tsx
  src/components/UI/Inputs/CurrencyInput/stories/Constraints.tsx
  src/components/UI/Inputs/CurrencyInput/stories/Currencies.tsx
  src/components/UI/Inputs/CurrencyInput/stories/FloatValues.tsx
  src/components/UI/Inputs/CurrencyInput/stories/Label.tsx
  src/components/UI/Inputs/CurrencyInput/stories/Simple.tsx
  src/components/UI/Inputs/CurrencyInput/stories/ValidationError.tsx
Labels: kind/dev-change

#2204 Create new file input and replace all the existing ones with it
  src/components/Apps/AppDetail/InstallAppModal/InstallAppForm.js
  src/components/Apps/AppDetail/InstallAppModal/InstallAppModal.js
  src/components/UI/Inputs/FileInput.tsx
  src/components/UI/Inputs/FileInput/__tests__/__snapshots__/index.tsx.snap
  src/components/UI/Inputs/FileInput/__tests__/index.tsx
  src/components/UI/Inputs/FileInput/index.tsx
  src/components/UI/Inputs/FileInput/stories/Disabled.tsx
  src/components/UI/Inputs/FileInput/stories/Error.tsx
  src/components/UI/Inputs/FileInput/stories/FileInput.stories.tsx
  src/components/UI/Inputs/FileInput/stories/Help.tsx
  src/components/UI/Inputs/FileInput/stories/Info.tsx
  src/components/UI/Inputs/FileInput/stories/Label.tsx
  src/components/UI/Inputs/FileInput/stories/Simple.tsx
  src/stores/appcatalog/actions.ts
  src/utils/componentUtils.ts
Labels: kind/dev-change

#2205 The great input cleanup
  src/components/Apps/AppDetail/InstallAppModal/InstallAppForm.js
  src/components/Cluster/ClusterDetail/AddNodePool/AddNodePool.js
  src/components/Cluster/ClusterDetail/AddNodePool/AddNodePoolMachineType.tsx
  src/components/Cluster/ClusterDetail/AddNodePool/AddNodePoolSpotInstances.tsx
  src/components/Cluster/ClusterDetail/AddNodePool/AddNodePoolSpotInstancesAzure.tsx
  src/components/Cluster/ClusterDetail/V5ClusterDetailTable.js
  src/components/Cluster/NewCluster/CreateNodePoolsCluster.js
  src/components/Cluster/NewCluster/CreateRegularCluster.js
  src/components/Cluster/NewCluster/MasterNodes.tsx
  src/components/Cluster/NewCluster/NewClusterWrapper.tsx
  src/components/Cluster/NewCluster/ProviderCredentials.js
  src/components/Cluster/NewCluster/V4AvailabilityZonesSelector.js
  src/components/SignUp/PasswordField.js
  src/components/UI/Display/Cluster/ClusterCreation/StyledInput.tsx
  src/components/UI/Inputs/Input.tsx
  src/components/UI/Inputs/InputGroup/__tests__/__snapshots__/index.tsx.snap
  src/components/UI/Inputs/InputGroup/__tests__/index.tsx
  src/components/UI/Inputs/InputGroup/index.tsx
  src/components/UI/Inputs/InputGroup/stories/InputGroup.stories.tsx
  src/components/UI/Inputs/InputGroup/stories/Simple.tsx
  src/components/UI/Inputs/ValidationErrorMessage.js
  src/components/UI/Inputs/ValidityStyledInputElement.tsx
  src/components/shared/EmailField.js
  src/components/shared/InputField.js
  testUtils/setupTests.js
Labels: kind/dev-change
