Repository giantswarm/happa, pull requests merged in 2021-12, with the labels that each got.

#2989 Update template cluster and template node pool CLI guides
  src/components/MAPI/clusters/guides/CreateClusterGuide.tsx
  src/components/MAPI/guides/__tests__/utils.ts
  src/components/MAPI/guides/utils.ts
  src/components/MAPI/workernodes/WorkerNodesCreateNodePool.tsx
  src/components/MAPI/workernodes/guides/CreateNodePoolGuide.tsx
Labels: kind/bug

#2992 Update ingress resources
  helm/happa/Chart.yaml
  helm/happa/templates/certs-secret.yaml
  helm/happa/templates/happaapi-certs-secret.yaml
  helm/happa/templates/happaapi-ingress.yaml
  helm/happa/templates/ingress.yaml
  helm/happa/templates/rbac.yaml
  helm/happa/values.yaml
Labels: kind/change

#2991 Fix G8sControlPlane CR's infrastructure reference namespace when creating non-org-namespaced AWS clusters
  src/components/MAPI/clusters/CreateCluster/patches.ts
Labels: kind/bug

#2986 Make cluster list page aware of permissions for a read-only user
  src/components/MAPI/clusters/ClusterList/ClusterListItem.tsx
  src/components/MAPI/clusters/ClusterList/__tests__/ClusterListItem.tsx
  src/components/MAPI/clusters/Clusters.tsx
  src/components/MAPI/clusters/__tests__/Clusters.tsx
  src/components/MAPI/releases/permissions/usePermissionsForReleases.ts
  src/components/MAPI/utils.ts
  src/components/MAPI/workernodes/permissions/usePermissionsForNodePools.ts
  src/components/UI/Controls/Button/__tests__/__snapshots__/index.tsx.snap
  src/components/UI/Controls/Button/index.tsx
  src/components/UI/Controls/Button/stories/Button.stories.mdx
  src/components/UI/Display/MAPI/clusters/ClusterList/ClusterListEmptyPlaceholder.tsx
Labels: kind/refactor

#2996 Revert dropping support for k8s > 1.19
  helm/happa/Chart.yaml
  helm/happa/templates/happaapi-ingress.yaml
  helm/happa/templates/ingress.yaml
Labels: kind/bug

#2997 Support preview releases as read-only
  src/components/MAPI/apps/AppInstallModal.tsx
  src/components/MAPI/apps/utils.ts
  src/components/MAPI/clusters/ClusterDetail/index.tsx
  src/components/MAPI/clusters/ClusterList/ClusterListItem.tsx
  src/components/MAPI/clusters/ClusterList/__tests__/ClusterListItem.tsx
  src/components/MAPI/clusters/Clusters.tsx
  src/components/MAPI/clusters/CreateCluster/CreateClusterRelease.tsx
  src/components/MAPI/clusters/CreateCluster/CreateClusterReleaseRow.tsx
  src/components/MAPI/clusters/CreateCluster/CreateClusterReleaseSelector.tsx
  src/components/MAPI/clusters/CreateCluster/__tests__/index.tsx
  src/components/MAPI/releases/utils.ts
  src/components/UI/Controls/Button/__tests__/__snapshots__/index.tsx.snap
  src/components/UI/Controls/Button/index.tsx
  src/components/UI/Display/MAPI/clusters/ClusterList/ClusterListItemMainInfo.tsx
  src/components/UI/Display/MAPI/releases/ReleaseStateLabel.tsx
  src/model/services/mapi/releasev1alpha1/types.ts
  test/mockHttpCalls/releasev1alpha1/releases.ts
Labels: kind/ux-enhancement

#3012 Make cluster details > worker nodes tab aware of permissions for a read-only user
  src/components/MAPI/clusters/ClusterDetail/__tests__/index.tsx
  src/components/MAPI/clusters/ClusterDetail/index.tsx
  src/components/MAPI/clusters/ClusterList/ClusterListItem.tsx
  src/components/MAPI/clusters/ClusterList/__tests__/ClusterListItem.tsx
  src/components/MAPI/guides/UnauthorizedMessage.tsx
  src/components/MAPI/workernodes/ClusterDetailWorkerNodes.tsx
  src/components/MAPI/workernodes/WorkerNodesNodePoolItem.tsx
  src/components/MAPI/workernodes/__tests__/ClusterDetailWorkerNodes.tsx
  src/components/MAPI/workernodes/__tests__/WorkerNodesNodePoolItem.tsx
  src/components/MAPI/workernodes/guides/DeleteNodePoolGuide.tsx
  src/components/MAPI/workernodes/guides/ModifyNodePoolGuide.tsx
  src/components/MAPI/workernodes/permissions/usePermissionsForNodePools.ts
  src/components/MAPI/workernodes/utils.ts
  src/components/UI/Controls/Button/index.tsx
  src/components/UI/Display/MAPI/workernodes/WorkerNodesNodePoolActions.tsx
  src/components/UI/Display/MAPI/workernodes/WorkerNodesNodePoolListPlaceholder.tsx
  src/components/UI/Inputs/ViewEditName.tsx
Labels: kind/refactor

#3024 Make cluster details > client certificates tab aware of permissions for a read-only user
  src/components/MAPI/clusters/guides/CreateKeyPairGuide.tsx
  src/components/MAPI/keypairs/ClusterDetailKeyPairs.tsx
  src/components/MAPI/keypairs/permissions/usePermissionsForCertConfigs.ts
  src/components/MAPI/keypairs/permissions/usePermissionsForKeyPairs.ts
  src/components/MAPI/keypairs/permissions/usePermissionsForStorageConfigs.ts
Labels: kind/refactor

#3035 Make cluster details > actions tab aware of permissions for a read-only user
  src/components/MAPI/apps/permissions/usePermissionsForApps.ts
  src/components/MAPI/clusters/ClusterDetail/ClusterDetailActions.tsx
  src/components/MAPI/clusters/guides/DeleteClusterGuide.tsx
  src/components/MAPI/permissions/utils.ts
  src/components/MAPI/workernodes/permissions/usePermissionsForNodePools.ts
  src/components/MAPI/workernodes/permissions/usePermissionsForSparks.ts
  src/components/UI/Display/MAPI/clusters/ClusterDetail/ClusterDetailDeleteAction.tsx
  src/components/UI/Display/MAPI/clusters/ClusterDetail/__tests__/ClusterDetailDeleteAction.tsx
Labels: kind/refactor

#3040 Fix not being able to find cluster's organization in organization list
  src/components/MAPI/clusters/ClusterList/ClusterListItem.tsx
Labels: kind/bug

#3043 Allow impersonation headers via CORS
  helm/happa/templates/happaapi-ingress.yaml
Labels: kind/dev-change
