Repository giantswarm/happa, pull requests merged in 2021-04, with the labels that each got.

#2319 Create component for n/a label
  src/components/Cluster/ClusterDetail/ClusterApps.js
  src/components/Cluster/ClusterDetail/KeyPairDetailsModal.js
  src/components/Cluster/ClusterDetail/NodePoolScalingSpotInstancesDetails.tsx
  src/components/Cluster/ClusterDetail/RegionAndVersions.tsx
  src/components/Cluster/ClusterDetail/UserInstalledApps/InstalledApp.js
  src/components/Cluster/ClusterDetail/WorkerNodesAWS.js
  src/components/Cluster/ClusterDetail/WorkerNodesAzure.js
  src/components/Cluster/ClusterDetail/WorkerNodesKVM.js
  src/components/UI/Display/Cluster/AvailabilityZones/AvailabilityZonesLabels.js
  src/components/UI/Display/Cluster/KubernetesVersionLabel.tsx
  src/components/UI/Display/NotAvailable/index.tsx
  src/components/UI/Display/NotAvailable/stories/NotAvailable.stories.tsx
  src/components/UI/Display/Organizations/OrganizationDetailPage.tsx
  src/components/UI/Display/Organizations/OrganizationListPage.tsx
  src/lib/helpers.tsx
Labels: kind/change

#2312 access control: add extra tests covering the rest of the business logic
  src/components/MAPI/organizations/AccessControl/__tests__/index.tsx
  src/components/MAPI/organizations/AccessControl/utils.ts
  src/model/services/mapi/corev1/deleteServiceAccount.ts
  src/model/services/mapi/metav1/types.ts
  src/model/services/mapi/rbacv1/deleteClusterRoleBinding.ts
  src/model/services/mapi/rbacv1/deleteRoleBinding.ts
  src/model/services/mapi/securityv1alpha1/deleteOrganization.ts
  testUtils/mockHttpCalls/corev1/index.ts
  testUtils/mockHttpCalls/corev1/serviceAccounts.ts
  testUtils/mockHttpCalls/rbacv1/roleBindings.ts
Labels: kind/dev-change

#2311 Bring back cluster count in new MAPI based org list
  src/components/MAPI/organizations/OrganizationList.tsx
  src/components/UI/Display/Organizations/OrganizationListPage.tsx
  src/components/UI/Display/Organizations/stories/Simple.tsx
  src/stores/cluster/selectors.ts
  src/stores/cluster/utils.ts
Labels: kind/feature

#2329 Access control UI tweaks
  src/components/MAPI/organizations/AccessControl/__tests__/index.tsx
  src/components/MAPI/organizations/AccessControl/index.tsx
  src/components/UI/Display/MAPI/AccessControl/AccessControlRoleListItem.tsx
  src/components/UI/Display/MAPI/AccessControl/AccessControlRolePermissions.tsx
  src/components/UI/Display/MAPI/AccessControl/AccessControlRoleVerbs.tsx
  src/components/UI/Display/MAPI/AccessControl/__tests__/AccessControlRoleList.tsx
  src/components/UI/Display/MAPI/AccessControl/__tests__/AccessControlRolePermissions.tsx
  src/components/UI/Util/Truncated.tsx
  src/components/UI/__tests__/Truncated.ts
Labels: kind/ux-enhancement

#2333 Upgrade storybook to v6.2.4
  package.json
  yarn.lock
Labels: dependencies

#2310 Refactor some mock http responses I added.
  __tests__/AdminLogin.tsx
  __tests__/Login.tsx
  testUtils/mockHttpCalls/authorizationv1/index.ts
  testUtils/mockHttpCalls/authorizationv1/selfSubjectAccessReviews.ts
  testUtils/mockHttpCalls/authorizationv1/selfSubjectRulesReviews.ts
  testUtils/mockHttpCalls/index.js
  testUtils/mockHttpCalls/securityv1alpha1/index.ts
  testUtils/mockHttpCalls/securityv1alpha1/organization.ts
  testUtils/mockHttpCalls/securityv1alpha1/organizations.ts
Labels: kind/refactor

#2336 update some deps and stuff
  .circleci/config.yml
  .storybook/main.js
  package.json
  src/components/UI/Display/Cluster/ClusterDetailPreinstalledApp.js
  src/components/UI/Display/Table/__tests__/__snapshots__/index.tsx.snap
  src/components/UI/Inputs/CheckBoxInput/__tests__/__snapshots__/index.tsx.snap
  src/components/UI/Inputs/CurrencyInput/__tests__/__snapshots__/CurrencyInput.tsx.snap
  src/components/UI/Inputs/DateInput/__tests__/__snapshots__/index.tsx.snap
  src/components/UI/Inputs/FileInput/__tests__/__snapshots__/index.tsx.snap
  src/components/UI/Inputs/InputGroup/__tests__/__snapshots__/index.tsx.snap
  src/components/UI/Inputs/MultiSelect/__tests__/__snapshots__/index.tsx.snap
  src/components/UI/Inputs/NumberPicker/__tests__/__snapshots__/index.tsx.snap
  src/components/UI/Inputs/RadioInput/__tests__/__snapshots__/index.tsx.snap
  src/components/UI/Inputs/Select/__tests__/__snapshots__/index.tsx.snap
  src/components/UI/Inputs/TextArea/__tests__/__snapshots__/index.tsx.snap
  src/components/UI/Inputs/TextInput/__tests__/__snapshots__/index.tsx.snap
  yarn.lock
Labels: dependencies

#2345 Add props to mitigate warnings in storybook
  src/components/UI/Display/Apps/AppDetailNew/AppDetailPage.stories.tsx
Labels: kind/dev-change

#2344 Add InstalledApp to storybook, convert to TS
  src/components/Cluster/ClusterDetail/UserInstalledApps/InstalledApp.tsx
  src/components/Cluster/ClusterDetail/UserInstalledApps/__tests__/InstalledApp.tsx
  src/components/Cluster/ClusterDetail/UserInstalledApps/stories/InstalledApp.stories.tsx
Labels: kind/dev-change

#2348 Add corev1.ConfigMap client functions and types
  src/model/services/mapi/corev1/createConfigMap.ts
  src/model/services/mapi/corev1/deleteConfigMap.ts
  src/model/services/mapi/corev1/getConfigMap.ts
  src/model/services/mapi/corev1/index.ts
  src/model/services/mapi/corev1/types.ts
  src/model/services/mapi/generic/createResource.ts
Labels: kind/dev-change

#2363 access control: fix role loading animation content
  src/components/UI/Display/MAPI/AccessControl/AccessControlRoleListItemLoadingPlaceholder.tsx
Labels: kind/bug

#2361 access control: display 'All (*)' where all verbs are supported
  src/components/MAPI/organizations/AccessControl/__tests__/index.tsx
  src/components/UI/Display/MAPI/AccessControl/AccessControlRoleVerbs.tsx
  src/components/UI/Display/MAPI/AccessControl/__tests__/AccessControlRolePermissions.tsx
Labels: kind/ux-enhancement

#2362 access control: extend search to look for queries EVERYWHERE
  src/components/MAPI/organizations/AccessControl/utils.ts
Labels: kind/ux-enhancement

#2366 access control: various ux improvements and bug fixes
  src/components/MAPI/organizations/AccessControl/__tests__/index.tsx
  src/components/MAPI/organizations/AccessControl/utils.ts
  src/components/UI/Display/MAPI/AccessControl/AccessControlRoleList.tsx
  src/components/UI/Display/MAPI/AccessControl/AccessControlRoleListItem.tsx
  src/components/UI/Display/MAPI/AccessControl/AccessControlRoleVerbs.tsx
  src/model/services/mapi/rbacv1/types.ts
Labels: kind/ux-enhancement

#2360 access control: reuse existing service accounts and display existing ones as suggestions
  src/components/MAPI/organizations/AccessControl/AccessControlRoleSubjects.tsx
  src/components/MAPI/organizations/AccessControl/__tests__/AccessControlRoleSubjects.tsx
  src/components/MAPI/organizations/AccessControl/__tests__/index.tsx
  src/components/MAPI/organizations/AccessControl/__tests__/utils.ts
  src/components/MAPI/organizations/AccessControl/index.tsx
  src/components/MAPI/organizations/AccessControl/utils.ts
  src/components/UI/Display/MAPI/AccessControl/AccessControlRoleDetail.tsx
  src/components/UI/Display/MAPI/AccessControl/AccessControlRoleVerbs.tsx
  src/components/UI/Display/MAPI/AccessControl/AccessControlSubjectAddForm.tsx
  src/components/UI/Display/MAPI/AccessControl/AccessControlSubjectSet.tsx
  src/components/UI/Display/MAPI/AccessControl/__tests__/AccessControlRoleDetail.tsx
  src/components/UI/Inputs/TextInput/index.tsx
  src/components/UI/Inputs/TextInput/stories/Suggestions.tsx
  src/components/UI/Inputs/TextInput/stories/TextInput.stories.tsx
  src/model/services/mapi/corev1/getServiceAccountList.ts
  src/model/services/mapi/corev1/index.ts
  src/model/services/mapi/corev1/types.ts
  testUtils/mockHttpCalls/corev1/serviceAccounts.ts
Labels: kind/feature

#2367 Add chart and configuration for FE Docs
  .circleci/config.yml
  Dockerfile
  Dockerfile.fe-docs
  helm/fe-docs/.helmignore
  helm/fe-docs/Chart.yaml
  helm/fe-docs/ci/default-values.yaml
  helm/fe-docs/templates/deployment.yaml
  helm/fe-docs/templates/ingress.yaml
  helm/fe-docs/templates/psp.yaml
  helm/fe-docs/templates/rbac.yaml
  helm/fe-docs/templates/service-account.yaml
  helm/fe-docs/templates/service.yaml
  helm/fe-docs/values.yaml
  nginx.conf
Labels: kind/dev-change

#2358 organizations: enable deletion for SSO users
  src/components/Cluster/ClusterDetail/KeypairCreateModal/KeyPairCreateModal.tsx
  src/components/MAPI/organizations/AccessControl/index.tsx
  src/components/MAPI/organizations/AccessControl/utils.ts
  src/components/MAPI/organizations/OrganizationDetail.tsx
  src/components/MAPI/organizations/OrganizationDetailDelete.tsx
  src/components/MAPI/organizations/__tests__/OrganizationDetail.tsx
  src/components/MAPI/organizations/utils.ts
  src/components/UI/Controls/Button/index.js
  src/components/UI/Display/Organizations/OrganizationDetailPage.tsx
  src/model/services/mapi/capiv1alpha3/getClusterList.ts
  src/model/services/mapi/capiv1alpha3/key.ts
  src/model/services/mapi/k8sUrl.ts
  src/stores/organization/actions.ts
Labels: kind/feature

#2376 authentication: make happa aware of permissions
  __tests__/AdminLogin.tsx
  src/@types/users.d.ts
  src/components/Layout.js
  src/components/MAPI/organizations/AccessControl/index.tsx
  src/components/UI/Display/Loading/LoadingOverlay.js
  src/components/__tests__/Layout.tsx
  src/model/services/mapi/authorizationv1/createSelfSubjectRulesReview.ts
  src/model/services/mapi/authorizationv1/types.ts
  src/stores/batchActions.ts
  src/stores/main/__tests__/utils.ts
  src/stores/main/actions.ts
  src/stores/main/constants.ts
  src/stores/main/reducer.ts
  src/stores/main/selectors.ts
  src/stores/main/types.ts
  src/stores/main/utils.ts
  src/stores/organization/actions.ts
  src/stores/organization/selectors.ts
  testUtils/mockHttpCalls/authorizationv1/selfSubjectRulesReviews.ts
  testUtils/preloginState.js
Labels: kind/feature

#2381 Remove error notification for expired credentials
  src/stores/batchActions.ts
Labels: kind/dev-change

#2379 organizations: populate cluster summary stats with real data
  src/components/MAPI/organizations/OrganizationDetail.tsx
  src/components/MAPI/organizations/OrganizationDetailGeneral/__tests__/index.tsx
  src/components/MAPI/organizations/OrganizationDetailGeneral/index.tsx
  src/components/MAPI/organizations/OrganizationDetailGeneral/utils.ts
  src/components/UI/Display/Organizations/OrganizationDetailPage.tsx
  src/components/UI/Display/Organizations/OrganizationDetailStatistic.tsx
  src/components/UI/Display/Organizations/OrganizationDetailStatisticPlaceholder.tsx
  src/components/UI/Display/Organizations/types.ts
  src/model/services/mapi/capiv1alpha3/exp/getMachinePoolList.ts
  src/model/services/mapi/capiv1alpha3/exp/index.ts
  src/model/services/mapi/capiv1alpha3/exp/types.ts
  src/model/services/mapi/capiv1alpha3/getMachineDeploymentList.ts
  src/model/services/mapi/capiv1alpha3/index.ts
  src/model/services/mapi/capiv1alpha3/key.ts
  src/model/services/mapi/capiv1alpha3/types.ts
  src/model/services/mapi/capzv1alpha3/exp/getAzureMachinePool.ts
  src/model/services/mapi/capzv1alpha3/exp/index.ts
  src/model/services/mapi/capzv1alpha3/exp/types.ts
  src/model/services/mapi/capzv1alpha3/getAzureMachineList.ts
  src/model/services/mapi/capzv1alpha3/index.ts
  src/model/services/mapi/capzv1alpha3/types.ts
  src/model/services/mapi/corev1/types.ts
Labels: kind/ux-enhancement

#2385 Rename admin group
  src/stores/main/utils.ts
Labels: kind/dev-change

#2386 authentication: get admin group from configmap
  .circleci/config.yml
  helm/happa/ci/default-values.yaml
  helm/happa/templates/configmap.yaml
  helm/happa/templates/deployment.yaml
  scripts/start.sh
  src/@types/global.d.ts
  src/index.ejs
  src/stores/main/utils.ts
Labels: kind/dev-change

#2382 Add azure catalog icon(s)
  src/images/repo_icons/azure-catalog-test.png
  src/images/repo_icons/azure-catalog.png
Labels: kind/dev-change

#2387 organizations: show stats for releases in the organization details page
  src/components/MAPI/organizations/OrganizationDetailGeneral/index.tsx
  src/components/MAPI/organizations/OrganizationDetailGeneral/utils.ts
  src/components/UI/Display/Organizations/OrganizationDetailPage.tsx
  src/model/services/mapi/releasev1alpha1/getRelease.ts
  src/model/services/mapi/releasev1alpha1/index.ts
  src/model/services/mapi/releasev1alpha1/key.ts
  src/model/services/mapi/releasev1alpha1/types.ts
Labels: kind/ux-enhancement

#2389 organizations: display stats about apps installed in clusters
  __tests__/ClusterManagement.js
  src/components/MAPI/organizations/OrganizationDetailGeneral/__tests__/index.tsx
  src/components/MAPI/organizations/OrganizationDetailGeneral/index.tsx
  src/components/MAPI/organizations/OrganizationDetailGeneral/utils.ts
  src/components/UI/Display/Organizations/OrganizationDetailPage.tsx
  src/components/UI/Display/Organizations/OrganizationDetailStatistic.tsx
  src/components/UI/Display/Organizations/types.ts
  src/model/services/mapi/applicationv1alpha1/getAppList.ts
  src/model/services/mapi/applicationv1alpha1/index.ts
  src/model/services/mapi/applicationv1alpha1/types.ts
  src/model/services/mapi/capiv1alpha3/getClusterInfraRef.ts
  src/model/services/mapi/capiv1alpha3/key.ts
  src/model/services/mapi/capiv1alpha3/types.ts
  src/model/services/mapi/capzv1alpha3/types.ts
  src/model/services/mapi/releasev1alpha1/types.ts
  testUtils/mockHttpCalls/applicationv1alpha1/apps.ts
  testUtils/mockHttpCalls/applicationv1alpha1/index.ts
  testUtils/mockHttpCalls/capiv1alpha3/clusters.ts
  testUtils/mockHttpCalls/capiv1alpha3/exp/index.ts
  testUtils/mockHttpCalls/capiv1alpha3/exp/machinePools.ts
  testUtils/mockHttpCalls/capiv1alpha3/index.ts
  testUtils/mockHttpCalls/capzv1alpha3/azureMachines.ts
  testUtils/mockHttpCalls/capzv1alpha3/exp/azureMachinePools.ts
  testUtils/mockHttpCalls/capzv1alpha3/exp/index.ts
  testUtils/mockHttpCalls/capzv1alpha3/index.ts
  testUtils/mockHttpCalls/releasev1alpha1/index.ts
  testUtils/mockHttpCalls/releasev1alpha1/releases.ts
Labels: kind/ux-enhancement

#2384 docs: add architecture overview and a couple recipes
  package.json
  src/components/UI/Display/Documentation/Mermaid.tsx
  src/stories/ArchitectureOverview.stories.mdx
  src/stories/Recipes/NewComponent.stories.mdx
  src/stories/Recipes/NewFeatureFlag.stories.mdx
  yarn.lock
Labels: kind/dev-change

#2394 Storybook 6.2.9
  package.json
  yarn.lock
Labels: dependencies
