Repository giantswarm/happa, pull requests merged in 2021-06, with the labels that each got.

#2478 Set JSON content type header for Passage requests
  src/lib/passageClient.ts
Labels: kind/bug

#2479 clusters: implement homepage cluster list via MAPI on Azure
  .circleci/config.yml
  helm/happa/templates/configmap.yaml
  helm/happa/templates/deployment.yaml
  jest.config.js
  scripts/start.sh
  src/@types/global.d.ts
  src/components/Layout.js
  src/components/MAPI/clusters/ClusterList.tsx
  src/components/MAPI/clusters/ClusterList/ClusterListItem.tsx
  src/components/MAPI/clusters/ClusterList/ClusterListItemStatus.tsx
  src/components/MAPI/clusters/ClusterListItem.tsx
  src/components/MAPI/clusters/ClusterListItemDetails.tsx
  src/components/MAPI/clusters/Clusters.tsx
  src/components/MAPI/clusters/utils.ts
  src/components/MAPI/organizations/OrganizationDetailGeneral/utils.ts
  src/components/MAPI/utils.ts
  src/components/UI/Controls/Button/index.js
  src/components/UI/Display/Cluster/ClusterIDLabel/index.js
  src/components/UI/Display/MAPI/clusters/ClusterList/ClusterListEmptyPlaceholder.tsx
  src/components/UI/Display/MAPI/clusters/ClusterList/ClusterListErrorPlaceholder.tsx
  src/components/UI/Display/MAPI/clusters/ClusterList/ClusterListItem.tsx
  src/components/UI/Display/MAPI/clusters/ClusterList/ClusterListItemLoadingPlaceholder.tsx
  src/components/UI/Display/MAPI/clusters/ClusterList/ClusterListItemMainInfo.tsx
  src/components/UI/Display/MAPI/clusters/ClusterList/ClusterListItemNodeInfo.tsx
  src/components/UI/Display/MAPI/clusters/ClusterList/ClusterListItemOptionalValue.tsx
  src/components/UI/Display/MAPI/clusters/ClusterList/ClusterListNoOrgsPlaceholder.tsx
  src/components/UI/Display/MAPI/clusters/types.ts
  src/index.ejs
  src/lib/ReleaseHelper.ts
  src/model/services/mapi/capiv1alpha3/key.ts
  src/model/services/mapi/corev1/index.ts
  src/model/services/mapi/corev1/key.ts
  src/model/services/mapi/releasev1alpha1/getReleaseList.ts
  src/model/services/mapi/releasev1alpha1/index.ts
  src/shared/featureFlags.ts
  src/shared/featureSupport.ts
  src/styles/transitions/BaseTransition.tsx
  webpack.common.js
Labels: kind/refactor

#2482 Update Sentry SDK to v6.5.1
  package.json
  yarn.lock
Labels: dependencies

#2480 Switch to the `swc` compiler
  .circleci/config.yml
  jest.config.js
  package.json
  src/components/index.tsx
  src/styles/index.ts
  tsconfig.json
  webpack.common.js
  yarn.lock
Labels: kind/dev-change

#2483 Change error message wording
  src/model/clients/HttpClient.ts
  src/model/clients/__tests__/HttpClient.ts
Labels: kind/change

#2484 clusters: add a new cluster detail page with basic functionality
  src/components/Cluster/ClusterDetail/URIBlock.js
  src/components/GettingStarted/GettingStarted.js
  src/components/MAPI/clusters/Cluster.tsx
  src/components/MAPI/clusters/ClusterDetail/ClusterDetailOverview.tsx
  src/components/MAPI/clusters/ClusterDetail/index.tsx
  src/components/MAPI/clusters/ClusterDetail/utils.ts
  src/components/MAPI/organizations/Organization.tsx
  src/components/UI/Display/Cluster/ClusterIDLabel/index.js
  src/components/UI/Display/MAPI/clusters/ClusterDetail/ClusterDetailOverview.tsx
  src/components/UI/Display/MAPI/clusters/ClusterDetail/ClusterDetailOverviewDelete.tsx
  src/components/UI/Display/MAPI/clusters/ClusterDetail/ClusterDetailWidget/__tests__/__snapshots__/index.tsx.snap
  src/components/UI/Display/MAPI/clusters/ClusterDetail/ClusterDetailWidget/__tests__/index.tsx
  src/components/UI/Display/MAPI/clusters/ClusterDetail/ClusterDetailWidget/index.tsx
  src/components/UI/Display/MAPI/clusters/ClusterDetail/ClusterDetailWidget/stories/ClusterDetailWidget.stories.tsx
  src/components/UI/Display/MAPI/clusters/ClusterDetail/ClusterDetailWidget/stories/Inline.tsx
  src/components/UI/Display/MAPI/clusters/ClusterDetail/ClusterDetailWidget/stories/Simple.tsx
  src/components/UI/Display/MAPI/clusters/ClusterDetail/ClusterDetailWidgetCreated.tsx
  src/components/UI/Display/MAPI/clusters/ClusterDetail/ClusterDetailWidgetKubernetesAPI.tsx
  src/components/UI/Display/MAPI/clusters/ClusterDetail/ClusterDetailWidgetLoadingPlaceholder.tsx
  src/components/UI/Display/MAPI/clusters/ClusterDetail/ClusterDetailWidgetOptionalValue.tsx
  src/components/UI/Display/MAPI/clusters/types.ts
  src/components/UI/Inputs/ViewEditName.tsx
  src/model/services/mapi/capiv1alpha3/deleteCluster.ts
  src/model/services/mapi/capiv1alpha3/getCluster.ts
  src/model/services/mapi/capiv1alpha3/index.ts
  src/model/services/mapi/capiv1alpha3/key.ts
  src/model/services/mapi/capiv1alpha3/updateCluster.ts
  src/shared/featureFlags.ts
Labels: kind/refactor

#2488 build: give the build process a bit of love
  .circleci/config.yml
  jest.config.js
  package.json
  src/components/UI/Controls/ConfirmationPrompt/__tests__/__snapshots__/index.tsx.snap
  src/components/UI/Display/MAPI/clusters/ClusterDetail/ClusterDetailWidget/__tests__/__snapshots__/index.tsx.snap
  src/components/UI/Display/Table/__tests__/__snapshots__/index.tsx.snap
  src/components/UI/Inputs/CheckBoxInput/__tests__/__snapshots__/index.tsx.snap
  src/components/UI/Inputs/CurrencyInput/__tests__/__snapshots__/CurrencyInput.tsx.snap
  src/components/UI/Inputs/DateInput/__tests__/__snapshots__/index.tsx.snap
  src/components/UI/Inputs/FileInput/__tests__/__snapshots__/index.tsx.snap
  src/components/UI/Inputs/InputGroup/__tests__/__snapshots__/index.tsx.snap
  src/components/UI/Inputs/MultiSelect/__tests__/__snapshots__/index.tsx.snap
  src/components/UI/Inputs/NumberPicker/__tests__/__snapshots__/index.tsx.snap
  src/components/UI/Inputs/RadioInput/__tests__/__snapshots__/index.tsx.snap
  src/components/UI/Inputs/Select/__tests__/__snapshots__/index.tsx.snap
  src/components/UI/Inputs/TextArea/__tests__/__snapshots__/index.tsx.snap
  src/components/UI/Inputs/TextInput/__tests__/__snapshots__/index.tsx.snap
  webpack.common.js
  webpack.dev.js
  webpack.prod.js
  yarn.lock
Labels: kind/dev-change

#2491 Fix sentry sourcemaps
  webpack.prod.js
Labels: kind/dev-change

#2490 Get rid of stylelint
  .stylelintrc
  package.json
  yarn.lock
Labels: kind/dev-change

#2489 Only run pre-commit hook for staged files
  .husky/pre-commit
  jest.config.js
  package.json
  webpack.prod.js
Labels: kind/dev-change

#2485 clusters: add cluster widgets for worker node, app, key pair stats
  src/components/MAPI/apps/utils.ts
  src/components/MAPI/clusters/ClusterDetail/ClusterDetailOverview.tsx
  src/components/MAPI/keypairs/utils.ts
  src/components/UI/Display/MAPI/apps/ClusterDetailWidgetApps.tsx
  src/components/UI/Display/MAPI/clusters/ClusterDetail/ClusterDetailCounter/__tests__/__snapshots__/index.tsx.snap
  src/components/UI/Display/MAPI/clusters/ClusterDetail/ClusterDetailCounter/__tests__/index.tsx
  src/components/UI/Display/MAPI/clusters/ClusterDetail/ClusterDetailCounter/index.tsx
  src/components/UI/Display/MAPI/clusters/ClusterDetail/ClusterDetailCounter/stories/ClusterDetailCounter.stories.tsx
  src/components/UI/Display/MAPI/clusters/ClusterDetail/ClusterDetailCounter/stories/PluralizedLabel.tsx
  src/components/UI/Display/MAPI/clusters/ClusterDetail/ClusterDetailCounter/stories/Simple.tsx
  src/components/UI/Display/MAPI/clusters/ClusterDetail/ClusterDetailOverview.tsx
  src/components/UI/Display/MAPI/clusters/ClusterDetail/ClusterDetailWidget/__tests__/__snapshots__/index.tsx.snap
  src/components/UI/Display/MAPI/clusters/ClusterDetail/ClusterDetailWidget/index.tsx
  src/components/UI/Display/MAPI/clusters/ClusterDetail/ClusterDetailWidgetWorkerNodes.tsx
  src/components/UI/Display/MAPI/clusters/types.ts
  src/components/UI/Display/MAPI/keypairs/ClusterDetailWidgetKeyPairs.tsx
  src/lib/docs.ts
  src/model/services/mapi/gscorev1alpha1/getStorageConfig.ts
  src/model/services/mapi/gscorev1alpha1/index.ts
  src/model/services/mapi/gscorev1alpha1/types.ts
  src/model/services/mapi/legacy/keypairs/getKeyPairList.ts
  src/model/services/mapi/legacy/keypairs/index.ts
  src/model/services/mapi/legacy/keypairs/key.ts
  src/model/services/mapi/legacy/keypairs/types.ts
  src/shared/constants/routes.ts
Labels: kind/refactor

#2487 clusters: add Control Plane nodes widget to the MAPI cluster detail page
  src/components/MAPI/clusters/ClusterDetail/ClusterDetailOverview.tsx
  src/components/MAPI/clusters/ClusterDetail/utils.ts
  src/components/MAPI/organizations/OrganizationDetailGeneral/__tests__/index.tsx
  src/components/MAPI/types.ts
  src/components/MAPI/utils.ts
  src/components/UI/Display/MAPI/clusters/ClusterDetail/ClusterDetailOverview.tsx
  src/components/UI/Display/MAPI/clusters/ClusterDetail/ClusterDetailWidgetControlPlaneNodes.tsx
  src/components/UI/Display/MAPI/clusters/ClusterDetail/ClusterDetailWidgetOptionalValue.tsx
  src/components/UI/Display/MAPI/clusters/ClusterDetail/utils.ts
  src/components/UI/Display/MAPI/clusters/types.ts
  src/model/services/mapi/capiv1alpha3/key.ts
  src/model/services/mapi/capiv1alpha3/types.ts
  src/model/services/mapi/capzv1alpha3/index.ts
  src/model/services/mapi/capzv1alpha3/key.ts
Labels: kind/refactor

#2486 clusters: add Labels widget to the MAPI cluster detail page
  src/components/Cluster/ClusterDetail/ClusterLabels/ClusterLabels.tsx
  src/components/Cluster/ClusterDetail/ClusterLabels/DeleteLabelButton.tsx
  src/components/Cluster/ClusterDetail/ClusterLabels/EditLabelTooltip.tsx
  src/components/Cluster/ClusterDetail/V5ClusterDetailTable.js
  src/components/MAPI/clusters/ClusterDetail/ClusterDetailOverview.tsx
  src/components/MAPI/clusters/ClusterDetail/utils.ts
  src/components/UI/Display/Cluster/ClusterLabels/DeleteLabelButton.tsx
  src/components/UI/Display/Cluster/ClusterLabels/LabelWrapper.tsx
  src/components/UI/Display/MAPI/clusters/ClusterDetail/ClusterDetailCounter/__tests__/__snapshots__/index.tsx.snap
  src/components/UI/Display/MAPI/clusters/ClusterDetail/ClusterDetailOverview.tsx
  src/components/UI/Display/MAPI/clusters/ClusterDetail/ClusterDetailWidget/__tests__/__snapshots__/index.tsx.snap
  src/components/UI/Display/MAPI/clusters/ClusterDetail/ClusterDetailWidgetLabels.tsx
  src/components/UI/Display/MAPI/clusters/types.ts
  src/components/UI/Display/ValueLabel.tsx
  src/model/services/mapi/capiv1alpha3/key.ts
  src/stores/clusterlabels/types.ts
Labels: kind/refactor

#2497 Update Sentry to v6.7.0
  package.json
  yarn.lock
Labels: dependencies

#2499 clusters: add 50% of the Release widget to the MAPI cluster detail page
  src/components/MAPI/clusters/ClusterDetail/ClusterDetailOverview.tsx
  src/components/MAPI/clusters/ClusterDetail/utils.ts
  src/components/UI/Display/MAPI/clusters/ClusterDetail/ClusterDetailOverview.tsx
  src/components/UI/Display/MAPI/clusters/ClusterDetail/ClusterDetailWidgetRelease.tsx
  src/components/UI/Display/MAPI/clusters/ClusterList/ClusterListItem.tsx
  src/components/UI/Display/MAPI/clusters/ClusterList/ClusterListItemMainInfo.tsx
  src/components/UI/Display/MAPI/clusters/types.ts
  src/components/UI/Display/MAPI/releases/types.ts
Labels: kind/refactor

#2500 clusters: add the Apps and Ingress tabs to the MAPI cluster detail page
  src/components/Cluster/ClusterDetail/ClusterDetailView.js
  src/components/MAPI/apps/ClusterDetailApps.tsx
  src/components/MAPI/apps/ClusterDetailIngress.tsx
  src/components/MAPI/clusters/ClusterDetail/index.tsx
Labels: kind/refactor

#2505 Rename master node to control plane node
  __tests__/V5ClusterManagement.js
  src/components/Cluster/ClusterDetail/MasterNodes/MasterNodes.tsx
  src/components/Cluster/ClusterDetail/MasterNodes/MasterNodesConverter.tsx
  src/components/Cluster/ClusterDetail/MasterNodes/MasterNodesUtils.ts
  src/components/Cluster/ClusterDetail/MasterNodes/__tests__/MasterNodes.ts
  src/components/Cluster/ClusterDetail/MasterNodes/__tests__/MasterNodesUtils.ts
  src/components/Cluster/NewCluster/MasterNodes.tsx
  src/components/Cluster/NewCluster/__tests__/MasterNodes.ts
  src/stores/cluster/__tests__/utils.ts
Labels: kind/change

#2506 Submit each URI visited to RUM
  src/components/index.tsx
  src/shared/constants/realUserMonitoring.ts
Labels: kind/change

#2507 Update sentry to v6.7.1
  package.json
  yarn.lock
Labels: dependencies

#2501 clusters: make cluster detail components and cluster list components more flexible
  src/components/MAPI/apps/ClusterDetailWidgetApps.tsx
  src/components/MAPI/clusters/ClusterDetail/ClusterDetailOverview.tsx
  src/components/MAPI/clusters/ClusterDetail/ClusterDetailOverviewDelete.tsx
  src/components/MAPI/clusters/ClusterDetail/ClusterDetailWidgetControlPlaneNodes.tsx
  src/components/MAPI/clusters/ClusterDetail/ClusterDetailWidgetCreated.tsx
  src/components/MAPI/clusters/ClusterDetail/ClusterDetailWidgetKubernetesAPI.tsx
  src/components/MAPI/clusters/ClusterDetail/ClusterDetailWidgetLabels.tsx
  src/components/MAPI/clusters/ClusterDetail/ClusterDetailWidgetProvider.tsx
  src/components/MAPI/clusters/ClusterDetail/ClusterDetailWidgetWorkerNodes.tsx
  src/components/MAPI/clusters/ClusterDetail/utils.ts
  src/components/MAPI/clusters/ClusterList/ClusterListItem.tsx
  src/components/MAPI/keypairs/ClusterDetailWidgetKeyPairs.tsx
  src/components/MAPI/releases/ClusterDetailWidgetRelease.tsx
  src/components/UI/Display/MAPI/apps/ClusterDetailWidgetApps.tsx
  src/components/UI/Display/MAPI/clusters/ClusterDetail/ClusterDetailOverview.tsx
  src/components/UI/Display/MAPI/clusters/ClusterDetail/ClusterDetailWidgetLabels.tsx
  src/components/UI/Display/MAPI/clusters/ClusterDetail/ClusterDetailWidgetProvider.tsx
  src/components/UI/Display/MAPI/clusters/ClusterDetail/ClusterDetailWidgetWorkerNodes.tsx
  src/components/UI/Display/MAPI/clusters/ClusterDetail/utils.ts
  src/components/UI/Display/MAPI/clusters/ClusterList/ClusterListItem.tsx
  src/components/UI/Display/MAPI/clusters/ClusterList/ClusterListItemMainInfo.tsx
  src/components/UI/Display/MAPI/clusters/ClusterList/ClusterListItemNodeInfo.tsx
  src/components/UI/Display/MAPI/clusters/types.ts
  src/components/UI/Display/MAPI/keypairs/ClusterDetailWidgetKeyPairs.tsx
  src/components/UI/Display/MAPI/releases/types.ts
Labels: kind/refactor

#2510 Use TypeScript for configuring webpack
  package.json
  tsconfig.json
  webpack.common.ts
  webpack.dev.ts
  webpack.prod.ts
  yarn.lock
Labels: kind/dev-change

#2509 Add external link icon to app website URL
  README.md
  src/components/UI/Display/Apps/AppDetailNew/AppDetailPage.tsx
  src/components/UI/Display/MAPI/clusters/ClusterDetail/ClusterDetailCounter/__tests__/__snapshots__/index.tsx.snap
  src/components/UI/Display/MAPI/clusters/ClusterDetail/ClusterDetailWidget/__tests__/__snapshots__/index.tsx.snap
  src/components/UI/Inputs/NumberPicker/__tests__/__snapshots__/index.tsx.snap
  src/components/UI/Inputs/RadioInput/__tests__/__snapshots__/index.tsx.snap
Labels: kind/ux-enhancement

#2513 clusters: display release details when clicking on release version
  src/components/MAPI/clusters/utils.ts
  src/components/MAPI/releases/ClusterDetailReleaseDetailsModal.tsx
  src/components/MAPI/releases/ClusterDetailWidgetRelease.tsx
  src/components/Modals/ReleaseDetailsModal/ReleaseDetailsModalSection.tsx
  src/components/UI/Display/MAPI/clusters/ClusterDetail/ClusterDetailStatus.tsx
  src/model/services/mapi/releasev1alpha1/key.ts
Labels: kind/refactor

#2516 clusters: add support for upgrading clusters using the MAPI cluster detail page
  src/components/MAPI/clusters/ClusterDetail/utils.ts
  src/components/MAPI/clusters/utils.ts
  src/components/MAPI/releases/ClusterDetailReleaseDetailsModal.tsx
  src/components/MAPI/releases/ClusterDetailUpgradeModal.tsx
  src/components/MAPI/releases/ClusterDetailWidgetRelease.tsx
  src/components/MAPI/releases/__tests__/utils.ts
  src/components/MAPI/releases/utils.ts
  src/components/UI/Display/MAPI/releases/ClusterDetailReleaseDetailsUpgradeOptions.tsx
  src/components/UI/Display/MAPI/releases/ClusterDetailUpgradeModalChangelog.tsx
  src/components/UI/Display/MAPI/releases/ClusterDetailUpgradeModalDisclaimer.tsx
  src/components/UI/Display/MAPI/releases/types.ts
  testUtils/mockHttpCalls/releasev1alpha1/releases.ts
Labels: kind/refactor

#2518 clusters: add support for updating node pool descriptions via the MAPI cluster detail page
  src/components/MAPI/workernodes/WorkerNodesNodePoolItem.tsx
  src/components/MAPI/workernodes/utils.ts
  src/components/UI/Controls/DropdownMenu.js
  src/components/UI/Display/MAPI/clusters/ClusterDetail/ClusterDetailCounter/__tests__/__snapshots__/index.tsx.snap
  src/components/UI/Display/MAPI/clusters/ClusterDetail/ClusterDetailWidget/__tests__/__snapshots__/index.tsx.snap
  src/components/UI/Display/MAPI/workernodes/WorkerNodesNodePoolActions.tsx
  src/components/UI/Inputs/ViewEditName.tsx
  src/components/UI/__tests__/ViewEditName.js
  src/model/services/mapi/capiv1alpha3/exp/getMachinePool.ts
  src/model/services/mapi/capiv1alpha3/exp/index.ts
  src/model/services/mapi/capiv1alpha3/exp/updateMachinePool.ts
Labels: kind/refactor

#2520 clusters: add support for node pool deletion from the MAPI cluster detail page
  src/components/MAPI/clusters/utils.ts
  src/components/MAPI/organizations/OrganizationDetailGeneral/utils.ts
  src/components/MAPI/types.ts
  src/components/MAPI/utils.ts
  src/components/MAPI/workernodes/WorkerNodesNodePoolItem.tsx
  src/components/MAPI/workernodes/WorkerNodesNodePoolItemDelete.tsx
  src/components/MAPI/workernodes/utils.ts
  src/components/UI/Display/MAPI/clusters/ClusterDetail/ClusterDetailCounter/__tests__/__snapshots__/index.tsx.snap
  src/components/UI/Display/MAPI/clusters/ClusterDetail/ClusterDetailWidget/__tests__/__snapshots__/index.tsx.snap
  src/components/UI/Display/MAPI/workernodes/WorkerNodesNodePoolActions.tsx
  src/model/services/mapi/capiv1alpha3/exp/deleteMachinePool.ts
  src/model/services/mapi/capiv1alpha3/exp/index.ts
Labels: kind/refactor
