Repository giantswarm/happa, pull requests merged in 2021-11, with the labels that each got.

#2881 Fix not being able to display any information about CAPZ clusters
  src/components/MAPI/clusters/ClusterDetail/ClusterDetailWidgetProvider.tsx
  src/components/MAPI/clusters/utils.ts
  src/components/MAPI/utils.ts
Labels: kind/bug

#2880 node pools: add support for configuring similar instance types on AWS via MAPI
  src/components/MAPI/utils.ts
  src/components/MAPI/workernodes/WorkerNodesCreateNodePool.tsx
  src/components/MAPI/workernodes/WorkerNodesCreateNodePoolMachineType.tsx
  src/components/MAPI/workernodes/WorkerNodesNodePoolItem.tsx
  src/components/MAPI/workernodes/WorkerNodesNodePoolItemMachineType.tsx
  src/components/MAPI/workernodes/patches.ts
Labels: kind/refactor

#2883 node pools: add support for changing descriptions on AWS via MAPI
  src/components/MAPI/workernodes/WorkerNodesNodePoolItem.tsx
  src/components/MAPI/workernodes/utils.ts
Labels: kind/refactor

#2889 Display command for deleting cluster resources for AWS
  src/components/MAPI/clusters/ClusterDetail/ClusterDetailActions.tsx
  src/components/MAPI/clusters/guides/DeleteClusterGuide.tsx
Labels: kind/refactor

#2890 Only display placeholders if the right resources were loaded
  src/components/MAPI/clusters/ClusterDetail/ClusterDetailActions.tsx
  src/components/MAPI/clusters/ClusterDetail/__tests__/index.tsx
  src/components/MAPI/clusters/ClusterDetail/index.tsx
  src/components/MAPI/clusters/ClusterList/ClusterListItem.tsx
  src/components/MAPI/clusters/ClusterList/__tests__/ClusterListItem.tsx
  src/components/MAPI/clusters/utils.ts
  src/components/MAPI/workernodes/WorkerNodesNodePoolItem.tsx
  src/components/MAPI/workernodes/WorkerNodesNodePoolItemMachineType.tsx
Labels: kind/refactor

#2892 node pools: adapt NP modifying guide to work for AWS
  src/components/MAPI/workernodes/ClusterDetailWorkerNodes.tsx
  src/components/MAPI/workernodes/guides/ModifyNodePoolGuide.tsx
Labels: kind/refactor

#2894 Fix memory leak when creating NPs in clusters with HA CP nodes
  src/components/MAPI/__tests__/utils.ts
  src/components/MAPI/utils.ts
Labels: kind/refactor

#2901 Remove reviewers from happa dependency PRs
  renovate.json
Labels: kind/dev-change

#2902 Fix flash messages duplication and content overflow
  src/components/UI/Util/FlashMessages/FlashMessagesController.ts
  src/components/UI/Util/FlashMessages/FlashMessagesNotification.tsx
  src/lib/Queue.ts
  src/lib/__tests__/flashMessage.tsx
Labels: kind/bug

#2906 Prevent trying to use user information if the user gets logged out
  src/components/Layout.js
  src/lib/OAuth2/OAuth2.ts
  src/stores/batchActions.ts
Labels: kind/bug

#2905 Improve app installation modal: keyboard accessibility and scrollable content
  src/components/Apps/AppDetail/InstallAppModal/ClusterPicker.tsx
  src/components/Apps/AppDetail/InstallAppModal/InstallAppForm.tsx
  src/components/UI/Layout/Modal/index.tsx
Labels: kind/ux-enhancement

#2907 Update commands in Get Started guide to use `kubectl gs`
  src/components/UI/Display/MAPI/clusters/GettingStarted/GettingStartedGetAccess.tsx
  src/components/UI/Display/MAPI/clusters/GettingStarted/GettingStartedInstallIngress.tsx
Labels: kind/bug

#2910 Make permissions auto-refreshable
  src/@types/users.d.ts
  src/components/ExceptionNotificationTest/ExceptionNotificationTest.tsx
  src/components/Layout.js
  src/components/Layout.tsx
  src/components/MAPI/__tests__/utils.ts
  src/components/MAPI/clusters/ClusterDetail/ClusterDetailWidgetProvider.tsx
  src/components/MAPI/clusters/CreateCluster/index.tsx
  src/components/MAPI/clusters/permissions/usePermissionsForCPNodes.ts
  src/components/MAPI/clusters/permissions/usePermissionsForClusters.ts
  src/components/MAPI/clusters/permissions/usePermissionsForOrgCredentials.ts
  src/components/MAPI/permissions/__tests__/utils.ts
  src/components/MAPI/permissions/types.ts
  src/components/MAPI/permissions/usePermissions.ts
  src/components/MAPI/permissions/utils.ts
  src/components/MAPI/utils.ts
  src/components/__tests__/Layout.tsx
  src/stores/batchActions.ts
  src/stores/main/actions.ts
  src/stores/main/constants.ts
  src/stores/main/reducer.ts
  src/stores/main/selectors.ts
  src/stores/main/types.ts
  src/stores/main/utils.ts
  src/stores/organization/reducer.ts
  testUtils/preloginState.js
  testUtils/renderUtils.js
Labels: kind/refactor

#2919 Display scheduled cluster upgrades
  src/components/MAPI/clusters/ClusterDetail/utils.ts
  src/components/MAPI/clusters/ClusterList/ClusterListItemStatus.tsx
  src/components/MAPI/clusters/ClusterList/__tests__/ClusterListItem.tsx
  src/components/MAPI/clusters/utils.ts
  src/components/MAPI/releases/ClusterDetailWidgetRelease.tsx
  src/components/MAPI/releases/__tests__/ClusterDetailWidgetRelease.tsx
  src/components/UI/Display/MAPI/clusters/ClusterDetail/ClusterDetailStatus.tsx
  src/lib/helpers.tsx
  src/model/services/mapi/capiv1alpha3/key.ts
Labels: kind/ux-enhancement

#2923 Align "No node pools" message
  src/components/MAPI/workernodes/ClusterDetailWidgetWorkerNodes.tsx
Labels: kind/ux-enhancement

#2915 Getting started: remove outdated text, apply sentence case
  src/components/GettingStarted/Steps/ConfigureKubectl.js
Labels: kind/bug

#2933 Fix node pool creation: spot instances should be disabled by default
  src/components/MAPI/utils.ts
  src/components/MAPI/workernodes/WorkerNodesCreateNodePoolSpotInstances.tsx
  src/components/MAPI/workernodes/utils.ts
Labels: kind/bug

#2934 Fix current selected version details for installed app stuck in loading state
  src/components/MAPI/apps/ClusterDetailAppListItem.tsx
  src/components/MAPI/apps/ClusterDetailAppListWidgetVersionInspector.tsx
Labels: kind/bug

#2924 Add staff support for impersonating users
  src/components/Auth/MAPI/MapiUnauthorized.tsx
  src/components/MAPI/Experiments.tsx
  src/components/MAPI/permissions/usePermissions.ts
  src/lib/OAuth2/OAuth2.ts
  src/lib/OAuth2/TestOAuth2.ts
  src/model/services/mapi/generic/ensureClientAuth.ts
Labels: kind/dev-change

#2929 Fix deleted cluster description stuck in loading state
  src/components/MAPI/apps/AppInstallModal.tsx
  src/components/MAPI/apps/utils.ts
  src/components/MAPI/clusters/ClusterDetail/ClusterDetailActions.tsx
  src/components/MAPI/clusters/ClusterDetail/index.tsx
  src/components/MAPI/clusters/ClusterList/ClusterListItem.tsx
  src/components/MAPI/clusters/Clusters.tsx
  src/components/MAPI/clusters/utils.ts
  src/components/MAPI/utils.ts
Labels: kind/bug

#2942 Take into account that the `.spec` property of a StorageConfig can be omited
  src/model/services/mapi/gscorev1alpha1/types.ts
  src/model/services/mapi/legacy/keypairs/getKeyPairList.ts
Labels: kind/bug

#2941 Guide users to create a first node pool after cluster creation
  src/components/MAPI/clusters/CreateCluster/index.tsx
  src/components/MAPI/workernodes/ClusterDetailWidgetWorkerNodes.tsx
  src/components/MAPI/workernodes/ClusterDetailWorkerNodes.tsx
  src/components/MAPI/workernodes/__tests__/ClusterDetailWidgetWorkerNodes.tsx
Labels: kind/ux-enhancement

#2948 Add a warning message to client certificates list
  src/components/MAPI/keypairs/ClusterDetailKeyPairs.tsx
Labels: kind/ux-enhancement

#2949 Take care of leftover TODOs and FIXMEs
  __tests__/ClusterManagement.js
  src/components/Apps/AppsList/utils.tsx
  src/components/Cluster/ClusterDetail/KeyPairDetailsModal.js
  src/components/Cluster/ClusterDetail/KeyPairs.js
  src/components/Cluster/ClusterDetail/RegionAndVersions.tsx
  src/components/Cluster/ClusterDetail/UserInstalledApps/InstalledApp.tsx
  src/components/Cluster/ClusterDetail/V5ClusterDetailTable.js
  src/components/Cluster/NewCluster/ReleaseSelector/ReleaseRow.tsx
  src/components/Home/ClusterDashboardItem.js
  src/components/MAPI/apps/ClusterDetailAppListItem.tsx
  src/components/MAPI/apps/ClusterDetailApps.tsx
  src/components/MAPI/apps/ClusterDetailIngress.tsx
  src/components/MAPI/clusters/ClusterDetail/ClusterDetailWidgetCreated.tsx
  src/components/MAPI/clusters/ClusterList/ClusterListItem.tsx
  src/components/MAPI/keypairs/ClusterDetailKeyPairDetailsModal.tsx
  src/components/MAPI/keypairs/ClusterDetailKeyPairs.tsx
  src/components/MAPI/releases/ClusterDetailReleaseDetailsModal.tsx
  src/components/MAPI/workernodes/WorkerNodesNodePoolItem.tsx
  src/components/Modals/ReleaseDetailsModal/ReleaseDetailsModal.js
  src/components/Organizations/Detail/View.js
  src/components/UI/Controls/VersionPicker/VersionPicker.tsx
  src/components/UI/Display/Apps/AppDetailNew/AppDetailPage.tsx
  src/components/UI/Display/Date/index.tsx
  src/components/UI/Display/Date/stories/Date.stories.tsx
  src/components/UI/Display/Date/stories/Relative.tsx
  src/components/UI/Display/Date/stories/Simple.tsx
  src/components/UI/Display/MAPI/clusters/ClusterDetail/ClusterDetailDeleteActionClusterDetails.tsx
  src/components/UI/Display/MAPI/clusters/ClusterList/ClusterListItemMainInfo.tsx
  src/components/UI/Inputs/FileInput/index.tsx
  src/components/UI/Layout/stories/Layout.stories.mdx
  src/components/Users/InvitesTable.js
  src/components/Users/UsersTable.js
  src/lib/__tests__/helpers.ts
  src/lib/helpers.ts
  src/model/services/mapi/capiv1alpha3/getClusterList.ts
  src/stores/batchActions.ts
  src/stores/callAPIMiddleware.js
  src/stores/cluster/actions.tsx
  src/stores/cluster/utils.ts
  src/stores/user/reducer.ts
  src/utils/__tests__/localStorageUtils.ts
  src/utils/localStorageUtils.ts
Labels: kind/refactor

#2958 Fix organization stats: releases in use and control plane nodes stats
  src/components/MAPI/organizations/OrganizationDetailGeneral/__tests__/index.tsx
  src/components/MAPI/organizations/OrganizationDetailGeneral/utils.ts
  src/components/UI/Display/Organizations/OrganizationDetailPage.tsx
Labels: kind/bug

#2961 Account for mixed-case organization names when creating clusters
  src/components/MAPI/clusters/CreateCluster/index.tsx
Labels: kind/bug

#2966 Make the password reset form work properly
  src/components/ForgotPassword/SetPassword.js
Labels: kind/bug

#2972 Make access control UI aware of permissions. Re-enable binding subjects.
  src/components/MAPI/organizations/AccessControl/AccessControlRoleSubjects.tsx
  src/components/MAPI/organizations/AccessControl/__tests__/AccessControlRoleSubjects.tsx
  src/components/MAPI/organizations/AccessControl/__tests__/index.tsx
  src/components/MAPI/organizations/AccessControl/index.tsx
  src/components/MAPI/organizations/AccessControl/utils.ts
  src/components/MAPI/organizations/permissions/usePermissionsForAccessControl.ts
  src/components/MAPI/permissions/utils.ts
  src/components/UI/Display/MAPI/AccessControl/AccessControlRoleDetail.tsx
  src/components/UI/Display/MAPI/AccessControl/AccessControlRoleList.tsx
  src/components/UI/Display/MAPI/AccessControl/AccessControlSubjectAddForm.tsx
  src/components/UI/Display/MAPI/AccessControl/AccessControlSubjectSet.tsx
  src/components/UI/Display/MAPI/AccessControl/__tests__/AccessControlRoleDetail.tsx
  src/components/UI/Display/MAPI/AccessControl/__tests__/AccessControlRoleList.tsx
  src/components/UI/Display/MAPI/AccessControl/types.ts
  src/model/services/mapi/rbacv1/getClusterRoleBindingList.ts
  src/model/services/mapi/rbacv1/getClusterRoleList.ts
  src/model/services/mapi/rbacv1/getRoleBindingList.ts
  src/model/services/mapi/rbacv1/getRoleList.ts
Labels: kind/feature

#2981 Improve cluster labels readability
  src/components/Cluster/ClusterDetail/ClusterLabels/ClusterLabels.tsx
  src/components/Cluster/ClusterDetail/ClusterLabels/DeleteLabelButton.tsx
  src/components/Cluster/ClusterDetail/ClusterLabels/EditLabelTooltip.tsx
  src/components/UI/Display/Cluster/ClusterLabels/DeleteLabelButton.tsx
  src/components/UI/Display/Cluster/ClusterLabels/ValidationError.tsx
  src/components/UI/Display/ValueLabel.tsx
Labels: kind/ux-enhancement

#2982 Only set impersonation group header if groups is defined
  src/model/services/mapi/generic/ensureClientAuth.ts
Labels: kind/dev-change
