Repository giantswarm/happa, pull requests merged in 2021-01, with the labels that each got.

#2014 Clarify that the EOL tag is associated with the Kubernetes release
  src/components/Cluster/ClusterDetail/ClusterApps.js
  src/components/Cluster/NewCluster/ReleaseSelector/ReleaseSelector.tsx
  src/components/Modals/ReleaseDetailsModal/ReleaseDetailsModal.js
  src/components/UI/KubernetesVersionLabel.tsx
  src/components/UI/__tests__/KubernetesVersionLabel.tsx
  src/stores/releases/__tests__/utils.ts
  src/stores/releases/utils.ts
Labels: kind/ux-enhancement

#2013 Align terminology by replacing term "BYOC credentials" to "provider credentials"
  src/components/Organizations/Detail/Detail.js
  src/components/Organizations/Detail/View.js
  src/components/Organizations/Detail/__tests__/View.tsx
  src/components/Organizations/List/List.js
  src/components/UI/OrganizationList/OrganizationList.js
  src/components/UI/OrganizationList/OrganizationListRow.js
  src/stores/organization/utils.ts
Labels: kind/ux-enhancement

#2015 Change variables to uppercase
  scripts/webpack/getServiceURL.js
Labels: kind/dev-change

#2016 Update axios to version 0.21.1
  package.json
  yarn.lock
Labels: dependencies, kind/security

#2018 Increase dependabot open PR limit
  .github/dependabot.yml
Labels: kind/dev-change

#2006 Add support for Azure node pool autoscaling
  __tests__/V5ClusterManagement.js
  src/components/Cluster/ClusterDetail/AddNodePool/AddNodePool.js
  src/components/Cluster/ClusterDetail/NodePool.tsx
  src/components/Cluster/ClusterDetail/NodePoolScaling.tsx
  src/components/Cluster/ClusterDetail/ScaleNodePoolModal.js
  src/components/Cluster/ClusterDetail/V5ClusterDetailTable.js
  src/components/Cluster/ClusterDetail/V5ClusterDetailTableNodePoolScaling.tsx
  src/components/Cluster/ClusterDetail/__tests__/ScaleClusterModal.js
  src/components/Cluster/NewCluster/CreateNodePoolsCluster.js
  src/components/shared/NodeCountSelector.js
  src/shared/constants/index.ts
  src/stores/cluster/utils.ts
  src/stores/nodepool/utils.ts
  testUtils/mockHttpCalls/clusters.js
Labels: kind/feature

#2027 Fix wrong NP nodes display on Azure
  src/components/Cluster/ClusterDetail/NodePoolScaling.tsx
Labels: kind/bug

#2031 Improve number picker UX to allow the user enter the value they want
  __tests__/V4AzureClusterManagement.js
  src/components/UI/NumberPicker.js
  src/components/shared/__tests__/NodeCountSelector.js
Labels: kind/ux-enhancement

#2037 Show correct node pool size on Azure autoscaling clusters
  src/components/Cluster/ClusterDetail/NodePoolScaling.tsx
Labels: kind/bug

#2042 Replace 'moment' with 'date-fns'
  __tests__/Users.js
  package.json
  src/components/Cluster/ClusterDetail/ExpiryHoursPicker.js
  src/components/Cluster/ClusterDetail/KeyPairDetailsModal.js
  src/components/Cluster/ClusterDetail/KeyPairs.js
  src/components/Cluster/ClusterDetail/V4ClusterDetailTable.js
  src/components/Cluster/ClusterDetail/V5ClusterDetailTable.js
  src/components/Home/ClusterDashboardItem.js
  src/components/Home/Home.js
  src/components/Users/UsersUtils.js
  src/lib/__tests__/helpers.ts
  src/lib/helpers.tsx
  src/stores/cluster/actions.ts
  src/stores/releases/__tests__/utils.ts
  webpack.common.js
  yarn.lock
Labels: kind/refactor

#2047 Allow passing date objects to date formatting utilities
  src/lib/helpers.tsx
Labels: kind/dev-change

#2048 Move cluster capability computation into single place
  src/@types/clusters.d.ts
  src/components/Cluster/ClusterDetail/AddNodePool/AddNodePool.js
  src/components/Cluster/ClusterDetail/NodePool.tsx
  src/components/Cluster/ClusterDetail/ScaleNodePoolModal.js
  src/components/Cluster/ClusterDetail/V5ClusterDetailTable.js
  src/components/Cluster/NewCluster/CreateNodePoolsCluster.js
  src/stores/cluster/actions.ts
  src/stores/cluster/utils.ts
  src/stores/nodepool/utils.ts
  src/stores/releases/__tests__/utils.ts
Labels: kind/dev-change

#2049 Refactor spot instances stuff to allow provider-specific customization
  src/components/Cluster/ClusterDetail/AddNodePool/AddNodePool.js
  src/components/Cluster/ClusterDetail/AddNodePool/AddNodePoolSpotInstances.tsx
  src/components/Cluster/ClusterDetail/NodePool.tsx
  src/components/Cluster/ClusterDetail/NodePoolScaling.tsx
  src/components/Cluster/ClusterDetail/NodePoolScalingSpotInstancesDetails.tsx
Labels: kind/refactor

#2064 Stop displaying the 'Get started' button in the cluster overview for old clusters
  __tests__/GettingStarted.js
  src/components/Cluster/ClusterDetail/KeyPairDetailsModal.js
  src/components/Cluster/ClusterDetail/KeyPairs.js
  src/components/Home/ClusterDashboardItem.js
  src/components/Users/UsersUtils.js
Labels: kind/bug

#2069 Remove code for RUM submission to Datadog
  Dockerfile
  scripts/rum.inc.html
  scripts/start.sh
  src/components/index.tsx
  src/index.html
Labels: kind/removal

#2068 Set main nav logo width and height
  src/components/UI/Controls/Navigation/Navigation.js
Labels: kind/change

#2074 Create currency input for handling money
  .storybook/main.js
  .storybook/preview-head.html
  .storybook/preview.js
  src/components/UI/Inputs/CurrencyInput/__tests__/CurrencyInput.tsx
  src/components/UI/Inputs/CurrencyInput/index.tsx
  src/components/UI/Inputs/CurrencyInput/stories/Constraints.tsx
  src/components/UI/Inputs/CurrencyInput/stories/Currencies.tsx
  src/components/UI/Inputs/CurrencyInput/stories/CurrencyInput.stories.tsx
  src/components/UI/Inputs/CurrencyInput/stories/FloatValues.tsx
  src/components/UI/Inputs/CurrencyInput/stories/Label.tsx
  src/components/UI/Inputs/CurrencyInput/stories/Simple.tsx
Labels: kind/dev-change

#2088 Fix release selector buttons being cut off
  src/components/UI/Controls/ExpandableSelector/Items.tsx
Labels: kind/bug

#2089 Expose storybook in production app
  .circleci/config.yml
  .gitignore
  .storybook/preview-head.html
  Dockerfile
  helm/happa/templates/ingress.yaml
  nginx.conf
  package.json
Labels: kind/dev-change

#2093 Modernizr straight to the trash
  .storybook/preview-head.html
  nginx.conf
  src/components/GettingStarted/Steps/ConfigureKubectlAlternative.js
  src/components/UI/Display/Documentation/FileBlock.js
  src/index.html
  src/vendor/modernizr.js
  testUtils/browserMocks.js
  webpack.prod.js
Labels: kind/deprecation

#2098 Allow setting node counter values in any order
  src/components/UI/Inputs/NumberPicker.js
  src/components/shared/NodeCountSelector.js
  src/components/shared/__tests__/NodeCountSelector.js
Labels: kind/bug
