Repository giantswarm/happa, pull requests merged in 2021-09, with the labels that each got.

#2699 Get rid of the need to use the info endpoint
  __tests__/V4AzureClusterManagement.js
  __tests__/V4KVMClusterManagement.js
  helm/happa/templates/configmap.yaml
  helm/happa/values.yaml
  jest.config.js
  scripts/getConfigurationValues.ts
  scripts/webpack/ConfigurationPlugin.ts
  src/@types/global.d.ts
  src/components/Cluster/ClusterDetail/AddNodePool/AddNodePool.js
  src/components/Cluster/ClusterDetail/AddNodePool/__tests__/AddNodePool.tsx
  src/components/Cluster/ClusterDetail/ClusterDetailView.js
  src/components/Cluster/ClusterDetail/KeyPairs.js
  src/components/Cluster/ClusterDetail/ScaleClusterModal.js
  src/components/Cluster/NewCluster/CreateNodePoolsCluster.js
  src/components/Cluster/NewCluster/CreateRegularCluster.js
  src/components/Cluster/NewCluster/NewClusterWrapper.tsx
  src/components/GettingStarted/Steps/InstallIngress.js
  src/components/Layout.js
  src/components/MAPI/apps/AppInstallModal.tsx
  src/components/MAPI/apps/ClusterDetailApps.tsx
  src/components/MAPI/clusters/ClusterDetail/ClusterDetailActions.tsx
  src/components/MAPI/clusters/ClusterDetail/ClusterDetailOverview.tsx
  src/components/MAPI/clusters/ClusterDetail/index.tsx
  src/components/MAPI/clusters/ClusterList/ClusterListItem.tsx
  src/components/MAPI/clusters/Clusters.tsx
  src/components/MAPI/clusters/CreateCluster/CreateClusterControlPlaneNodeAZs.tsx
  src/components/MAPI/clusters/CreateCluster/__tests__/index.tsx
  src/components/MAPI/clusters/CreateCluster/index.tsx
  src/components/MAPI/clusters/GettingStarted/index.tsx
  src/components/MAPI/clusters/guides/CreateClusterGuide.tsx
  src/components/MAPI/clusters/guides/InspectClusterGuide.tsx
  src/components/MAPI/clusters/guides/ListAppsGuide.tsx
  src/components/MAPI/clusters/guides/SetClusterLabelsGuide.tsx
  src/components/MAPI/guides/utils.ts
  src/components/MAPI/organizations/Organization.tsx
  src/components/MAPI/organizations/OrganizationDetailGeneral/index.tsx
  src/components/MAPI/organizations/OrganizationList.tsx
  src/components/MAPI/releases/ClusterDetailWidgetRelease.tsx
  src/components/MAPI/utils.ts
  src/components/MAPI/workernodes/ClusterDetailWorkerNodes.tsx
  src/components/MAPI/workernodes/WorkerNodesCreateNodePool.tsx
  src/components/MAPI/workernodes/WorkerNodesCreateNodePoolAvailabilityZones.tsx
  src/components/MAPI/workernodes/WorkerNodesCreateNodePoolSpotInstances.tsx
  src/components/MAPI/workernodes/__tests__/WorkerNodesCreateNodePool.tsx
  src/components/MAPI/workernodes/guides/CreateNodePoolGuide.tsx
  src/components/MAPI/workernodes/guides/DeleteNodePoolGuide.tsx
  src/components/MAPI/workernodes/guides/ListNodePoolsGuide.tsx
  src/components/MAPI/workernodes/guides/ModifyNodePoolGuide.tsx
  src/components/Organizations/Detail/Detail.js
  src/components/Organizations/List/List.js
  src/components/Users/Users.js
  src/index.ejs
  src/lib/hooks/useInstanceTypeSelectionConfiguration.ts
  src/stores/batchActions.ts
  src/stores/cluster/selectors.ts
  src/stores/main/reducer.ts
  src/stores/main/selectors.ts
  testUtils/preloginState.js
Labels: kind/dev-change

#2707 apps: add basic components for the new list of cluster apps
  helm/happa/templates/configmap.yaml
  jest.config.js
  scripts/getConfigurationValues.ts
  src/@types/global.d.ts
  src/components/MAPI/apps/ClusterDetailAppList.tsx
  src/components/MAPI/apps/ClusterDetailAppListItem.tsx
  src/components/MAPI/apps/ClusterDetailApps.tsx
  src/components/MAPI/apps/__tests__/ClusterDetailAppList.tsx
  src/index.ejs
  src/model/services/mapi/applicationv1alpha1/key.ts
  src/shared/featureFlags.ts
  src/styles/theme.ts
Labels: kind/refactor

#2651 Modify "List clusters ..." MAPI guide to list clusters for the current org namespace only
  src/components/MAPI/clusters/Clusters.tsx
  src/components/MAPI/clusters/guides/ListClustersGuide.tsx
Labels: kind/change

#2718 Fix organization usage when SSO is used but MAPI cluster management is disabled
  src/components/Apps/AppDetail/InstallAppModal/InstallAppModal.tsx
  src/components/Cluster/NewCluster/NewClusterWrapper.tsx
  src/components/Home/ClusterDashboardItem.js
  src/lib/helpers.tsx
  src/stores/cluster/actions.ts
  src/stores/cluster/selectors.ts
  src/stores/nodepool/actions.ts
Labels: kind/bug

#2719 apps: create widgets for displaying and modifying the app's configuration
  src/components/Cluster/ClusterDetail/AppDetailsModal/YAMLFileUpload.tsx
  src/components/MAPI/apps/AppValueConfigurator.tsx
  src/components/MAPI/apps/ClusterDetailAppListItem.tsx
  src/components/MAPI/apps/ClusterDetailAppListWidgetConfiguration.tsx
  src/components/MAPI/apps/__tests__/ClusterDetailAppListWidgetConfiguration.tsx
  src/components/MAPI/apps/utils.ts
Labels: kind/refactor

#2724 Push happa to docker.io
  .circleci/config.yml
Labels: kind/dev-change

#2723 Apps: create widget for uninstalling an app
  src/components/MAPI/apps/ClusterDetailAppList.tsx
  src/components/MAPI/apps/ClusterDetailAppListItem.tsx
  src/components/MAPI/apps/ClusterDetailAppListWidgetUninstall.tsx
  src/components/MAPI/apps/__tests__/ClusterDetailAppListWidgetUninstall.tsx
  src/components/MAPI/apps/utils.ts
  src/components/UI/Controls/ConfirmationPrompt/index.tsx
Labels: kind/refactor

#2727 apps: add widget for inspecting and changing cluster app versions in the new UI
  src/components/MAPI/apps/ClusterDetailAppListItem.tsx
  src/components/MAPI/apps/ClusterDetailAppListWidgetVersionInspector.tsx
  src/components/MAPI/apps/__tests__/ClusterDetailAppListWidgetVersionInspector.tsx
  src/components/MAPI/apps/utils.ts
  src/components/UI/Display/MAPI/apps/AppVersionInspectorOption.tsx
  src/components/UI/Display/MAPI/clusters/ClusterDetail/ClusterDetailCounter/__tests__/__snapshots__/index.tsx.snap
  src/components/UI/Display/MAPI/clusters/ClusterDetail/ClusterDetailWidget/__tests__/__snapshots__/index.tsx.snap
  src/components/UI/Display/OptionalValue/OptionalValue.tsx
  src/components/UI/Inputs/NumberPicker/__tests__/__snapshots__/index.tsx.snap
  src/components/UI/Inputs/RadioInput/__tests__/__snapshots__/index.tsx.snap
Labels: kind/refactor

#2728 apps: display deleted cluster apps in a different way
  src/components/MAPI/apps/ClusterDetailAppListItem.tsx
  src/components/MAPI/apps/__tests__/ClusterDetailAppList.tsx
  src/components/MAPI/apps/utils.ts
  src/components/UI/Display/MAPI/clusters/ClusterDetail/ClusterDetailCounter/__tests__/__snapshots__/index.tsx.snap
  src/components/UI/Display/MAPI/clusters/ClusterDetail/ClusterDetailWidget/__tests__/__snapshots__/index.tsx.snap
  src/components/UI/Inputs/NumberPicker/__tests__/__snapshots__/index.tsx.snap
  src/components/UI/Inputs/RadioInput/__tests__/__snapshots__/index.tsx.snap
Labels: kind/refactor

#2729 Compute namespace if the Organization CR does not have the required status field
  src/stores/main/actions.ts
Labels: kind/bug

#2733 apps: enable new cluster apps UI for all SSO users
  helm/happa/templates/configmap.yaml
  jest.config.js
  scripts/getConfigurationValues.ts
  src/@types/global.d.ts
  src/components/MAPI/apps/ClusterDetailAppListItem.tsx
  src/components/MAPI/apps/ClusterDetailApps.tsx
  src/components/MAPI/apps/__tests__/ClusterDetailApps.tsx
  src/components/UI/Display/MAPI/apps/ClusterDetailAppListWidget/__tests__/__snapshots__/index.tsx.snap
  src/components/UI/Display/MAPI/clusters/ClusterDetail/ClusterDetailCounter/__tests__/__snapshots__/index.tsx.snap
  src/components/UI/Display/MAPI/clusters/ClusterDetail/ClusterDetailWidget/__tests__/__snapshots__/index.tsx.snap
  src/components/UI/Inputs/NumberPicker/__tests__/__snapshots__/index.tsx.snap
  src/components/UI/Inputs/RadioInput/__tests__/__snapshots__/index.tsx.snap
  src/index.ejs
  src/shared/featureFlags.ts
Labels: kind/feature

#2732 Add tests for MAPI organization listing and creating
  src/components/MAPI/organizations/OrganizationListCreateOrg.tsx
  src/components/MAPI/organizations/__tests__/OrganizationList.tsx
Labels: kind/dev-change

#2735 Block possibility to edit the `cluster.x-k8s.io/watch-filter` label.
  src/utils/labelUtils.ts
Labels: kind/ux-enhancement

#2736 apps: use normalized app versions for comparisons
  src/components/MAPI/apps/ClusterDetailAppListWidgetVersionInspector.tsx
  src/components/MAPI/apps/utils.ts
Labels: kind/bug

#2734 Get k8s version info from giantswarm/config
  helm/happa/templates/configmap.yaml
  helm/happa/values.yaml
  jest.config.js
  scripts/getConfigurationValues.ts
  src/@types/global.d.ts
  src/index.ejs
  src/lib/config.ts
  src/stores/main/selectors.ts
  src/stores/releases/actions.ts
Labels: kind/dev-change

#2740 Remove leftover info endpoint stuff
  __tests__/AccountSettings.js
  __tests__/AdminLogin.tsx
  __tests__/AppDetailPane.tsx
  __tests__/Apps.js
  __tests__/ClusterManagement.js
  __tests__/ForgotPassword.js
  __tests__/GettingStarted.js
  __tests__/KeyPairs.js
  __tests__/Login.tsx
  __tests__/Logout.js
  __tests__/Organization.js
  __tests__/SignUp.js
  __tests__/Users.js
  __tests__/V4AWSClusterManagement.js
  __tests__/V4AzureClusterManagement.js
  __tests__/V4KVMClusterManagement.js
  __tests__/V5ClusterManagement.js
  src/@types/info.d.ts
  src/components/Cluster/ClusterDetail/__tests__/ScaleClusterModal.js
  src/components/Cluster/NewCluster/CreateRegularCluster.js
  src/model/clients/GiantSwarmClient.ts
  src/model/clients/__tests__/GiantSwarmClient.ts
  src/model/services/giantSwarm/__tests__/info.ts
  src/model/services/giantSwarm/info.ts
  src/model/services/giantSwarm/types.ts
  src/model/services/metadata/__tests__/configuration.ts
  src/stores/batchActions.ts
  src/stores/cluster/__tests__/utils.ts
  src/stores/cluster/actions.ts
  src/stores/main/actions.ts
  src/stores/main/constants.ts
  src/stores/main/reducer.ts
  src/stores/main/selectors.ts
  src/stores/main/types.ts
  testUtils/mockHttpCalls/index.js
  testUtils/mockHttpCalls/info.js
  testUtils/modelMocks.js
  testUtils/preloginState.js
Labels: kind/dev-change

#2741 Display Kubernetes version EOL information on MAPI features
  src/components/Cluster/NewCluster/ReleaseSelector/ReleaseSelector.tsx
  src/components/MAPI/apps/ClusterDetailApps.tsx
  src/components/MAPI/clusters/CreateCluster/CreateClusterRelease.tsx
  src/components/MAPI/releases/ClusterDetailWidgetRelease.tsx
  src/components/UI/Display/MAPI/clusters/ClusterList/ClusterListItemMainInfo.tsx
  src/components/UI/Display/Organizations/OrganizationDetailPage.tsx
Labels: kind/ux-enhancement

#2743 Prevent trying to select an app version when version loading fails
  src/components/MAPI/apps/ClusterDetailAppListWidgetVersionInspector.tsx
Labels: kind/bug

#2742 apps: display cluster app status next to app version in collapsed mode
  src/components/MAPI/apps/ClusterDetailAppListItem.tsx
  src/components/MAPI/apps/ClusterDetailAppListItemStatus.tsx
  src/components/MAPI/apps/__tests__/ClusterDetailAppList.tsx
  src/components/MAPI/apps/__tests__/ClusterDetailAppListItemStatus.tsx
Labels: kind/ux-enhancement

#2751 Use consistent labelling in the role listing CLI guide
  src/components/MAPI/organizations/AccessControl/guides/ListRolesGuide.tsx
Labels: kind/bug

#2750 Fix: truncate long names in User dropdown UI
  __tests__/Login.tsx
  __tests__/Logout.js
  __tests__/Users.js
  src/components/UI/Controls/Navigation/UserDropdown.tsx
Labels: kind/bug

#2752 apps: display error details when YAML validation fails
  src/components/Apps/AppDetail/InstallAppModal/InstallAppModal.tsx
  src/components/Cluster/ClusterDetail/AppDetailsModal/YAMLFileUpload.tsx
  src/components/MAPI/apps/AppInstallModal.tsx
  src/components/MAPI/apps/utils.ts
Labels: kind/ux-enhancement

#2754 Use CircleCI convenience image
  .circleci/config.yml
Labels: kind/dev-change

#2755 Improve Apps browsing performance: virtualize the Apps list
  src/components/UI/Display/Apps/AppList/AppGrid.tsx
  src/components/UI/Display/Apps/AppList/AppsListPage.tsx
  src/components/UI/Display/MAPI/CLIGuide/__tests__/__snapshots__/index.tsx.snap
  src/components/UI/Display/MAPI/apps/ClusterDetailAppListWidget/__tests__/__snapshots__/index.tsx.snap
  src/components/UI/Display/MAPI/clusters/ClusterDetail/ClusterDetailCounter/__tests__/__snapshots__/index.tsx.snap
  src/components/UI/Display/MAPI/clusters/ClusterDetail/ClusterDetailWidget/__tests__/__snapshots__/index.tsx.snap
  src/components/UI/Inputs/NumberPicker/__tests__/__snapshots__/index.tsx.snap
  src/components/UI/Inputs/RadioInput/__tests__/__snapshots__/index.tsx.snap
Labels: kind/ux-enhancement

#2756 Use the new 'template organization' command in kubectl-gs in the CLI guide for creating an organization
  src/components/MAPI/guides/utils.ts
  src/components/MAPI/organizations/guides/CreateOrganizationGuide.tsx
Labels: kind/change

#2759 Refactor all modals to use the <GenericModal /> component
  src/components/Cluster/ClusterDetail/KeypairCreateModal/KeyPairCreateModal.tsx
  src/components/Cluster/ClusterDetail/ScaleClusterModal.js
  src/components/Cluster/ClusterDetail/ScaleNodePoolModal.tsx
  src/components/Cluster/ClusterDetail/UpgradeClusterModal.js
  src/components/MAPI/releases/ClusterDetailUpgradeModal.tsx
  src/components/Modals/GenericModal.js
  src/components/Modals/GenericModal.tsx
  src/components/Modals/Modals.js
  src/components/Modals/ReleaseDetailsModal/ReleaseDetailsModal.js
  src/components/Users/UsersModal.js
Labels: kind/refactor

#2762 Improve Apps browsing performance: preload App icons
  src/components/UI/Display/Apps/AppList/AppGrid.tsx
  src/components/shared/ImgWithFallback.tsx
Labels: kind/ux-enhancement

#2771 Remove "What's changed" headline from release notes template
  .github/release-template.yml
Labels: kind/dev-change

#2773 Align flash messages for updating installed apps
  src/components/MAPI/apps/ClusterDetailAppListWidgetVersionInspector.tsx
  src/components/MAPI/apps/__tests__/ClusterDetailAppListWidgetVersionInspector.tsx
Labels: kind/ux-enhancement

#2782 Only display the `Users` page to admins, and only if customer SSO is disabled
  src/components/Layout.js
Labels: kind/bug

#2786 Fix semver comparison
  src/lib/__tests__/semver.ts
  src/lib/semver.ts
Labels: kind/bug

#2783 Use `athena` for submitting RUM events
  helm/happa/templates/configmap.yaml
  helm/happa/values.yaml
  jest.config.js
  package.json
  scripts/getConfigurationValues.ts
  src/@types/global.d.ts
  src/@types/graphql.d.ts
  src/@types/realUserMonitoring.d.ts
  src/components/index.tsx
  src/index.ejs
  src/lib/RUMService.ts
  src/model/clients/GraphQLClient.ts
  src/model/clients/GraphQLError.ts
  src/model/services/athena/analytics.ts
  src/model/services/athena/index.ts
  src/model/services/athena/mutations/CreateAnalyticsEvent.graphql
  src/model/services/athena/types.ts
  webpack.common.ts
  webpack.dev.ts
Labels: kind/refactor

#2787 Add alpha support for node pools on CAPZ clusters
  src/components/MAPI/clusters/utils.ts
  src/components/MAPI/types.ts
  src/components/MAPI/utils.ts
  src/components/MAPI/workernodes/ClusterDetailWorkerNodes.tsx
  src/components/MAPI/workernodes/WorkerNodesAzureMachinePoolSpotInstances.tsx
  src/components/MAPI/workernodes/WorkerNodesCreateNodePool.tsx
  src/components/MAPI/workernodes/WorkerNodesCreateNodePoolScale.tsx
  src/components/MAPI/workernodes/WorkerNodesNodePoolItem.tsx
  src/components/MAPI/workernodes/WorkerNodesNodePoolItemScale.tsx
  src/components/MAPI/workernodes/utils.ts
  src/components/UI/Controls/DropdownMenu.tsx
  src/components/UI/Display/MAPI/workernodes/WorkerNodesNodePoolActions.tsx
  src/components/UI/Display/MAPI/workernodes/WorkerNodesNodePoolListPlaceholder.tsx
  src/components/UI/Inputs/ViewEditName.tsx
  src/model/services/mapi/capiv1alpha4/createMachinePool.ts
  src/model/services/mapi/capiv1alpha4/deleteMachinePool.ts
  src/model/services/mapi/capiv1alpha4/getMachinePool.ts
  src/model/services/mapi/capiv1alpha4/getMachinePoolList.ts
  src/model/services/mapi/capiv1alpha4/index.ts
  src/model/services/mapi/capiv1alpha4/key.ts
  src/model/services/mapi/capiv1alpha4/types.ts
  src/model/services/mapi/capiv1alpha4/updateMachinePool.ts
  src/model/services/mapi/capzv1alpha4/createAzureMachinePool.ts
  src/model/services/mapi/capzv1alpha4/getAzureMachinePool.ts
  src/model/services/mapi/capzv1alpha4/index.ts
  src/model/services/mapi/capzv1alpha4/key.ts
  src/model/services/mapi/capzv1alpha4/types.ts
  src/shared/constants/index.ts
Labels: kind/feature

#2790 Show the number of apps to be upgraded in cluster overview
  src/components/MAPI/apps/ClusterDetailWidgetApps.tsx
  src/components/MAPI/apps/__tests__/ClusterDetailWidgetApps.tsx
  src/components/MAPI/apps/utils.ts
  src/components/MAPI/clusters/ClusterDetail/ClusterDetailOverview.tsx
Labels: kind/ux-enhancement
