Repository giantswarm/happa, pull requests merged in 2021-03, with the labels that each got.

#2243 Add Storybook stories for buttons
  package.json
  src/components/UI/Controls/Button/index.js
  src/components/UI/Controls/Button/stories/Button.stories.mdx
  yarn.lock
Labels: kind/dev-change

#2248 Fix dimensions of Button style "danger"
  src/components/UI/Controls/Button/index.js
Labels: kind/bug

#2254 Fix a problem that would prevent the app from being deployed
  helm/happa/templates/configmap.yaml
Labels: kind/bug

#2209 Create table components for simple tables
  src/components/Cluster/ClusterDetail/InstanceTypeSelector/InstanceTypeRow.tsx
  src/components/Cluster/ClusterDetail/InstanceTypeSelector/InstanceTypeSelector.tsx
  src/components/Cluster/NewCluster/ReleaseSelector/ReleaseRow.tsx
  src/components/Cluster/NewCluster/ReleaseSelector/ReleaseSelector.tsx
  src/components/UI/Controls/ExpandableSelector/Items.tsx
  src/components/UI/Controls/ExpandableSelector/Selector.tsx
  src/components/UI/Display/OrganizationList/OrganizationList.js
  src/components/UI/Display/OrganizationList/OrganizationListRow.js
  src/components/UI/Display/Table/Table.tsx
  src/components/UI/Display/Table/TableBody.tsx
  src/components/UI/Display/Table/TableCell.tsx
  src/components/UI/Display/Table/TableFooter.tsx
  src/components/UI/Display/Table/TableHeader.tsx
  src/components/UI/Display/Table/TableRow.tsx
  src/components/UI/Display/Table/__tests__/__snapshots__/index.tsx.snap
  src/components/UI/Display/Table/__tests__/index.tsx
  src/components/UI/Display/Table/index.tsx
  src/components/UI/Display/Table/stories/Simple.tsx
  src/components/UI/Display/Table/stories/Table.stories.tsx
  src/components/Users/InvitesTable.js
  src/components/Users/UsersTable.js
  src/styles/app.sass
  src/styles/components/_table.sass
  src/styles/theme.ts
Labels: kind/dev-change

#2255 Add storybook item for Tabs
  src/components/shared/Tabs/index.tsx
  src/components/shared/Tabs/stories/Tabs.stories.mdx
Labels: kind/dev-change

#2263 Log user out if silent token renewal fails
  src/lib/OAuth2/OAuth2.ts
Labels: kind/bug

#2261 Stop pre-commit hook if compilation fails
  .husky/pre-commit
Labels: kind/dev-change

#2276 Add k8s API error handling utility types and functions
  src/components/MAPI/clusters/ClusterList.tsx
  src/components/MAPI/clusters/ClusterListItem.tsx
  src/components/MAPI/clusters/ClusterListItemDetails.tsx
  src/model/services/mapi/capiv1alpha3/getClusterInfraRef.ts
  src/model/services/mapi/capiv1alpha3/getClusterList.ts
  src/model/services/mapi/capiv1alpha3/index.ts
  src/model/services/mapi/capiv1alpha3/key.ts
  src/model/services/mapi/capiv1alpha3/types.ts
  src/model/services/mapi/capzv1alpha3/getAzureClusterByName.ts
  src/model/services/mapi/capzv1alpha3/index.ts
  src/model/services/mapi/capzv1alpha3/types.ts
  src/model/services/mapi/clusters/types.ts
  src/model/services/mapi/corev1/index.ts
  src/model/services/mapi/corev1/types.ts
  src/model/services/mapi/meta/types.ts
  src/model/services/mapi/metav1/index.ts
  src/model/services/mapi/metav1/key.ts
  src/model/services/mapi/metav1/types.ts
Labels: kind/dev-change

#2284 Disable airbrake remoteConfig to prevent requests to notifier-configs.airbrake.io
  src/components/index.tsx
Labels: kind/bug

#2286 Organization management using the MAPI
  src/components/Layout.js
  src/components/MAPI/organizations/OrganizationIndex.tsx
  src/components/MAPI/organizations/OrganizationList.tsx
  src/components/UI/Display/Organizations/OrganizationListPage.tsx
  src/components/UI/Display/Organizations/stories/OrganizationListPage.stories.tsx
  src/components/UI/Display/Organizations/stories/Simple.tsx
  src/lib/__tests__/organizationValidation.ts
  src/lib/docs.ts
  src/lib/organizationValidation.ts
  src/model/services/mapi/metav1/types.ts
  src/model/services/mapi/organizations/createOrganization.ts
  src/model/services/mapi/organizations/getOrganizationList.ts
  src/model/services/mapi/organizations/key.ts
  src/model/services/mapi/organizations/types.ts
  src/styles/theme.ts
Labels: kind/feature

#2292 Update some dependencies
  package.json
  src/@types/grommet.d.ts
  src/components/UI/Inputs/CheckBoxInput/index.tsx
  src/components/UI/Inputs/CurrencyInput/__tests__/__snapshots__/CurrencyInput.tsx.snap
  src/components/UI/Inputs/DateInput/__tests__/__snapshots__/index.tsx.snap
  src/components/UI/Inputs/FileInput/__tests__/__snapshots__/index.tsx.snap
  src/components/UI/Inputs/InputGroup/index.tsx
  src/components/UI/Inputs/MultiSelect/__tests__/__snapshots__/index.tsx.snap
  src/components/UI/Inputs/NumberPicker/__tests__/__snapshots__/index.tsx.snap
  src/components/UI/Inputs/RadioInput/index.tsx
  src/components/UI/Inputs/Select/__tests__/__snapshots__/index.tsx.snap
  src/components/UI/Inputs/Select/index.tsx
  src/components/UI/Inputs/TextArea/__tests__/__snapshots__/index.tsx.snap
  src/components/UI/Inputs/TextInput/__tests__/__snapshots__/index.tsx.snap
  src/components/UI/Inputs/TextInput/index.tsx
  yarn.lock
Labels: kind/dev-change

#2293 Add types and functions required for access control
  src/model/services/mapi/capiv1alpha3/getClusterInfraRef.ts
  src/model/services/mapi/corev1/createServiceAccount.ts
  src/model/services/mapi/corev1/deleteServiceAccount.ts
  src/model/services/mapi/corev1/getServiceAccount.ts
  src/model/services/mapi/corev1/index.ts
  src/model/services/mapi/corev1/types.ts
  src/model/services/mapi/metav1/types.ts
  src/model/services/mapi/rbacv1/createClusterRoleBinding.ts
  src/model/services/mapi/rbacv1/createRoleBinding.ts
  src/model/services/mapi/rbacv1/deleteClusterRoleBinding.ts
  src/model/services/mapi/rbacv1/deleteRoleBinding.ts
  src/model/services/mapi/rbacv1/getClusterRoleBinding.ts
  src/model/services/mapi/rbacv1/getClusterRoleBindingList.ts
  src/model/services/mapi/rbacv1/getClusterRoleList.ts
  src/model/services/mapi/rbacv1/getRoleBinding.ts
  src/model/services/mapi/rbacv1/getRoleBindingList.ts
  src/model/services/mapi/rbacv1/getRoleList.ts
  src/model/services/mapi/rbacv1/index.ts
  src/model/services/mapi/rbacv1/key.ts
  src/model/services/mapi/rbacv1/types.ts
  src/model/services/mapi/rbacv1/updateClusterRoleBinding.ts
  src/model/services/mapi/rbacv1/updateRoleBinding.ts
Labels: kind/dev-change

#2294 Change "There is a problem" headline to "Insufficient permissions"
  src/components/Auth/MAPI/MapiUnauthorized.tsx
Labels: kind/ux-enhancement

#2297 Orgs listing using MAPI, also for non admins
  __tests__/AdminLogin.tsx
  __tests__/ClusterManagement.js
  __tests__/Login.tsx
  src/components/MAPI/organizations/OrganizationList.tsx
  src/model/services/mapi/authorizationv1/index.ts
  src/model/services/mapi/authorizationv1/selfSubjectAccessReview.ts
  src/model/services/mapi/authorizationv1/selfSubjectRulesReview.ts
  src/model/services/mapi/authorizationv1/types.ts
  src/model/services/mapi/organizations/index.ts
  src/stores/batchActions.ts
  src/stores/organization/actions.ts
  src/stores/organization/constants.ts
  src/stores/organization/selectors.ts
  src/stores/organization/types.ts
  testUtils/mockHttpCalls/index.js
  testUtils/mockHttpCalls/mapiOrganizations.js
  testUtils/mockHttpCalls/selfSubjectAccessReviews.ts
  testUtils/mockHttpCalls/selfSubjectRulesReviews.ts
  testUtils/modelMocks.js
Labels: kind/feature

#2299 Add a logout link to the insufficient permissions screen
  src/components/Auth/MAPI/MapiUnauthorized.tsx
Labels: kind/ux-enhancement

#2298 access control: add components needed for displaying the role list sidebar
  src/components/MAPI/organizations/AccessControl/utils.ts
  src/components/UI/Display/MAPI/AccessControl/AccessControlRoleList.tsx
  src/components/UI/Display/MAPI/AccessControl/AccessControlRoleListItem.tsx
  src/components/UI/Display/MAPI/AccessControl/AccessControlRoleListItemLoadingPlaceholder.tsx
  src/components/UI/Display/MAPI/AccessControl/AccessControlRolePlaceholder.tsx
  src/components/UI/Display/MAPI/AccessControl/AccessControlRoleSearchPlaceholder.tsx
  src/components/UI/Display/MAPI/AccessControl/__tests__/AccessControlRoleList.tsx
  src/components/UI/Display/MAPI/AccessControl/types.ts
Labels: kind/dev-change

#2304 access control: add other components required for rendering the role detail view
  src/components/UI/Display/MAPI/AccessControl/AccessControlRoleDetail.tsx
  src/components/UI/Display/MAPI/AccessControl/AccessControlRoleDetailLoadingPlaceholder.tsx
  src/components/UI/Display/MAPI/AccessControl/AccessControlRolePermissions.tsx
  src/components/UI/Display/MAPI/AccessControl/AccessControlRoleType.tsx
  src/components/UI/Display/MAPI/AccessControl/AccessControlRoleVerbs.tsx
  src/components/UI/Display/MAPI/AccessControl/__tests__/AccessControlRoleDetail.tsx
  src/components/UI/Display/MAPI/AccessControl/__tests__/AccessControlRolePermissions.tsx
Labels: kind/dev-change

#2303 Update the validation regex for organization names
  src/components/Modals/Modals.js
Labels: kind/ux-enhancement

#2305 access control: add other components required to render the whole thing
  src/components/MAPI/organizations/AccessControl/index.tsx
  src/components/MAPI/organizations/AccessControl/utils.ts
  src/components/UI/Display/MAPI/AccessControl/AccessControlDescription.tsx
  src/components/UI/Display/MAPI/AccessControl/AccessControlRoleType.tsx
Labels: kind/dev-change

#2307 Use what's in the ui annotation for org name if it's there.
  __tests__/Login.tsx
  src/model/services/mapi/k8sUrl.ts
  src/model/services/mapi/organizations/__tests__/key.ts
  src/model/services/mapi/organizations/getOrganization.ts
  src/model/services/mapi/organizations/index.ts
  src/model/services/mapi/organizations/key.ts
  src/stores/organization/actions.ts
  testUtils/mockHttpCalls/mapiOrganizations.js
  testUtils/modelMocks.js
Labels: kind/feature

#2288 Add organization detail page, together with the new access control UI
  __tests__/AdminLogin.tsx
  __tests__/Login.tsx
  src/components/Auth/MAPI/MapiUnauthorized.tsx
  src/components/MAPI/organizations/AccessControl/__tests__/index.tsx
  src/components/MAPI/organizations/Organization.tsx
  src/components/MAPI/organizations/OrganizationDetail.tsx
  src/components/MAPI/organizations/OrganizationIndex.tsx
  src/components/MAPI/organizations/OrganizationList.tsx
  src/components/UI/Display/MAPI/AccessControl/AccessControlRoleDetail.tsx
  src/components/UI/Display/MAPI/AccessControl/AccessControlRoleList.tsx
  src/components/UI/Display/MAPI/AccessControl/AccessControlRoleListItem.tsx
  src/components/UI/Display/Organizations/OrganizationDetailLoadingPlaceholder.tsx
  src/components/UI/Display/Organizations/OrganizationDetailPage.tsx
  src/model/services/mapi/metav1/types.ts
  src/model/services/mapi/securityv1alpha1/__tests__/key.ts
  src/model/services/mapi/securityv1alpha1/createOrganization.ts
  src/model/services/mapi/securityv1alpha1/deleteOrganization.ts
  src/model/services/mapi/securityv1alpha1/getOrganization.ts
  src/model/services/mapi/securityv1alpha1/getOrganizationList.ts
  src/model/services/mapi/securityv1alpha1/index.ts
  src/model/services/mapi/securityv1alpha1/key.ts
  src/model/services/mapi/securityv1alpha1/types.ts
  src/shared/constants/routes.ts
  src/stores/organization/actions.ts
  testUtils/mockHttpCalls/index.js
  testUtils/mockHttpCalls/rbacv1/clusterRoles.ts
  testUtils/mockHttpCalls/rbacv1/index.ts
  testUtils/mockHttpCalls/rbacv1/roleBindings.ts
  testUtils/mockHttpCalls/rbacv1/roles.ts
  testUtils/modelMocks.js
Labels: kind/feature

#2309 Upgrade storybook to v6.2.1
  package.json
  yarn.lock
Labels: dependencies
