Repository giantswarm/happa, pull requests merged in 2021-08, with the labels that each got.

#2583 Move MAPI error message formatter to a common location
  src/components/MAPI/apps/AppDetailsModal/index.tsx
  src/components/MAPI/apps/AppList/AppDetail.tsx
  src/components/MAPI/apps/AppList/index.tsx
  src/components/MAPI/apps/AppList/utils.tsx
  src/components/MAPI/apps/ClusterDetailApps.tsx
  src/components/MAPI/apps/ClusterDetailIngress.tsx
  src/components/MAPI/apps/InstallIngressButton.tsx
  src/components/MAPI/clusters/ClusterDetail/ClusterDetailOverviewDelete.tsx
  src/components/MAPI/clusters/ClusterDetail/ClusterDetailWidgetLabels.tsx
  src/components/MAPI/clusters/ClusterDetail/index.tsx
  src/components/MAPI/clusters/ClusterList/ClusterListItem.tsx
  src/components/MAPI/clusters/CreateCluster/CreateClusterRelease.tsx
  src/components/MAPI/clusters/CreateCluster/index.tsx
  src/components/MAPI/clusters/GettingStarted/index.tsx
  src/components/MAPI/keypairs/ClusterDetailKeyPairs.tsx
  src/components/MAPI/organizations/AccessControl/index.tsx
  src/components/MAPI/organizations/AccessControl/utils.ts
  src/components/MAPI/organizations/OrganizationDetailGeneral/index.tsx
  src/components/MAPI/organizations/OrganizationList.tsx
  src/components/MAPI/organizations/OrganizationListCreateOrg.tsx
  src/components/MAPI/organizations/utils.ts
  src/components/MAPI/releases/ClusterDetailWidgetRelease.tsx
  src/components/MAPI/utils.ts
  src/components/MAPI/workernodes/ClusterDetailWorkerNodes.tsx
  src/components/MAPI/workernodes/WorkerNodesCreateNodePool.tsx
  src/components/MAPI/workernodes/WorkerNodesNodePoolItem.tsx
  src/components/MAPI/workernodes/WorkerNodesNodePoolItemScale.tsx
Labels: kind/dev-change

#2584 Add CLI Guide UI components
  src/components/UI/Display/MAPI/CLIGuide/CLIGuideAdditionalInfo.tsx
  src/components/UI/Display/MAPI/CLIGuide/__tests__/__snapshots__/index.tsx.snap
  src/components/UI/Display/MAPI/CLIGuide/__tests__/index.tsx
  src/components/UI/Display/MAPI/CLIGuide/index.tsx
  src/components/UI/Display/MAPI/CLIGuide/stories/AdditionalInfo.tsx
  src/components/UI/Display/MAPI/CLIGuide/stories/CLIGuide.stories.tsx
  src/components/UI/Display/MAPI/CLIGuide/stories/Simple.tsx
  src/styles/theme.ts
Labels: kind/dev-change

#2585 Add guides for using the CLI for fetching the data displayed in the UI
  src/components/MAPI/guides/LoginGuideStep.tsx
  src/components/MAPI/organizations/AccessControl/guides/BindRolesToSubjectsGuide.tsx
  src/components/MAPI/organizations/AccessControl/guides/InspectRoleGuide.tsx
  src/components/MAPI/organizations/AccessControl/guides/ListRolesGuide.tsx
  src/components/MAPI/organizations/AccessControl/index.tsx
  src/components/MAPI/organizations/OrganizationDetailGeneral/index.tsx
  src/components/MAPI/organizations/OrganizationList.tsx
  src/components/MAPI/organizations/guides/CreateOrganizationGuide.tsx
  src/components/MAPI/organizations/guides/GetOrganizationDetailsGuide.tsx
  src/components/MAPI/organizations/guides/ListOrganizationsGuide.tsx
  src/components/MAPI/utils.ts
  src/components/UI/Display/Documentation/CodeBlock.js
  src/components/UI/Display/Documentation/Styles.js
  src/components/UI/Display/Documentation/__tests__/CodeBlock.js
  src/components/UI/Display/MAPI/CLIGuide/CLIGuideAdditionalInfo.tsx
  src/components/UI/Display/MAPI/CLIGuide/CLIGuideStep.tsx
  src/components/UI/Display/MAPI/CLIGuide/CLIGuideStepList.tsx
  src/components/UI/Display/MAPI/CLIGuide/__tests__/__snapshots__/index.tsx.snap
  src/components/UI/Display/MAPI/CLIGuide/index.tsx
  src/components/UI/Display/MAPI/CLIGuide/stories/AdditionalInfo.tsx
  src/components/UI/Display/MAPI/CLIGuide/stories/Simple.tsx
  src/lib/docs.ts
  src/styles/theme.ts
Labels: kind/feature

#2588 Change Node Pools table header font size in MAPI UI to align with Key Pairs table
  src/components/MAPI/workernodes/ClusterDetailWorkerNodes.tsx
Labels: kind/ux-enhancement

#2590 Align Access Control subject item's loading spinner width and margin with delete icon's
  src/components/UI/Display/MAPI/AccessControl/AccessControlSubjectSetItem.tsx
Labels: kind/ux-enhancement

#2589 Add guide on deleting the current org
  src/components/MAPI/organizations/OrganizationDetailGeneral/index.tsx
  src/components/MAPI/organizations/guides/DeleteOrganizationGuide.tsx
Labels: kind/dev-change

#2600 Make MAPI `Cluster detail` page tabs behave like pages
  src/components/MAPI/apps/ClusterDetailApps.tsx
  src/components/MAPI/apps/ClusterDetailIngress.tsx
  src/components/MAPI/clusters/ClusterDetail/index.tsx
  src/components/MAPI/keypairs/ClusterDetailKeyPairs.tsx
  src/components/MAPI/workernodes/ClusterDetailWorkerNodes.tsx
Labels: kind/ux-enhancement

#2607 Improve cluster deletion by requiring multiple confirmation steps
  __tests__/V4AWSClusterManagement.js
  __tests__/V5ClusterManagement.js
  src/components/Cluster/ClusterDetail/ClusterActions.tsx
  src/components/Cluster/ClusterDetail/ClusterApps.tsx
  src/components/Cluster/ClusterDetail/ClusterDetailView.js
  src/components/Modals/Modals.js
  src/components/UI/Display/MAPI/CLIGuide/__tests__/__snapshots__/index.tsx.snap
  src/components/UI/Display/MAPI/clusters/ClusterDetail/ClusterDetailCounter/__tests__/__snapshots__/index.tsx.snap
  src/components/UI/Display/MAPI/clusters/ClusterDetail/ClusterDetailDeleteAction.tsx
  src/components/UI/Display/MAPI/clusters/ClusterDetail/ClusterDetailDeleteActionClusterDetails.tsx
  src/components/UI/Display/MAPI/clusters/ClusterDetail/ClusterDetailDeleteActionClusterName.tsx
  src/components/UI/Display/MAPI/clusters/ClusterDetail/ClusterDetailWidget/__tests__/__snapshots__/index.tsx.snap
  src/components/UI/Display/MAPI/clusters/ClusterDetail/__tests__/ClusterDetailDeleteAction.tsx
  src/shared/constants/routes.ts
  src/stores/batchActions.ts
  src/stores/cluster/actions.ts
  src/stores/cluster/constants.ts
  src/stores/cluster/reducer.ts
  src/stores/cluster/types.ts
  src/stores/cluster/utils.ts
  src/stores/entityloading/selectors.ts
  src/stores/modal/reducer.ts
Labels: kind/change

#2608 Improve MAPI cluster deletion by requiring multiple confirmation steps
  src/components/MAPI/clusters/ClusterDetail/ClusterDetailActions.tsx
  src/components/MAPI/clusters/ClusterDetail/ClusterDetailOverview.tsx
  src/components/MAPI/clusters/ClusterDetail/ClusterDetailOverviewDelete.tsx
  src/components/MAPI/clusters/ClusterDetail/__tests__/ClusterDetailOverviewDelete.tsx
  src/components/MAPI/clusters/ClusterDetail/index.tsx
  src/components/MAPI/clusters/ClusterDetail/utils.ts
  src/components/MAPI/clusters/Clusters.tsx
  src/components/UI/Display/MAPI/clusters/ClusterDetail/ClusterDetailDeleteAction.tsx
  src/components/UI/Display/MAPI/clusters/ClusterDetail/ClusterDetailDeleteActionClusterName.tsx
  src/components/UI/Display/MAPI/clusters/ClusterDetail/__tests__/ClusterDetailDeleteAction.tsx
Labels: kind/dev-change

#2609 Fix cluster details page - Subscription ID sometimes not appearing
  src/components/MAPI/clusters/ClusterDetail/ClusterDetailWidgetProvider.tsx
Labels: kind/bug

#2614 Don't display tooltips with the full date on relative dates when they are not needed
  src/components/MAPI/clusters/ClusterDetail/ClusterDetailWidgetCreated.tsx
  src/components/MAPI/keypairs/ClusterDetailKeyPairDetailsModal.tsx
  src/components/UI/Display/MAPI/clusters/ClusterDetail/ClusterDetailDeleteActionClusterDetails.tsx
Labels: kind/ux-enhancement

#2613 Mapi skeleton loading animations
  src/components/MAPI/clusters/ClusterDetail/ClusterDetailWidgetControlPlaneNodes.tsx
  src/components/MAPI/clusters/ClusterDetail/ClusterDetailWidgetCreated.tsx
  src/components/MAPI/clusters/ClusterDetail/ClusterDetailWidgetKubernetesAPI.tsx
  src/components/MAPI/clusters/ClusterDetail/ClusterDetailWidgetLabels.tsx
  src/components/MAPI/clusters/ClusterDetail/ClusterDetailWidgetProvider.tsx
  src/components/MAPI/clusters/ClusterDetail/index.tsx
  src/components/MAPI/clusters/ClusterList/ClusterListItem.tsx
  src/components/MAPI/keypairs/ClusterDetailKeyPairs.tsx
  src/components/MAPI/releases/ClusterDetailWidgetRelease.tsx
  src/components/MAPI/workernodes/WorkerNodesAzureMachinePoolSpotInstances.tsx
  src/components/MAPI/workernodes/WorkerNodesNodePoolItem.tsx
  src/components/UI/Display/Apps/AppDetailNew/AppDetailPage.tsx
  src/components/UI/Display/Apps/AppDetailNew/AppDetailPageOptionalValue.tsx
  src/components/UI/Display/Apps/AppDetailNew/AppDetailsLoadingPlaceholder.tsx
  src/components/UI/Display/LoadingPlaceholder/LoadingPlaceholder.tsx
  src/components/UI/Display/MAPI/CLIGuide/__tests__/__snapshots__/index.tsx.snap
  src/components/UI/Display/MAPI/clusters/ClusterDetail/ClusterDetailCounter/__tests__/__snapshots__/index.tsx.snap
  src/components/UI/Display/MAPI/clusters/ClusterDetail/ClusterDetailCounter/index.tsx
  src/components/UI/Display/MAPI/clusters/ClusterDetail/ClusterDetailWidget/__tests__/__snapshots__/index.tsx.snap
  src/components/UI/Display/MAPI/clusters/ClusterList/ClusterListItemLoadingPlaceholder.tsx
  src/components/UI/Display/MAPI/clusters/ClusterList/ClusterListItemMainInfo.tsx
  src/components/UI/Display/MAPI/clusters/ClusterList/ClusterListItemNodeInfo.tsx
  src/components/UI/Display/MAPI/clusters/ClusterList/ClusterListItemOptionalValue.tsx
  src/components/UI/Display/OptionalValue/OptionalValue.tsx
  src/components/UI/Display/OptionalValue/stories/OptionalValue.stories.tsx
  src/components/UI/Display/Organizations/OrganizationDetailStatistic.tsx
  src/components/UI/Display/Organizations/OrganizationListPage.tsx
Labels: kind/ux-enhancement

#2616 Disable username and password login when SSO feature flag is enabled
  __tests__/ForgotPassword.js
  __tests__/Login.tsx
  src/components/Auth/Login.tsx
Labels: kind/dev-change

#2615 Fix version picker closing itself when ticking 'Use test versions'
  src/components/UI/Controls/VersionPicker/VersionPicker.tsx
Labels: kind/refactor

#2618 Access control: Improve deletion confirmation prompt for deleting service account subjects
  src/components/MAPI/organizations/AccessControl/AccessControlRoleSubjects.tsx
  src/components/MAPI/organizations/AccessControl/__tests__/AccessControlRoleSubjects.tsx
  src/components/MAPI/organizations/AccessControl/__tests__/index.tsx
  src/components/UI/Display/MAPI/AccessControl/AccessControlSubjectSetItem.tsx
  src/components/UI/Display/MAPI/CLIGuide/__tests__/__snapshots__/index.tsx.snap
Labels: kind/ux-enhancement

#2621 Access control: Turn of spell-checking for subject name input
  src/components/UI/Display/MAPI/AccessControl/AccessControlSubjectAddForm.tsx
Labels: kind/ux-enhancement

#2620 Use utility function for extracting error message from org error
  src/components/MAPI/organizations/OrganizationDetail.tsx
Labels: kind/ux-enhancement

#2617 Add CLI guides for listing and creating clusters
  src/components/GettingStarted/Steps/SimpleExample.js
  src/components/MAPI/clusters/Clusters.tsx
  src/components/MAPI/clusters/CreateCluster/index.tsx
  src/components/MAPI/clusters/guides/CreateClusterGuide.tsx
  src/components/MAPI/clusters/guides/ListClustersGuide.tsx
  src/components/MAPI/guides/__tests__/utils.ts
  src/components/MAPI/guides/utils.ts
  src/components/UI/Display/MAPI/CLIGuide/__tests__/__snapshots__/index.tsx.snap
  src/components/UI/Display/MAPI/clusters/ClusterDetail/ClusterDetailCounter/__tests__/__snapshots__/index.tsx.snap
  src/components/UI/Display/MAPI/clusters/ClusterDetail/ClusterDetailWidget/__tests__/__snapshots__/index.tsx.snap
  src/components/UI/Display/MAPI/clusters/GettingStarted/GettingStartedSimpleExample.tsx
  src/components/UI/Inputs/NumberPicker/__tests__/__snapshots__/index.tsx.snap
  src/components/UI/Inputs/RadioInput/__tests__/__snapshots__/index.tsx.snap
  src/lib/__tests__/helpers.ts
  src/lib/docs.ts
  src/lib/helpers.tsx
Labels: kind/dev-change

#2549 Refactor the Tab components to use grommet instead of bootstrap
  src/components/Cluster/ClusterDetail/ClusterDetailView.js
  src/components/GettingStarted/Steps/ConfigureKubectl.js
  src/components/GettingStarted/Steps/SimpleExample.js
  src/components/MAPI/clusters/ClusterDetail/index.tsx
  src/components/MAPI/clusters/GettingStarted/GettingStartedPlatformTabs.tsx
  src/components/MAPI/organizations/OrganizationDetail.tsx
  src/components/UI/Controls/ExpiryHoursPicker.stories.tsx
  src/components/UI/Display/Apps/AppDetails/AppDetails.js
  src/components/UI/Display/MAPI/AccessControl/AccessControlRoleDetail.tsx
  src/components/UI/Display/MAPI/clusters/ClusterDetail/ClusterDetailCounter/__tests__/__snapshots__/index.tsx.snap
  src/components/UI/Display/MAPI/clusters/ClusterDetail/ClusterDetailWidget/__tests__/__snapshots__/index.tsx.snap
  src/components/UI/Display/Tabs/Tab.tsx
  src/components/UI/Display/Tabs/Tabs.tsx
  src/components/UI/Display/Tabs/__tests__/Tabs.tsx
  src/components/UI/Display/Tabs/__tests__/__snapshots__/Tabs.tsx.snap
  src/components/UI/Display/Tabs/index.tsx
  src/components/UI/Display/Tabs/stories/Tabs.stories.mdx
  src/components/UI/Inputs/NumberPicker/__tests__/__snapshots__/index.tsx.snap
  src/components/UI/Inputs/RadioInput/__tests__/__snapshots__/index.tsx.snap
  src/components/shared/Tabs/index.tsx
  src/components/shared/__tests__/Tabs.tsx
  src/styles/_breakpoints.sass
  src/styles/app.sass
  src/styles/theme.ts
Labels: kind/refactor

#2629 Remove leftover bootstrap tabs
  src/components/UI/Display/Apps/AppDetails/AppDetails.js
  src/components/UI/Display/Tabs/stories/Tabs.stories.mdx
Labels: kind/dev-change

#2619 Add CLI guides for the cluster overview tab
  src/components/MAPI/clusters/ClusterDetail/ClusterDetailOverview.tsx
  src/components/MAPI/clusters/guides/InspectClusterGuide.tsx
  src/components/MAPI/clusters/guides/InspectClusterReleaseGuide.tsx
  src/components/MAPI/clusters/guides/SetClusterLabelsGuide.tsx
  src/components/MAPI/guides/__tests__/utils.ts
  src/components/MAPI/guides/utils.ts
  src/components/UI/Display/MAPI/CLIGuide/CLIGuideStep.tsx
  src/lib/docs.ts
Labels: kind/feature

#2630 Use grommet's DataTable component for complex tables, instead of the bootstrap one
  __tests__/Users.js
  package.json
  src/components/Cluster/ClusterDetail/KeyPairs.js
  src/components/Organizations/Detail/View.js
  src/components/UI/DataTable/__tests__/__snapshots__/index.tsx.snap
  src/components/UI/DataTable/__tests__/index.tsx
  src/components/UI/DataTable/index.tsx
  src/components/UI/DataTable/stories/DataTable.stories.tsx
  src/components/UI/DataTable/stories/Simple.tsx
  src/components/Users/InvitesTable.js
  src/components/Users/UsersTable.js
  src/styles/app.sass
  src/styles/theme.ts
  src/styles/vendor/react-bootstrap-table-next.scss
  yarn.lock
Labels: kind/refactor

#2637 Access Control: Sort roles list by (cluster) role name
  src/components/MAPI/organizations/AccessControl/utils.ts
Labels: kind/ux-enhancement

#2627 Access control: Improve service account flash messages
  src/components/MAPI/organizations/AccessControl/AccessControlRoleSubjects.tsx
  src/components/MAPI/organizations/AccessControl/__tests__/AccessControlRoleSubjects.tsx
  src/components/MAPI/organizations/AccessControl/__tests__/index.tsx
  src/components/MAPI/organizations/AccessControl/index.tsx
  src/components/MAPI/organizations/AccessControl/utils.ts
  src/components/UI/Display/MAPI/AccessControl/AccessControlRoleDetail.tsx
  src/components/UI/Display/MAPI/AccessControl/types.ts
Labels: kind/ux-enhancement

#2638 Update base Docker images
  Dockerfile
  Dockerfile.fe-docs
Labels: dependencies

#2639 Add Management API guide to the key pairs list
  src/components/MAPI/clusters/guides/CreateKeyPairGuide.tsx
  src/components/MAPI/keypairs/ClusterDetailKeyPairs.tsx
  src/lib/docs.ts
Labels: kind/feature

#2640 Add Management API guide to list installed apps
  src/components/MAPI/apps/ClusterDetailApps.tsx
  src/components/MAPI/clusters/guides/ListAppsGuide.tsx
  src/components/MAPI/guides/__tests__/utils.ts
  src/components/MAPI/guides/utils.ts
  src/lib/docs.ts
Labels: kind/feature

#2643 Add CLI guide for modifying a node pool
  src/components/MAPI/workernodes/ClusterDetailWorkerNodes.tsx
  src/components/MAPI/workernodes/guides/ListNodePoolsGuide.tsx
  src/components/MAPI/workernodes/guides/ModifyNodePoolGuide.tsx
  src/lib/docs.ts
Labels: kind/feature

#2642 Use function to produce CRD schema docs URL
  src/components/MAPI/clusters/guides/CreateClusterGuide.tsx
  src/components/MAPI/clusters/guides/InspectClusterGuide.tsx
  src/components/MAPI/clusters/guides/InspectClusterReleaseGuide.tsx
  src/components/MAPI/clusters/guides/ListAppsGuide.tsx
  src/components/MAPI/clusters/guides/ListClustersGuide.tsx
  src/components/MAPI/clusters/guides/SetClusterLabelsGuide.tsx
  src/components/MAPI/organizations/guides/CreateOrganizationGuide.tsx
  src/components/MAPI/organizations/guides/GetOrganizationDetailsGuide.tsx
  src/components/MAPI/organizations/guides/ListOrganizationsGuide.tsx
  src/components/MAPI/workernodes/guides/ModifyNodePoolGuide.tsx
  src/lib/docs.ts
Labels: kind/refactor

#2644 Add CLI guide for deleting a node pool
  src/components/MAPI/workernodes/ClusterDetailWorkerNodes.tsx
  src/components/MAPI/workernodes/guides/DeleteNodePoolGuide.tsx
Labels: kind/feature

#2647 Create feature flag value for mapiAuth (SSO)
  helm/happa/Chart.yaml
  helm/happa/templates/configmap.yaml
  helm/happa/values.yaml
Labels: kind/dev-change

#2648 Fix config version in chart
  helm/happa/Chart.yaml
Labels: kind/dev-change

#2645 Add CLI guide for creating a node pool
  src/components/MAPI/guides/__tests__/utils.ts
  src/components/MAPI/guides/utils.ts
  src/components/MAPI/workernodes/WorkerNodesCreateNodePool.tsx
  src/components/MAPI/workernodes/guides/CreateNodePoolGuide.tsx
  src/lib/docs.ts
Labels: kind/feature

#2649 Add CLI guide for deleting a cluster
  src/components/MAPI/clusters/ClusterDetail/ClusterDetailActions.tsx
  src/components/MAPI/clusters/guides/DeleteClusterGuide.tsx
Labels: kind/feature

#2655 Keep footer button padding consistent while hovering and increase color contrast
  src/components/Footer/FooterUpdateButton.tsx
  src/components/UI/Controls/Button/__tests__/__snapshots__/index.tsx.snap
  src/components/UI/Controls/Button/index.tsx
  src/components/UI/Controls/ConfirmationPrompt/__tests__/__snapshots__/index.tsx.snap
  src/components/UI/DataTable/__tests__/__snapshots__/index.tsx.snap
  src/components/UI/Display/MAPI/CLIGuide/__tests__/__snapshots__/index.tsx.snap
  src/components/UI/Display/MAPI/clusters/ClusterDetail/ClusterDetailCounter/__tests__/__snapshots__/index.tsx.snap
  src/components/UI/Display/MAPI/clusters/ClusterDetail/ClusterDetailWidget/__tests__/__snapshots__/index.tsx.snap
  src/components/UI/Display/Table/__tests__/__snapshots__/index.tsx.snap
  src/components/UI/Display/Tabs/__tests__/__snapshots__/Tabs.tsx.snap
  src/components/UI/Inputs/CheckBoxInput/__tests__/__snapshots__/index.tsx.snap
  src/components/UI/Inputs/CurrencyInput/__tests__/__snapshots__/CurrencyInput.tsx.snap
  src/components/UI/Inputs/DateInput/__tests__/__snapshots__/index.tsx.snap
  src/components/UI/Inputs/FileInput/__tests__/__snapshots__/index.tsx.snap
  src/components/UI/Inputs/InputGroup/__tests__/__snapshots__/index.tsx.snap
  src/components/UI/Inputs/MultiSelect/__tests__/__snapshots__/index.tsx.snap
  src/components/UI/Inputs/NumberPicker/__tests__/__snapshots__/index.tsx.snap
  src/components/UI/Inputs/RadioInput/__tests__/__snapshots__/index.tsx.snap
  src/components/UI/Inputs/Select/__tests__/__snapshots__/index.tsx.snap
  src/components/UI/Inputs/TextArea/__tests__/__snapshots__/index.tsx.snap
  src/components/UI/Inputs/TextInput/__tests__/__snapshots__/index.tsx.snap
Labels: kind/bug

#2654 Make SSO app management fetch app catalog versions from MAPI, instead of GitHub
  src/components/MAPI/apps/AppDetailsModal/__tests__/index.tsx
  src/components/MAPI/apps/AppList/AppDetail.tsx
  src/components/MAPI/apps/AppList/__tests__/AppDetail.tsx
  src/components/MAPI/apps/AppList/__tests__/index.tsx
  src/components/MAPI/apps/AppList/index.tsx
  src/components/MAPI/apps/AppList/utils.tsx
  src/model/services/mapi/applicationv1alpha1/key.ts
  src/model/services/mapi/applicationv1alpha1/types.ts
  testUtils/mockHttpCalls/applicationv1alpha1/appcatalogentries.ts
  testUtils/mockHttpCalls/applicationv1alpha1/appcatalogindexes.ts
  testUtils/mockHttpCalls/applicationv1alpha1/appcatalogs.ts
  testUtils/mockHttpCalls/applicationv1alpha1/index.ts
Labels: kind/ux-enhancement

#2656 Hide Users page if the customer SSO feature flag is enabled
  __tests__/Users.js
  src/components/Layout.js
  src/components/UI/Controls/Navigation/MainMenu.js
  src/components/UI/Controls/Navigation/Navigation.js
Labels: kind/dev-change

#2657 Change "Control plane nodes" label to "Control plane"
  __tests__/V5ClusterManagement.js
  src/components/Cluster/ClusterDetail/MasterNodes/MasterNodes.tsx
  src/components/MAPI/clusters/ClusterDetail/ClusterDetailWidgetControlPlaneNodes.tsx
Labels: kind/ux-enhancement

#2636 Use `GenericResponseError` for typing MAPI error responses
  src/components/MAPI/apps/AppDetailsModal/index.tsx
  src/components/MAPI/apps/AppInstallModal.tsx
  src/components/MAPI/apps/AppList/AppDetail.tsx
  src/components/MAPI/apps/AppList/index.tsx
  src/components/MAPI/apps/ClusterDetailApps.tsx
  src/components/MAPI/apps/ClusterDetailIngress.tsx
  src/components/MAPI/apps/InstallIngressButton.tsx
  src/components/MAPI/organizations/AccessControl/AccessControlRoleSubjects.tsx
  src/components/MAPI/organizations/AccessControl/index.tsx
  src/components/MAPI/organizations/OrganizationDetail.tsx
  src/components/MAPI/organizations/OrganizationDetailGeneral/index.tsx
Labels: kind/refactor

#2659 Activate renovate dependency dashboard
  renovate.json
Labels: kind/dev-change

#2658 Hide "upgrade available" information during cluster creation
  src/components/MAPI/releases/ClusterDetailWidgetRelease.tsx
  src/components/UI/Display/MAPI/clusters/ClusterDetail/ClusterDetailStatus.tsx
Labels: kind/ux-enhancement

#2698 Add spacing between buttons in upgrade modal
  src/components/MAPI/releases/ClusterDetailUpgradeModal.tsx
Labels: kind/bug

#2697 Access control: order subjects by name and briefly highlight last added subject(s)
  src/components/MAPI/organizations/AccessControl/AccessControlRoleSubjects.tsx
  src/components/UI/Display/MAPI/AccessControl/AccessControlSubjectSet.tsx
  src/components/UI/Display/MAPI/AccessControl/AccessControlSubjectSetItem.tsx
Labels: kind/ux-enhancement

#2685 Add support for using configuration values from a production environment
  README.md
  package.json
  scripts/createProxy.ts
  scripts/getProdConfiguration.ts
  scripts/templateIndex.ts
  scripts/webpack/ConfigurationPlugin.ts
  scripts/webpack/computeEndpoints.ts
  scripts/webpack/getServiceURL.js
  scripts/webpack/proxyPlugin.js
  webpack.dev.ts
  yarn.lock
Labels: kind/dev-change

#2703 Align release widget in cluster creation and cluster details display
  src/components/Cluster/NewCluster/ReleaseSelector/ReleaseSelector.tsx
  src/components/Cluster/NewCluster/ReleaseSelector/__tests__/ReleaseSelector.ts
  src/components/MAPI/clusters/CreateCluster/__tests__/index.tsx
Labels: kind/ux-enhancement

#2704 Fix cluster and node pool description tooltips and error messages in MAPI UI
  src/components/MAPI/clusters/ClusterDetail/index.tsx
  src/components/MAPI/workernodes/WorkerNodesNodePoolItem.tsx
  src/components/UI/Inputs/ViewEditName.tsx
Labels: kind/bug
