Repository giantswarm/happa, pull requests merged in 2021-07, with the labels that each got.

#2523 clusters: add support for node pool scaling from the MAPI cluster detail page
  src/components/MAPI/workernodes/WorkerNodesNodePoolItem.tsx
  src/components/MAPI/workernodes/WorkerNodesNodePoolItemScale.tsx
  src/components/MAPI/workernodes/utils.ts
  src/components/UI/Display/MAPI/workernodes/WorkerNodesNodePoolActions.tsx
  src/components/shared/NodeCountSelector.js
Labels: kind/refactor

#2521 Add Monitoring link to the main menu
  .circleci/config.yml
  README.md
  helm/happa/ci/default-values.yaml
  helm/happa/templates/deployment.yaml
  jest.config.js
  scripts/start.sh
  src/@types/global.d.ts
  src/components/UI/Controls/Navigation/MainMenu.js
  src/index.ejs
  webpack.common.ts
Labels: kind/feature

#2519 Remove login form sass
  src/components/Auth/AdminLogin.tsx
  src/components/Auth/Login.tsx
  src/components/ForgotPassword/ForgotPassword.js
  src/components/ForgotPassword/SetPassword.js
  src/components/UI/Display/MAPI/clusters/ClusterDetail/ClusterDetailCounter/__tests__/__snapshots__/index.tsx.snap
  src/components/UI/Display/MAPI/clusters/ClusterDetail/ClusterDetailWidget/__tests__/__snapshots__/index.tsx.snap
  src/components/UI/Inputs/CheckBoxInput/__tests__/__snapshots__/index.tsx.snap
  src/components/UI/Inputs/NumberPicker/__tests__/__snapshots__/index.tsx.snap
  src/components/UI/Inputs/RadioInput/__tests__/__snapshots__/index.tsx.snap
  src/components/shared/ShadowMask.tsx
  src/styles/app.sass
  src/styles/components/_login_form.sass
Labels: kind/refactor

#2526 Refactor MAPI resource deletion
  src/components/MAPI/clusters/ClusterDetail/utils.ts
  src/components/MAPI/organizations/AccessControl/utils.ts
  src/components/MAPI/workernodes/utils.ts
  src/model/services/mapi/applicationv1alpha1/deleteApp.ts
  src/model/services/mapi/capiv1alpha3/deleteCluster.ts
  src/model/services/mapi/capiv1alpha3/exp/deleteMachinePool.ts
  src/model/services/mapi/corev1/deleteConfigMap.ts
  src/model/services/mapi/corev1/deleteSecret.ts
  src/model/services/mapi/corev1/deleteServiceAccount.ts
  src/model/services/mapi/generic/deleteResource.ts
  src/model/services/mapi/rbacv1/deleteClusterRoleBinding.ts
  src/model/services/mapi/rbacv1/deleteRoleBinding.ts
  src/model/services/mapi/securityv1alpha1/deleteOrganization.ts
Labels: kind/refactor

#2525 clusters: add basic node pool creation from the MAPI cluster details page
  src/components/MAPI/__tests__/utils.ts
  src/components/MAPI/clusters/ClusterDetail/ClusterDetailWidgetWorkerNodes.tsx
  src/components/MAPI/types.ts
  src/components/MAPI/utils.ts
  src/components/MAPI/workernodes/ClusterDetailWorkerNodes.tsx
  src/components/MAPI/workernodes/WorkerNodesCreateNodePool.tsx
  src/components/MAPI/workernodes/WorkerNodesCreateNodePoolDescription.tsx
  src/components/MAPI/workernodes/WorkerNodesCreateNodePoolName.tsx
  src/components/MAPI/workernodes/patches.ts
  src/components/MAPI/workernodes/utils.ts
  src/components/UI/Display/MAPI/workernodes/WorkerNodesNodePoolListPlaceholder.tsx
  src/components/UI/Inputs/DateInput/__tests__/__snapshots__/index.tsx.snap
  src/components/UI/Inputs/FileInput/__tests__/__snapshots__/index.tsx.snap
  src/components/UI/Inputs/NumberPicker/__tests__/__snapshots__/index.tsx.snap
  src/components/UI/Inputs/Select/__tests__/__snapshots__/index.tsx.snap
  src/components/UI/Inputs/TextArea/__tests__/__snapshots__/index.tsx.snap
  src/components/UI/Inputs/TextInput/__tests__/__snapshots__/index.tsx.snap
  src/model/services/mapi/capiv1alpha3/exp/createMachinePool.ts
  src/model/services/mapi/capiv1alpha3/exp/index.ts
  src/model/services/mapi/capiv1alpha3/exp/key.ts
  src/model/services/mapi/capiv1alpha3/key.ts
  src/model/services/mapi/capzv1alpha3/exp/createAzureMachinePool.ts
  src/model/services/mapi/capzv1alpha3/exp/index.ts
  src/model/services/mapi/corev1/key.ts
  src/model/services/mapi/gscorev1alpha1/createSpark.ts
  src/model/services/mapi/gscorev1alpha1/index.ts
  src/model/services/mapi/gscorev1alpha1/types.ts
  src/shared/constants/index.ts
  src/styles/theme.ts
Labels: kind/refactor

#2532 clusters: add support for configuring the machine type when creating node pools via the MAPI cluster detail page
  src/components/Cluster/ClusterDetail/InstanceTypeSelector/InstanceTypeRow.tsx
  src/components/Cluster/ClusterDetail/InstanceTypeSelector/InstanceTypeSelector.tsx
  src/components/MAPI/workernodes/WorkerNodesCreateNodePool.tsx
  src/components/MAPI/workernodes/WorkerNodesCreateNodePoolMachineType.tsx
  src/components/MAPI/workernodes/patches.ts
  src/components/UI/Controls/ExpandableSelector/Selector.tsx
Labels: kind/refactor

#2535 Replace 'happa' with 'web interface'
  .circleci/config.yml
  src/components/Cluster/ClusterDetail/KeypairCreateModal/Utils.ts
  src/components/Footer/Footer.tsx
  src/components/Footer/FooterUtils.ts
  src/components/Footer/__tests__/Footer.ts
  src/components/GettingStarted/Steps/ConfigureKubectlAlternative.js
  src/index.ejs
  src/shared/constants/index.ts
Labels: kind/change

#2537 Avoid error notification for invalid app values file
  src/components/Apps/AppDetail/InstallAppModal/InstallAppModal.tsx
  src/components/Cluster/ClusterDetail/AppDetailsModal/YAMLFileUpload.tsx
  src/components/MAPI/apps/AppInstallModal.tsx
Labels: kind/dev-change

#2536 clusters: add support for setting AZs when creating NPs via the MAPI cluster detail page
  src/components/Cluster/AZSelection/AZSelection.tsx
  src/components/Cluster/AZSelection/AZSelectionAutomatic.tsx
  src/components/Cluster/AZSelection/AZSelectionCheckbox.tsx
  src/components/Cluster/AZSelection/AZSelectionManual.tsx
  src/components/Cluster/AZSelection/AZSelectionNotSpecified.tsx
  src/components/MAPI/__tests__/utils.ts
  src/components/MAPI/utils.ts
  src/components/MAPI/workernodes/WorkerNodesCreateNodePool.tsx
  src/components/MAPI/workernodes/WorkerNodesCreateNodePoolAvailabilityZones.tsx
  src/components/MAPI/workernodes/patches.ts
  src/components/UI/Display/Cluster/AvailabilityZones/AvailabilityZonesLabel.js
  src/components/UI/Inputs/RadioInput/__tests__/__snapshots__/index.tsx.snap
  src/components/UI/Inputs/RadioInput/index.tsx
Labels: kind/refactor

#2538 clusters: add support for configuring scaling when creating NPs via the MAPI cluster detail page
  src/components/Cluster/ClusterDetail/AddNodePool/AddNodePool.js
  src/components/MAPI/workernodes/WorkerNodesCreateNodePool.tsx
  src/components/MAPI/workernodes/WorkerNodesCreateNodePoolScale.tsx
  src/components/MAPI/workernodes/patches.ts
  src/components/MAPI/workernodes/utils.ts
  src/components/UI/Inputs/NumberPicker/index.tsx
  src/components/shared/NodeCountSelector.js
Labels: kind/refactor

#2545 Stop displaying inactive versions as upgradable for admins
  src/stores/cluster/__tests__/selectors.ts
  src/stores/cluster/selectors.ts
Labels: kind/bug

#2546 clusters: add getting started guide specific for MAPI clusters
  src/components/MAPI/clusters/Cluster.tsx
  src/components/MAPI/clusters/GettingStarted/GettingStartedPlatformTabs.tsx
  src/components/MAPI/clusters/GettingStarted/GettingStartedProvider.tsx
  src/components/MAPI/clusters/GettingStarted/index.tsx
  src/components/MAPI/utils.ts
  src/components/UI/Display/Documentation/Styles.js
  src/components/UI/Display/MAPI/clusters/GettingStarted/GettingStartedGetAccess.tsx
  src/components/UI/Display/MAPI/clusters/GettingStarted/GettingStartedInstallIngress.tsx
  src/components/UI/Display/MAPI/clusters/GettingStarted/GettingStartedNavigation.tsx
  src/components/UI/Display/MAPI/clusters/GettingStarted/GettingStartedNextSteps.tsx
  src/components/UI/Display/MAPI/clusters/GettingStarted/GettingStartedOverview.tsx
  src/components/UI/Display/MAPI/clusters/GettingStarted/GettingStartedSimpleExample.tsx
  src/components/shared/Tabs/index.tsx
  src/lib/blog.ts
Labels: kind/refactor

#2540 clusters: add support for configuring spot instances on NP creation via the MAPI page
  src/components/Cluster/ClusterDetail/AddNodePool/AddNodePool.js
  src/components/Cluster/ClusterDetail/AddNodePool/AddNodePoolSpotInstancesAzure.tsx
  src/components/Cluster/ClusterDetail/AddNodePool/__tests__/AddNodePool.tsx
  src/components/Cluster/ClusterDetail/NodePoolScalingSpotInstancesDetails.tsx
  src/components/Cluster/ClusterDetail/V5ClusterDetailTableSpotInstancesTab.tsx
  src/components/Cluster/ClusterDetail/__tests__/NodePoolScaling.tsx
  src/components/Cluster/ClusterDetail/__tests__/V5ClusterDetailTableNodePoolScaling.tsx
  src/components/MAPI/utils.ts
  src/components/MAPI/workernodes/ClusterDetailWorkerNodes.tsx
  src/components/MAPI/workernodes/WorkerNodesAzureMachinePoolSpotInstances.tsx
  src/components/MAPI/workernodes/WorkerNodesCreateNodePool.tsx
  src/components/MAPI/workernodes/WorkerNodesCreateNodePoolSpotInstances.tsx
  src/components/MAPI/workernodes/patches.ts
  src/components/UI/Inputs/CheckBoxInput/__tests__/__snapshots__/index.tsx.snap
  src/components/UI/Inputs/CheckBoxInput/index.tsx
  src/model/services/mapi/capzv1alpha3/types.ts
  src/model/services/mapi/metav1/key.ts
  src/model/services/mapi/metav1/types.ts
  src/shared/constants/index.ts
Labels: kind/refactor

#2543 Clean up some modal sass. Identify it as bootstrap override css
  src/styles/_base.sass
  src/styles/app.sass
  src/styles/components/_modal.sass
Labels: kind/refactor

#2547 clusters: add support for really basic cluster creation via the MAPI cluster creation page
  jest.config.js
  src/components/MAPI/clusters/Cluster.tsx
  src/components/MAPI/clusters/CreateCluster/CreateClusterDescription.tsx
  src/components/MAPI/clusters/CreateCluster/CreateClusterName.tsx
  src/components/MAPI/clusters/CreateCluster/index.tsx
  src/components/MAPI/clusters/CreateCluster/patches.ts
  src/components/MAPI/clusters/utils.ts
  src/components/MAPI/utils.ts
  src/model/services/mapi/capiv1alpha3/createCluster.ts
  src/model/services/mapi/capiv1alpha3/index.ts
  src/model/services/mapi/capiv1alpha3/key.ts
  src/model/services/mapi/capzv1alpha3/createAzureCluster.ts
  src/model/services/mapi/capzv1alpha3/createAzureMachine.ts
  src/model/services/mapi/capzv1alpha3/index.ts
  src/model/services/mapi/capzv1alpha3/types.ts
  src/shared/constants/index.ts
  testUtils/mockHttpCalls/capzv1alpha3/azureMachines.ts
Labels: kind/refactor

#2544 Consolidate an extracted label style that is only being used in one place
  src/components/UI/Display/Cluster/ClusterCreation/ClusterCreationLabelSpan.tsx
  src/styles/cluster-creation.ts
Labels: kind/refactor

#2548 clusters: add release and CP node AZ configuration to MAPI cluster creation
  src/components/Cluster/AZSelection/AZSelection.tsx
  src/components/Cluster/AZSelection/AZSelectionAutomatic.tsx
  src/components/Cluster/NewCluster/CreateNodePoolsCluster.js
  src/components/Cluster/NewCluster/NewClusterWrapper.tsx
  src/components/Cluster/NewCluster/ReleaseSelector/ReleaseRow.tsx
  src/components/Cluster/NewCluster/ReleaseSelector/ReleaseSelector.tsx
  src/components/Cluster/NewCluster/ReleaseSelector/__tests__/ReleaseSelector.ts
  src/components/MAPI/clusters/CreateCluster/CreateClusterControlPlaneNodeAZs.tsx
  src/components/MAPI/clusters/CreateCluster/CreateClusterDescription.tsx
  src/components/MAPI/clusters/CreateCluster/CreateClusterRelease.tsx
  src/components/MAPI/clusters/CreateCluster/index.tsx
  src/components/MAPI/clusters/CreateCluster/patches.ts
  src/components/UI/Controls/ExpandableSelector/Items.tsx
  src/components/UI/Display/Cluster/ReleaseComponentLabel/index.js
  src/components/UI/Display/MAPI/clusters/ClusterDetail/ClusterDetailCounter/__tests__/__snapshots__/index.tsx.snap
  src/components/UI/Display/MAPI/clusters/ClusterDetail/ClusterDetailWidget/__tests__/__snapshots__/index.tsx.snap
  src/components/UI/Inputs/RadioInput/index.tsx
Labels: kind/refactor

#2550 clusters: write tests for all the cluster details overview functionalities
  src/components/MAPI/apps/__tests__/ClusterDetailWidgetApps.tsx
  src/components/MAPI/clusters/ClusterDetail/ClusterDetailOverview.tsx
  src/components/MAPI/clusters/ClusterDetail/ClusterDetailOverviewDelete.tsx
  src/components/MAPI/clusters/ClusterDetail/ClusterDetailWidgetControlPlaneNodes.tsx
  src/components/MAPI/clusters/ClusterDetail/ClusterDetailWidgetProvider.tsx
  src/components/MAPI/clusters/ClusterDetail/__tests__/ClusterDetailOverviewDelete.tsx
  src/components/MAPI/clusters/ClusterDetail/__tests__/ClusterDetailWidgetControlPlaneNodes.tsx
  src/components/MAPI/clusters/ClusterDetail/__tests__/ClusterDetailWidgetCreated.tsx
  src/components/MAPI/clusters/ClusterDetail/__tests__/ClusterDetailWidgetKubernetesAPI.tsx
  src/components/MAPI/clusters/ClusterDetail/__tests__/ClusterDetailWidgetLabels.tsx
  src/components/MAPI/clusters/ClusterDetail/__tests__/ClusterDetailWidgetProvider.tsx
  src/components/MAPI/clusters/ClusterDetail/__tests__/index.tsx
  src/components/MAPI/clusters/utils.ts
  src/components/MAPI/keypairs/__tests__/ClusterDetailWidgetKeyPairs.tsx
  src/components/MAPI/releases/ClusterDetailReleaseDetailsModal.tsx
  src/components/MAPI/releases/__tests__/ClusterDetailWidgetRelease.tsx
  src/components/MAPI/workernodes/ClusterDetailWidgetWorkerNodes.tsx
  src/components/MAPI/workernodes/__tests__/ClusterDetailWidgetWorkerNodes.tsx
  src/components/UI/Display/Cluster/ReleaseComponentLabel/index.js
  src/components/UI/Display/MAPI/clusters/ClusterDetail/ClusterDetailCounter/index.tsx
  src/components/UI/Display/MAPI/clusters/ClusterDetail/ClusterDetailWidget/__tests__/__snapshots__/index.tsx.snap
  src/components/UI/Display/MAPI/clusters/ClusterDetail/ClusterDetailWidget/index.tsx
  src/model/services/mapi/capiv1alpha3/key.ts
  testUtils/mockHttpCalls/capiv1alpha3/clusters.ts
  testUtils/mockHttpCalls/capzv1alpha3/azureClusters.ts
  testUtils/mockHttpCalls/capzv1alpha3/azureMachines.ts
  testUtils/mockHttpCalls/capzv1alpha3/index.ts
  testUtils/mockHttpCalls/legacy/clusterService.ts
  testUtils/mockHttpCalls/legacy/index.ts
  testUtils/mockHttpCalls/releasev1alpha1/releases.ts
Labels: kind/refactor

#2552 Move signup sass to signup component, delete sass files.
  src/components/SignUp/SignUp.tsx
  src/styles/app.sass
  src/styles/components/_signup.sass
Labels: kind/refactor

#2551 clusters: write tests specific for cluster listing
  src/components/MAPI/clusters/ClusterList/ClusterListItem.tsx
  src/components/MAPI/clusters/ClusterList/ClusterListItemStatus.tsx
  src/components/MAPI/clusters/ClusterList/__tests__/ClusterListItem.tsx
  src/components/MAPI/clusters/__tests__/Clusters.tsx
  src/components/UI/Display/Cluster/KubernetesVersionLabel.tsx
  src/components/UI/Display/MAPI/clusters/ClusterList/ClusterListItemMainInfo.tsx
  src/components/UI/Display/MAPI/clusters/ClusterList/ClusterListItemNodeInfo.tsx
  testUtils/assertUtils.ts
Labels: kind/refactor

#2553 clusters: write tests for MAPI cluster creation
  src/components/Apps/AppDetail/InstallAppModal/InstallAppModal.tsx
  src/components/Cluster/NewCluster/ReleaseSelector/ReleaseRow.tsx
  src/components/MAPI/apps/AppInstallModal.tsx
  src/components/MAPI/clusters/CreateCluster/CreateClusterDescription.tsx
  src/components/MAPI/clusters/CreateCluster/CreateClusterName.tsx
  src/components/MAPI/clusters/CreateCluster/__tests__/index.tsx
  src/components/UI/Display/Cluster/AvailabilityZones/AvailabilityZonesLabel.js
  src/components/UI/Display/Cluster/ClusterIDLabel/index.tsx
  testUtils/assertUtils.ts
Labels: kind/refactor

#2559 clusters: write tests for MAPI node pools listing/updating
  src/components/MAPI/workernodes/ClusterDetailWorkerNodes.tsx
  src/components/MAPI/workernodes/WorkerNodesAzureMachinePoolSpotInstances.tsx
  src/components/MAPI/workernodes/WorkerNodesNodePoolItem.tsx
  src/components/MAPI/workernodes/__tests__/ClusterDetailWorkerNodes.tsx
  src/components/MAPI/workernodes/__tests__/WorkerNodesNodePoolItem.tsx
  src/components/MAPI/workernodes/utils.ts
  src/components/UI/Display/MAPI/workernodes/WorkerNodesNodePoolActions.tsx
  testUtils/mockHttpCalls/capiv1alpha3/exp/machinePools.ts
Labels: kind/refactor

#2560 clusters: write tests for MAPI node pool creation
  src/components/Cluster/ClusterDetail/InstanceTypeSelector/InstanceTypeRow.tsx
  src/components/Cluster/ClusterDetail/InstanceTypeSelector/InstanceTypeSelector.tsx
  src/components/MAPI/workernodes/WorkerNodesCreateNodePoolAvailabilityZones.tsx
  src/components/MAPI/workernodes/__tests__/WorkerNodesCreateNodePool.tsx
  testUtils/mockHttpCalls/gscorev1alpha1/index.ts
  testUtils/mockHttpCalls/gscorev1alpha1/sparks.ts
Labels: kind/refactor

#2562 releases: use app `componentVersion` property where available in the MAPI world
  src/components/MAPI/apps/utils.ts
  src/components/MAPI/clusters/CreateCluster/CreateClusterRelease.tsx
  src/components/MAPI/releases/ClusterDetailWidgetRelease.tsx
  src/components/MAPI/releases/__tests__/ClusterDetailWidgetRelease.tsx
  src/components/MAPI/releases/__tests__/utils.ts
  src/components/MAPI/releases/utils.ts
Labels: kind/refactor

#2561 clusters: display MAPI cluster release version k8s component version as `n/a` when the release cannot be found
  src/components/MAPI/clusters/ClusterList/ClusterListItem.tsx
Labels: kind/refactor

#2564 organizations: rework organization listing to use MAPI for cluster clusters
  src/components/MAPI/organizations/OrganizationList.tsx
  src/components/MAPI/organizations/OrganizationListCreateOrg.tsx
  src/components/MAPI/organizations/__tests__/utils.ts
  src/components/MAPI/organizations/utils.ts
  src/components/MAPI/types.ts
  src/components/MAPI/utils.ts
  src/components/UI/Display/Organizations/OrganizationListPage.tsx
  src/components/UI/Display/Organizations/stories/Simple.tsx
  src/lib/__tests__/organizationValidation.ts
  src/lib/docs.ts
  src/lib/organizationValidation.ts
Labels: kind/refactor

#2565 clusters: don't execute cluster-specific GS API requests if MAPI cluster FF is turned on
  src/stores/batchActions.ts
Labels: kind/refactor

#2566 Create VSCode workspace configuration and add React component snippet
  .gitignore
  .vscode/happa.code-snippets
  .vscode/launch.json
  happa.code-workspace
Labels: kind/dev-change

#2573 Fix cluster name in MAPI UI to display `Cluster name` label on hover.
  src/components/MAPI/clusters/ClusterDetail/index.tsx
  src/components/MAPI/clusters/ClusterList/ClusterListItem.tsx
  src/components/MAPI/clusters/CreateCluster/CreateClusterName.tsx
  src/components/UI/Display/Cluster/ClusterIDLabel/index.tsx
  src/components/UI/Display/Cluster/ClusterIDLabel/stories/ClusterIDLabel.stories.tsx
Labels: kind/bug

#2575 Fix MAPI cluster and node pool description validation messages
  src/components/MAPI/clusters/CreateCluster/CreateClusterDescription.tsx
  src/components/MAPI/workernodes/WorkerNodesCreateNodePoolDescription.tsx
  src/lib/__tests__/helpers.ts
  src/lib/helpers.tsx
Labels: kind/bug

#2574 Update sentry to v6.10.0
  package.json
  yarn.lock
Labels: dependencies

#2576 apps: write tests for cluster app management
  src/components/Apps/AppDetail/InstallAppModal/InstallAppForm.tsx
  src/components/MAPI/apps/AppDetailsModal/__tests__/index.tsx
  src/components/MAPI/apps/AppDetailsModal/index.tsx
  src/components/MAPI/apps/AppInstallModal.tsx
  src/components/MAPI/apps/ClusterDetailApps.tsx
  src/components/MAPI/apps/__tests__/AppInstallModal.tsx
  src/components/MAPI/apps/__tests__/ClusterDetailApps.tsx
  testUtils/mockHttpCalls/applicationv1alpha1/appcatalogentries.ts
  testUtils/mockHttpCalls/applicationv1alpha1/index.ts
Labels: kind/dev-change

#2567 Control MAPI cluster management feature flag from the config repo
  helm/happa/templates/configmap.yaml
  helm/happa/values.yaml
Labels: kind/dev-change

#2577 Update storybook to v6.3.6
  package.json
  yarn.lock
Labels: dependencies

#2581 Add tests for displaying data on the Apps page
  src/components/MAPI/apps/AppList/__tests__/AppDetail.tsx
  src/components/MAPI/apps/AppList/__tests__/index.tsx
  src/components/MAPI/apps/AppList/utils.tsx
  src/components/UI/Display/Apps/AppList/App.tsx
  src/components/UI/Display/Apps/AppList/Toolbar.tsx
  testUtils/mockHttpCalls/applicationv1alpha1/appcatalogindexes.ts
  testUtils/mockHttpCalls/applicationv1alpha1/appcatalogs.ts
  testUtils/mockHttpCalls/applicationv1alpha1/index.ts
Labels: kind/dev-change
