Repository giantswarm/happa, pull requests merged in 2021-05, with the labels that each got.

#2399 Remove unused create cluster styles.
  src/styles/app.sass
  src/styles/components/_create_cluster.sass
Labels: kind/refactor

#2398 Remove more sass
  src/components/shared/Copyable.tsx
  src/styles/_base.sass
  src/styles/app.sass
  src/styles/components/_configure_containers.sass
  src/styles/components/_copyable.sass
Labels: kind/refactor

#2397 Remove component_slider.sass
  src/components/GettingStarted/Steps/ConfigureKubectl.js
  src/components/GettingStarted/Steps/InstallIngress.js
  src/components/GettingStarted/Steps/NextSteps.js
  src/components/GettingStarted/Steps/Overview.js
  src/components/GettingStarted/Steps/SimpleExample.js
  src/components/UI/Display/Documentation/GettingStartedBottomNav.tsx
  src/styles/app.sass
  src/styles/components/_component_slider.sass
Labels: kind/refactor

#2383 Convert signup page to typescript.
  __tests__/SignUp.js
  src/components/SignUp/SignUp.tsx
Labels: kind/bug

#2410 Remove sass styles related to ExpiryHoursPicker, refactor to typescri…
  src/components/Cluster/ClusterDetail/KeypairCreateModal/AddKeyPairTemplate.tsx
  src/components/UI/Controls/ExpiryHoursPicker.stories.tsx
  src/components/UI/Controls/ExpiryHoursPicker.tsx
  src/styles/app.sass
  src/styles/components/_expiry_hours_picker.sass
Labels: kind/refactor

#2411 remove some old styles and consolidate them
  src/styles/_base.sass
  src/styles/_breakpoints.sass
  src/styles/app.sass
  src/styles/vendor/_simple-grid.scss
Labels: kind/refactor

#2412 Sass removal
  src/components/ForgotPassword/ForgotPassword.js
  src/components/ForgotPassword/SetPassword.js
  src/styles/app.sass
  src/styles/components/_forgot_password.sass
  src/styles/components/_select_cluster.sass
  src/styles/components/_textfield.sass
  src/styles/vendor/_clearfix.scss
Labels: kind/refactor

#2349 apps: refactor the installation/management components to TypeScript
  __tests__/AppDetailPane.tsx
  src/components/Apps/AppDetail/InstallAppModal/InstallAppForm.tsx
  src/components/Apps/AppDetail/InstallAppModal/InstallAppModal.tsx
  src/components/Cluster/ClusterDetail/AppDetailsModal/AppDetailsModal.js
  src/components/Cluster/ClusterDetail/AppDetailsModal/AppDetailsModal.tsx
  src/components/Cluster/ClusterDetail/AppDetailsModal/DeleteConfirmFooter.js
  src/components/Cluster/ClusterDetail/AppDetailsModal/DeleteConfirmFooter.tsx
  src/components/Cluster/ClusterDetail/AppDetailsModal/EditChartVersionPane.js
  src/components/Cluster/ClusterDetail/AppDetailsModal/EditChartVersionPane.tsx
  src/components/Cluster/ClusterDetail/AppDetailsModal/InitialPane.tsx
  src/components/Cluster/ClusterDetail/AppDetailsModal/YAMLFileUpload.tsx
  src/components/Cluster/ClusterDetail/AppDetailsModal/YamlFileUpload.js
  src/components/Cluster/ClusterDetail/ClusterApps.js
  src/components/Modals/GenericModal.js
  src/stores/appcatalog/actions.ts
Labels: kind/refactor

#2413 apps: install apps via MAPI if the user is logged in via SSO
  src/components/Apps/AppDetail/AppDetail.tsx
  src/components/MAPI/apps/AppInstallModal.tsx
  src/components/MAPI/apps/__tests__/utils.ts
  src/components/MAPI/apps/utils.ts
  src/model/services/mapi/applicationv1alpha1/createApp.ts
  src/model/services/mapi/applicationv1alpha1/index.ts
  src/model/services/mapi/applicationv1alpha1/key.ts
  src/model/services/mapi/capiv1alpha3/key.ts
  src/model/services/mapi/corev1/createSecret.ts
  src/model/services/mapi/corev1/deleteSecret.ts
  src/model/services/mapi/corev1/getSecret.ts
  src/model/services/mapi/corev1/index.ts
  src/model/services/mapi/corev1/types.ts
  src/model/services/mapi/corev1/updateConfigMap.ts
  src/model/services/mapi/corev1/updateSecret.ts
  src/model/services/mapi/generic/updateResource.ts
Labels: kind/refactor

#2416 apps: update app configuration via MAPI
  src/components/Cluster/ClusterDetail/ClusterApps.js
  src/components/MAPI/apps/AppDetailsModal/AppDetailsModalInitialPane.tsx
  src/components/MAPI/apps/AppDetailsModal/index.tsx
  src/components/MAPI/apps/utils.ts
  src/model/services/mapi/applicationv1alpha1/deleteApp.ts
  src/model/services/mapi/applicationv1alpha1/getApp.ts
  src/model/services/mapi/applicationv1alpha1/getAppCatalogEntryList.ts
  src/model/services/mapi/applicationv1alpha1/index.ts
  src/model/services/mapi/applicationv1alpha1/key.ts
  src/model/services/mapi/applicationv1alpha1/types.ts
  src/model/services/mapi/applicationv1alpha1/updateApp.ts
Labels: kind/refactor

#2424 Pin underscore version to 1.13.1
  package.json
  yarn.lock
Labels: dependencies, kind/security

#2423 Set nodeJS version to v14
  .circleci/config.yml
  README.md
Labels: kind/dev-change

#2426 Update nginx to 1.19-alpine
  Dockerfile
Labels: kind/dev-change

#2422 Faster pre commit hook
  .husky/pre-commit
Labels: kind/dev-change

#2421 apps: fetch apps in cluster via MAPI if the user is logged in via SSO
  src/components/Cluster/ClusterDetail/ClusterApps.tsx
  src/components/Cluster/ClusterDetail/ClusterDetailView.js
  src/components/Cluster/ClusterDetail/UserInstalledApps/InstalledApp.tsx
  src/components/Cluster/ClusterDetail/UserInstalledApps/UserInstalledApps.tsx
  src/components/Cluster/ClusterDetail/UserInstalledApps/stories/InstalledApp.stories.tsx
  src/components/MAPI/apps/AppDetailsModal/index.tsx
  src/components/MAPI/apps/ClusterDetailAppLoadingPlaceholder.tsx
  src/components/MAPI/apps/ClusterDetailApps.tsx
  src/components/MAPI/apps/utils.ts
  src/model/services/mapi/applicationv1alpha1/key.ts
  src/stores/cluster/utils.ts
  src/styles/theme.ts
Labels: kind/refactor

#2425 apps: make ingress creation possible via MAPI for users logged in via SSO
  src/components/Cluster/ClusterDetail/ClusterDetailView.js
  src/components/GettingStarted/Steps/InstallIngress.js
  src/components/MAPI/apps/ClusterDetailIngress.tsx
  src/components/MAPI/apps/InstallIngressButton.tsx
  src/components/MAPI/apps/utils.ts
  src/model/services/mapi/applicationv1alpha1/key.ts
Labels: kind/refactor

#2430 auth: fix memory leak when renewing the auth token fails
  src/components/Auth/MAPI/MapiAuthProvider.tsx
  src/lib/OAuth2/OAuth2.ts
  src/lib/OAuth2/TestOAuth2.ts
  src/stores/main/actions.ts
  src/stores/main/middleware.ts
Labels: kind/bug

#2428 Make the PR template more concise
  .github/pull_request_template.md
Labels: kind/dev-change

#2393 Use Sentry for monitoring
  .circleci/config.yml
  .sentrycliignore
  helm/happa/templates/configmap.yaml
  helm/happa/templates/deployment.yaml
  package.json
  scripts/start.sh
  src/@types/global.d.ts
  src/components/App.tsx
  src/components/Apps/Apps.tsx
  src/components/Cluster/Cluster.js
  src/components/Cluster/ClusterDetail/ClusterDetail.js
  src/components/Footer/FooterUtils.ts
  src/components/Footer/__tests__/Footer.ts
  src/components/GettingStarted/GettingStarted.js
  src/components/Layout.js
  src/components/MAPI/organizations/Organization.tsx
  src/components/MAPI/organizations/OrganizationIndex.tsx
  src/components/Organizations/Detail/Detail.js
  src/components/Organizations/Organizations.js
  src/components/Route.tsx
  src/components/Routes.js
  src/components/index.tsx
  src/components/shared/ErrorBoundary.tsx
  src/index.ejs
  src/lib/__tests__/patchedAirbrakeRequester.ts
  src/lib/errors/ErrorReporter.ts
  src/lib/errors/SentryErrorNotifier.ts
  src/lib/errors/__tests__/ErrorReporter.ts
  src/lib/patchedAirbrakeRequester.ts
  webpack.prod.js
  yarn.lock
Labels: kind/dev-change

#2432 apps: fix a bunch of smaller bugs
  src/components/Cluster/ClusterDetail/UserInstalledApps/UserInstalledApps.tsx
  src/components/MAPI/apps/AppDetailsModal/AppDetailsModalInitialPane.tsx
  src/components/MAPI/apps/utils.ts
Labels: kind/bug

#2434 auth: fix resuming an existing SSO session
  src/lib/OAuth2/OAuth2.ts
Labels: kind/bug

#2435 footer: add `v` prefix to the version in the release notes URL
  src/components/Footer/FooterUtils.ts
Labels: kind/bug

#2436 Revert copy path for images
  .sentrycliignore
  webpack.prod.js
Labels: kind/bug

#2437 Update architect-orb to 2.8.0
  .circleci/config.yml
Labels: kind/dev-change

#2438 Update sentry to v6.4.1
  package.json
  src/lib/errors/SentryErrorNotifier.ts
  yarn.lock
Labels: dependencies

#2440 apps: disable app features via MAPI on KVM installations
  src/components/Apps/AppDetail/AppDetail.tsx
  src/components/Cluster/ClusterDetail/ClusterDetailView.js
  src/components/GettingStarted/Steps/InstallIngress.js
Labels: kind/change

#2442 Fix uncaught error when fetching user invitations fails
  src/stores/user/actions.ts
Labels: kind/bug

#2443 Close app sorting dropdown after picking a value
  src/components/UI/Controls/DropdownMenu.js
Labels: kind/bug

#2445 Use app name and catalog from app spec
  src/components/MAPI/apps/AppDetailsModal/index.tsx
  src/components/MAPI/apps/ClusterDetailApps.tsx
Labels: kind/bug

#2449 apps: take into consideration that the ingress app can be in another catalog
  src/components/MAPI/apps/InstallIngressButton.tsx
  src/components/MAPI/apps/utils.ts
Labels: kind/bug

#2455 organizations: improve deletion experience for SSO users
  src/components/MAPI/organizations/AccessControl/__tests__/index.tsx
  src/components/MAPI/organizations/AccessControl/index.tsx
  src/components/MAPI/organizations/OrganizationDetail.tsx
  src/components/MAPI/organizations/OrganizationDetailDelete.tsx
  src/components/MAPI/organizations/OrganizationDetailGeneral/__tests__/index.tsx
  src/components/MAPI/organizations/OrganizationDetailGeneral/index.tsx
  src/components/UI/Controls/ConfirmationPrompt/__tests__/__snapshots__/index.tsx.snap
  src/components/UI/Controls/ConfirmationPrompt/__tests__/index.tsx
  src/components/UI/Controls/ConfirmationPrompt/index.tsx
  src/components/UI/Controls/ConfirmationPrompt/stories/ConfirmationPrompt.stories.tsx
  src/components/UI/Controls/ConfirmationPrompt/stories/Simple.tsx
  src/components/UI/Controls/ConfirmationPrompt/stories/WithButtons.tsx
  src/components/UI/Controls/ConfirmationPrompt/stories/WithTitle.tsx
  src/components/UI/Display/Organizations/OrganizationDetailPage.tsx
Labels: kind/ux-enhancement

#2459 apps: prevent infinite loading spinners for apps that don't have an app version or homepage set
  src/components/MAPI/apps/AppList/AppDetail.tsx
  src/components/MAPI/apps/AppList/utils.tsx
  src/components/UI/Display/Apps/AppDetailNew/AppDetailPage.tsx
  src/components/UI/Display/Apps/AppDetailNew/AppDetailPageOptionalValue.tsx
Labels: kind/bug

#2457 apps: persist selected catalogs when navigating between app pages
  src/components/MAPI/apps/AppList/index.tsx
  src/components/MAPI/apps/Apps.tsx
  src/components/MAPI/apps/AppsProvider.tsx
Labels: kind/ux-enhancement

#2461 apps: use the correct catalog name when installing app in workload cluster
  src/components/MAPI/apps/AppList/AppDetail.tsx
Labels: kind/bug

#2460 access control: disable adding/deleting groups and users
  src/components/MAPI/organizations/AccessControl/AccessControlRoleSubjects.tsx
  src/components/MAPI/organizations/AccessControl/__tests__/AccessControlRoleSubjects.tsx
  src/components/MAPI/organizations/AccessControl/__tests__/index.tsx
  src/components/MAPI/organizations/AccessControl/index.tsx
  src/components/MAPI/organizations/AccessControl/utils.ts
  src/components/UI/Display/MAPI/AccessControl/AccessControlRoleDetail.tsx
  src/components/UI/Display/MAPI/AccessControl/AccessControlSubjectSet.tsx
  src/components/UI/Display/MAPI/AccessControl/__tests__/AccessControlRoleDetail.tsx
  src/components/UI/Display/MAPI/AccessControl/types.ts
  testUtils/mockHttpCalls/rbacv1/roleBindings.ts
Labels: kind/ux-enhancement

#2467 Actually import 'supportsMapiApps' before using it
  src/components/GettingStarted/Steps/InstallIngress.js
Labels: kind/bug

#2465 Upgrade node-sass to v6.0.0
  package.json
  yarn.lock
Labels: dependencies

#2473 Add support for experiments
  __tests__/Login.tsx
  src/components/Auth/Login.tsx
  src/components/Layout.js
  src/components/MAPI/Experiments.tsx
  src/components/UI/Controls/Navigation/UserDropdown.tsx
  src/components/index.tsx
  src/shared/FeatureFlags.ts
  src/shared/constants/routes.ts
  src/shared/featureFlags.ts
  src/stories/Recipes/NewFeatureFlag.stories.mdx
  testUtils/setupTests.js
Labels: kind/dev-change

#2474 Upgrade ws
  package.json
  yarn.lock
Labels: kind/security

#2477 apps: use the correct chart name when installing an app
  src/components/MAPI/apps/__tests__/utils.ts
  src/components/MAPI/apps/utils.ts
Labels: kind/bug
