Repository giantswarm/happa, pull requests merged in 2022-04, with the labels that each got.

#3314 Set cluster labels via the Management API: use `kubectl label` command
  src/components/MAPI/clusters/guides/SetClusterLabelsGuide.tsx
Labels: kind/ux-enhancement, kind/change

#3315 Add components' version labels to CRs for cluster and node pool creation
  src/components/MAPI/clusters/CreateCluster/CreateClusterRelease.tsx
  src/components/MAPI/clusters/CreateCluster/CreateClusterReleaseRow.tsx
  src/components/MAPI/clusters/CreateCluster/CreateClusterReleaseSelector.tsx
  src/components/MAPI/clusters/CreateCluster/index.tsx
  src/components/MAPI/clusters/CreateCluster/patches.ts
  src/components/MAPI/clusters/utils.ts
  src/components/MAPI/workernodes/WorkerNodesCreateNodePool.tsx
  src/components/MAPI/workernodes/utils.ts
  src/model/services/mapi/capiv1alpha3/exp/key.ts
  src/model/services/mapi/capiv1beta1/key.ts
  src/model/services/mapi/capzv1alpha3/exp/key.ts
  src/model/services/mapi/capzv1beta1/key.ts
Labels: kind/change

#3321 Align cluster status between different components
  src/components/MAPI/clusters/ClusterDetail/__tests__/index.tsx
  src/components/MAPI/clusters/ClusterDetail/index.tsx
  src/components/MAPI/clusters/ClusterList/ClusterListItem.tsx
  src/components/MAPI/clusters/ClusterList/ClusterListItemStatus.tsx
  src/components/MAPI/clusters/ClusterList/__tests__/ClusterListItem.tsx
  src/components/MAPI/clusters/ClusterStatus/ClusterStatus.tsx
  src/components/MAPI/clusters/hooks/useClusterStatus.ts
  src/components/MAPI/clusters/utils.ts
  src/components/MAPI/releases/ClusterDetailWidgetRelease.tsx
  src/components/MAPI/releases/__tests__/ClusterDetailWidgetRelease.tsx
  src/components/UI/Display/MAPI/clusters/ClusterDetail/ClusterDetailStatus.tsx
  test/mockHttpCalls/capiv1beta1/clusters.ts
Labels: kind/ux-enhancement, kind/refactor

#3322 Fix token refreshing request issued twice with the same refresh token
  src/utils/MapiAuth/makeDefaultConfig.ts
  src/utils/OAuth2/OAuth2.ts
Labels: kind/bug

#3329 Auto refresh relative dates
  src/components/MAPI/apps/__tests__/ClusterDetailAppListItem.tsx
  src/components/MAPI/clusters/ClusterDetail/ClusterDetailWidgetCreated.tsx
  src/components/MAPI/keypairs/ClusterDetailKeyPairDetailsModal.tsx
  src/components/UI/Display/Date/index.tsx
  src/components/UI/Display/MAPI/apps/AppVersionInspectorOption.tsx
  src/components/UI/Display/MAPI/clusters/ClusterDetail/ClusterDetailDeleteActionClusterDetails.tsx
  src/utils/helpers.ts
Labels: kind/ux-enhancement

#3331 Update placeholders and more
  src/components/Cluster/ClusterDetail/Ingress/Instructions.tsx
  src/components/Cluster/ClusterDetail/Ingress/__tests__/Ingress.ts
  src/components/MAPI/clusters/guides/InspectClusterReleaseGuide.tsx
  src/components/UI/Display/MAPI/clusters/GettingStarted/GettingStartedGetAccess.tsx
Labels: kind/ux-enhancement

#3338 App catalog: display app installation status for current selected cluster
  src/components/Apps/AppDetail/InstallAppModal/ClusterPicker.tsx
  src/components/MAPI/apps/AppInstallModal.tsx
  src/components/MAPI/apps/AppList/AppDetail.tsx
  src/components/MAPI/apps/AppList/__tests__/AppDetail.tsx
  src/components/MAPI/apps/AppList/__tests__/index.tsx
  src/components/MAPI/apps/AppList/index.tsx
  src/components/MAPI/apps/AppList/utils.tsx
  src/components/MAPI/apps/__tests__/AppInstallModal.tsx
  src/components/MAPI/apps/utils.ts
  src/components/UI/Display/Apps/AppDetailNew/AppDetailPage.tsx
  src/components/UI/Display/Apps/AppList/App.tsx
  src/components/UI/Display/Apps/AppList/AppsListPage.tsx
  src/components/UI/Display/MAPI/apps/AppInstallationSelectedCluster.tsx
  src/model/stores/main/actions.ts
  src/model/stores/main/reducer.ts
  src/model/stores/main/types.ts
Labels: kind/change

#3343 Improve build time in CI
  .circleci/config.yml
Labels: kind/dev-change

#3361 Allow to display longer node pool names
  src/components/MAPI/workernodes/ClusterDetailWorkerNodes.tsx
  src/components/MAPI/workernodes/WorkerNodesNodePoolItem.tsx
  src/components/MAPI/workernodes/__tests__/WorkerNodesNodePoolItem.tsx
  src/components/UI/Display/MAPI/workernodes/styles.tsx
  src/components/shared/Copyable.tsx
  src/styles/index.ts
  src/utils/__tests__/helpers.ts
  src/utils/helpers.ts
Labels: kind/ux-enhancement, kind/change

#3363 Check installed app's `.spec.name` against app catalog entry name
  src/components/MAPI/apps/AppList/__tests__/AppDetail.tsx
  src/components/MAPI/apps/AppList/__tests__/index.tsx
  src/components/MAPI/apps/__tests__/AppInstallModal.tsx
  src/components/MAPI/apps/__tests__/ClusterDetailAppListItemStatus.tsx
  src/components/MAPI/apps/__tests__/ClusterDetailAppListWidgetVersion.tsx
  src/components/MAPI/apps/__tests__/ClusterDetailWidgetApps.tsx
  src/components/MAPI/apps/utils.ts
  test/mockHttpCalls/applicationv1alpha1/appcatalogentries.ts
Labels: kind/bug

#3364 Allow retrying cluster and nodepool creation
  src/components/MAPI/clusters/CreateCluster/__tests__/index.tsx
  src/components/MAPI/clusters/CreateCluster/index.tsx
  src/components/MAPI/clusters/utils.ts
  src/components/MAPI/workernodes/WorkerNodesCreateNodePool.tsx
  src/components/MAPI/workernodes/__tests__/WorkerNodesCreateNodePool.tsx
  src/components/MAPI/workernodes/utils.ts
Labels: kind/ux-enhancement

#3384 Refactoring towards React v18 upgrade
  babel.config.js
  babel.config.json
  package.json
  renovate.json
  src/components/App.tsx
  src/components/MAPI/apps/ClusterDetailAppListItem.tsx
  src/components/MAPI/apps/ClusterDetailAppListWidgetCatalog.tsx
  src/components/MAPI/apps/ClusterDetailAppListWidgetVersion.tsx
  src/components/MAPI/clusters/ClusterDetail/ClusterDetailWidgetCreated.tsx
  src/components/MAPI/clusters/ClusterDetail/index.tsx
  src/components/MAPI/clusters/ClusterList/ClusterListItem.tsx
  src/components/MAPI/releases/ClusterDetailWidgetRelease.tsx
  src/components/MAPI/workernodes/WorkerNodesNodePoolItem.tsx
  src/components/MAPI/workernodes/WorkerNodesNodePoolItemMachineType.tsx
  src/components/MAPI/workernodes/WorkerNodesSpotInstancesAWS.tsx
  src/components/UI/Display/Apps/AppDetailNew/AppDetailPage.tsx
  src/components/UI/Display/MAPI/apps/AppVersionInspectorOption.tsx
  src/components/UI/Display/MAPI/clusters/ClusterList/ClusterListItemMainInfo.tsx
  src/components/UI/Display/MAPI/clusters/ClusterList/ClusterListItemNodeInfo.tsx
  src/components/UI/Display/OptionalValue/OptionalValue.tsx
  src/components/UI/Display/OptionalValue/stories/OptionalValue.stories.tsx
  src/components/UI/Layout/Modal/index.tsx
  webpack.common.ts
  webpack.dev.ts
  yarn.lock
Labels: kind/refactor

#3385 Parse permissions use cases file
  scripts/getConfigurationValues.ts
  scripts/getPermissionsUseCasesConfig.ts
  scripts/permissions-use-cases.yaml
  scripts/prepare.ts
  scripts/webpack/ConfigurationPlugin.ts
  src/@types/global.d.ts
  src/components/MAPI/permissions/types.ts
  src/components/MAPI/permissions/utils.ts
  src/index.ejs
Labels: kind/dev-change

#3388 Create stories file for use case definition YAML
  src/stories/UseCaseDefinitionYAML.stories.mdx
Labels: kind/dev-change

#3392 Display CGroups version for node pools
  src/components/MAPI/workernodes/ClusterDetailWorkerNodes.tsx
  src/components/MAPI/workernodes/WorkerNodesNodePoolItem.tsx
  src/components/MAPI/workernodes/__tests__/ClusterDetailWorkerNodes.tsx
  src/components/MAPI/workernodes/__tests__/WorkerNodesNodePoolItem.tsx
  src/components/MAPI/workernodes/utils.ts
  src/components/UI/Display/MAPI/workernodes/styles.tsx
  src/model/constants/index.ts
  src/model/services/mapi/capiv1beta1/key.ts
Labels: kind/ux-enhancement

#3398 Fix CGroups annotation check
  src/components/MAPI/workernodes/utils.ts
Labels: kind/bug

#3397 Prolong display of flash messages for configuring app values
  src/components/MAPI/apps/ClusterDetailAppListWidgetConfiguration.tsx
Labels: kind/ux-enhancement

#3400 Handle app catalog entry versions with `v-` prefixes
  src/components/MAPI/apps/ClusterDetailAppListItem.tsx
  src/components/MAPI/apps/ClusterDetailAppListItemStatus.tsx
  src/components/MAPI/apps/ClusterDetailAppListWidgetVersion.tsx
  src/components/MAPI/apps/ClusterDetailAppListWidgetVersionInspector.tsx
  src/components/MAPI/apps/utils.ts
  src/model/services/mapi/applicationv1alpha1/key.ts
Labels: kind/bug
