Repository giantswarm/happa, pull requests merged in 2022-09, with the labels that each got.

#3697 Make cluster management read-only for GCP
  src/components/Cluster/ClusterDetail/ClusterLabels/ClusterLabels.tsx
  src/components/Cluster/ClusterDetail/ClusterLabels/EditLabelTooltip.tsx
  src/components/MAPI/clusters/ClusterDetail/ClusterDetailWidgetLabels.tsx
  src/components/MAPI/clusters/ClusterDetail/index.tsx
  src/components/MAPI/clusters/ClusterList/ClusterList.tsx
  src/components/MAPI/clusters/ClusterList/ClusterListItem.tsx
  src/components/MAPI/clusters/ClusterList/__tests__/ClusterListItem.tsx
  src/components/MAPI/clusters/Clusters.tsx
  src/components/UI/Inputs/ViewEditName/__tests__/ViewEditName.js
  src/components/UI/Inputs/ViewEditName/index.tsx
  src/components/UI/Inputs/ViewEditName/stories/ReadOnly.tsx
  src/components/UI/Inputs/ViewEditName/stories/Simple.tsx
  src/components/UI/Inputs/ViewEditName/stories/Unauthorized.tsx
  src/components/UI/Inputs/ViewEditName/stories/ViewEditName.stories.tsx
Labels: kind/refactor

#3701 Update list of cluster labels hidden by default
  __tests__/V5ClusterManagement.js
  src/components/Cluster/ClusterDetail/ClusterLabels/ClusterLabels.tsx
  src/components/MAPI/clusters/ClusterDetail/__tests__/ClusterDetailWidgetLabels.tsx
  src/model/constants/index.ts
Labels: kind/ux-enhancement

#3706 Make node pool management read-only for GCP
  src/components/MAPI/utils.ts
  src/components/MAPI/workernodes/ClusterDetailWidgetWorkerNodes.tsx
  src/components/MAPI/workernodes/ClusterDetailWorkerNodes.tsx
  src/components/MAPI/workernodes/WorkerNodesNodePoolItem.tsx
  src/components/UI/Display/MAPI/workernodes/WorkerNodesNodePoolListPlaceholder.tsx
  src/components/UI/Display/MAPI/workernodes/styles.tsx
Labels: kind/refactor

#3707 Fix layout bug in non-MAPI UI control plane widget
  src/components/Cluster/ClusterDetail/MasterNodes/MasterNodes.tsx
  src/components/Cluster/ClusterDetail/MasterNodes/MasterNodesInfo.tsx
Labels: kind/bug

#3711 Don't fetch cluster-service StorageConfigs for CAPI providers
  src/components/MAPI/keypairs/ClusterDetailKeyPairs.tsx
  src/components/MAPI/keypairs/ClusterDetailWidgetKeyPairs.tsx
  src/components/MAPI/keypairs/utils.ts
  src/components/MAPI/utils.ts
Labels: kind/bug

#3713 Display app logo for app items in catalogs if provided
  src/components/MAPI/apps/AppList/AppDetail.tsx
  src/components/MAPI/apps/AppList/utils.tsx
  src/model/services/mapi/applicationv1alpha1/key.ts
Labels: kind/ux-enhancement, kind/refactor

#3722 Display correct Kubernetes API endpoint for CAPI clusters
  jest.config.ts
  package.json
  src/components/MAPI/clusters/ClusterDetail/__tests__/ClusterDetailWidgetKubernetesAPI.tsx
  src/components/MAPI/guides/LoginGuideStep.tsx
  src/components/MAPI/utils.ts
  src/components/UI/Display/MAPI/clusters/GettingStarted/GettingStartedGetAccess.tsx
  src/model/services/mapi/capiv1beta1/key.ts
  src/utils/helpers.ts
  test/mockHttpCalls/capiv1beta1/clusters.ts
  yarn.lock
Labels: kind/ux-enhancement

#3736 Fix app details UI bugs
  src/components/UI/Display/Apps/AppDetailNew/AppDetailPage.tsx
Labels: kind/bug

#3735 Don't display the management cluster
  src/components/MAPI/utils.ts
  src/model/constants/index.ts
Labels: kind/refactor

#3731 Support permissions for apps: app resources in organization namespace
  src/components/MAPI/apps/AppList/AppDetail.tsx
  src/components/MAPI/apps/ClusterDetailApps.tsx
  src/components/MAPI/apps/ClusterDetailIngress.tsx
  src/components/MAPI/apps/ClusterDetailWidgetApps.tsx
  src/components/MAPI/apps/InstallIngressButton.tsx
  src/components/MAPI/apps/permissions/usePermissionsForApps/index.ts
  src/components/MAPI/apps/permissions/usePermissionsForApps/usePermissionsForAppConfigsInClusterNamespace.ts
  src/components/MAPI/apps/permissions/usePermissionsForApps/usePermissionsForAppConfigsInOrgNamespace.ts
  src/components/MAPI/apps/permissions/usePermissionsForApps/usePermissionsForApps.ts
  src/components/MAPI/apps/permissions/usePermissionsForApps/usePermissionsForAppsInClusterNamespace.ts
  src/components/MAPI/apps/permissions/usePermissionsForApps/usePermissionsForAppsInOrgNamespace.ts
  src/components/MAPI/apps/permissions/usePermissionsForClusterApps.ts
  src/components/MAPI/clusters/ClusterDetail/ClusterDetailActions.tsx
  src/components/MAPI/clusters/ClusterDetail/index.tsx
Labels: kind/ux-enhancement, kind/refactor

#3741 App installation support on GCP
  src/components/Cluster/ClusterDetail/ClusterDetailView.js
  src/components/GettingStarted/Steps/InstallIngress.js
  src/components/MAPI/apps/AppInstallModal.tsx
  src/components/MAPI/apps/ClusterDetailAppList.tsx
  src/components/MAPI/apps/ClusterDetailAppListItem.tsx
  src/components/MAPI/apps/ClusterDetailAppListWidgetConfiguration.tsx
  src/components/MAPI/apps/ClusterDetailAppListWidgetUninstall.tsx
  src/components/MAPI/apps/ClusterDetailAppListWidgetVersionInspector.tsx
  src/components/MAPI/apps/ClusterDetailApps.tsx
  src/components/MAPI/apps/ClusterDetailDefaultApps.tsx
  src/components/MAPI/apps/ClusterDetailIngress.tsx
  src/components/MAPI/apps/ClusterDetailReleaseApps.tsx
  src/components/MAPI/apps/InstallIngressButton.tsx
  src/components/MAPI/apps/__tests__/ClusterDetailAppListItem.tsx
  src/components/MAPI/apps/__tests__/ClusterDetailAppListWidgetConfiguration.tsx
  src/components/MAPI/apps/__tests__/ClusterDetailAppListWidgetUninstall.tsx
  src/components/MAPI/apps/__tests__/utils.ts
  src/components/MAPI/apps/utils.ts
  src/components/MAPI/clusters/ClusterDetail/index.tsx
  src/components/MAPI/clusters/GettingStarted/GettingStartedInstallIngress.tsx
  src/components/MAPI/clusters/GettingStarted/index.tsx
  src/components/UI/Display/MAPI/clusters/GettingStarted/GettingStartedInstallIngress.tsx
Labels: kind/refactor

#3744 Fix Tabs component in Storybook
  src/components/UI/Display/Tabs/stories/Simple.tsx
  src/components/UI/Display/Tabs/stories/Tabs.stories.mdx
  src/components/UI/Display/Tabs/stories/Tabs.stories.tsx
Labels: kind/bug

#3745 Update CLI guide for listing installed apps
  src/components/MAPI/apps/ClusterDetailApps.tsx
  src/components/MAPI/clusters/guides/ListAppsGuide.tsx
Labels: kind/ux-enhancement

#3749 Support displaying app installation status for app resources in organization namespaces
  src/components/MAPI/apps/utils.ts
Labels: kind/bug

#3748 Fix displaying app's catalog name and versions info for users with limited permissions
  src/components/MAPI/apps/ClusterDetailAppListItem.tsx
  src/components/MAPI/apps/ClusterDetailAppListWidgetCatalog.tsx
  src/components/MAPI/apps/ClusterDetailAppListWidgetVersionInspector.tsx
  src/components/MAPI/apps/ClusterDetailWidgetApps.tsx
  src/components/MAPI/apps/__tests__/ClusterDetailAppListItem.tsx
  src/components/MAPI/apps/__tests__/ClusterDetailAppListWidgetCatalog.tsx
  src/components/MAPI/apps/__tests__/ClusterDetailAppListWidgetVersionInspector.tsx
  src/components/MAPI/apps/__tests__/ClusterDetailWidgetApps.tsx
  src/components/MAPI/apps/utils.ts
  src/components/UI/Display/MAPI/apps/AppVersionInspectorOption.tsx
Labels: kind/bug

#3756 Protection of GitOps managed resources
  src/components/MAPI/apps/ClusterDetailAppListItem.tsx
  src/components/MAPI/apps/__tests__/ClusterDetailAppListItem.tsx
  src/components/MAPI/clusters/ClusterDetail/ClusterDetailOverview.tsx
  src/components/MAPI/clusters/ClusterDetail/ClusterDetailWidgetLabels.tsx
  src/components/MAPI/clusters/ClusterDetail/__tests__/index.tsx
  src/components/MAPI/clusters/ClusterDetail/index.tsx
  src/components/MAPI/clusters/ClusterList/ClusterListItemReleaseInfo.tsx
  src/components/MAPI/clusters/ClusterList/ClusterListItemVersionsInfo.tsx
  src/components/MAPI/clusters/ClusterList/__tests__/ClusterListItem.tsx
  src/components/MAPI/organizations/OrganizationDetail.tsx
  src/components/MAPI/organizations/OrganizationDetailGeneral/__tests__/index.tsx
  src/components/MAPI/organizations/OrganizationDetailGeneral/index.tsx
  src/components/MAPI/utils.ts
  src/components/MAPI/workernodes/WorkerNodesNodePoolItem.tsx
  src/components/MAPI/workernodes/__tests__/WorkerNodesNodePoolItem.tsx
  src/components/UI/Display/MAPI/GitOpsManaged/GitOpsManagedNote.tsx
  src/components/UI/Display/MAPI/clusters/ClusterList/ClusterListItemMainInfo.tsx
  src/components/UI/Display/Organizations/OrganizationDetailPage.tsx
  src/model/constants/docs.ts
  src/model/constants/index.ts
Labels: kind/feature, kind/ux-enhancement

#3765 Change web UI release notes link
  src/components/Footer/FooterUtils.tsx
Labels: kind/change
