Repository giantswarm/happa, pull requests merged in 2022-11, with the labels that each got.

#3843 Generate client functions for MAPI resources
  package.json
  scripts/generate/getCRD.ts
  scripts/generate/getMapiResourcesList.ts
  scripts/generate/getTypes.ts
  scripts/generate/index.ts
  scripts/generate/mapi-resources.yaml
  scripts/generate/templates.ts
  scripts/generate/write.ts
  scripts/generateTypes/index.ts
  scripts/generateTypes/writeTypes.ts
  src/model/services/mapi/capav1beta1/getAWSCluster.ts
  src/model/services/mapi/capav1beta1/getAWSClusterRoleIdentity.ts
  src/model/services/mapi/capav1beta1/getAWSMachinePool.ts
  src/model/services/mapi/capav1beta1/getAWSMachinePoolList.ts
  src/model/services/mapi/capav1beta1/getAWSMachineTemplate.ts
  src/model/services/mapi/capav1beta1/getAWSMachineTemplateList.ts
  src/model/services/mapi/capgv1beta1/getGCPCluster.ts
  src/model/services/mapi/capgv1beta1/getGCPMachineTemplate.ts
  src/model/services/mapi/capgv1beta1/getGCPMachineTemplateList.ts
Labels: kind/dev-change

#3844 Add documentation for how to generate MAPI TS types and client functions
  src/stories/GeneratingMapiTypesClientFunctions.stories.mdx
Labels: kind/dev-change

#3856 Update cluster creation message for GCP
  src/components/MAPI/clusters/ClusterDetail/__tests__/index.tsx
  src/components/MAPI/clusters/ClusterDetail/index.tsx
  src/components/MAPI/clusters/ClusterList/ClusterListItem.tsx
  src/components/MAPI/clusters/ClusterStatus/ClusterStatus.tsx
  src/components/MAPI/clusters/CreateCluster/index.tsx
  src/components/MAPI/clusters/hooks/useClusterStatus.ts
  src/components/MAPI/clusters/utils.ts
  src/components/MAPI/releases/ClusterDetailWidgetRelease.tsx
Labels: kind/ux-enhancement

#3863 Provide link to catalog and catalog item for installed apps
  src/components/MAPI/apps/AppList/index.tsx
  src/components/MAPI/apps/ClusterDetailAppListItem.tsx
  src/components/MAPI/apps/ClusterDetailAppListWidgetCatalog.tsx
  src/components/MAPI/apps/ClusterDetailAppListWidgetName.tsx
  src/components/MAPI/apps/__tests__/ClusterDetailAppListWidgetCatalog.tsx
  src/components/MAPI/apps/__tests__/ClusterDetailAppListWidgetName.tsx
  src/components/UI/Display/Apps/AppList/CatalogLabel.tsx
Labels: kind/ux-enhancement

#3868 Fix cluster details Ingress tab
  src/components/Cluster/ClusterDetail/Ingress/Instructions.tsx
  src/components/MAPI/apps/ClusterDetailIngress.tsx
  src/components/MAPI/apps/__tests__/ClusterDetailIngress.tsx
  src/components/MAPI/apps/utils.ts
  src/components/MAPI/clusters/ClusterDetail/ClusterDetailWidgetKubernetesAPI.tsx
  src/components/MAPI/clusters/ClusterDetail/__tests__/ClusterDetailWidgetKubernetesAPI.tsx
  src/components/MAPI/clusters/ClusterDetail/index.tsx
  src/components/MAPI/utils.ts
  src/model/services/mapi/capiv1beta1/key.ts
  test/mockHttpCalls/applicationv1alpha1/apps.ts
  test/mockHttpCalls/capiv1beta1/clusters.ts
Labels: kind/refactor

#3875 Remove infrastructure.giantswarm.io/v1alpha2 types and checks
  src/components/MAPI/clusters/ClusterDetail/ClusterDetailWidgetProvider.tsx
  src/components/MAPI/clusters/ClusterDetail/utils.ts
  src/components/MAPI/clusters/CreateCluster/patches.ts
  src/components/MAPI/clusters/utils.ts
  src/components/MAPI/types.ts
  src/components/MAPI/utils.ts
  src/components/MAPI/workernodes/utils.ts
  src/model/services/mapi/infrastructurev1alpha2/index.ts
  src/model/services/mapi/infrastructurev1alpha2/types.ts
Labels: kind/refactor

#3877 Revert "Remove infrastructure.giantswarm.io/v1alpha2 types and checks"
  src/components/MAPI/clusters/ClusterDetail/ClusterDetailWidgetProvider.tsx
  src/components/MAPI/clusters/ClusterDetail/utils.ts
  src/components/MAPI/clusters/CreateCluster/patches.ts
  src/components/MAPI/clusters/utils.ts
  src/components/MAPI/types.ts
  src/components/MAPI/utils.ts
  src/components/MAPI/workernodes/utils.ts
  src/model/services/mapi/infrastructurev1alpha2/index.ts
  src/model/services/mapi/infrastructurev1alpha2/types.ts
Labels: kind/bug

#3882 Display longer cluster names
  src/components/Apps/AppDetail/InstallAppModal/ClusterPicker.tsx
  src/components/MAPI/clusters/ClusterList/ClusterList.tsx
  src/components/MAPI/clusters/ClusterList/ClusterListItem.tsx
  src/components/UI/Display/Cluster/ClusterIDLabel/index.tsx
  src/components/UI/Util/Truncated.tsx
Labels: kind/ux-enhancement

#3883 Improve how we determine when clusters should display "Upgrade available" status
  src/components/MAPI/clusters/hooks/useClusterStatus.ts
  src/components/MAPI/clusters/utils.ts
  src/components/MAPI/releases/ClusterDetailWidgetRelease.tsx
Labels: kind/ux-enhancement

#3915 Delete port number from ingress information
  src/components/MAPI/apps/__tests__/ClusterDetailIngress.tsx
  src/components/MAPI/apps/utils.ts
Labels: kind/bug
