Repository giantswarm/happa, pull requests merged in 2022-08, with the labels that each got.

#3612 Display cluster app and Kubernetes versions information for CAPG
  src/components/MAPI/apps/AppInstallModal.tsx
  src/components/MAPI/clusters/ClusterDetail/ClusterDetailOverview.tsx
  src/components/MAPI/clusters/ClusterDetail/ClusterDetailWidgetVersions.tsx
  src/components/MAPI/clusters/ClusterDetail/ClusterDetailWidgetVersionsLoader.tsx
  src/components/MAPI/clusters/ClusterDetail/__tests__/ClusterDetailOverview.tsx
  src/components/MAPI/clusters/ClusterDetail/__tests__/ClusterDetailWidgetVersions.tsx
  src/components/MAPI/clusters/ClusterDetail/index.tsx
  src/components/MAPI/clusters/ClusterList/ClusterList.tsx
  src/components/MAPI/clusters/ClusterList/ClusterListItem.tsx
  src/components/MAPI/clusters/ClusterList/ClusterListItemNodeInfo.tsx
  src/components/MAPI/clusters/ClusterList/ClusterListItemReleaseInfo.tsx
  src/components/MAPI/clusters/ClusterList/ClusterListItemVersionsInfo.tsx
  src/components/MAPI/clusters/ClusterList/__tests__/ClusterListItem.tsx
  src/components/MAPI/clusters/Clusters.tsx
  src/components/MAPI/clusters/utils.ts
  src/components/MAPI/releases/ClusterDetailReleaseDetailsModal.tsx
  src/components/MAPI/utils.ts
  src/components/UI/Display/Cluster/KubernetesVersionLabel.tsx
  src/components/UI/Display/MAPI/clusters/ClusterDetail/ClusterDetailWidget/__tests__/__snapshots__/index.tsx.snap
  src/components/UI/Display/MAPI/clusters/ClusterDetail/ClusterDetailWidget/index.tsx
  src/components/UI/Display/MAPI/clusters/ClusterList/ClusterListItemMainInfo.tsx
  src/model/constants/index.ts
  src/model/services/mapi/capiv1beta1/key.ts
Labels: kind/refactor

#3628 Fix cluster upgrade modal disclaimer
  src/components/MAPI/releases/ClusterDetailUpgradeModal.tsx
  src/components/MAPI/releases/ClusterDetailWidgetRelease.tsx
  src/components/UI/Display/MAPI/releases/ClusterDetailUpgradeModalDisclaimer.tsx
Labels: kind/bug

#3618 Display app status in collapsed view
  src/components/MAPI/apps/ClusterDetailAppListItemStatus.tsx
  src/components/MAPI/apps/ClusterDetailAppListWidgetStatus.tsx
  src/components/UI/Display/MAPI/apps/ClusterDetailAppStatus/ClusterDetailAppStatus.tsx
  src/components/UI/Display/MAPI/apps/ClusterDetailAppStatus/__tests__/__snapshots__/index.tsx.snap
  src/components/UI/Display/MAPI/apps/ClusterDetailAppStatus/__tests__/index.tsx
  src/components/UI/Display/MAPI/apps/ClusterDetailAppStatus/index.ts
  src/components/UI/Display/MAPI/apps/ClusterDetailAppStatus/stories/ClusterDetailAppListWidget.stories.tsx
  src/components/UI/Display/MAPI/apps/ClusterDetailAppStatus/stories/Predefined.tsx
  src/components/UI/Display/MAPI/apps/ClusterDetailAppStatus/stories/Simple.tsx
  src/model/services/mapi/applicationv1alpha1/key.ts
Labels: kind/ux-enhancement

#3642 Fix login: create SelfSubjectAccessReview in correct namespace
  src/components/__tests__/Layout.tsx
  src/model/stores/organization/actions.tsx
Labels: kind/bug

#3640 Display cluster app and Kubernetes version information in Organizations > General tab
  src/components/MAPI/organizations/OrganizationDetailGeneral/__tests__/index.tsx
  src/components/MAPI/organizations/OrganizationDetailGeneral/index.tsx
  src/components/MAPI/organizations/OrganizationDetailGeneral/utils.ts
  src/components/UI/Display/Organizations/OrganizationDetailPage.tsx
  src/components/UI/Display/Organizations/types.ts
  test/mockHttpCalls/capiv1beta1/clusters.ts
Labels: kind/refactor

#3657 Change cluster preinstalled apps UI
  __tests__/GettingStarted.js
  src/@types/clusters.d.ts
  src/components/Cluster/ClusterDetail/AddNodePool/__tests__/AddNodePool.tsx
  src/components/Cluster/ClusterDetail/ClusterActions.tsx
  src/components/Cluster/ClusterDetail/ClusterApps.tsx
  src/components/Cluster/ClusterDetail/ClusterDetailView.js
  src/components/GettingStarted/GettingStarted.js
  src/components/MAPI/apps/ClusterDetailAppList.tsx
  src/components/MAPI/apps/ClusterDetailAppListItem.tsx
  src/components/MAPI/apps/ClusterDetailAppListItemStatus.tsx
  src/components/MAPI/apps/ClusterDetailAppListWidgetVersion.tsx
  src/components/MAPI/apps/ClusterDetailAppLoadingPlaceholder.tsx
  src/components/MAPI/apps/ClusterDetailApps.tsx
  src/components/MAPI/apps/ClusterDetailReleaseApps.tsx
  src/components/MAPI/apps/ClusterDetailWidgetApps.tsx
  src/components/MAPI/apps/__tests__/ClusterDetailAppListWidgetVersion.tsx
  src/components/MAPI/apps/utils.ts
  src/components/MAPI/clusters/ClusterDetail/ClusterDetailActions.tsx
  src/components/MAPI/clusters/ClusterDetail/index.tsx
  src/components/UI/Display/MAPI/apps/ClusterDetailAppListItemSummary/index.tsx
  src/components/UI/Display/MAPI/apps/ClusterDetailAppListWidget/__tests__/__snapshots__/index.tsx.snap
  src/components/UI/Display/MAPI/apps/ClusterDetailAppListWidget/index.tsx
  src/model/services/mapi/applicationv1alpha1/key.ts
  src/model/stores/cluster/__tests__/utils.ts
  src/model/stores/cluster/utils.ts
Labels: kind/ux-enhancement

#3658 Allow installing app multiple times if `clusterSingleton` restriction is not set on AppCatalogEntry
  src/components/MAPI/apps/AppInstallModal.tsx
  src/components/MAPI/apps/AppList/AppDetail.tsx
  src/components/MAPI/apps/__tests__/AppInstallModal.tsx
Labels: kind/bug

#3650 Display node pool details for CAPG
  src/components/MAPI/utils.ts
  src/components/MAPI/workernodes/ClusterDetailWorkerNodes.tsx
  src/components/MAPI/workernodes/WorkerNodesNodePoolItem.tsx
  src/components/MAPI/workernodes/WorkerNodesNodePoolItemMachineType.tsx
  src/components/MAPI/workernodes/WorkerNodesSpotInstancesAWS.tsx
  src/components/MAPI/workernodes/__tests__/ClusterDetailWorkerNodes.tsx
  src/components/MAPI/workernodes/__tests__/WorkerNodesNodePoolItem.tsx
  src/components/MAPI/workernodes/guides/ListNodePoolsGuide.tsx
  src/components/UI/Display/Cluster/AvailabilityZones/AvailabilityZonesLabel.tsx
  src/components/UI/Display/Cluster/AvailabilityZones/AvailabilityZonesLabels.tsx
  src/components/UI/Display/MAPI/CLIGuide/CLIGuidesList.tsx
  src/components/UI/Display/MAPI/CLIGuide/__tests__/__snapshots__/index.tsx.snap
  src/components/UI/Display/MAPI/CLIGuide/__tests__/index.tsx
  src/components/UI/Display/MAPI/workernodes/styles.tsx
  src/model/services/mapi/capiv1beta1/key.ts
  test/mockHttpCalls/capiv1beta1/machineDeployments.ts
  test/mockHttpCalls/infrastructurev1alpha3/awsMachineDeployments.ts
Labels: kind/refactor

#3659 Refactor how cluster organization is determined
  src/components/MAPI/apps/AppInstallModal.tsx
  src/components/MAPI/apps/utils.ts
  src/components/MAPI/clusters/ClusterDetail/__tests__/ClusterDetailWidgetLabels.tsx
  src/components/MAPI/clusters/ClusterList/ClusterListItem.tsx
  src/components/MAPI/clusters/Clusters.tsx
  src/components/MAPI/clusters/utils.ts
  src/components/MAPI/organizations/OrganizationDetailGeneral/__tests__/index.tsx
  src/components/MAPI/organizations/OrganizationDetailGeneral/index.tsx
  src/components/MAPI/organizations/OrganizationList.tsx
  src/components/MAPI/organizations/__tests__/OrganizationList.tsx
  src/components/MAPI/organizations/utils.ts
  src/components/MAPI/utils.ts
  src/components/MAPI/workernodes/WorkerNodesCreateNodePool.tsx
  src/components/MAPI/workernodes/__tests__/WorkerNodesCreateNodePool.tsx
  src/model/services/mapi/capiv1beta1/key.ts
  src/model/services/mapi/infrastructurev1alpha3/key.ts
  test/mockHttpCalls/capgv1beta1/gcpClusters.ts
  test/mockHttpCalls/capgv1beta1/gcpMachineTemplates.ts
  test/mockHttpCalls/capiv1beta1/clusters.ts
  test/mockHttpCalls/capiv1beta1/machineDeployments.ts
  test/mockHttpCalls/capiv1beta1/machines.ts
Labels: kind/refactor

#3670 Fix default branch in CircleCI badge
  README.md
Labels: kind/dev-change

#3681 App bundles UI and GCP support for cluster apps
  src/components/Cluster/ClusterDetail/ClusterDetailView.js
  src/components/MAPI/apps/ClusterDetailAppList.tsx
  src/components/MAPI/apps/ClusterDetailAppListItem.tsx
  src/components/MAPI/apps/ClusterDetailApps.tsx
  src/components/MAPI/apps/ClusterDetailDefaultApps.tsx
  src/components/MAPI/apps/ClusterDetailReleaseApps.tsx
  src/components/MAPI/apps/ClusterDetailWidgetApps.tsx
  src/components/MAPI/apps/ClusterDetailWidgetAppsLoader.tsx
  src/components/MAPI/apps/__tests__/ClusterDetailWidgetApps.tsx
  src/components/MAPI/apps/utils.ts
  src/components/MAPI/clusters/ClusterDetail/ClusterDetailActions.tsx
  src/components/MAPI/clusters/ClusterDetail/ClusterDetailOverview.tsx
  src/components/MAPI/clusters/ClusterDetail/index.tsx
  src/components/MAPI/organizations/OrganizationDetailGeneral/__tests__/index.tsx
  src/components/MAPI/organizations/OrganizationDetailGeneral/index.tsx
  src/components/MAPI/organizations/OrganizationDetailGeneral/utils.ts
  src/components/MAPI/utils.ts
  src/components/UI/Display/MAPI/apps/ClusterDetailAppListTreeView/index.tsx
  src/components/UI/Display/MAPI/clusters/ClusterDetail/ClusterDetailCounter/index.tsx
  src/components/UI/Display/Organizations/OrganizationDetailPage.tsx
  src/components/UI/Display/Organizations/types.ts
  src/model/services/mapi/applicationv1alpha1/key.ts
  src/styles/stories/Colors/Colors.stories.mdx
  src/styles/theme.ts
Labels: kind/feature, kind/ux-enhancement, kind/change

#3676 Update permissions use cases for GCP
  scripts/permissions-use-cases.yaml
  src/components/MAPI/permissions/Permissions.tsx
  src/components/MAPI/permissions/PermissionsOverview/PermissionsOverview.tsx
  src/components/MAPI/permissions/PermissionsOverview/__tests__/PermissionsOverview.tsx
  src/components/MAPI/permissions/useUseCasesPermissions.ts
  src/components/MAPI/permissions/utils.ts
Labels: kind/refactor
