Repository giantswarm/happa, pull requests merged in 2022-12, with the labels that each got.

#3922 Only build fe docs when creating tags
  .circleci/config.yml
Labels: kind/dev-change

#3905 Add support for app bundles installation
  __tests__/Apps.js
  src/components/Apps/AppDetail/InstallAppModal/InstallAppForm.tsx
  src/components/MAPI/apps/AppInstallModal.tsx
  src/components/MAPI/apps/__tests__/AppInstallModal.tsx
  src/components/MAPI/apps/utils.ts
  src/model/services/mapi/applicationv1alpha1/key.ts
  test/mockHttpCalls/applicationv1alpha1/appcatalogentries.ts
  test/mockHttpCalls/applicationv1alpha1/apps.ts
Labels: kind/feature, kind/ux-enhancement

#3867 Add basic chart tests
  .ats/main.yaml
  .circleci/config.yml
  .gitignore
  ats/Pipfile
  ats/Pipfile.lock
  ats/kind_config.yaml
  ats/test-values.yaml
  ats/test_basic_cluster.py
Labels: kind/dev-change

#3961 add-custom-cluster-issuer
  helm/happa/templates/happaapi-ingress.yaml
  helm/happa/templates/ingress.yaml
  helm/happa/values.yaml
Labels: kind/dev-change

#3952 Customise array and object fields
  src/components/MAPI/clusters/CreateCluster/ClusterNameWidget.tsx
  src/components/UI/Inputs/NumberPicker/index.tsx
  src/components/UI/JSONSchemaForm/ArrayFieldTemplate/index.tsx
  src/components/UI/JSONSchemaForm/BaseInputTemplate/index.tsx
  src/components/UI/JSONSchemaForm/FieldTemplate/index.tsx
  src/components/UI/JSONSchemaForm/ObjectFieldTemplate/index.tsx
  src/components/UI/JSONSchemaForm/SelectWidget/index.tsx
  src/components/UI/JSONSchemaForm/UpDownWidget/index.tsx
  src/components/UI/JSONSchemaForm/index.tsx
Labels: kind/ux-enhancement

#3969 Add form fields descriptions
  src/components/MAPI/clusters/CreateCluster/ClusterNameWidget.tsx
  src/components/UI/JSONSchemaForm/ArrayFieldTemplate/index.tsx
  src/components/UI/JSONSchemaForm/BaseInputTemplate/index.tsx
  src/components/UI/JSONSchemaForm/CheckboxWidget/index.tsx
  src/components/UI/JSONSchemaForm/FieldTemplate/index.tsx
  src/components/UI/JSONSchemaForm/ObjectFieldTemplate/index.tsx
  src/components/UI/JSONSchemaForm/SelectWidget/index.tsx
  src/components/UI/JSONSchemaForm/ToggleWidget/index.tsx
Labels: kind/ux-enhancement

#3973 Cluster app form fields suggestions
  src/components/UI/JSONSchemaForm/BaseInputTemplate/index.tsx
  src/components/UI/JSONSchemaForm/SelectWidget/index.tsx
Labels: kind/ux-enhancement

#3974 Allow to delete a group prefix in permissions overview
  src/components/MAPI/permissions/SubjectForm/SubjectForm.tsx
Labels: kind/change
