Repository giantswarm/happa, pull requests merged in 2022-01, with the labels that each got.

#3059 Fix cluster deletion for KVM
  src/components/MAPI/clusters/ClusterDetail/ClusterDetailActions.tsx
  src/components/UI/Display/MAPI/clusters/ClusterDetail/ClusterDetailDeleteAction.tsx
  src/components/UI/Display/MAPI/clusters/ClusterDetail/__tests__/ClusterDetailDeleteAction.tsx
Labels: kind/bug

#3044 Make cluster details overview aware of permissions for a read-only user
  src/components/Cluster/ClusterDetail/ClusterLabels/ClusterLabels.tsx
  src/components/Cluster/ClusterDetail/ClusterLabels/DeleteLabelButton.tsx
  src/components/Cluster/ClusterDetail/ClusterLabels/EditLabelTooltip.tsx
  src/components/MAPI/apps/ClusterDetailWidgetApps.tsx
  src/components/MAPI/apps/__tests__/ClusterDetailWidgetApps.tsx
  src/components/MAPI/apps/permissions/usePermissionsForAppCatalogEntries.ts
  src/components/MAPI/apps/permissions/usePermissionsForApps.ts
  src/components/MAPI/apps/permissions/usePermissionsForCatalogs.ts
  src/components/MAPI/apps/utils.ts
  src/components/MAPI/clusters/ClusterDetail/ClusterDetailOverview.tsx
  src/components/MAPI/clusters/ClusterDetail/ClusterDetailWidgetControlPlaneNodes.tsx
  src/components/MAPI/clusters/ClusterDetail/ClusterDetailWidgetKubernetesAPI.tsx
  src/components/MAPI/clusters/ClusterDetail/ClusterDetailWidgetLabels.tsx
  src/components/MAPI/clusters/ClusterDetail/__tests__/ClusterDetailWidgetControlPlaneNodes.tsx
  src/components/MAPI/clusters/ClusterDetail/__tests__/ClusterDetailWidgetKubernetesAPI.tsx
  src/components/MAPI/clusters/ClusterDetail/__tests__/ClusterDetailWidgetLabels.tsx
  src/components/MAPI/clusters/ClusterDetail/__tests__/index.tsx
  src/components/MAPI/clusters/ClusterDetail/index.tsx
  src/components/MAPI/clusters/ClusterList/ClusterListItem.tsx
  src/components/MAPI/clusters/ClusterList/__tests__/ClusterListItem.tsx
  src/components/MAPI/clusters/guides/SetClusterLabelsGuide.tsx
  src/components/MAPI/keypairs/ClusterDetailWidgetKeyPairs.tsx
  src/components/MAPI/keypairs/__tests__/ClusterDetailWidgetKeyPairs.tsx
  src/components/MAPI/organizations/OrganizationDetailGeneral/__tests__/index.tsx
  src/components/MAPI/releases/ClusterDetailReleaseDetailsModal.tsx
  src/components/MAPI/releases/ClusterDetailWidgetRelease.tsx
  src/components/MAPI/releases/__tests__/ClusterDetailWidgetRelease.tsx
  src/components/MAPI/utils.ts
  src/components/MAPI/workernodes/ClusterDetailWidgetWorkerNodes.tsx
  src/components/MAPI/workernodes/__tests__/ClusterDetailWidgetWorkerNodes.tsx
  src/components/MAPI/workernodes/__tests__/WorkerNodesCreateNodePool.tsx
  src/components/Modals/ReleaseDetailsModal/ReleaseDetailsModalUpgradeOptionsVersion.tsx
  src/components/UI/Display/Cluster/ClusterLabels/DeleteLabelButton.tsx
  src/components/UI/Display/MAPI/releases/ClusterDetailReleaseDetailsUpgradeOptions.tsx
  src/components/UI/Display/ValueLabel.tsx
  src/components/UI/Inputs/ViewEditName.tsx
Labels: kind/refactor

#3045 Use normalized app version when comparing app versions
  src/components/MAPI/apps/ClusterDetailAppListItem.tsx
  src/components/MAPI/apps/ClusterDetailAppListItemStatus.tsx
  src/components/MAPI/apps/ClusterDetailAppListWidgetVersion.tsx
  src/components/MAPI/apps/ClusterDetailAppListWidgetVersionInspector.tsx
  src/components/MAPI/apps/utils.ts
Labels: kind/bug

#3070 Make cluster details > apps tab permissions aware
  src/components/MAPI/apps/AppValueConfigurator.tsx
  src/components/MAPI/apps/ClusterDetailAppList.tsx
  src/components/MAPI/apps/ClusterDetailAppListItem.tsx
  src/components/MAPI/apps/ClusterDetailAppListItemStatus.tsx
  src/components/MAPI/apps/ClusterDetailAppListWidgetCatalog.tsx
  src/components/MAPI/apps/ClusterDetailAppListWidgetConfiguration.tsx
  src/components/MAPI/apps/ClusterDetailAppListWidgetUninstall.tsx
  src/components/MAPI/apps/ClusterDetailAppListWidgetVersion.tsx
  src/components/MAPI/apps/ClusterDetailAppListWidgetVersionInspector.tsx
  src/components/MAPI/apps/ClusterDetailApps.tsx
  src/components/MAPI/apps/__tests__/ClusterDetailAppListItem.tsx
  src/components/MAPI/apps/__tests__/ClusterDetailAppListItemStatus.tsx
  src/components/MAPI/apps/__tests__/ClusterDetailAppListWidgetCatalog.tsx
  src/components/MAPI/apps/__tests__/ClusterDetailAppListWidgetConfiguration.tsx
  src/components/MAPI/apps/__tests__/ClusterDetailAppListWidgetUninstall.tsx
  src/components/MAPI/apps/__tests__/ClusterDetailAppListWidgetVersion.tsx
  src/components/MAPI/apps/__tests__/ClusterDetailWidgetApps.tsx
  src/components/MAPI/apps/guides/ConfigureAppGuide.tsx
  src/components/MAPI/apps/guides/UninstallAppGuide.tsx
  src/components/MAPI/apps/guides/UpdateAppGuide.tsx
  src/components/MAPI/apps/permissions/types.ts
  src/components/MAPI/apps/permissions/usePermissionsForAppConfigs.ts
  src/components/MAPI/apps/permissions/usePermissionsForApps.ts
  src/components/UI/Controls/Button/__tests__/__snapshots__/index.tsx.snap
  src/components/UI/Controls/Button/index.tsx
  src/components/UI/Display/Tooltip/TooltipContainer.tsx
Labels: kind/refactor

#3077 Make cluster details > ingress tab permissions aware
  src/components/MAPI/apps/ClusterDetailApps.tsx
  src/components/MAPI/apps/ClusterDetailIngress.tsx
  src/components/MAPI/apps/InstallIngressButton.tsx
  src/components/MAPI/apps/permissions/usePermissionsForAppConfigs.ts
  src/components/MAPI/apps/permissions/usePermissionsForApps.ts
  src/components/MAPI/apps/utils.ts
  src/model/constants/index.ts
  src/model/services/mapi/applicationv1alpha1/key.ts
Labels: kind/refactor

#3082 Fix upgradable apps count in cluster details overview > apps widget
  src/components/MAPI/apps/utils.ts
Labels: kind/bug

#3083 Move headers set in ingress configuration snippets to nginx.conf
  Dockerfile
  helm/happa/templates/ingress.yaml
  nginx/headers.conf
  nginx/nginx.conf
Labels: kind/dev-change

#3089 Push to openstack-app-collection
  .circleci/config.yml
Labels: kind/dev-change

#3088 Make organization overview aware of permissions for a read-only user
  src/components/MAPI/organizations/OrganizationList.tsx
  src/components/MAPI/organizations/OrganizationListCreateOrg.tsx
  src/components/MAPI/organizations/__tests__/OrganizationList.tsx
  src/components/MAPI/organizations/guides/CreateOrganizationGuide.tsx
  src/components/MAPI/organizations/permissions/usePermissionsForOrganizations.ts
  src/components/MAPI/organizations/utils.ts
  src/model/stores/organization/actions.tsx
  test/mockHttpCalls/authorizationv1/selfSubjectAccessReviews.ts
Labels: kind/refactor

#3093 Make organization details > general tab aware of permissions for a read-only user
  src/components/MAPI/organizations/OrganizationDetailDelete.tsx
  src/components/MAPI/organizations/OrganizationDetailGeneral/__tests__/index.tsx
  src/components/MAPI/organizations/OrganizationDetailGeneral/index.tsx
  src/components/MAPI/organizations/OrganizationDetailGeneral/utils.ts
  src/components/MAPI/organizations/OrganizationList.tsx
  src/components/MAPI/organizations/guides/DeleteOrganizationGuide.tsx
  src/components/MAPI/organizations/permissions/usePermissionsForOrganizations.ts
  src/components/MAPI/permissions/types.ts
  src/components/UI/Display/Organizations/OrganizationDetailPage.tsx
Labels: kind/refactor

#3101 Make app catalogs page permission-aware
  src/components/MAPI/apps/AppList/__tests__/index.tsx
  src/components/MAPI/apps/AppList/index.tsx
  src/components/MAPI/apps/utils.ts
  test/mockHttpCalls/authorizationv1/selfSubjectAccessReviews.ts
Labels: kind/refactor

#3108 Add a 'pipeline' tag to Sentry events, to distinguish stable/testing
  helm/happa/templates/configmap.yaml
  scripts/getConfigurationValues.ts
  src/@types/global.d.ts
  src/components/index.tsx
  src/index.ejs
  src/utils/errors/SentryErrorNotifier.ts
Labels: kind/dev-change

#3110 Avoid reporting invalid invite token errors to Sentry
  src/components/SignUp/SignUp.tsx
Labels: kind/dev-change

#3118 Make organizations > access control permission-aware (part 2)
  src/components/MAPI/organizations/AccessControl/AccessControlRoleSubjects.tsx
  src/components/MAPI/organizations/AccessControl/guides/BindRolesToSubjectsGuide.tsx
  src/components/MAPI/organizations/AccessControl/index.tsx
  src/components/MAPI/organizations/AccessControl/utils.ts
  src/components/UI/Display/MAPI/AccessControl/AccessControlRoleDetail.tsx
  src/components/UI/Display/MAPI/AccessControl/types.ts
Labels: kind/refactor

#3109 Make app details aware of permissions for a read-only user
  src/components/MAPI/apps/AppInstallModal.tsx
  src/components/MAPI/apps/AppList/AppDetail.tsx
  src/components/MAPI/apps/AppList/__tests__/AppDetail.tsx
  src/components/MAPI/apps/AppList/index.tsx
  src/components/MAPI/apps/__tests__/AppInstallModal.tsx
  src/components/MAPI/apps/guides/InstallAppGuide.tsx
  src/components/MAPI/apps/permissions/usePermissionsForAppConfigs.ts
  src/components/MAPI/apps/utils.ts
  src/components/UI/Controls/Button/__tests__/__snapshots__/index.tsx.snap
  src/components/UI/Controls/Button/index.tsx
Labels: kind/refactor

#3124 Improve handling of fetch errors during login
  src/model/clients/HttpClient.ts
  src/model/stores/batchActions.ts
Labels: kind/ux-enhancement

#3130 Fix non-admin users not able to see Playground catalog
  src/components/MAPI/apps/utils.ts
Labels: kind/bug

#3134 Add documentation for permissions
  src/stories/Permissions.stories.mdx
  src/stories/PermissionsForUserActions.stories.mdx
Labels: kind/dev-change

#3137 Fix accessing method on undefined value
  src/components/MAPI/apps/ClusterDetailApps.tsx
Labels: kind/bug

#3141 Improve app uninstallation confirmation info
  src/components/MAPI/apps/ClusterDetailAppListWidgetUninstall.tsx
Labels: kind/ux-enhancement

#3148 Clear cached data from fetch responses when impersonation is set/cleared
  src/components/Auth/MAPI/MapiUnauthorized.tsx
  src/components/MAPI/Experiments.tsx
Labels: kind/dev-change
