Repository giantswarm/happa, pull requests merged in 2022-10, with the labels that each got.

#3766 Add instance types info for CAPA
  helm/happa/templates/configmap.yaml
  helm/happa/values.yaml
  scripts/getConfigurationValues.ts
Labels: kind/refactor

#3776 Add support for fetching CAPA cluster resources
  src/components/MAPI/clusters/permissions/usePermissionsForClusters.ts
  src/components/MAPI/utils.ts
  src/model/constants/providers.ts
  test/mockHttpCalls/capav1beta1/awsClusters.ts
  test/mockHttpCalls/capav1beta1/index.ts
  test/mockHttpCalls/capiv1beta1/clusters.ts
Labels: kind/refactor

#3781 Display details for CAPA clusters
  src/components/MAPI/clusters/ClusterDetail/__tests__/ClusterDetailWidgetVersions.tsx
  src/components/MAPI/clusters/ClusterDetail/__tests__/index.tsx
  src/components/MAPI/clusters/ClusterList/__tests__/ClusterListItem.tsx
  src/components/MAPI/clusters/utils.ts
  src/components/MAPI/organizations/OrganizationDetailGeneral/__tests__/index.tsx
  src/components/MAPI/utils.ts
  test/mockHttpCalls/capiv1beta1/clusters.ts
Labels: kind/refactor

#3787 Display node pool details and stats for CAPA
  jest.config.ts
  src/components/MAPI/clusters/utils.ts
  src/components/MAPI/organizations/OrganizationDetailGeneral/__tests__/index.tsx
  src/components/MAPI/organizations/OrganizationDetailGeneral/utils.ts
  src/components/MAPI/utils.ts
  src/components/MAPI/workernodes/ClusterDetailWorkerNodes.tsx
  src/components/MAPI/workernodes/WorkerNodesNodePoolItemMachineType.tsx
  src/components/MAPI/workernodes/__tests__/ClusterDetailWidgetWorkerNodes.tsx
  src/components/MAPI/workernodes/__tests__/ClusterDetailWorkerNodes.tsx
  src/components/MAPI/workernodes/__tests__/WorkerNodesNodePoolItem.tsx
  src/components/MAPI/workernodes/guides/ListNodePoolsGuide.tsx
  src/components/MAPI/workernodes/permissions/usePermissionsForNodePools.ts
  test/mockHttpCalls/capav1beta1/awsMachinePools.ts
  test/mockHttpCalls/capav1beta1/index.ts
  test/mockHttpCalls/capiv1beta1/machinePools.ts
Labels: kind/refactor

#3798 Fix YAMLException error parsing for app installation
  src/components/Apps/AppDetail/InstallAppModal/InstallAppForm.tsx
  src/components/Apps/AppDetail/InstallAppModal/InstallAppModal.tsx
  src/components/MAPI/apps/AppInstallModal.tsx
  src/components/MAPI/apps/utils.ts
  src/components/UI/Inputs/FileInput/index.tsx
Labels: kind/bug

#3794 Display CAPA provider info
  src/components/MAPI/clusters/ClusterDetail/ClusterDetailOverview.tsx
  src/components/MAPI/clusters/ClusterDetail/ClusterDetailWidgetProvider.tsx
  src/components/MAPI/clusters/ClusterDetail/ClusterDetailWidgetProviderAWS.tsx
  src/components/MAPI/clusters/ClusterDetail/ClusterDetailWidgetProviderAzure.tsx
  src/components/MAPI/clusters/ClusterDetail/ClusterDetailWidgetProviderCAPA.tsx
  src/components/MAPI/clusters/ClusterDetail/ClusterDetailWidgetProviderCAPG.tsx
  src/components/MAPI/clusters/ClusterDetail/ClusterDetailWidgetProviderLoader.tsx
  src/components/MAPI/clusters/ClusterDetail/__tests__/ClusterDetailWidgetProvider.tsx
  src/components/MAPI/clusters/permissions/usePermissionsForAWSClusterRoleIdentities.ts
  src/components/MAPI/utils.ts
  src/model/services/mapi/capav1beta1/getAWSClusterRoleIdentity.ts
  src/model/services/mapi/capav1beta1/index.ts
  src/model/services/mapi/capav1beta1/types.ts
  test/mockHttpCalls/capav1beta1/awsClusterRoleIdentities.ts
  test/mockHttpCalls/capav1beta1/index.ts
Labels: kind/refactor

#3800 Support displaying installed apps for CAPA
  src/model/services/mapi/applicationv1alpha1/key.ts
Labels: kind/refactor

#3802 Display control plane nodes info for CAPA
  src/components/MAPI/clusters/ClusterDetail/__tests__/ClusterDetailWidgetControlPlaneNodes.tsx
  src/components/MAPI/clusters/permissions/usePermissionsForCPNodes.ts
  src/components/MAPI/organizations/OrganizationDetailGeneral/utils.ts
  src/components/MAPI/utils.ts
  test/mockHttpCalls/capav1beta1/awsMachineTemplates.ts
  test/mockHttpCalls/capav1beta1/index.ts
  test/mockHttpCalls/capiv1beta1/machines.ts
Labels: kind/refactor

#3806 Adapt permissions overview for CAPA
  scripts/permissions-use-cases.yaml
  src/components/MAPI/permissions/PermissionsOverview/__tests__/PermissionsOverview.tsx
  src/components/MAPI/permissions/utils.ts
Labels: kind/refactor, kind/change

#3814 Display node pool instance distribution details for CAPA
  src/components/MAPI/utils.ts
  src/components/MAPI/workernodes/ClusterDetailWorkerNodes.tsx
  src/components/MAPI/workernodes/WorkerNodesSpotInstancesCAPA.tsx
  src/components/MAPI/workernodes/__tests__/WorkerNodesNodePoolItem.tsx
  src/model/services/mapi/capav1beta1/types.ts
  test/mockHttpCalls/capav1beta1/awsMachinePools.ts
Labels: kind/refactor

#3818 Tests for apps resources in organization namespaces
  src/components/MAPI/apps/ClusterDetailWidgetApps.tsx
  src/components/MAPI/apps/__tests__/ClusterDetailAppList.tsx
  src/components/MAPI/apps/__tests__/ClusterDetailAppListItem.tsx
  src/components/MAPI/apps/__tests__/ClusterDetailAppListItemStatus.tsx
  src/components/MAPI/apps/__tests__/ClusterDetailAppListWidgetCatalog.tsx
  src/components/MAPI/apps/__tests__/ClusterDetailAppListWidgetConfiguration.tsx
  src/components/MAPI/apps/__tests__/ClusterDetailAppListWidgetInstalledAs.tsx
  src/components/MAPI/apps/__tests__/ClusterDetailAppListWidgetName.tsx
  src/components/MAPI/apps/__tests__/ClusterDetailAppListWidgetNamespace.tsx
  src/components/MAPI/apps/__tests__/ClusterDetailAppListWidgetStatus.tsx
  src/components/MAPI/apps/__tests__/ClusterDetailAppListWidgetUninstall.tsx
  src/components/MAPI/apps/__tests__/ClusterDetailAppListWidgetVersion.tsx
  src/components/MAPI/apps/__tests__/ClusterDetailAppListWidgetVersionInspector.tsx
  src/components/MAPI/apps/__tests__/ClusterDetailApps.tsx
  src/components/MAPI/apps/__tests__/ClusterDetailWidgetApps.tsx
  test/mockHttpCalls/applicationv1alpha1/app.ts
  test/mockHttpCalls/applicationv1alpha1/apps.ts
  test/mockHttpCalls/applicationv1alpha1/index.ts
Labels: kind/refactor

#3815 Allow specifying providers for permissions use cases and permissions rules
  jest.config.ts
  scripts/permissions-use-cases.yaml
  src/components/MAPI/permissions/PermissionsOverview/PermissionsOverview.tsx
  src/components/MAPI/permissions/PermissionsOverview/__tests__/PermissionsOverview.tsx
  src/components/MAPI/permissions/__tests__/utils.ts
  src/components/MAPI/permissions/types.ts
  src/components/MAPI/permissions/utils.ts
  src/stories/UseCaseDefinitionYAML.stories.mdx
Labels: kind/refactor, kind/dev-change

#3819 Fix bug in cluster deletion confirmation form
  src/components/UI/Display/MAPI/clusters/ClusterDetail/ClusterDetailDeleteAction.tsx
  src/components/UI/Display/MAPI/clusters/ClusterDetail/__tests__/ClusterDetailDeleteAction.tsx
Labels: kind/bug

#3822 Generate TS types for MAPI resources from CRDs
  package.json
  scripts/generateTypes/getMapiResourcesList.ts
  scripts/generateTypes/getTypesForResource.ts
  scripts/generateTypes/index.ts
  scripts/generateTypes/mapi-resources.yaml
  scripts/generateTypes/writeTypes.ts
  scripts/utils.ts
  src/model/services/mapi/capav1beta1/types.ts
  src/model/services/mapi/capgv1beta1/types.ts
  yarn.lock
Labels: kind/dev-change

#3840 Fix dropdown elements being underlined
  src/components/UI/Controls/DropdownMenu.tsx
Labels: kind/ux-enhancement

#3842 Align style of keywords and cluster labels
  src/components/UI/Display/Apps/AppDetailNew/AppDetailPage.tsx
Labels: kind/ux-enhancement
