Repository giantswarm/happa, pull requests merged in 2022-06, with the labels that each got.

#3505 Support node pools for Azure release v17.1.0
  src/components/MAPI/organizations/OrganizationDetailGeneral/__tests__/index.tsx
  src/components/MAPI/utils.ts
  src/components/MAPI/workernodes/ClusterDetailWorkerNodes.tsx
  src/components/MAPI/workernodes/WorkerNodesCreateNodePool.tsx
  src/components/MAPI/workernodes/__tests__/ClusterDetailWidgetWorkerNodes.tsx
  src/components/MAPI/workernodes/__tests__/ClusterDetailWorkerNodes.tsx
  src/components/MAPI/workernodes/__tests__/WorkerNodesNodePoolItem.tsx
  src/components/MAPI/workernodes/guides/DeleteNodePoolGuide.tsx
  src/components/MAPI/workernodes/guides/ModifyNodePoolGuide.tsx
  src/components/MAPI/workernodes/utils.ts
  src/model/constants/index.ts
  src/model/services/mapi/capiv1alpha3/exp/types.ts
  src/model/services/mapi/capiv1beta1/key.ts
  src/model/services/mapi/capzv1alpha3/exp/types.ts
  test/mockHttpCalls/capiv1alpha3/exp/machinePools.ts
  test/mockHttpCalls/capiv1beta1/clusters.ts
  test/mockHttpCalls/capiv1beta1/index.ts
  test/mockHttpCalls/capiv1beta1/machinePools.ts
  test/mockHttpCalls/capzv1alpha3/exp/azureMachinePools.ts
  test/mockHttpCalls/capzv1beta1/azureClusters.ts
  test/mockHttpCalls/capzv1beta1/azureMachinePools.ts
  test/mockHttpCalls/capzv1beta1/index.ts
  test/mockHttpCalls/gscorev1alpha1/sparks.ts
  test/mockHttpCalls/releasev1alpha1/releases.ts
Labels: kind/refactor

#3494 Future-proof Catalog CR by adding .spec.repositories
  src/model/services/mapi/applicationv1alpha1/types.ts
  test/mockHttpCalls/applicationv1alpha1/appcatalogs.ts
Labels: kind/dev-change

#3517 Fix node pool creation for Azure: Spark not created
  src/components/MAPI/workernodes/WorkerNodesCreateNodePool.tsx
  src/components/MAPI/workernodes/utils.ts
Labels: kind/bug

#3536 Make default request timeout configurable
  helm/happa/templates/configmap.yaml
  helm/happa/values.yaml
Labels: kind/dev-change

#3534 Synchronize selected chart version in app install form and app details page
  src/components/Apps/AppDetail/AppDetail.tsx
  src/components/Apps/AppDetail/InstallAppModal/InstallAppModal.tsx
  src/components/MAPI/apps/AppInstallModal.tsx
  src/components/MAPI/apps/AppList/AppDetail.tsx
  src/components/MAPI/apps/__tests__/AppInstallModal.tsx
Labels: kind/change

#3547 Sort ConfigMap options
  helm/happa/templates/configmap.yaml
Labels: kind/refactor

#3546 Add "Use web UI" use case to permissions overview
  src/components/MAPI/permissions/PermissionsOverview/PermissionsOverview.tsx
  src/components/MAPI/permissions/PermissionsOverview/__tests__/PermissionsOverview.tsx
  src/components/MAPI/permissions/guides/InspectPermissionsGuide.tsx
  src/components/MAPI/permissions/utils.ts
Labels: kind/ux-enhancement

#3550 Reduce resource requests and limits for fe-docs.giantswarm.io
  helm/fe-docs/templates/deployment.yaml
Labels: kind/dev-change

#3518 Fix configuring an installed app: object modified error
  src/components/MAPI/apps/AppDetailsModal/AppDetailsModalInitialPane.tsx
  src/components/MAPI/apps/AppDetailsModal/__tests__/index.tsx
  src/components/MAPI/apps/AppDetailsModal/index.tsx
  src/components/MAPI/apps/AppValueConfigurator.tsx
  src/components/MAPI/apps/ClusterDetailApps.tsx
  src/components/MAPI/apps/__tests__/ClusterDetailAppListWidgetConfiguration.tsx
  src/components/MAPI/apps/guides/ConfigureAppGuide.tsx
  src/components/MAPI/apps/utils.ts
  src/model/services/mapi/applicationv1alpha1/index.ts
  src/model/services/mapi/applicationv1alpha1/patchApp.ts
  src/model/services/mapi/generic/patchResource.ts
  src/utils/helpers.ts
Labels: kind/bug
