Repository giantswarm/happa, pull requests merged in 2022-03, with the labels that each got.

#3228 Don't rely on `Rolebinding.subjects` being defined
  src/components/MAPI/organizations/AccessControl/utils.ts
  src/model/services/mapi/rbacv1/types.ts
Labels: kind/bug

#3224 MAPI organizations: don't fetch `Clusters` CRs on KVM installations
  src/components/MAPI/organizations/OrganizationList.tsx
  src/components/MAPI/organizations/__tests__/OrganizationList.tsx
  src/model/stores/cluster/utils.ts
Labels: kind/refactor

#3229 Truncate node pool name
  src/components/MAPI/workernodes/WorkerNodesNodePoolItem.tsx
  src/components/MAPI/workernodes/__tests__/WorkerNodesNodePoolItem.tsx
  src/components/UI/Display/MAPI/workernodes/styles.tsx
Labels: kind/bug

#3240 Align flags used in CLI guides
  src/components/MAPI/apps/guides/InstallAppGuide.tsx
  src/components/MAPI/clusters/guides/CreateClusterGuide.tsx
  src/components/MAPI/clusters/guides/SetClusterLabelsGuide.tsx
  src/components/MAPI/organizations/AccessControl/guides/BindRolesToSubjectsGuide.tsx
  src/components/MAPI/organizations/AccessControl/guides/InspectRoleGuide.tsx
  src/components/MAPI/organizations/AccessControl/guides/ListRolesGuide.tsx
  src/components/MAPI/organizations/guides/CreateOrganizationGuide.tsx
  src/components/MAPI/workernodes/guides/CreateNodePoolGuide.tsx
Labels: kind/refactor

#3242 Update architect-orb
  .circleci/config.yml
Labels: kind/dev-change

#3241 Configure specific reviewers for renovate-bot PRs
  CODEOWNERS
  renovate.json
Labels: kind/dev-change

#3244 Use our fork of oidc-client-js
  package.json
  yarn.lock
Labels: kind/dev-change

#3252 Align managed app catalog label
  src/components/MAPI/apps/ClusterDetailAppListWidgetCatalog.tsx
  src/components/UI/Display/Apps/AppList/CatalogLabel.tsx
Labels: kind/refactor

#3251 access control: improve roles list
  src/components/MAPI/organizations/AccessControl/__tests__/index.tsx
  src/components/UI/Display/MAPI/AccessControl/AccessControlRoleListItem.tsx
  src/components/UI/Display/MAPI/AccessControl/AccessControlSubjectSet.tsx
  src/components/UI/Display/MAPI/AccessControl/AccessControlSubjectSetItem.tsx
  src/components/UI/Display/MAPI/AccessControl/__tests__/AccessControlRoleList.tsx
  src/components/UI/Display/RefreshableLabel.js
Labels: kind/ux-enhancement

#3257 Header visual fixes
  src/components/UI/Controls/Navigation/Hamburger.js
  src/components/UI/Controls/Navigation/MainMenu.js
  src/components/UI/Controls/Navigation/Navigation.js
  src/components/UI/Controls/Navigation/OrganizationDropdown.js
  src/components/UI/Controls/Navigation/UserDropdown.tsx
Labels: kind/ux-enhancement

#3260 Change Select component z-index
  src/components/UI/Inputs/Select/index.tsx
Labels: kind/ux-enhancement

#3262 access control: don't display flash messages on successful role binding events
  src/components/MAPI/organizations/AccessControl/AccessControlRoleSubjects.tsx
  src/components/MAPI/organizations/AccessControl/__tests__/AccessControlRoleSubjects.tsx
  src/components/MAPI/organizations/AccessControl/__tests__/index.tsx
Labels: kind/ux-enhancement

#3264 Align style of scrollbars
  src/components/MAPI/organizations/AccessControl/index.tsx
  src/components/UI/Display/MAPI/AccessControl/AccessControlRoleList.tsx
  src/components/UI/Layout/Modal/index.tsx
  src/styles/index.ts
Labels: kind/ux-enhancement

#3268 Fix extra LOGIN_SUCCESS redux actions
  src/model/stores/main/actions.ts
  src/utils/OAuth2/OAuth2.ts
Labels: kind/bug

#3276 Disable permissions revalidation when stale
  src/components/MAPI/permissions/usePermissions.ts
Labels: kind/bug

#3283 Upgrade @braintree/sanitize-url from 3.1.0 to 6.0.0
  package.json
  yarn.lock
Labels: dependencies

#3282 Improve experimental impersonation experience for staff
  src/components/Auth/MAPI/MapiUnauthorized.tsx
  src/components/MAPI/Experiments.tsx
  src/components/MAPI/apps/AppList/index.tsx
  src/components/MAPI/apps/utils.ts
  src/components/MAPI/clusters/ClusterList/ClusterListItem.tsx
  src/components/MAPI/clusters/CreateCluster/CreateClusterRelease.tsx
  src/components/MAPI/releases/ClusterDetailWidgetRelease.tsx
  src/model/stores/main/actions.ts
  src/model/stores/main/constants.ts
  src/model/stores/main/reducer.ts
  src/model/stores/main/selectors.ts
  src/model/stores/main/types.ts
  test/preloginState.ts
Labels: kind/refactor

#3298 Fix permissions list scrolling
  src/components/UI/Display/MAPI/AccessControl/AccessControlRolePermissions.tsx
Labels: kind/ux-enhancement

#3299 Don't rely on `apiVersion` to distinguish between provider-specific resources
  src/components/MAPI/clusters/ClusterDetail/ClusterDetailWidgetProvider.tsx
  src/components/MAPI/clusters/ClusterDetail/utils.ts
  src/components/MAPI/clusters/CreateCluster/patches.ts
  src/components/MAPI/clusters/utils.ts
  src/components/MAPI/organizations/OrganizationDetailGeneral/utils.ts
  src/components/MAPI/utils.ts
  src/components/MAPI/workernodes/WorkerNodesCreateNodePoolSpotInstances.tsx
  src/components/MAPI/workernodes/WorkerNodesNodePoolItemMachineType.tsx
  src/components/MAPI/workernodes/patches.ts
  src/components/MAPI/workernodes/utils.ts
Labels: kind/refactor
