Repository giantswarm/happa, pull requests merged in 2022-07, with the labels that each got.

#3571 Empty list items type error
  src/model/services/mapi/applicationv1alpha1/getAppCatalogEntryList.ts
  src/model/services/mapi/applicationv1alpha1/getAppList.ts
  src/model/services/mapi/applicationv1alpha1/getCatalogList.ts
  src/model/services/mapi/capiv1alpha3/exp/getMachinePoolList.ts
  src/model/services/mapi/capiv1beta1/getClusterList.ts
  src/model/services/mapi/capiv1beta1/getMachineDeploymentList.ts
  src/model/services/mapi/capiv1beta1/getMachinePoolList.ts
  src/model/services/mapi/capzv1beta1/getAzureMachineList.ts
  src/model/services/mapi/corev1/getSecretList.ts
  src/model/services/mapi/corev1/getServiceAccountList.ts
  src/model/services/mapi/generic/__tests__/getListResource.ts
  src/model/services/mapi/generic/getListResource.ts
  src/model/services/mapi/infrastructurev1alpha3/getAWSClusterList.ts
  src/model/services/mapi/infrastructurev1alpha3/getAWSControlPlaneList.ts
  src/model/services/mapi/infrastructurev1alpha3/getG8sControlPlaneList.ts
  src/model/services/mapi/rbacv1/getClusterRoleBindingList.ts
  src/model/services/mapi/rbacv1/getClusterRoleList.ts
  src/model/services/mapi/rbacv1/getRoleBindingList.ts
  src/model/services/mapi/rbacv1/getRoleList.ts
  src/model/services/mapi/releasev1alpha1/getReleaseList.ts
  src/model/services/mapi/securityv1alpha1/getOrganizationList.ts
Labels: kind/bug

#3574 Fix uploading a file with the same name for configuring an installed app
  src/components/Cluster/ClusterDetail/AppDetailsModal/YAMLFileUpload.tsx
Labels: kind/bug

#3572 Add GCP machine types
  helm/happa/templates/configmap.yaml
  helm/happa/values.yaml
  jest.config.ts
  scripts/getConfigurationValues.ts
  src/@types/clusters.d.ts
  src/@types/global.d.ts
  src/components/MAPI/utils.ts
  src/index.ejs
  src/utils/MapiAuth/makeDefaultConfig.ts
Labels: kind/refactor

#3576 Add support for determining permissions for CAPG resources
  src/components/MAPI/apps/permissions/usePermissionsForClusterApps.ts
  src/components/MAPI/clusters/permissions/usePermissionsForCPNodes.ts
  src/components/MAPI/clusters/permissions/usePermissionsForClusters.ts
  src/components/MAPI/workernodes/permissions/usePermissionsForNodePools.ts
  src/model/constants/providers.ts
Labels: kind/refactor

#3577 Add support for fetching CAPG resources
  src/components/MAPI/utils.ts
  src/model/services/mapi/k8sUrl.ts
Labels: kind/refactor

#3581 CAPG: Display node pools stats
  jest.config.ts
  scripts/getConfigurationValues.ts
  src/components/MAPI/clusters/utils.ts
  src/components/MAPI/organizations/OrganizationDetailGeneral/utils.ts
  src/components/MAPI/utils.ts
  src/components/MAPI/workernodes/ClusterDetailWidgetWorkerNodes.tsx
  src/components/UI/Display/MAPI/clusters/ClusterList/ClusterListItemNodeInfo.tsx
  src/components/UI/Display/Organizations/OrganizationDetailPage.tsx
  src/utils/__tests__/helpers.ts
  src/utils/helpers.ts
Labels: kind/ux-enhancement, kind/refactor

#3587 Display control plane nodes for CAPG
  src/components/MAPI/clusters/ClusterDetail/ClusterDetailWidgetControlPlaneNodes.tsx
  src/components/MAPI/clusters/ClusterDetail/__tests__/ClusterDetailWidgetControlPlaneNodes.tsx
  src/components/MAPI/clusters/ClusterDetail/__tests__/ClusterDetailWidgetProvider.tsx
  src/components/MAPI/clusters/ClusterDetail/utils.ts
  src/components/MAPI/organizations/OrganizationDetailGeneral/__tests__/index.tsx
  src/components/MAPI/organizations/OrganizationDetailGeneral/utils.ts
  src/components/MAPI/utils.ts
  src/components/UI/Display/Cluster/AvailabilityZones/AvailabilityZonesLabel.tsx
  src/components/UI/Display/Cluster/AvailabilityZones/AvailabilityZonesLabels.js
  src/components/UI/Display/Cluster/AvailabilityZones/AvailabilityZonesLabels.tsx
  src/components/UI/Display/Organizations/OrganizationDetailPage.tsx
  src/model/services/mapi/metav1/types.ts
  test/mockHttpCalls/capgv1beta1/gcpMachineTemplates.ts
  test/mockHttpCalls/capgv1beta1/index.ts
  test/mockHttpCalls/capiv1beta1/clusters.ts
  test/mockHttpCalls/capiv1beta1/index.ts
  test/mockHttpCalls/capiv1beta1/machineDeployments.ts
  test/mockHttpCalls/capiv1beta1/machines.ts
  test/mockHttpCalls/infrastructurev1alpha3/awsClusters.ts
  test/mockHttpCalls/infrastructurev1alpha3/awsControlPlanes.ts
  test/mockHttpCalls/infrastructurev1alpha3/awsMachineDeployments.ts
  test/mockHttpCalls/infrastructurev1alpha3/g8sControlPlanes.ts
  test/mockHttpCalls/infrastructurev1alpha3/index.ts
Labels: kind/refactor

#3595 GCP cluster provider info
  src/components/MAPI/clusters/ClusterDetail/ClusterDetailWidgetProvider.tsx
  src/components/MAPI/clusters/ClusterDetail/__tests__/ClusterDetailWidgetProvider.tsx
  src/components/MAPI/organizations/OrganizationDetailGeneral/__tests__/index.tsx
  src/components/MAPI/utils.ts
  test/mockHttpCalls/capgv1beta1/gcpClusters.ts
  test/mockHttpCalls/capgv1beta1/index.ts
  test/mockHttpCalls/capiv1beta1/clusters.ts
Labels: kind/refactor

#3603 Push to gcp app collection
  .circleci/config.yml
Labels: kind/dev-change

#3596 GCP cluster status and description
  src/components/MAPI/clusters/ClusterDetail/__tests__/index.tsx
  src/components/MAPI/clusters/ClusterList/__tests__/ClusterListItem.tsx
  src/components/MAPI/clusters/utils.ts
  src/components/MAPI/utils.ts
  src/model/services/mapi/capiv1beta1/key.ts
  test/mockHttpCalls/infrastructurev1alpha3/awsClusters.ts
Labels: kind/refactor

#3607 Combine the display of multiple CLI guides into one component
  src/components/MAPI/apps/AppList/AppDetail.tsx
  src/components/MAPI/apps/ClusterDetailAppListItem.tsx
  src/components/MAPI/clusters/ClusterDetail/ClusterDetailOverview.tsx
  src/components/MAPI/organizations/AccessControl/index.tsx
  src/components/MAPI/organizations/OrganizationDetailGeneral/index.tsx
  src/components/MAPI/organizations/OrganizationList.tsx
  src/components/MAPI/workernodes/ClusterDetailWorkerNodes.tsx
  src/components/UI/Display/MAPI/CLIGuide/CLIGuidesList.tsx
  src/components/UI/Display/MAPI/CLIGuide/__tests__/__snapshots__/index.tsx.snap
  src/components/UI/Display/MAPI/CLIGuide/__tests__/index.tsx
  src/components/UI/Display/MAPI/CLIGuide/index.tsx
  src/components/UI/Display/MAPI/CLIGuide/stories/CLIGuide.stories.tsx
  src/components/UI/Display/MAPI/CLIGuide/stories/CLIGuidesList.stories.tsx
  src/components/UI/Display/MAPI/CLIGuide/stories/CLIGuidesList.tsx
Labels: kind/ux-enhancement
