Repository giantswarm/happa, pull requests merged in 2022-05, with the labels that each got.

#3403 Fix upgradable apps count calculation in cluster details overview
  src/components/MAPI/apps/utils.ts
Labels: kind/bug

#3391 Display permissions for use cases for the current user
  src/components/Layout.tsx
  src/components/MAPI/permissions/Permissions.tsx
  src/components/MAPI/permissions/PermissionsOverview/PermissionsOverview.tsx
  src/components/MAPI/permissions/PermissionsOverview/PermissionsOverviewGlobal.tsx
  src/components/MAPI/permissions/PermissionsOverview/PermissionsOverviewOrganizations.tsx
  src/components/MAPI/permissions/PermissionsOverview/__tests__/PermissionsOverviewGlobal.tsx
  src/components/MAPI/permissions/PermissionsOverview/__tests__/PermissionsOverviewOrganizations.tsx
  src/components/MAPI/permissions/PermissionsOverview/index.ts
  src/components/MAPI/permissions/__tests__/utils.ts
  src/components/MAPI/permissions/types.ts
  src/components/MAPI/permissions/utils.ts
  src/components/UI/Controls/Navigation/UserDropdown.tsx
  src/components/UI/Display/MAPI/permissions/PermissionsUseCases/PermissionsUseCases.tsx
  src/components/UI/Display/MAPI/permissions/PermissionsUseCases/ScrollableContainer.tsx
  src/components/UI/Display/MAPI/permissions/PermissionsUseCases/StatusesForCategory.tsx
  src/components/UI/Display/MAPI/permissions/PermissionsUseCases/UseCaseLabel.tsx
  src/components/UI/Display/MAPI/permissions/PermissionsUseCases/UseCaseStatus.tsx
  src/components/UI/Display/MAPI/permissions/PermissionsUseCases/UseCasesForCategory.tsx
  src/components/UI/Display/MAPI/permissions/PermissionsUseCases/UseCasesPreloader.tsx
  src/components/UI/Display/MAPI/permissions/PermissionsUseCases/index.ts
  src/model/constants/routes.ts
  src/model/services/mapi/rbacv1/getClusterRole.ts
  src/model/services/mapi/rbacv1/index.ts
  src/utils/helpers.ts
  test/mockHttpCalls/authorizationv1/selfSubjectAccessReviews.ts
Labels: kind/feature

#3429 Get permissions for a user/group
  jest.config.ts
  src/components/MAPI/organizations/AccessControl/utils.ts
  src/components/MAPI/permissions/PermissionsOverview/PermissionsOverview.tsx
  src/components/MAPI/permissions/PermissionsOverview/PermissionsOverviewGlobal.tsx
  src/components/MAPI/permissions/PermissionsOverview/PermissionsOverviewOrganizations.tsx
  src/components/MAPI/permissions/PermissionsOverview/__tests__/PermissionsOverview.tsx
  src/components/MAPI/permissions/PermissionsOverview/__tests__/PermissionsOverviewOrganizations.tsx
  src/components/MAPI/permissions/__tests__/utils.ts
  src/components/MAPI/permissions/types.ts
  src/components/MAPI/permissions/useSubjectPermissions.ts
  src/components/MAPI/permissions/useUseCasesPermissions.ts
  src/components/MAPI/permissions/utils.ts
  src/model/services/mapi/authorizationv1/createLocalSubjectAccessReview.ts
  src/model/services/mapi/authorizationv1/index.ts
  src/model/services/mapi/authorizationv1/types.ts
  src/model/services/mapi/rbacv1/getClusterRoleList.ts
  src/model/services/mapi/rbacv1/getRoleList.ts
  src/model/services/mapi/rbacv1/key.ts
  test/mockHttpCalls/rbacv1/roleBindings.ts
Labels: kind/refactor

#3439 Determine whether a user can inspect a user's/group's permissions
  src/components/MAPI/permissions/utils.ts
Labels: kind/refactor

#3448 Update permissions use cases: permissions for "Inspecting Apps"
  jest.config.ts
  scripts/permissions-use-cases.yaml
Labels: kind/change

#3443 Add permissions overview subject select form
  src/components/MAPI/permissions/Permissions.tsx
  src/components/MAPI/permissions/PermissionsOverview/PermissionsOverview.tsx
  src/components/MAPI/permissions/PermissionsPreloader/PermissionsPreloader.tsx
  src/components/MAPI/permissions/PermissionsPreloader/index.ts
  src/components/MAPI/permissions/SubjectForm/SubjectForm.tsx
  src/components/MAPI/permissions/SubjectForm/index.ts
  src/components/MAPI/permissions/useUseCasesPermissions.ts
  src/components/UI/Display/MAPI/permissions/PermissionsUseCases/PermissionsUseCases.tsx
  src/components/UI/Display/MAPI/permissions/PermissionsUseCases/ScrollableContainer.tsx
  src/components/UI/Display/MAPI/permissions/PermissionsUseCases/StatusesForCategory.tsx
  src/components/UI/Display/MAPI/permissions/PermissionsUseCases/UseCasesForCategory.tsx
  src/styles/theme.ts
Labels: kind/feature

#3452 Increase permissions overview column width
  src/components/UI/Display/MAPI/permissions/PermissionsUseCases/PermissionsUseCases.tsx
  src/components/UI/Display/MAPI/permissions/PermissionsUseCases/StatusesForCategory.tsx
Labels: kind/ux-enhancement

#3449 Add CLI guide for inspecting permissions
  src/components/MAPI/permissions/PermissionsOverview/PermissionsOverview.tsx
  src/components/MAPI/permissions/guides/InspectPermissionsGuide.tsx
Labels: kind/ux-enhancement
