Repository giantswarm/happa, pull requests merged in 2023-04, with the labels that each got.

#4205 JSON schema form fixes
  src/components/UI/JSONSchemaForm/BaseInputTemplate/index.tsx
  src/components/UI/JSONSchemaForm/CheckboxWidget/index.tsx
  src/components/UI/JSONSchemaForm/SelectWidget/index.tsx
  src/components/UI/JSONSchemaForm/__tests__/utils.ts
  src/components/UI/JSONSchemaForm/index.tsx
  src/components/UI/JSONSchemaForm/utils.ts
Labels: kind/bug

#4227 Remove shared app collection from circle CI
  .circleci/config.yml
Labels: kind/dev-change

#4226 Provide machine types information for CAPZ
  helm/happa/templates/configmap.yaml
  helm/happa/values.schema.json
  helm/happa/values.yaml
  scripts/getConfigurationValues.ts
Labels: kind/dev-change

#4231 Display machine statistics for CAPZ
  jest.config.ts
  src/components/MAPI/clusters/ClusterList/__tests__/ClusterListItem.tsx
  src/components/MAPI/clusters/utils.ts
  src/components/MAPI/organizations/OrganizationDetailGeneral/__tests__/index.tsx
  src/components/MAPI/organizations/OrganizationDetailGeneral/utils.ts
  src/components/MAPI/utils.ts
  src/components/MAPI/workernodes/__tests__/ClusterDetailWidgetWorkerNodes.tsx
  test/mockHttpCalls/capiv1beta1/clusters.ts
  test/mockHttpCalls/capiv1beta1/machineDeployments.ts
  test/mockHttpCalls/capiv1beta1/machines.ts
  test/mockHttpCalls/capzv1beta1/azureMachineTemplates.ts
  test/mockHttpCalls/capzv1beta1/index.ts
Labels: kind/refactor

#4234 Display worker nodes details for CAPZ
  src/components/MAPI/utils.ts
  src/components/MAPI/workernodes/ClusterDetailWorkerNodes.tsx
  src/components/MAPI/workernodes/WorkerNodesNodePoolItemMachineType.tsx
  src/components/MAPI/workernodes/__tests__/ClusterDetailWorkerNodes.tsx
  src/components/MAPI/workernodes/__tests__/WorkerNodesNodePoolItem.tsx
  src/components/MAPI/workernodes/guides/ListNodePoolsGuide.tsx
  test/mockHttpCalls/capiv1beta1/machineDeployments.ts
Labels: kind/refactor

#4242 Display machine types in cluster creation form for CAPZ installations
  helm/happa/templates/configmap.yaml
  src/components/MAPI/clusters/CreateClusterAppBundles/schemaUtils.ts
  src/model/stores/main/selectors.ts
  src/utils/hooks/useInstanceTypeSelectionConfiguration.ts
Labels: kind/ux-enhancement

#4246 Increase CircleCI resource class for building FE docs
  .circleci/config.yml
Labels: kind/dev-change

#4252 Remove `kubernetes.auth.controlPlaneAdminTargetGroup`
  ats/test-values.yaml
  helm/happa/values.schema.json
  helm/happa/values.yaml
Labels: kind/dev-change

#4258 Add tests for cluster details on CAPZ
  src/components/MAPI/clusters/ClusterDetail/__tests__/ClusterDetailWidgetControlPlaneNodes.tsx
  src/components/MAPI/clusters/ClusterDetail/__tests__/ClusterDetailWidgetKubernetesAPI.tsx
  src/components/MAPI/clusters/ClusterDetail/__tests__/ClusterDetailWidgetVersions.tsx
  src/components/MAPI/clusters/ClusterDetail/__tests__/index.tsx
  test/mockHttpCalls/capiv1beta1/clusters.ts
Labels: kind/refactor

#4268 Display `write_all_group` name if logged in user cannot manage users
  jest.config.ts
  src/components/Users/Users.js
  test/renderUtils.tsx
Labels: kind/ux-enhancement

#4257 Display ingress details for CAPZ
  src/components/MAPI/apps/__tests__/ClusterDetailIngress.tsx
  src/components/MAPI/apps/utils.ts
Labels: kind/refactor

#4253 Include cluster ID in default app resource name for CAPI
  src/components/MAPI/apps/AppInstallModal.tsx
  src/components/MAPI/apps/__tests__/AppInstallModal.tsx
  src/components/MAPI/apps/utils.ts
Labels: kind/bug
