Repository giantswarm/happa, pull requests merged in 2023-05, with the labels that each got.

#4279 Fix cluster details UI bugs
  src/components/UI/Display/MAPI/clusters/ClusterDetail/ClusterDetailDeleteActionClusterName.tsx
  src/components/UI/Display/MAPI/workernodes/WorkerNodesNodePoolListPlaceholder.tsx
Labels: kind/ux-enhancement

#4280 Preprocess schema to handle pattern properties
  src/components/UI/JSONSchemaForm/BaseInputTemplate/index.tsx
  src/components/UI/JSONSchemaForm/CheckboxWidget/index.tsx
  src/components/UI/JSONSchemaForm/SelectWidget/index.tsx
  src/components/UI/JSONSchemaForm/__tests__/schemaUtils.ts
  src/components/UI/JSONSchemaForm/__tests__/utils.ts
  src/components/UI/JSONSchemaForm/index.tsx
  src/components/UI/JSONSchemaForm/schemaUtils.ts
  src/components/UI/JSONSchemaForm/test.schema.json
  src/components/UI/JSONSchemaForm/utils.ts
  src/utils/__tests__/helpers.ts
  src/utils/helpers.ts
Labels: kind/feature

#4284 Update readme and release documentation
  README.md
  docs/Release.md
Labels: kind/dev-change

#4293 Roll back Happa API ingress configuration change
  helm/happa/templates/happaapi-ingress.yaml
Labels: kind/bug

#4297 stop pushing to openstack-app-collection
  .circleci/config.yml
Labels: kind/dev-change

#4298 Remove v20.0.0-alpha1 releases
  src/components/MAPI/clusters/CreateCluster/__tests__/index.tsx
  src/components/MAPI/clusters/utils.ts
  src/components/MAPI/utils.ts
  src/model/services/mapi/capzv1beta1/index.ts
  src/model/services/mapi/capzv1beta1/key.ts
  test/mockHttpCalls/capav1beta1/awsClusters.ts
  test/mockHttpCalls/capav1beta1/awsMachinePools.ts
  test/mockHttpCalls/capav1beta1/awsMachineTemplates.ts
  test/mockHttpCalls/capiv1beta1/clusters.ts
  test/mockHttpCalls/capiv1beta1/machinePools.ts
  test/mockHttpCalls/capiv1beta1/machines.ts
  test/mockHttpCalls/releasev1alpha1/releases.ts
Labels: kind/refactor

#4299 Remove infrastructure.giantswarm.io/v1alpha2 types
  src/components/MAPI/clusters/ClusterDetail/ClusterDetailWidgetProviderAWS.tsx
  src/components/MAPI/clusters/ClusterDetail/utils.ts
  src/components/MAPI/clusters/CreateCluster/patches.ts
  src/components/MAPI/clusters/utils.ts
  src/components/MAPI/types.ts
  src/model/services/mapi/infrastructurev1alpha2/index.ts
  src/model/services/mapi/infrastructurev1alpha2/types.ts
  test/mockHttpCalls/infrastructurev1alpha3/awsMachineDeployments.ts
Labels: kind/refactor

#4301 Migrate master taint to control-plane taint
  test/mockHttpCalls/status.js
  test/statusState.ts
Labels: kind/dev-change

#4305 Change ownership in charts
  helm/fe-docs/Chart.yaml
  helm/happa/Chart.yaml
Labels: kind/dev-change

#4313 Display cluster creation form values as config values and manifest
  jest.config.ts
  package.json
  src/components/MAPI/apps/utils.ts
  src/components/MAPI/clusters/CreateClusterAppBundles/CreateClusterConfigViewer.tsx
  src/components/MAPI/clusters/CreateClusterAppBundles/CreateClusterConfigViewerConfigInspector.tsx
  src/components/MAPI/clusters/CreateClusterAppBundles/index.tsx
  src/components/MAPI/clusters/CreateClusterAppBundles/utils.ts
  src/styles/theme.ts
  yarn.lock
Labels: kind/feature

#4326 Allow selecting cluster app version for cluster creation
  src/components/MAPI/clusters/CreateClusterAppBundles/index.tsx
Labels: kind/feature

#4327 Improve display of validation errors in cluster creation form
  src/components/MAPI/clusters/CreateClusterAppBundles/ClusterAppSchemaTester.tsx
  src/components/MAPI/clusters/CreateClusterAppBundles/CreateClusterAppBundlesForm.tsx
  src/components/MAPI/clusters/CreateClusterAppBundles/index.tsx
  src/components/UI/JSONSchemaForm/ErrorListTemplate/ErrorList.tsx
  src/components/UI/JSONSchemaForm/ErrorListTemplate/ValidationStatus.tsx
  src/components/UI/JSONSchemaForm/ErrorListTemplate/index.tsx
  src/components/UI/JSONSchemaForm/index.tsx
Labels: kind/ux-enhancement

#4338 Change code owners
  CODEOWNERS
  renovate.json
Labels: kind/dev-change

#4345 Change renovate schedule for some packages
  renovate.json
Labels: kind/dev-change
