Repository giantswarm/happa, pull requests merged in 2023-01, with the labels that each got.

#3999 Replace old testing installation in README.md
  README.md
Labels: kind/dev-change

#3996 Support various dex connectors for login
  __tests__/AdminLogin.tsx
  helm/happa/templates/configmap.yaml
  helm/happa/values.schema.json
  helm/happa/values.yaml
  jest.config.ts
  scripts/getConfigurationValues.ts
  src/@types/global.d.ts
  src/components/Auth/AdminLogin.tsx
  src/index.ejs
  src/model/stores/main/actions.ts
  src/model/stores/main/selectors.ts
  src/model/stores/main/utils.ts
  src/utils/MapiAuth/MapiAuth.ts
Labels: kind/change

#4017 Fix user installed apps view
  src/components/MAPI/apps/ClusterDetailApps.tsx
  src/components/MAPI/apps/ClusterDetailWidgetApps.tsx
Labels: kind/bug

#4019 Replace oidc-client with oidc-client-ts
  package.json
  src/utils/MapiAuth/makeDefaultConfig.ts
  src/utils/OAuth2/OAuth2.ts
  src/utils/OAuth2/OAuth2CustomMetadata.ts
  src/utils/OAuth2/OAuth2User.ts
  yarn.lock
Labels: kind/dev-change
